PreMiD/Activities

Deezer/dist/presence.js, Deezer/presence.ts, SoundCloud/dist/metadata.json, SoundCloud/dist/presence.js, SoundCloud/presence.ts
Query selecting strings are much shorter and should be more accurate. When your control bar, at the bottom, is not playing anything and is at 00:00, it will display the "browsing" message. Along with extra information when the user visits playlists, albums, artists, and podcasts.
Ready to be deployed, mention me on the discord server if there are issues.
This edit applies to both Deezer and SoundCloud.
=>  shortened: query strings // changed: browsing

Google Play Music/dist/metadata.json, Google Play Music/dist/presence.js, Google Play Music/presence.ts, Google Play Music/tsconfig.json
close #30
GPM stops updating the DOM when the tab is not active, so it currently doesn't get playback time information when the tab is inactive.
=> Add Google Play Music

ToradorAPI/dist/metadata.json, Toradora Wikia/dist/metadata.json, Toradora Wikia/dist/presence.js, Toradora Wikia/presence.ts, Toradora Wikia/tsconfig.json
Added Toradora Wikia Presence and changed the tags of ToradorAPI to also have the tag "Toradora" as there are now two presences focused around Toradora.
=> Toradora Wikia Presence

Fandom/dist/metadata.json, Fandom/dist/presence.js
This is a presence for fandom.com/*.fandom.com (also known as FANDOM and FANDOM powered by Wikia). This presence is made so every page on the fandom.com site is detectable, whether is the Fandom part (those articles, videos, etc) and the Wikia part (wikis with MediaWiki)
Due to the nature of different implementations of the pages on the website ([to the point they even acknowledge it](https://community.fandom.com/wiki/User_blog:MisterWoodhouse/Fandom_is_upgrading_to_a_modern_version_of_MediaWiki)), it took a while on making this presence so it supports vast majority of the pages compared on making a Wikipedia presence.
This is my first presence, hope this is get accepted.
There are multiple thumbnails that I have prepared for this presence. I tried to make those so it shows the Fandom …
=> Add Fandom Presence

Gamepedia/dist/metadata.json, Gamepedia/dist/presence.js, Gamepedia/presence.ts, Gamepedia/tsconfig.json
This is a presence for Gamepedia (gamepedia.com). Gamepedia is a wiki that also owned by the Fandom. Although it is operated by Fandom, they used a different version of MediaWiki, making the code for this presence more simple compared than the Fandom ones.
*TBA*
- https://i.imgur.com/Dr5wG06.png (https://www.gamepedia.com on the left, https://help.gamepedia.com, the central wiki of Gamepedia, on the right)
- https://i.imgur.com/6FDtk1e.png (alternate version of the previous one)
- https://i.imgur.com/djEyS7P.png (https://www.gamepedia.com)
- https://i.imgur.com/G6cJbFa.png (https://help.gamepedia.com)
*TBA*
=> Add Gamepedia presence

Fandom/dist/metadata.json, Fandom/dist/presence.js, Fandom/presence.ts, Fandom/tsconfig.json
This is an update for the Fandom (fandom.com) presence, made by me.
The update introduces optimizations, such as, but not limited to...
1. Less resource footprint by setting the presence data only once.
2. Shorter way to select details based on the prefix.
3. Fixes so TypeScript doesn't bugs me out.
Some minor changes are also included, such as changes on the message for some details.
Please accept these changes, thanks.
----
*P.S.*
*1. What is the Presence of the Week thing? How does it work? What does it take for a presence to get in?*
*2. How do you remove that comment at the end of the ``.js`` file?*
*3. I am going to create a pull request for Gamepedia, sometime later.*
*4. How's your day, guys?*
=> Update Fandom presence (1.1.0)

Typeracer/dist/metadata.json, Typeracer/dist/presence.js, Typeracer/presence.ts, Typeracer/tsconfig.json
This is a presence for Typeracer (https://play.typeracer.com), a typing test game where you, well, type texts, with an addition of racing each other with players around the world. It also works with the [pit stop](https://data.typeracer.com/pit) and some other pages, but not the blog, because it's unrelated. The main feature of this presence is it shows the stats of the game played (WPM, percentage) in real time.
- Due to the old website, there is no high-quality images available for the logo, so I just upscale the 64x64 logo using waifu2x, and IMO it looks pretty good.
| -- | -- |
|![2019-12-15_20-43-21](https://user-images.githubusercontent.com/11584103/70911075-04782a80-2009-11ea-9cda-0f0d67f8b166.png)|https://play.typeracer.com/ …
=> Add Typeracer presence

Pocket Casts/dist/metadata.json, Pocket Casts/dist/presence.js
This adds support for the [Pocket Casts web player](https://play.pocketcasts.com/).
If nothing is playing, the current page is shown instead:
=> Add Pocket Casts

Pocket Casts/dist/metadata.json, Pocket Casts/dist/presence.js
Fixes the timestamp when a podcast is 60 minutes or longer (e.g. 01:02 -> 01:02:03).
=> Pocket Casts: Fix hours

Skyra/dist/metadata.json, Skyra/dist/presence.js, Skyra/presence.ts, Skyra/tsconfig.json
Superseding #1253 as requested
---
I'd like to add a Presence for [skyra.pw](https://skyra.pw/), the website and dashboard for [Skyra](https://github.com/skyra-project/skyra)
Before a remark is made about the using of `data-premid` in the query-selectors, I'm a co-owner of Skyra and added those attributes to the sourcecode of the website myself, so it's a perfectly safe selector to use. 
Screenshots in collapsed view:
<details><summary>Click here to view screenshots</summary>
</details
---
---
If I may give you guys some general advice/remarks from 1 software engineer (who does this for a living might I add) to many others. You do not have to take any of these points to heart at all, I'd just like to share them.
- ~~You have a `.prettierrc.json` config, trailing commas in there are …
=> feat: add presence for skyra.pw

Fandom/dist/metadata.json, Fandom/dist/presence.js, Fandom/presence.ts, Fandom/tsconfig.json
Here's a minor update for Fandom, which introduces code refactors and fixes here and there, along with the requested update.
- Changed things for consistency
- Changed default presence texts (request from staff members)
- Refactored code related to current path
- Added site name on the discussion parts for wikis
- Supported more pages on www.fandom.com
- Refactored code for ESLint validation
- Add alternative names on the tag
| ![2020-03-30_16-36-06](https://user-images.githubusercontent.com/11584103/79352538-315f2e80-7f64-11ea-8ff9-6b7e10cb3884.png) | https://www.fandom.com/ |
| ![2020-03-30_16-36-54](https://user-images.githubusercontent.com/11584103/79352548-345a1f00-7f64-11ea-98c1-56fbf83c0410.png) | …
=> Update Fandom presence (1.1.1)

Apple Music/dist/metadata.json
Changed URL to music.apple.com as beta.music.apple.com now redirects to music.apple.com and appears to have released.
=> 🔗 Fix Apple Music URL

Bing/dist/metadata.json
One of them had an exclamation mark at the end and the other didn't.
=> 🐛 Bing - Fix Message Inconsitency

DuckDuckGo/dist/metadata.json
One of them had an exclamation mark at the end and the other didn't.
(forgot to do this to DuckDuckGo and only did it to Bing #1457)
=> 🐛 DuckDuckGo - Fix Message Inconsitency

schemaValidator.ts
Prevents first error from being on the same line as the presence name.
=> Fix error output

websites/0-9/4anime/dist/metadata.json, websites/0-9/4anime/presence.ts
`#video1_html5_api` was supposed to be `#videoo1_html5_api`, so anybody using the default vjs player wouldn't have been detected.
=> [4anime] Fixed typo that broke vjs compatibility

websites/W/Wikiwand/dist/metadata.json, websites/W/Wikiwand/presence.ts, websites/W/Wikiwand/tsconfig.json
*See also: #1735, Hans5958/PreMiD-Presences-Personal#2*
This is the presence for Wikiwand (www.wikiwand.com), a web app for viewing Wikipedia articles/pages better. I think that's it.
This PR resolves #1735.
- Images are from the press kit, and the logo is manually upscaled by me.
- On an unrelated note, I actually have rewritten the Wikipedia presence, along with a plan to do all wikis from the Wikimedia Foundation. I'm not sure if the rewritten part is applicable, so I will need a discussion.
| Image                                                                                                                        | Link visited                                   |
| ------------------------------------------------------------------------------------------------------------------------ …
=> Add Wikiwand presence

websites/M/ManiaExchange/dist/metadata.json, websites/M/ManiaExchange/presence.ts
*See also: Hans5958/PreMiD-Presences-Personal#4*
Here's an update for the ManiaExchange presence, which is done to add support for the new [TrackmaniaExchange](https://trackmania.exchange), as well to introduce new supported pages and bug fixes.
- Update base script
- Fix `currentPath` by also removing the last slash if required so it is consistent
- Update how `resetData()` works so the fields that have been changed before are also included
- Update metadata schema from 1.1
- Add support for TrackmaniaExchange (a TMX variation, but for the 2020 Trackmania)
- Edit description to avoid confusion for both TMX
- Swap the small image with the large image for some parts of the website
- Add support for more pages
- Are newlines work on the description?
| ----- | …
=> Update ManiaExchange presence (1.0.1)

websites/T/TrackMania Exchange/dist/metadata.json, websites/T/TrackMania Exchange/presence.ts
*See also: Hans5958/PreMiD-Presences-Personal#4*
Here's an update for the TrackMania Exchange presence, which is done to avoid confusion for the new [TrackmaniaExchange](https://trackmania.exchange), as well to introduce new supported pages and bug fixes.
- Update base script
- Fix `currentPath` by also removing the last slash if required so it is consistent
- Update how `resetData()` works so the fields that have been changed before are also included
- Update metadata schema from 1.1
- Add alternative name for TMX (`TM-Exchange`)
- Edit description to avoid confusion for both TMX
- Add support for more pages
- Regarding altnames, am I doing it right?
- Are newlines work on the description?
| …
=> Update TrackMania Exchange presence (1.0.1)

.github/workflows/SA.yml
ESLint's warnings have been removed from DeepScan thanks to its inconsistency regarding a few pull requests and to also make reviewing easier. What the workflow basically does is check the modified/added lines first and If there are any errors it posts a review using the bot pointing at the exact line with the issue (+ links to how it can be fixed), and in case there are no errors in the modified files another job will run, the second job checks by files instead of diff, so it can spot the issues not included in diff (e.g. stuff DeepScan missed before :bruh:), if it does then instead of reviewing like before, it uses code annotations (thanks GitHub for the technical limitations), the code annotations are the same as the reviews except they are in the commits and the workflow's run page, …
=> Workflow Maintenance

websites/W/Wikibooks/dist/metadata.json, websites/W/Wikibooks/presence.ts, websites/W/Wikibooks/tsconfig.json
This is a presence for Wikibooks (www.wikibooks.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains free textbooks.
- This presence supports all languages of Wikibooks.
| ![](https://user-images.githubusercontent.com/11584103/90745357-6d334780-e2fa-11ea-9f81-7fe1082ad912.png) | https://www.wikibooks.org |
| ![](https://user-images.githubusercontent.com/11584103/90745387-6efd0b00-e2fa-11ea-873c-1943a8192946.png) | https://en.wikibooks.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90745397-6f95a180-e2fa-11ea-8f24-d9960b2c7895.png) | …
=> Add Wikibooks presence

websites/W/Wikidata/dist/metadata.json, websites/W/Wikidata/presence.ts, websites/W/Wikidata/tsconfig.json
This is a presence for Wikidata (www.wikidata.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains abstract, strucuted data of everything on other Wikimedia projects (Wikipedia, Wiktionary, etc).
- This presence also supports the test version of Wikimedia Commons (https://test.wikidata.org/).
| ![](https://user-images.githubusercontent.com/11584103/90747450-2003a580-e2fb-11ea-84ad-81804599c979.png) | https://www.wikidata.org/wiki/Wikidata:Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90747564-49bccc80-e2fb-11ea-8451-3e9de6221263.png) | …
=> Add Wikidata presence

websites/W/Wikimedia Commons/dist/metadata.json, websites/W/Wikimedia Commons/presence.ts, websites/W/Wikimedia Commons/tsconfig.json
This is a presence for Wikimedia Commons (commons.wikimedia.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains usable media (photos, videos, etc) that lsi
- This presence also supports the test version of Wikimedia Commons (https://test-commons.wikimedia.org/).
| ![](https://user-images.githubusercontent.com/11584103/90747877-a6b88280-e2fb-11ea-8d39-e211e36b7e55.png) | https://commons.wikimedia.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90747880-a7e9af80-e2fb-11ea-8e2d-01b0beac0c5c.png) | …
=> Add Wikimedia Commons presence

websites/W/Wikinews/dist/metadata.json, websites/W/Wikinews/presence.ts, websites/W/Wikinews/tsconfig.json
This is a presence for Wikinews (www.wikinews.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains news about anything.
- This presence supports all languages of Wikinews.
| ![](https://user-images.githubusercontent.com/11584103/90750892-a6ba8180-e2ff-11ea-94ad-4dba83ee1c21.png) | https://www.wikinews.org |
| ![](https://user-images.githubusercontent.com/11584103/90750894-a7ebae80-e2ff-11ea-8cea-5cf0a4379e2c.png) | https://en.wikinews.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90750897-a8844500-e2ff-11ea-94ff-373a4eb152fb.png) | …
=> Add Wikinews presence

websites/W/Wikisource/dist/metadata.json, websites/W/Wikisource/presence.ts, websites/W/Wikisource/tsconfig.json
This is a presence for Wikisource (www.wikisource.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains texts of various stuffs. It's basically a library.
- This presence supports all languages of Wikisource, including the multilingual one on wikisource.org.
| ![](https://user-images.githubusercontent.com/11584103/90757178-8393d000-e307-11ea-963b-24271e36162b.png) | https://www.wikisource.org |
| ![](https://user-images.githubusercontent.com/11584103/90757198-88588400-e307-11ea-8c60-dfc22b998df7.png) | https://en.wikisource.org/wiki/Main_Page |
| …
=> Add Wikisource presence

websites/W/Wikispecies/dist/metadata.json, websites/W/Wikispecies/presence.ts, websites/W/Wikispecies/tsconfig.json
This is a presence for Wikispecies (species.wikimedia.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that is a directory for species around the world.
| ![](https://user-images.githubusercontent.com/11584103/90757331-b63dc880-e307-11ea-8d9b-a544a36108a2.png) | https://species.wikimedia.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90757338-b76ef580-e307-11ea-8cab-b98e54e020ed.png) | https://species.wikimedia.org/wiki/Rafflesia_arnoldii |
=> Add Wikispecies presence

websites/W/Wikivoyage/dist/metadata.json, websites/W/Wikivoyage/presence.ts, websites/W/Wikivoyage/tsconfig.json
This is a presence for Wikivoyage (www.wikivoyage.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains travel guides for free.
- This presence supports all languages of Wikivoyage.
| ![](https://user-images.githubusercontent.com/11584103/90757509-edac7500-e307-11ea-9389-c53d6e8289cd.png) | https://www.wikivoyage.org |
| ![](https://user-images.githubusercontent.com/11584103/90757512-eedda200-e307-11ea-8c6a-10fa90464b52.png) | https://en.wikivoyage.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90757518-ef763880-e307-11ea-9744-bd7f9f708916.png) | …
=> Add Wikivoyage presence

websites/W/Wiktionary/dist/metadata.json, websites/W/Wiktionary/presence.ts, websites/W/Wiktionary/tsconfig.json
This is a presence for Wiktionary (www.wiktionary.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that is basically a dictionary.
- This presence supports all languages of Wiktionary.
| ![](https://user-images.githubusercontent.com/11584103/90757591-0583f900-e308-11ea-940f-4342a3f5f21e.png) | https://www.wiktionary.org |
| ![](https://user-images.githubusercontent.com/11584103/90757594-061c8f80-e308-11ea-885f-ff68f7f2e159.png) | https://en.wiktionary.org/wiki/Wiktionary:Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90757595-074dbc80-e308-11ea-9509-18c88ac716dc.png) | …
=> Add Wiktionary presence

websites/T/Trello/dist/metadata.json, websites/T/Trello/presence.ts
Fixes #2006
#2017 fixed that issue already and it is working but only when the page is set to English
The current solution detects if text on the button is `Private` but my solution detects presence of "lock" icon
=> Fix Trello presence showing private boards

websites/G/GitHub/dist/metadata.json, websites/G/GitHub/presence.ts
Adds "Browsing codespaces..." to people that are viewing the [codespaces page](https://github.com/codespaces/) ([image](https://get.snaz.in/8c7uEkh.png))
> At the moment, codespaces are [available to a small group of GitHub users while in limited beta](https://github.com/features/codespaces#faq), so it may or may not be available for you. I can show this off a bit more if needed.
=> GitHub: Detect Codespace browsing

websites/G/GitHub Codespaces/dist/metadata.json, websites/G/GitHub Codespaces/presence.ts
This PR adds the `%ext%` argument to the `details` and `state` options.
- i.e. `main.ts` has an `%ext` of `"TS"`
=> GitHub Codespaces: Add ext argument

websites/P/Pylon/dist/metadata.json, websites/P/Pylon/presence.ts
Since the original presence maker is inactive and I wanted to add more advanced functionality, I wanted to take over this one.
This PR rewrites the presence to
- Add 4 settings for showing guild/doc names and details/state template
- Add studio editor presence using the format similar to [GitHub Codespaces](https://premid.app/store/presences/GitHub%20Codespaces)
- Add SDK reference showing the document name you are on
- Fix viewing a server in the studio
<details>
</details>
<details>
</details>
=> Pylon: Rewrite presence

websites/L/LinusTechTips/dist/metadata.json, websites/L/LinusTechTips/presence.ts
The Linus Tech Tips Forum dropped the "main" of its url structure. Furthermore the selectors did not work anymore. With these changes everything should be back in working order.
=> Linus Tech Tips: Fix URL and selectors

websites/W/Wikipedia/dist/metadata.json
Currently using the old logo. Updated to the new one.
=> Update to new Wikipedia logo

websites/A/AniList/dist/metadata.json, websites/A/AniList/presence.ts
`ADD` Notifications and Settings page to AniList. (they previously showed nothing)
=> Add notifications and settings page to AniList Presence

websites/J/Jellyfin/dist/metadata.json, websites/J/Jellyfin/presence.ts
- Fix issue #2831 where getting presence metadata would fail if the service was installed under a subpath such as https://domain.tld/jellyfin.
- Used presence helpers for console logging, and getting timestamps from media elements.
- Added some presence settings:
- Show media timestamps (boolean): show or hide timestamps when playing back media
- Show timestamps (boolean): show or hide timestamps for other cases
Proof screenshots:
=> Fix issue #2831, added some presence settings & migrated to presence helpers

websites/J/JUKE/dist/metadata.json, websites/J/JUKE/presence.ts, websites/M/Magister/dist/metadata.json
[JUKE.nl](https://juke.nl/) (try it out!):
Magister already worked.
=> Overhaul JUKE.nl presence, Update Magister presence

websites/F/Fandom/dist/metadata.json, websites/F/Fandom/presence.ts, websites/G/Gamepedia/dist/metadata.json, websites/G/Gamepedia/presence.ts
<h3>Reviewers, please read!</h3>
Well, this is awkward. 
In a recent turn of event, [the people on Fandom decided that it would be a good idea to migrate Gamepedia wikis to the Fandom domain](https://community.fandom.com/wiki/User_blog:MisterWoodhouse/The_Future_of_Gamepedia). This means that any wikis on https://gamepedia.com (like https://minecraft.gamepedia.com) is going to reside on https://fandom.com (like https://minecraft.fandom.com). SEO improvement is their main reason, if you believe.
<details><summary>Google's Featured Snippet summary, because it somehow sums up perfectly.</summary>
Today, we have a big announcement. After nearly two years of working together to bring Fandom and Gamepedia wikis onto one platform, we will be starting to migrate all Gamepedia wikis to a …
=> Update multiple presences (Gamepedia domain merge)

websites/F/Fandom/dist/metadata.json, websites/F/Fandom/presence.ts, websites/G/Gamepedia/dist/metadata.json, websites/G/Gamepedia/presence.ts
Well, it looks that my first attempt on resolving this issue kind of failed. Here's the second one, along with additional additions that are astonishingly overlooked.
By the way, I need to wrap the entire code in an if statement, so that's why the changes looked a lot. [This is the commit that I made on my side](https://github.com/Hans5958/PreMiD-Presences-Personal/commit/838a89d01adebc110479add5d3edf94e548b470b).
This PR includes updates to the following presences:
- Fandom (1.2.3)
- Gamepedia (1.2.3)
- Change method of early termination to fix critical bug where Fandom and Gamepedia presence can't run at the same time
- Add language code on the state/details for other languages than English (feature from WP)
- Revert feature "updating when there is presence data"
- Fix regex to only …
=> Update multiple presences (Gamepedia domain merge 2)

websites/R/Replit/dist/metadata.json, websites/R/Replit/presence.ts
Due to DOM changes, presence while editing a file was broken. Updated the presence to fix this.
Screenshot
=> Replit - Fixed file editing presence

websites/B/BeatSaver/dist/metadata.json, websites/B/BeatSaver/presence.ts
Adds a small image to indicate that user is showing auto-generated beatmaps.
Show auto-generated beatmaps checked:
Show auto-generated beatmaps unchecked:
Works on every Browse page and the Search and Uploader pages
=> Add small image Auto-generated

websites/P/Plex/dist/metadata.json, websites/P/Plex/presence.ts, websites/Z/Zalando/dist/metadata.json, websites/Z/Zalando/presence.ts
For both Plex and Zalando, they referenced an old redirect to the discord server.
Updated to the PreMiD Sub-Domain
=> Update discord link to premid sub-domain

websites/Z/Zoom/dist/metadata.json, websites/Z/Zoom/presence.ts
Fixes a bug when presence displays that user is still in a meeting when on the meeting end screen
It now shows count of the participants in a room
=> Zoom: Add users in room & fix leaving bug

websites/O/Overleaf/dist/metadata.json
The language is not that important in the Presence since the language is just the display language for Overleaf and doesn't change the rest. The Presence just needed to be triggered on some specific subdomains.
=> Fixed URL problems for Overleaf Presence

@types/premid/index.d.ts
This makes it so that you can only have a maximum of 2 buttons and not infinite like previously. I only made the second element of the array optional because I assume you'd want to add at least one button when setting buttons, although passing an empty array would technically also be correct.
=> Fix buttons type

.github/workflows/SE.yml, .github/workflows/SV.yml
Closes #4950. This PR uses the cache feature built-in the setup-node action instead of a different action just for caching
=> ci: remove actions/cache

.github/ISSUE_TEMPLATE/bug_report.yml
This PR improves the bug report template by replacing the steps to reproduce preset value with a placeholder (grey text that disappears once you start writing), makes the "Expected behavior" section an input instead of textarea, adds "Actual behavior" and moves "Screenshots" above these two
=> chore(bug_report): improve template

package.json, util/configs/tsconfig.massCompile.json, util/configs/tsconfig.metadataSorter.json, util/tools/auto/schemaValidator.ts, util/tools/auto/syntaxEnforcer.ts, util/tools/massCompile.ts, util/tools/massVer.ts, util/tools/metadataSorter.ts
This PR adds 2 new scripts and improves existing ones to use them.
- Refactored the package.json file to remove the :compile scripts and move them to their original script as they weren't used anywhere else anymore
- Updated SV to check if all Presences were bumped correctly. This currently has a flaw due to how the script was originally made which is that it will not produce an error if the PR didn't change the metadata file at all. This could be improved in the future.
- Added a script to compile all presences 1 by 1. This wasn't added to any CI so it can only be ran by maintainers when needed as it takes a long time to run. The script **must** compile each presence after the other, otherwise your computer will catch on fire
- Added script to sort metadata files according to the order …
=> feat(util): add and improve scripts

package.json, util/tools/translator.ts, yarn.lock
This PR fixes the translator tool by downgrading ora to the latest version 5 (as v6 is now pure ESM only) and changing the chalk import to a default import instead of destructuring. If you ask me why this fixes it I have no clue, but it does and that's all that matters, right?
<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
no
</details>
=> fix(Translator): downgrade ora and use default imports for chalk

package.json
This pull requests removes Prettier from the `lint:ci` script as it is unneeded - `prettier/prettier` on ESLint handles these errors, and by removing prettier it will speed up the time it takes to run the script.
=> ci(Lint): remove pretty from lint

util/tools/auto/schemaValidator.ts, util/tools/auto/syntaxEnforcer.ts
This PR brings you yet another improvement to the scripts
- Fixes a bug noticed in #5165 where a version wasn't bumped since the only change was done to the metadata file
- Improves SV to more strictly check version bumps: it now only allows you to bump 1 part of semver and you can't bump a version more than once. Examples of invalid bumps are 1.1.1 -> 1.1.3 and 1.1.1 -> 1.2.1.
<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
hell no
</details>
=> feat(Scripts): fix bugs and improve SV

.commitlintrc.json, .github/COMMIT_CONVENTION.md, .github/workflows/SE.yml, .husky/commit-msg, README.md, package.json, yarn.lock
This PR adds husky and pre-commit hooks to the repo in order to enforce the use of commitlint. This is being done in order for us to be able to generate presence changelogs in the future, which is a planned feature for PreMiD v3. All documentation and known issues were also documented on this PR
=> chore: enforce commitlint

.editorconfig
This PR fixes the .editorconfig file to use tabs instead of spaces.
Honestly, can't we just remove this?
=> style: set editorconfig to use tabs

.husky/pre-commit
This PR removes the pre-commit hook from husky as it is way too slow for some contributors on some machines due to the amount of files this PR has. Husky is being kept simply for enforcing commitlint, however file linting will now be handled through CI only
=> chore: remove husky pre-commit lint hook

.github/PULL_REQUEST_TEMPLATE.MD
The semver acknowledgment didn't make sense since we already have SV which checks for that, so I added this new one to ensure people read the doc in case they're not familiar with it. I also plan on adding a CI in the future that checks this for us
=> chore: replace last PR ack with commitlint

.github/workflows/SV.yml
It seems like before #6339 SV was being run on push but it wasn't doing anything since the files changed wouldn't get written so it would always validate 0 presences. This PR makes it so the CI just doesn't run at all on push, avoiding unnecessary fails
=> ci(SV): don't run on push

.commitlintrc.json
Disables the scope-case rule in commitlint since presences can have many different casing styles
=> chore: disable scope case rule

package.json, util/tools/util.ts
When SE has local uncommitted changes the command wasn't picking this up and was returning an empty diff. This PR resolves that hopefully (was tested)
=> fix(SE): check uncommitted files diff

.github/workflows/compileLint.yml
No reason to have the same CI run twice on PRs made through internal branches
=> ci: only run on pushes to main and prs

websites/F/FlixTor/dist/metadata.json, websites/F/FlixTor/presence.ts
Presence were not showing because of the invalid clientId for the presence object. I've replaced it and corrected a bug for the displaying of movies' cover.
close #6485 
<details>
</details>
=> Fix(flixTor): fix presence not showing

websites/H/Homestuck^2/dist/metadata.json
url metadata without `www.` fails to actually support `www.`, this change adds support for both.
<details>
(Screenshot taken with `www.`)
</details>
=> fix(Homestuck^2): corrected domain support

websites/C/Crunchyroll/dist/metadata.json, websites/C/Crunchyroll/presence.ts
Due to the fresh new addition done in the PR #6504, some users were complaining on the Premid's DIscord about the missing of a setting to deactivate or not the showing of the anime cover.
So I've added it.
<details>
</details>
=> feat(Crunchyroll): add showCover setting

websites/N/Neovel/dist/metadata.json
I've forgot to change the color in the metadata file for this presence. So I've patched it.
<details>
</details>
=> fix(Neovel): change presence's color

websites/F/Facebook/dist/metadata.json, websites/F/Facebook/presence.ts
Resolves #6511 by adding an imgur url to the facebook watch logo to the `presenceData.largeImageKey` at the top of the part handling the Facebook watch part of the website.
<details>
</details>
=> feat(Facebook): add facebook watch logo

websites/D/dod Games/dist/metadata.json, websites/D/dod Games/presence.ts
In some cases (when browser window height is low and another case I could not reproduce) the site's "pseudo-URLs" are not showing, so the presence fails to detect open game rooms. I added a fallback game detection method that doesn't rely on URLs to catch those cases.
<details>
</details>
=> fix(dod Games): add alternative fallback game detection

websites/C/Coub/dist/metadata.json, websites/C/Coub/presence.ts
- Fixed top page regex + presence data (null in buttons array wont display presence).
- Added largeImageKeys images (toggleable in settings) for coub channels & communities
- Added Elapsed timestamp (toggleable in settings)
- Removed youtube source buttons
<details>
New Settings (Show community/channel images & Show elapsed time):
Community Images:
Channel Images:
Playing Media:
</details>
=> feat(Coub): buttons, regex, external largeImageKey, elapsed timestamp

websites/T/TruckersMP/dist/metadata.json, websites/T/TruckersMP/presence.ts
- Fixed spelling for "Browsing"
- Fixed buttons displaying when privacy mode is enabled
=> feat(TruckersMP): buttons shouldn't show if privacy mode is enabled

websites/A/AniMixPlay/dist/metadata.json, websites/A/AniMixPlay/presence.ts
Resolves #6585 by adding the cover of the anime when you're on the anime informations page.
~~Sadly, it can't be done for when you're watching an episode since the cover isn't displayed on the episode page.~~ *Finally done by getting it in the metadata of the page.*
I've also added a setting to let the user choose if he want to show the cover or not.
<details>
</details>
=> feat(AniMixPlay): add cover when viewing episode and anime info

websites/F/Facebook/dist/metadata.json, websites/F/Facebook/presence.ts
Resolves #6588 by adding the case of when the user is on an FB watch user's page.
Also, a little grammatical correction, a "Watch" was written "Wattch" lol.
<details>
</details>
=> feat(Facebook): add user's page displaying

websites/T/Twitch/dist/metadata.json, websites/T/Twitch/presence.ts
Thanks @Bas950 for the help to understand better some case in the code !
- fix user's tab display when viewing an user
- fix tab display in settings
- remove friends part, since this feature has been removed by Twitch
- fix display of the searching keywords when you search something on Twitch
- fix displaying of the currently activeDrop the user is viewing
- fix subscriptions' tab display -> **should be localized to remove the word "Subscriptions" in every language (actually available in English and French)**
- fix wallet's tab display
- fix directory following part's tab display
- fix game name display in esport category
- fix display of the currently viewed category
- fix directory part's tab display
<details>
<summary> Proof showing the creation/modification is working as expected …
=> fix(Twitch): fix several querySelectors and remove useless code

websites/F/Facebook/dist/metadata.json, websites/F/Facebook/presence.ts
Resolves #6218 and Resolves #6602 by adding the support for Facebook's reels.
Also Resolves #6606 by adding a work around for the query of the user's page name depending of the UI.
<details>
</details>
=> feat(Facebook): add reels support and fix bad display

websites/M/MangaDex/dist/metadata.json, websites/M/MangaDex/presence.ts
- Redo all the codebase by removing if/else statements for a switch.
- Add buttons w/ setting to disable them
- Add cover w/ setting to disable them, Resolves #6664 
- Add enum for Assets such as Logo, Searching image key, etc...
- Add a func to retrieve the cover to display with the website's API when the user is reading a chapter
- Add myself as contributor to the presence (currently discussing with the current author to swap property to me).
<details>
</details>
=> refactor(MangaDex): redo all codebase and add features

websites/T/Tellingtone/dist/metadata.json, websites/T/Tellingtone/presence.ts
Fix an error on the querySelector for the episode currently listened. The title displayed was always the first one and not the listened to.
<details>
</details>
=> fix(Tellingtone): fix bad display on episode name

websites/V/VLC/dist/metadata.json, websites/V/VLC/presence.ts
Fix an error on formatting for `'`. Quite ugly (since it's a for loop on all values of `media`), but I didn't achieve a better way to avoid the problem.
Also fix a bad displaying : title of a song and some other things were not displayed in some cases.
Thanks to Sammie on Discord (@Sammie0210 on Github) for the help on what should be normally displayed !
_Version 1.4.31 xD_
<details>
</details>
=> fix(VLC): fix formatting error and display

websites/Y/YouTube/dist/metadata.json, websites/Y/YouTube/presence.ts
- Resolves #6678 
For some reasons when browsing YouTube (there's multiple cases, for me it was when you're at your subscriptions page, you go home, and you choose a random vid), the wrong channel name was displayed.
It's due to this part of the code : 
In fact, for some reason, the `uploader` value can be null, but not the `uploaderTV`. OR, when the `finalUploader` variable is initialized, it takes the `uploaderTV` value before the `uploader` one.
So It cause this behavior : 
The `finalUploader` is okay first, the `uploaderTV` is okay too BUT the `uploader` is null. It triggers the `if` statement, changing the `finalUploader` to a wrong value.
So I've edited the if to check the `uploaderTV` too.
<details> …
=> fix(YouTube): fix wrong channel name display

websites/S/SOAP2DAY/dist/metadata.json, websites/S/SOAP2DAY/presence.ts
- Resolves #6687 by adding a setting to display the name of the show/movie/etc currently viewed if enable (disabled by default !)
_Note : when the title of the show/movie/etc... is the same as the one in the video, it will be deleted from the `presenceData.state`._
- Change code structure to avoid useless indent and lines
- Remove some variables in consequence
- Remove useless comment
- Add myself as contributor
<details>
</details>
=> refactor(SOAP2DAY): change code structure and add setting

websites/M/myCANAL/dist/metadata.json, websites/M/myCANAL/presence.ts
Added functionality that allows the user to choose whether or not to display a show's or movie's cover. I also fixed some tiny presence bugs 
<details>
</details>
=> feat(myCanal): add Show Cover setting

websites/F/Facebook/dist/metadata.json, websites/F/Facebook/presence.ts
Fixed the check for viewing photo's on someone's profile.
<details>
</details>
=> fix(Facebook): url for photo on profile

websites/S/Stack Overflow/dist/metadata.json, websites/S/Stack Overflow/presence.ts
Add buttons for Stack Exchange websites, as requested in the closed PR #6751. Also, I've moved the browsingTimestamp at the initialisation of the `presenceData`, to avoid repetition.
<details>
</details>
=> feat(Stack Overflow): add buttons with setting

websites/S/Stack Exchange/dist/metadata.json, websites/S/Stack Exchange/presence.ts
Add buttons for Stack Exchange websites, as requested in the closed PR #6751.
<details>
</details>
=> feat(Stack Exchange): add buttons with setting

util/tools/metadataSorter.ts
Fixes a problem in the metadata sorter that prevents it from actually sorting the correct metadata file.
<details>
</details>
=> fix(metadataSorter): fix not sorting metadata

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
Split the two scenarios (not cached & different id) and Added a delay so it doesn't show the wrong short uploader when it's played. 
<details>
</details>
=> fix(Youtube): fix shorts

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
Resolves #6842 Fixed bug that uploader was used after watching a short.
<details>
</details>
=> fix(Youtube): wrong uploader after short

.github/CODEOWNERS
Signed-off-by: Rhys Rakoff <64903135+EncryptedDev@users.noreply.github.com>
CODEOWNERs are not needed on this repo because we have a different process of requesting reviews by maintainers to reduce crossover
=> chore: delete codeowners

websites/D/Desu-Online/metadata.json, websites/D/Desu-Online/presence.ts
* If the episode title had a `-` character, it only displayed the first title segment before the `-` character in the status. This commit fixes that
<details>
</details>
=> feat(Desu-Online): fix for episode title

util/tools/auto/presenceUpdater.ts
Fixes the undefined `__dirname` error in the presence updater which was missed in a previous PR.
Reopened from #6920 (ci rewrite doesn't appear to be becoming merged soon?)
=> workflow(presenceUpdater): fix __dirname error

tsconfig.json
Ref: https://www.typescriptlang.org/tsconfig#moduleResolution
turns out module esnext needs this I think?
=> chore: set moduleResolution to nodenext

websites/0-9/9anime/metadata.json, websites/B/Buienalarm/metadata.json, websites/D/Desu-Online/metadata.json, websites/M/myCANAL/metadata.json, websites/R/RTL+/metadata.json, websites/S/Shikimori/metadata.json, websites/S/Shoob/metadata.json, websites/S/Stake/metadata.json, websites/S/SteamDB/metadata.json, websites/V/Videoland/metadata.json
This Pull Request bumps the version on a few presences which were merged when the `CD`/`DePloY`/`Update Presences` action began to fail. 
|  Presence  | Displayed Version  | Original PR Version   | Bumped Version  | PR Reference  |
|---|---|---|---|---|
| Buienalarm  | New Presence  | `1.0.0`  | `1.0.1`  | #6874  |
| Stake  | New Presence   | `1.0.0`  | `1.0.1`  | #6875   |
| SteamDB  | `1.0.10`   | `1.1.0`  | `1.1.1`  | #6908 |
| VideoLand | `1.1.0` | `1.2.0`| `1.2.1` | #6912
| Desu-Online | `1.0.0`| `1.0.1` | `1.0.2` | #6913
| 9anime | `1.3.1` | `1.4.0` | `1.4.1` | #6935
| myCANAL | `1.2.1` | `2.0.0` | `2.0.1` | #6895
| TVNOW  | Deleted | N/A | N/A | #6928 
| RTL+ | New Presence | `1.0.0` | `1.0.1` | #6928 
| Shikimori | `1.0.3` |`1.1.0` | `1.1.1` | #6921
| Shoob | New Presence | …
=> chore: bump presences to update store versions

package.json, tools/classes/PresenceCompiler.ts, tools/util.ts
This PR addresses the issue mentioned by @theusaf in #6923 and solves it by adding an empty line after the compiled file:
This PR also adds back the uncommitted "event option" as this makes running the script locally for testing/development possible.
=> fix(CD): add an empty line after sourcemap

tools/auto/presenceUpdater.ts, tools/util.ts
* Corrects the order of sources in getting diffs
* Allows new presences to be detected and uploaded
* Allows deleted presences to be detected and deleted
* Adds a check for changed presences before writing
* Avoids preventing a presence from being deleted
=> fix(presenceUpdater): correctly detect changed folders

.github/workflows/CI.yml, tools/util.ts
By default, git will print non-ASCII file names in quoted octal notation, and this disabled that.
=> chore: set core.quotePath to false on getDiff()

.github/renovate.json
previous cron was "At _every minute_ past hour 17 on Friday.", this is "At 17:00 on Friday."
=> chore: fix invalid renovate cron

websites/F/Facebook/metadata.json, websites/F/Facebook/presence.ts
This pr fixes the following:
- Resolves #6122
<details>
<summary>Facebook gaming</summary>
</details>
<details>
<summary>Facebook watch</summary>
</details>
=> fix(Facebook): fix fb.watch & fb.gg profile names

websites/K/Kinopub/iframe.ts, websites/K/Kinopub/metadata.json, websites/K/Kinopub/presence.ts
Add presence for Kinopub
Settings:
1. Private mode.
2. Show remaining listening/viewing time.
3. Showing movie/serial covers.
4. Show buttons.
<details>
</details>
=> feat(Kinopub): add presence

websites/G/GitHub/metadata.json, websites/G/GitHub/presence.ts
Closes #7070
Fixed the code bugging when showing a pr outisde of the discussions tab.
<details>
</details>
=> fix(Github): show in all PR tabs

.github/workflows/CI.yml
This PR disables CI that would happen on the Push event, reason being that a PR already runs CI and when CI would fail on that PR the PR should not be accepted in normal circumstances. It's just double trouble for the same result.
=> chore: remove ci on push

websites/V/Vodafone FM/metadata.json, websites/V/Vodafone FM/presence.ts
Added a new Presence for [Vodafone FM](https://vodafone.fm), a famous Portuguese FM radio.
Do let me know if this qualifies as a valid Presence as the Contribution guide wasn't fully clear for me.
```
Presences for online radios are only allowed if the radio has at least 100 weekly listeners and 15 concurrent
and must have some features other than just showing album/song title, etc.
```
Are the mentioned features about the radio or the Presence?
Thanks in advance!
<details>
</details>
=> feat(Vodafone FM): add new presence

websites/A/Apple TV+/metadata.json, websites/A/Apple TV+/presence.ts
The Apple TV+ website got updated and made the presence break, so I pretty much adapted the code to the new changes.
Resolves #7054
<details>
<summary>Profile</summary>
</details>
<details>
<summary>Home</summary>
</details>
<details>
<summary>Watching</summary>
</details>
=> fix(Apple TV+): fix breaking bugs

websites/A/Animes Vision/metadata.json, websites/A/Animes Vision/presence.ts
Animes Vision has a big logo for discord presence on pages like home and for pages like episode, the logo don't exist
<details>
old version
new version
</details>
=> fix(Animes Vision): logo

.gitignore
Adds `pnpm-lock.yaml` to the gitignore
=> chore: add correct pnpm lockfile to gitignore

websites/S/signed.host/metadata.json, websites/S/signed.host/presence.ts
Addition of signed.host, a private media, and bio page hosting service.
<details>
</details>
I'll be happy to provide additional information in order for the process be sped up.
=> feat(signed.host): add presence

.github/CONTRIBUTING.md
- Removes `tsconfig.json` references
- Updates the names of PR checks
- Specifies 512x512px for logo image
=> docs(Guidelines): update for up-to-date guidelines and structure

websites/T/Tidal/metadata.json, websites/T/Tidal/presence.ts
I recently noticed that the artist list looked like this:
notice how there are no commas seperating the artists.
This pull request fixes the formatting of artists.
<details>
After changes:
</details>
=> fix(Tidal): fix artists not being seperated after update

websites/W/Wolfy/metadata.json, websites/W/Wolfy/presence.ts
Changed all selectors to just search in class the string that we want, due to the fact that the and of each class name are randomly re-generated during a website update
=> refactor(Wolfy): Change static selectors to more polyvalent

websites/S/Shikimori/metadata.json
Changed URL of [Shikimori](https://shikimori.me/): shikimori.one -> shikimori.me
<details>
| Home | User's Page | Anime Page |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/37224822/236697400-6b98c4e5-b410-4436-914c-fadd1c55e6d8.png) | ![image](https://user-images.githubusercontent.com/37224822/236697280-e2a94b56-1f9c-4033-9295-338ea63409ea.png) | ![image](https://user-images.githubusercontent.com/37224822/236697437-f96c1ade-9fc0-4e03-9395-ef0e40b2d7a9.png) |
</details>
=> fix(Shikimori): update url

websites/I/ITVX/metadata.json, websites/I/ITVX/presence.ts
ITVX has slightly changed the structure of the NEXT_DATA page props, and as a result broke the ability to correctly display the presence when viewing live channels.
<details>
</details>
=> fix(ITVX): fix live channel presence due to data structure change

websites/S/SVT Play/metadata.json, websites/S/SVT Play/presence.ts
Since the current presence version of the website doesn't work with the old query selectors, they have now been fixed to work with the latest changes to the SVT Play website.
<details>
> COMMENT: SVT Play seems to now use a set duration/timecode when watching live broadcasts via "/video/" instead of showing how much time has passed since the broadcast started. This means that for live material watched through the "/video/" path, the "fetched" time will be a "left" time.
</details>
=> fix(svtplay): update query selectors

websites/W/WaniKani/metadata.json, websites/W/WaniKani/presence.ts
* Uses Imgur links instead of Discord asset names
* Updates paths and selectors for the lessons/reviews
<details>
</details>
=> fix(WaniKani): update paths, selectors, and assets

websites/S/Songsterr/metadata.json, websites/S/Songsterr/presence.ts
I added support for songsterr.com, a website for searching instruments' tabs. It's one of the most popular ones.
<details>
</details>
=> feat(Songsterr): add presence

package.json
This should prevent issues where the format/lint command needs to be run twice to resolve all issues.
Eslint can change files to a state that prettier does not like, so eslint should run first
=> chore: rearrage lint commands

websites/M/Mastodon/metadata.json, websites/M/Mastodon/presence.ts
I added timestamps, privacy mode and a new pathname. The masto.ai instance is supported now
<details>
</details>
=> feat(Mastodon): add timestamps, privacy mode and a new pathname

websites/G/GitHub/metadata.json, websites/G/GitHub/presence.ts
This PR fixes the `org` page
<samp>see screenshots.</samp>
<details>
- shows nothing.
- displaying the user profile instead of organization profile.
- wrong title. (it displays `Global Navigation`)
</br>
**privacy mode on**
**privacy mode off**
**privacy mode on**
**privacy mode off**
</details>
=> fix(GitHub): organization page

.gitignore, package.json
Due to the size of the project, this *significantly* decreases the runtime of repeat invocations of `npm run lint` in my case.
(Prettier's cache doesn't need to be added to `.gitignore` as it's stored in `node_modules`.)
=> perf: cache eslint and prettier

websites/S/Stremio/metadata.json, websites/S/Stremio/presence.ts
Add support for the new Stremio web (a.k.a Stremio 5) domain and add improvements to the old domain (Stremio 4) and website.
I work closely with the Stremio team and community. We find it necessary for the Stremio presence to support the following features at minimum:
- Support Stremio 5, 4 and the website
- Due to the nature of some addons (e.g. adult content), showing search queries in Discord activities should be a setting (turned **off** by default)
- In case of Stremio 5, favor usage of [stremio core](https://github.com/Stremio/stremio-core) to fetch information when possible.
There's another PR https://github.com/PreMiD/Presences/pull/7457 opened a few days ago by @DarkVillager, which lacks some of the features above and implements a few things differently. I'll leave the choice up …
=> feat(Stremio): add Stremio 5 & rewrite presence

websites/B/bilibilitv/metadata.json, websites/B/bilibilitv/presence.ts
1. The thumbnail was not being displayed correctly due to an incorrect parsing of the `og:image` property.
2. Resolved the "Cannot read properties of null" error that occurred when trying to access the `textContent` property of certain elements.
<details>
<summary>Proof showing the creation/modification is working as expected</summary>
</details>
=> fix(bilibilitv): thumbnail and null property access error

websites/M/myCANAL/metadata.json, websites/M/myCANAL/presence.ts
Changed the selector path for the img tag, as it was deprecated once again.
<details>
</details>
=> fix(MyCanal): rechanged path for channel's img tag

websites/R/Rádio Animu/metadata.json, websites/R/Rádio Animu/presence.ts
Added a fallback message for any part of the site that is unimplemented in the presence because of the existence of temporary event/easter egg(ish) pages that don't really need to be defined in the presence.
Before this commit, it would only show the default question block image with the name of the instance in these pages.
<details>
</details>
=> fix(Rádio Animu): add a fallback message

websites/T/Tidal/metadata.json, websites/T/Tidal/presence.ts
Another update from Tidal that required changing the selectors.
<details>
Before:
After:
</details>
=> fix(Tidal): update songTitle selector to account for update

tools/classes/AssetsManager.ts
Resolves an import mistake in the `AssetManager`.
=> chore(AssetsManager): fix util import

websites/F/FMovies/metadata.json, websites/F/FMovies/presence.ts
Previous code did not dynamically update the season and episode. It would require a manual reload for changes to take place. With the current code, it dynamically obtains the season and episode from the URL, so the season and episode will always be up to date on the Discord Rich Presence.
=> fix(FMovies): Fix Season and Episode Bug

websites/T/Tidal/metadata.json, websites/T/Tidal/presence.ts
Another update from Tidal that changed specificallly the song title selector, we're now using the attribute instead of a random class which should lead to more persitent functionality.
<details>
</details>
=> fix(Tidal): update selector

websites/M/Mastodon/metadata.json
I added social.vivaldi.net as a supported url
Resolves #7558
</details>
=> feat(Mastodon): add social.vivaldi.net as a supported url

websites/D/Discord.js/metadata.json, websites/D/Discord.js/presence.ts
Discord.js docs have moved to old.discordjs.dev while then remake the docs. I have added regex that supports the old docs url and the current docs url
<details>
</details>
=> fix(discord.js): url didnt support old docs

websites/I/ITVX/metadata.json, websites/I/ITVX/presence.ts
ITVX has slightly changed the structure of the NEXT_DATA page props, and as a result broke the ability to correctly display the presence when watching videos.
=> fix(ITVX): fix videos presence due to data structure change

tools/util.ts
When checking for `deleted` only check if they are metadata files. Not tested but should work
=> chore: fix util.getDiff('removed')

websites/R/Reaper Scans/metadata.json, websites/R/Reaper Scans/presence.ts
Updates the query selectors for the percentage. This fixes the errors in the console when reading a comic.
<details>
</details>
=> fix(Reaper Scans): update query selector for reading percentage

websites/V/VtuberWiki/metadata.json, websites/V/VtuberWiki/presence.ts
Fixed typo Vuber -> Vtuber and fixed images from being broken.
<details>
</details>
=> fix(VtuberWiki): fixed typo and missing images

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts, websites/Y/YouTube/util.ts, websites/Y/YouTube/video_sources/default.ts, websites/Y/YouTube/video_sources/embed.ts, websites/Y/YouTube/video_sources/movies.ts, websites/Y/YouTube/video_sources/old.ts, websites/Y/YouTube/video_sources/shorts.ts, websites/Y/YouTube/video_sources/tv.ts
* Refactors the code
* Removes lots of duplication of code
* Uses `switch(true)` to replace long if-else chains
* Moves various title/uploader queries into separate files/methods
* Removes unneeded typing and other inconsistencies
* Fixes
* Viewing a playlist now works
* Potentially resolves viewing a video again?
* Notes/Observations
* The old YouTube code may not be needed (new YouTube layout seems to be forced now?), but keeping it just in case.
* Unsure if there is a difference between YouTube movies and videos in terms of query selectors
<details>
</details>
=> feat(YouTube): refactor and update selectors

websites/A/atomicradio/metadata.json, websites/A/atomicradio/presence.ts
A query selector for the title has been adapted as the presence no longer worked. The play / pause icons were set incorrectly so I have now corrected this. The user is no longer shown the Space Ids but the actual Space name.
<details>
</details>
=> feat(atomicradio): fix presence and added space names

websites/D/draw.io/metadata.json, websites/D/draw.io/presence.ts
Add presence for draw.io (AKA diagrams.net)
<details>
</details>
=> feat(draw.io): add presence

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts, websites/Y/YouTube/util.ts
The likely cause of "YouTube not working" was that the `lang` setting never loaded or timed out.
Changes:
- prevents presence from failing to show when `lang` setting doesn't load
- defaults to `en` language
- fetches strings and settings in background intervals
- Resolves #7709
<details>
</details>
=> perf(YouTube): add fallback to settings retrieval

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
https://discord.com/channels/493130730549805057/1181769179070734398
The issue is still there and will have to be looked into.
Only added null check, to prevent error / presence freezing
Currently, the listen along button won't lead to the actual song
If possible, it now takes the `watchID` from the url
=> fix(YouTube Music): no href temp fix

websites/X/X.com/metadata.json, websites/X/X.com/presence.ts
* Removes creation of `Presence` objects every `UpdateData`
* Only changes presence when setting is changed
* Loads settings in parallel
* Doesn't hide twitter setting
* Not sure where that arbitrary 224 value came from, especially since it was added to a presence when the latest stable version is 223. It should still work.
* Refactors code with latest guidelines
<details>
</details>
=> perf(X.com): remove unnecessary creation of presence objects

websites/W/wumpus.store/metadata.json, websites/W/wumpus.store/presence.ts
Presence for Wumpus.store. Displays what bot you are viewing along with buttons to vote for the bot on the site. Also displays when you are adding a bit, searching for one or viewing the homepage.
<details>
</details>
=> feat(wumpus.store): add presence

websites/G/GitHub/metadata.json, websites/G/GitHub/presence.ts
- fixes showing wrong image
- adds better null checks for images
- fixes organization repositories tab not showing
- fixes users pronouns showing in name
<details><summary>screenshots</summary>
<p>
</details> 
</p>
=> fix(GitHub): fix images & show org repo's tab

websites/T/Tetris/iframe.ts, websites/T/Tetris/metadata.json, websites/T/Tetris/presence.ts
* Adds a presence for Tetris
* Adds articles and gameplay
* Needs custom js injection for game to find deep-buried fields
* Resolves #5475 
<details>
</details>
=> feat(Tetris): add presence

websites/O/Otakudesu/metadata.json
changing from **otakudesu.bid** to **otakudesu.cam**
<details>
</details>
=> fix(Otakudesu): changing to new url domain (.cam)

websites/I/Is it Christmas/metadata.json, websites/I/Is it Christmas/presence.ts
Adds a presence for isitchristmas.com
Eslint rule is to deal with https://github.com/Bas950/eslint-plugin-no-one-time-vars/issues/10
<details>
</details>
=> feat(Is it Christmas): add presence

websites/J/Jackbox/metadata.json, websites/J/Jackbox/presence.ts
* Updates the Jackbox presence's usage of `getLogs` to match current types
=> refactor(Jackbox): update `getLogs` usage

websites/T/Taiyō/metadata.json, websites/T/Taiyō/presence.ts
- New route on the dashboard
- New button in the reader
- Refactored code to "switch case"
- Manga cover in the reader
- News Altnames
New button and cover in the reader
=> refactor(Taiyō): add button, new page and refactor code

websites/V/Vidoza/metadata.json, websites/V/Vidoza/presence.ts
- Added presence for vidoza (since some series/movies/anime websites now just send you to video hosting sites like vidoza. E.g. s.to & aniworld.to)
<details>
</details>
=> feat(Vidoza): add presence

websites/D/Doodstreams/metadata.json, websites/D/Doodstreams/presence.ts
- Added presence for doodstreams (since some series/movies/anime websites now just send you to video hosting sites like doodstreams. E.g. s.to & aniworld.to)
<details>
</details>
=> feat(Doodstreams): add presence

websites/K/KEXP/metadata.json, websites/K/KEXP/presence.ts
- Add presence for [KEXP](https://kexp.org/)
- The presence updates based on whether the radio is being listened to or not
- The presence image is taken from the cover of the currently playing song; if not available, it uses the station logo
- It includes a button to listen along simultaneously
- If there's no song playing, only the show name is shown
- Given support for the following parts of the page: [archive](https://kexp.org/archive/), [podcasts](https://kexp.org/podcasts/), [shows](https://kexp.org/shows/), [djs](https://kexp.org/djs/), [schedule](https://kexp.org/schedule/)
- Shows information about articles if the user is reading one, take these articles as examples:
- [50 Years of Hip-Hop](https://kexp.org/podcasts/50-years-of-hip-hop/) under Podcasts
- …
=> feat(KEXP): add presence

websites/K/KEXP/metadata.json, websites/K/KEXP/presence.ts
- Changed the thumbnail in the hopes of making it look better on the store.
- Multilingual support.
- Changed the copies for the `smallImageText` in some cases, since I was using the same copy for the `details` and `smallImageText`, which in some cases doesn't look good (e.g.`Viewing:` as `smallImageText`).
- Made a little refactor for the `setDetails` function to avoid using the `document.querySelector` on every case statement.
- Added support for the articles under the `/read/` route.
<details>
In Spanish:
</details>
=> feat(KEXP): copies and thumbnail improvements

websites/S/SoundCloud/metadata.json, websites/S/SoundCloud/presence.ts
- Add toggle to chose whether presence is hidden when nothing is playing and browsing status is disabled
- Fix TS2339 'string | Node' (line 269)
<details>
<image src="https://github.com/PreMiD/Presences/assets/150862116/6cc30dab-eb9a-45fa-a122-bc06e79dc9a2">
Active playback:
<image src="https://github.com/PreMiD/Presences/assets/150862116/0ea4fab3-edac-4a8d-a5ef-f307f15ef041">
Inactive playback - 'hide while paused' enabled, 'browsing status' disabled
<image src="https://github.com/PreMiD/Presences/assets/150862116/827e0f5e-621b-4aa9-af5e-43aaee95dacd">
Inactive playback - 'hide while paused' enabled, 'browsing status' enabled
<image src="https://github.com/PreMiD/Presences/assets/150862116/9c94c09b-5614-46 …
=> feat(SoundCloud): add hide when paused

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts, websites/Y/YouTube/util/index.ts, websites/Y/YouTube/util/pvPrivacyUI.ts, websites/Y/YouTube/video_sources/default.ts, websites/Y/YouTube/video_sources/embed.ts, websites/Y/YouTube/video_sources/movies.ts, websites/Y/YouTube/video_sources/old.ts, websites/Y/YouTube/video_sources/shorts.ts, websites/Y/YouTube/video_sources/tv.ts
* Removes the shorts cache and uses different selectors and checks to retrieve the current title/user
* Adds a method to resolvers for fetching channel urls
* Fixes #7934 
<details>
</details>
=> fix(YouTube): remove shorts cache

websites/Y/YouTube/metadata.json, websites/Y/YouTube/util/pvPrivacyUI.ts
* Makes the hover text ignore pointer events, no longer blocking interaction with the title behind it.
* Fixes #7977 
<details>
</details>
=> fix(YouTube/pvPrivacyUI): stop privacy ui from blocking interactions

websites/B/BeatLeader/iframe.ts, websites/B/BeatLeader/metadata.json, websites/B/BeatLeader/presence.ts
Pass image element directly into LargeImageKey instead of .src so the covers for OST maps (which are blobs) work
In Iframe.ts send cover as DataURL, because of potential blobs
Updated regExp for URL
Added fallbacks for getting difficulty and mode from leaderboard pages
<details>
</details>
=> feat(BeatLeader): add OST blob images support

websites/J/Jet Set Radio Live/metadata.json, websites/J/Jet Set Radio Live/presence.ts
This PR adds updates to the Jet Set Radio Live presence:
- Use "Listening" type for v2.6
- Use images as large image keys
- Update station names
- Remove "Paused" small image when not tuned in
<details>
<summary>Presence Screenshot</summary>
</details>
=> feat(Jet Set Radio Live): use v2.6 types, images, new stations

tools/classes/AssetsManager.ts
* Passes only the pathname to path.extname, rather than the entire url
=> fix(AssetsManager): ignore query selector when extracting file extension

websites/A/AniWatch/metadata.json
In many countries like India, the main domain (aniwatch.to) has been inaccessible for a while. Aniwatchtv.to is an official proxy site that works for now.
<details>
<summary>Proof of working</summary>
Without:
<br>
With:
</details>
=> feat(AniWatch): add aniwatchtv.to proxy

websites/M/MangaLife/metadata.json, websites/M/MangaLife/presence.ts
The API used before has been shut down, so the cover no longer works. I've used the one MangaLife currently uses in this PR.
<details>
</details>
=> fix(MangaLife): use working api for cover

websites/T/TuMangaOnline/metadata.json, websites/T/TuMangaOnline/presence.ts
Closes #7929 
Add the new visortmo.com domain. This domain gets redirected from the original domain.
<details>
</details>
=> fix(TuMangaOnline): add new redirect domain

websites/T/Tumblr/metadata.json, websites/T/Tumblr/presence.ts
Closes #7984
The existing tumblr presence did not have support for (username).tumblr.com
I have added a simple default case which will check if the page is a profile exactly like the way it is determined in the www.tumblr.com subdomain.
<details>
</details>
=> feat(Tumblr): add support for subdomain profiles

websites/I/iHeartRadio/metadata.json, websites/I/iHeartRadio/presence.ts
Closes #8056
I've inversed the statement that determines whether the user is browsing or playing a radio.
<details>
</details>
=> fix(iHeartRadio): inverse statement determining state

websites/O/Otakudesu/metadata.json
Closes #8014
Uses otakudesu.cloud domain, which is redirected to by the original domain otakudesu.cam
<details>
</details>
=> fix(Otakudesu): use new domain

websites/H/HBO Max/metadata.json
Closes #7371 
Adds regExp option to enable all subdomains on domains hbomax.com and max.com
<details>
In max.com:
</details>
=> feat(HBO Max): add regex

websites/A/AniWatch/metadata.json, websites/A/AniWatch/presence.ts
Closes #8146
Adds HiAnime.to domain support.
Note: The application name needs to be changed when they completely phase out the name AniWatch.
<details>
</details>
=> feat(AniWatch): add HiAnime rebrand

websites/I/Incels.is/metadata.json, websites/I/Incels.is/presence.ts
Added "incels.is". There is really not much else to it. Depending on which sites you visit within incels.is, the funny text in your Discord presence changes. And it also shows you how long you have been on the same page for.
Disclaimer: When you share their website link, you get an embedded image. I took that image, and am using it for both the logo, as it meets the size requirements, and the thumbnail, as it is the official "thumbnail" of the website URL. Hope that works!
<details>
</details>
=> feat(Incels.is): add presence

websites/A/Audible/metadata.json, websites/A/Audible/presence.ts
Replaced old element selectors for webplayer, that were no longer valid. Added chapter information to state as well as timestamps.
<details>
</details>
=> fix(Audible): replace broken selectors on webplayer, add chapter info and timestamps

websites/L/Library of Babel/metadata.json, websites/L/Library of Babel/presence.ts
I fixed a bug where if the user was viewing a bookmark or anglicized page, the presence wouldn't show the page or title. I also removed the "page number" from the bookmark presence status as bookmarks are single page only.
<details>
</details>
=> feat(Library of Babel): fix presence bug

websites/M/movie-web/metadata.json
Added sites from the official movie-web docs, and removed the old non working ones since the takedown.
<details>
The screenshots will look literally exact same.
</details>
=> feat(movie-web): add more sites from official docs

websites/J/Japanese Mahjong Wiki/metadata.json, websites/J/Japanese Mahjong Wiki/pages/special.ts, websites/J/Japanese Mahjong Wiki/pages/static.ts, websites/J/Japanese Mahjong Wiki/presence.ts, websites/J/Japanese Mahjong Wiki/util/util.ts
Adds a presence for the Japanese Mahjong Wiki (riichi.wiki)
<details>
</details>
=> feat(Japanese Mahjong Wiki): add presence

websites/M/Mahjong Soul/metadata.json, websites/M/Mahjong Soul/presence.ts
Adds the Japanese version domains to the metadata. The internal code and structure appears to be the same
=> feat(Mahjong Soul): add more domains

websites/I/Incels.is/metadata.json
Removes the `nsfw` tag from the metadata by request of the original author. The service/presence does not appear to have an NSFW focus.
=> refactor(Incels.is): remove nsfw tag

websites/B/bilibilitv/metadata.json, websites/B/bilibilitv/presence.ts
Does not appear or is not detected when watching anime.
This happens when I use the search feature on bilibili and start watching but the Activity Tab doesn't show that I'm watching but in details I'm browsing on the home pages
Because there is no `id` or `en` after `play`
for example:
https://www.bilibili.tv/play/2090295
not like:
https://www.bilibili.tv/en/play/2090295
<details>
[Link Anime](https://www.bilibili.tv/en/play/2097863)
[Link Anime](https://www.bilibili.tv/play/2090295)
</details>
=> fix(bilibilitv): not detect watching an anime

websites/N/Neko-sama.fr/metadata.json, websites/N/Neko-sama.fr/presence.ts
Before, when an episode didn't have a thumbnail, the default logo of neko-sama was displayed.
Now, when an episode doesn't have a thumbnail, the anime thumbnail is displayed (and if there's no anime thumbnail, then the default thumbnail is displayed).
I also fixed the domain name, which was replaced by "animecat.net"
Before the bug fix:
Before the feature:
After:
</details>
=> feat(Neko-sama.fr): display anime img if episode img is not present

websites/R/Reddit/metadata.json
Reddit's layout changed and the old one can be found at new.reddit.com. This URL was added so the presence can work on there as well.
=> feat(Reddit): Add support for old layout

websites/O/Ongaku/metadata.json, websites/O/Ongaku/presence.ts
Integrate PreMiD presence for Ongaku to display the current song playing.
<details>
</details>
=> feat(Ongaku): add presence

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts, websites/Y/YouTube/video_sources/api.ts, websites/Y/YouTube/video_sources/default.ts, websites/Y/YouTube/video_sources/miniplayer.ts, websites/Y/YouTube/video_sources/old.ts
- Updates the `default` resolver to work for new layout
- Moves older selectors to `old` resolver
- Separates miniplayer selectors into new `miniplayer` resolver
- Default resolver falls back to url parameters
- API resolver should not throw errors constantly if things don't exist
- Fixes #8049
- Fixes #8269
<details>
</details>
=> fix(YouTube): add support for new layout

websites/O/Ongaku/metadata.json, websites/O/Ongaku/presence.ts
=> chore(Ongaku): update assets

websites/M/Minecraft Wiki/metadata.json, websites/M/Minecraft Wiki/presence.ts, websites/M/Minecraft Wiki/util.ts
- Resolves #8281
<details>
</details>
=> feat(Minecraft Wiki): add presence

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
* Changed all `ActivityType.Listening` to `ActivityType.Playing` so the timestamps are actually displayed
* Added the "Use Time Left" setting that allows a user to switch between displaying the time left and displaying the time elapsed
<details>
</details>
Resolves https://github.com/PreMiD/Presences/issues/8262
=> fix(Youtube Music): timestamps

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
Added a toggle that clears/hides the presence when the video is paused.
resolves https://github.com/PreMiD/Presences/issues/8061
<details>
</details>
=> fix(YouTube): added auto-hide option

websites/B/bilibili/metadata.json, websites/B/bilibili/presence.ts
I added an option that just displays any video being watched as "watching a video"
resolves https://github.com/PreMiD/Presences/issues/8125
<details>
</details>
=> fix(bilibili): add privacy mode

websites/A/AnimeDrive/iframe.ts, websites/A/AnimeDrive/metadata.json, websites/A/AnimeDrive/presence.ts
I added support so know you can see how much is left from an Anime.
Added hungarian translation to the metadata.json and the iframe things.
<details>
</details>
=> feat(AnimeDrive): add support for iFrame and Hungarian description

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
Came across instance where channel name and selected tabs were not showing up in Presence (`undefined` and `null` respectively)
Line 330: Adjusted an `if` statement that was causing channel name to be reported as `null` when an element on page was not found (`String.includes('')` is always true)
Line 349: Changed querystring to properly find selected tab of viewed content (Featured, Videos, ...) as it was returning `undefined`
<details>
</details>
=> fix(youtube): channel name and viewed content

websites/P/Pocket Casts/metadata.json, websites/P/Pocket Casts/presence.ts
PocketCasts stopped working and spams the console with errors, some minor selector changes to fix it
<details>
</details>
=> fix(PocketCasts): update broken selectors

websites/D/Discord/metadata.json, websites/D/Discord/presence.ts
This PR fixes the bug where if you navigated to a dm channel, the console would be flooded with `cannot read properties of undefined`
fixes  #8372 
<details>
</details>
=> fix(Discord): update serverChannel selector

websites/R/Radio Garden/metadata.json, websites/R/Radio Garden/presence.ts
This PR fixes a bug, where if you navigated to the `All Stations` menu, the extension would grab the "All Stations" string, instead of the current country.
reproduction note: you can reproduce the bug by navigating to the  [/channels/](http://radio.garden/visit/damascus/8ElQnK3h/channels) route
<details>
</details>
=> fix(RadioGarden): update broken selector

websites/C/Codewars/metadata.json, websites/C/Codewars/presence.ts
- Fixed a major issue that prevented anything besides "Browsing..." from being displayed in the description
- Added a small feature that shows the difficulty of the kata being searched for
<details>
</details>
=> fix(Codewars): show states aside from browsing

websites/C/ChatGPT/metadata.json
Increased version number from 1.0.6 to 1.0.7 as this is a minor change that doesn't affect the functionality of the presence
Changed URL to `chatgpt.com` following ChatGPTs new domain from `chat.openai.com`
=> fix(ChatGPT): change url

websites/S/Songsterr/metadata.json, websites/S/Songsterr/presence.ts
Presence was not working as expected in the previous version as "#sticky-list-header" is no more a thing. Also, since complementary role is also available when doing a search, the condition was blocking details to change accordingly for search. Rewritten the problematic part. Also made details title-case as it is more consistent and aesthetic.
<details>
</details>
=> fix(Songsterr): fix search tab not showing and make details title-case

websites/P/Prime Video/metadata.json
This pull request updates the regular expression pattern for Prime Video URLs to include URLs without specific paths, such as https://www.amazon.co.jp. The updated regular expression ensures broader compatibility with various Amazon and Prime Video domains. Additionally, minor description updates for multiple languages are included.
<details>
</details>
=> fix(Amazon Prime Video): amazon prime video regExp support japan amazon

websites/B/BeatLeader/metadata.json
Hopefully makes the RegExp of the BeatLeader presence not inject into every website that ends in .net
<details>
</details>
=> fix(BeatLeader): fix broken regexp

websites/A/Apple Music/metadata.json, websites/A/Apple Music/presence.ts
Changes the Apple Music presence from `Playing` to `Listening` with a setting to change between the two.
-  [x] I linted the code by running `yarn format`
Proof showing the creation/modification is working as expected </summary>
=> feat(Apple Music): add listening setting

websites/S/Stremio/metadata.json, websites/S/Stremio/presence.ts
Fixes a bug in the Stremio presence where the extracted 'series info' can be null (this is the case when a movie is selected for instance), causing the object destructure to fail and thus halting the execution of the rest of the presence code due to an error being thrown.
*Not applicable*
Resolves #8488
=> fix(Stremio): series info can be null

websites/S/Stremio/metadata.json, websites/S/Stremio/presence.ts
There's an issue with Chromium-based browsers (such as Chrome and Microsoft Edge) in particular where the received player state is always `null`. On Firefox this issue does not occur. I'm not 100% sure of the exact cause of the discrepancy between the two browsers, but it seems like Chromium has trouble resolving promises that were dispatched by the `CustomEvent` event. So, to address this issue we have to resolve the promise first before dispatching the event.
I also added a check to gracefully handle cases where the `metaItem` field is still `undefined`, which may happen to users with slow network speeds.
*Not applicable*
=> fix(Stremio): resolve player state promise before submitting the event

websites/M/MangaDex/metadata.json, websites/M/MangaDex/presence.ts
This PR fixes a bug where a title's image get blocked by discord's cdn
Resolves #8530
<details>
</details>
=> fix(MangaDex): title image blocked by cdn

websites/P/Plex/metadata.json, websites/P/Plex/presence.ts
Resolves #8606 
Resolves #8470 
- Added watch/listen as type
- Added setting to use title as presenceData.name
- Fixed issues with not loading the thumbnail (by checking if the image is locally hosted, if so dont try to display it)
<details>
</details>
=> feat(Plex): add watch/listen type & add option to use title as name

websites/A/AnimeUnity/metadata.json, websites/A/AnimeUnity/presence.ts
When presence gets the episode number, the episode has unnecessary spaces. It can be noticed using a smartphone
same thing with the “Tutto” category in top anime
<details>
BEFORE:
AFTER:
</details>
=> fix(AnimeUnity): show correctly on smartphone

websites/C/Cisco Networking Academy/metadata.json
Fix issue #8695 with legacy url added to metadata.json
<details>
</details>
=> feat(Cisco Networking Academy): add Legacy URL

websites/N/niconico/metadata.json, websites/N/niconico/presence.ts
In early August, [ニコニコ動画(niconico)](https://www.nicovideo.jp/) released a major update.
ref: https://blog.nicovideo.jp/niconews/226054.html
With this update, the existing `presence` can no longer retrieve `/watch/` browsing status.
Therefore, these have been fixed in this PR.
<details>
|before|after|
|--|--|
|not available|![Screenshot 2024-09-11 012003](https://github.com/user-attachments/assets/df047b25-42cd-4099-8b29-d7d645546453)|
</details>
=> fix(niconico): `/watch/` information was not available.

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
- Don't add timestamps when the video is paused.
<details>
</details>
=> fix(Youtube): do not set timestamps when there is no video

websites/A/Asura Scans/metadata.json, websites/A/Asura Scans/presence.ts
- Added the new URL.
- Fixed regex for URL to accommodate Asura Scans' new paths.
- Added fetching for comic covers.
- Fixed the progress calculation issue.
- Fixed the issue with retrieving the comic title.
- Fixed the issue with retrieving the current chapter.
- Added settings to the presence:
- Privacy Mode: Only displays that the user is on Asura Scans.
- Display Current Chapter.
- Display Reading Percentage.
- Show Cover.
- Show Buttons.
<details>
</details>
=> fix(AsuraScans): remake the presence to match asura website

websites/Y/YTPLR/iframe.ts, websites/Y/YTPLR/metadata.json, websites/Y/YTPLR/presence.ts
Adds a Presence for YTPLR (YouTube Playlist Randomizer)
<details>
</details>
<details>
<summary> Proof showing the Website and Discord Profile without the Presence </summary>
</details>
<details>
<summary> Proof showing the Website and Discord Profile with the Presence enabled </summary>
</details>
<details>
<summary> Screenshot of the Settings Window </summary>
</details>
=> feat(YTPLR): add Presence

websites/C/ChatGPT/metadata.json, websites/C/ChatGPT/presence.ts
<details>
Now the chat title will be shown in the presence, if the setting is activated
If deactivated, it will show this
</details>
=> fix(chatgpt): fixed title not showing

websites/M/Miruro/metadata.json, websites/M/Miruro/presence.ts
Changes: Update timestamp logic to correctly set startTimestamp and endTimestamp while the video is playing. This ensures accurate display of the total video duration and current progress.
Issue: The current use of getTimestampsfromMedia causes inaccuracies in the progress bar.
<details>
</details>
=> fix(Miruro): update timestamp calculation

package-lock.json, websites/W/Weverse/metadata.json, websites/W/Weverse/presence.ts
Add presence for Weverse Kpop. The presence displays real-time updates about Kpop artists, including their current activities and recent posts on the platform.
<details>
</details>
=> feat(Weverse): add presence 

websites/S/Simkl/metadata.json, websites/S/Simkl/presence.ts
Add presence for Simkl. The presence shows what movies, lists, profiles, anime, and TV shows users are currently viewing and searching for information about.
<details>
</details>
=> feat(Simkl): add presence

websites/P/Proxer/metadata.json, websites/P/Proxer/presence.ts
Resolves #8788 
- add watch type
- change path to pathname
<details>
n/a
</details>
=> feat(Proxer): add watch type

websites/B/Brave Search/metadata.json, websites/B/Brave Search/presence.ts
Add presence for Brave Search. The presence shows what the user is searching on index, news, images, videos, or goggles and the help pages or settings. Solves #8437 
<details>
</details>
=> feat(Brave Search): add presence

websites/I/IDLIX/metadata.json
Update domain 
<details>
</details>
=> fix(IDLIX): update domain

websites/E/Emby/metadata.json, websites/E/Emby/package-lock.json, websites/E/Emby/package.json, websites/E/Emby/presence.ts
Resolves #8749
<details>
</details>
=> feat(Emby): add support for new and old versions

websites/K/Kick/metadata.json, websites/K/Kick/presence.ts
Resolves #8671
- add VOD support
- add watching activity type support
- fix issues due to code change
<details>
</details>
=> feat(Kick): add VOD support & watchtype && fix(Kick): fix issues due to code change

websites/Y/YTPLR/iframe.ts, websites/Y/YTPLR/metadata.json
This PR fixes an Error only present on PreMiD 2.6.12 (and likely older Versions?) that is not present on either Alpha or Beta Versions of PreMiD 2.7.x
Said Error being `Uncaught SyntaxError: Identifier 'iframe' has already been declared (at iframe.js:1:1)`
<details>
<summary> Error Screenshot </summary>
</details>
=> fix(YTPLR): fix iframe has already been declared

websites/P/Prime Video/metadata.json, websites/P/Prime Video/presence.ts
I noticed that the currentTime and duration of what I was watching in Prime Video was actually of a short segment, and not of the full video itself. I fixed that by getting the current time and duration from the html.
<details>
</details>
=> fix(Prime Video): fix durations

websites/B/bilibili/metadata.json, websites/B/bilibili/presence.ts
1. Added support for bilibili's search page
2. Added support for bilibili's homepage
3. Fixed the unreasonable behavior of the "Watch Later" playlist
Now if the privacy mode is not turned on, the presence information when watching "Watch Later" will be the same as when watching a normal video
<details>
<details>
<summary>Homepage</summary>
</details>
<details>
<summary>Search</summary>
</details>
<details>
<summary>Watchlater</summary>
</details>
</details>
=> feat(bilibili): update presence

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
Resolves #8838
fix(Youtube Music): remove old if check for showBrowsing to preven it from erasing presenceData when showbrowsing is off and you aren listening to a song.
<details>
</details>
=> fix(Youtube Music): remove old if check for showBrowsing

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
Resolves #8406 
fix(Youtube">: channel name being null
<details>
</details>
=> fix(Youtube): channel name & image being null

websites/R/RTL+/metadata.json, websites/Y/YNOProject/metadata.json, websites/Y/YNOProject/presence.ts
=> feat(YNOProject): add Presence

package-lock.json, websites/G/Gemini/metadata.json, websites/G/Gemini/presence.ts
feat(gemini): added option to show title
<details>
When show title is activated
When show title is deactivated
</details>
=> feat(Gemini): added option to show title

websites/D/DashNet/metadata.json, websites/D/DashNet/presence.ts
Resolves #8881
- fix memory leak issue
- change weird selectors that glitch to pagevar
<details>
</details>
=> fix(DashNet): prevent memory leak & change to pagevar code

websites/B/BeatLeader/assets.ts, websites/B/BeatLeader/metadata.json, websites/B/BeatLeader/presence.ts
Added all the new ReBeat images.
Added watching ActivityType where it is applicable, so the time bar will show.
<details>
</details>
=> feat(BeatLeader): add watching & ReBeat images

websites/W/Wcostream/metadata.json
Updated: 
- Domain to .tv 
- **version number this time**
Will change fork name next time to reflect proper naming convention. Never done this before. 
<details>
Immense help from crunchy I have no idea what I'm doing.
</details>
=> refactor(Wcostream): update display domain name

websites/C/Crowdin/metadata.json, websites/C/Crowdin/presence.ts
fix some broken querySelector
<details>
Just looping errors with no status
Language not displayed
Likewise, the Presence is blocked because of the first problem.
Information displayed correctly
</details>
=> fix(Crowdin): fix some broken querySelector

websites/H/Heroku/metadata.json
This pull request includes updates to the `websites/H/Heroku/metadata.json` file, primarily focusing on versioning and configuration settings.
Version update:
* Updated the `version` field from "1.0.9" to "1.0.10".
Configuration settings:
* Removed the `multiLanguage` property from the "showNames" configuration setting.
=> fix(Heroku): remove unused multiLanguage property

websites/H/Holodex/metadata.json
This pull request includes updates to the `websites/H/Holodex/metadata.json` file. The changes involve version increment and a correction to the `multiLanguage` setting.
* Updated the version from `1.0.24` to `1.0.25`.
* Corrected the `multiLanguage` setting from a string `"true"` to a boolean `true`.
=> fix(Holodex): correct the multiLanguage property

websites/C/Club Penguin Journey/metadata.json, websites/C/Club Penguin Journey/presence.ts
Input the wrong Client Id which was Fixed. Previously was the Etsy one for some reason.
- [ x ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ x ] I linted the code by running `yarn format`
- [ x ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>
=> fix(Club Penguin Journey): fix ClientId

websites/G/Genius/metadata.json, websites/G/Genius/presence.ts
Genius is currently working on their new song page and somewhere along the line, introduced a change that broke the way this Presence found the title for every song. Currently this makes every song show "undefined" as the title like so:
This pull request includes one change that alters the class that the Presence is looking for, letting it find the song title properly.
[Tested on "hey now" by Kendrick Lamar.](https://genius.com/Kendrick-lamar-hey-now-lyrics)
The extension seems to have another glitch where I can't do the "Load Presence" thing so I can't run this fork of the Presence myself, but I can show you that the selector works in console on mobile web and desktop web:
=> fix(Genius): addressing bug where song titles are undefined

websites/0-9/4chan/metadata.json
Adds the "boards.4chan.org" and "www.boards.4chan.org" URLs to the URL list in metadata.json.
<details>
</details>
=> fix(4chan): add urls

websites/S/Spotify Podcasts/metadata.json, websites/S/Spotify Podcasts/presence.ts
Fixed large image covers not appearing on Spotify Podcasts shows.
<details>
</details>
=> fix(Spotify Podcasts): show large image cover

websites/Y/YouTube/metadata.json, websites/Y/YouTube/presence.ts
This Pull Request changes the id of the `logo` option so that it gets reset for all users, this is because we changed the default value and for all current users its on the old default aka YouTube Logo
Metadata updates:
* [`websites/Y/YouTube/metadata.json`](diffhunk://#diff-eeee46808f5302d469ed34bac56b60789b3568b0d2c9b2eb418b664f3e857d84L75-R75): Updated the version from `5.13.6` to `5.13.7`.
Configuration setting renaming:
* [`websites/Y/YouTube/metadata.json`](diffhunk://#diff-eeee46808f5302d469ed34bac56b60789b3568b0d2c9b2eb418b664f3e857d84L161-R161): Renamed the `"id"` field from `"logo"` to `"largeImage"`.
* [`websites/Y/YouTube/presence.ts`](diffhunk://#diff-3d6bbda83d32ce58c2aad1b5f9304ec66ea7b243bbdfd2a7dc76b431c1144f76L64-R64): Updated the setting key from `"logo"` to …
=> chore(YouTube): change id to reset setting to default

.github/workflows/stale.yml
Updates the stale config to require both `bug` and `needs repro` as requested by @theusaf
=> chore(workflows): update stale issue handling

websites/R/RTLplay/metadata.json, websites/R/RTLplay/presence.ts, websites/R/RTLplay/util.ts
Bugfixes:
- When a movie was played, the activity was cleared by accident.
- The selector for the media title on the live broadcast page has been updated
Added:
- New tv channel: RTL sports
<details>
</details>
=> fix(RTLplay): movie and channel media issues

websites/N/Netflix/metadata.json, websites/N/Netflix/presence.ts
- Set timestamps to `0` when the video is paused - setting it to `null` breaks the `.setActivity()` function, only updating the information when the video is running;
- Set `smallImageKey` to `null` when `showSmallImages` is `false` - setting it to `""` didn't remove the image.
Closes #9031.
<details>
(pausing)
(`showSmallImages` set to `false`)
</details>
=> fix(Netflix): pause and showsmallimages issues

websites/A/AnimeLib/metadata.json, websites/A/AnimeLib/presence.ts
feat(AnimeLib): add supprot for 'faq' page
fix(AnimeLib): wrong else block position in 'franchise' case
Since the else block was in a wrong position, the browsing franchises state was never shown.
style(AnimeLib): change activity style for 'news', 'user' 'team' cases
Added a site logo to smallImageKey
<details>
(Feat) Buttons:
The Show Buttons setting goes with it as well
(Feat) Support for 'faq' page
(Fix) Browsing franchises state
</details>
=> feat(AnimeLib): add support for buttons

websites/F/Freek/iframe.ts, websites/F/Freek/metadata.json, websites/F/Freek/presence.ts
This pr implements the following:
Resolves https://github.com/PreMiD/Presences/issues/9000
Adds Freek presence, with page support for current existing pages (will update new features in the future) and iframe support for watching streams.
Support for current pages:
- Movies
- TV Shows
- Anime
- Manga
Unsupported (coming soon):
- K-dramas
- Live tv
<details> 
<summary> Watching a movie </summary>
</details>
<details>
<summary> Watching a tv show </summary>
</details>
<details>
<summary> Searching </summary>
</details>
<details>
<summary> Exploring </summary>
</details>
<details>
<summary> Private browsing </summary>
</details>
<details>
<summary> History </summary>
</details>
<details>
<summary> Manga </summary>
</details>
=> feat(Freek): add presence

websites/A/AnimeLib/metadata.json, websites/A/AnimeLib/presence.ts
feat(AnimeLib): add support for 'notifications' under 'user' case
<details>
</details>
=> feat(AnimeLib): add support for 'messages' and 'downloads' cases

websites/S/Sflix/iframe.ts, websites/S/Sflix/metadata.json, websites/S/Sflix/presence.ts
Added a [Sflix](https://sflix2.to/)/[EnormeTV](https://enorme.tv/) presence. Closes #5305.
<details>
</details>
=> feat(Sflix): add presence

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
This pull request includes updates to the YouTube Music integration, focusing on metadata versioning and the presence update functionality. The most important changes include fixing attribute casing, initializing `presenceData` correctly, and updating the activity type and details for presence data. It now also shows "Listening to xyz" instead of "Listening to YouTube Music"
Metadata versioning:
* [`websites/Y/YouTube Music/metadata.json`](diffhunk://#diff-e1c3b8f15f102627384b3c2bf0e720c3e22ecabe59fcdcac3d653748b9f1bc58L23-R23): Updated the version from `3.0.24` to `3.0.25`.
Presence update functionality:
* [`websites/Y/YouTube Music/presence.ts`](diffhunk://#diff-5f14e1c675234b5bddcca686dffea56d54e32f294432a10d578ba3eeefdc2bb9L40-R40): Fixed the casing of the `repeat-mode` attribute to …
=> chore(YouTube Music): update various things

websites/G/Granblue Fantasy/metadata.json, websites/G/Granblue Fantasy/presence.ts
- Improve query performance by only getting necessary data
- Fix getting main character by getting list of all characters instead of only on-field
- Add option to show profile (details), raid element, event title, turn counter
<details>
</details>
=> feat(Granblue Fantasy): add raid details & query only necessary data

websites/G/Granblue Fantasy/metadata.json, websites/G/Granblue Fantasy/presence.ts
- Get the highest Max HP boss of the stage (aka. the actual "boss")
- Handle not being able to find "alive" bosses when stage is cleared and user does not move to results page, making the concatenation of activity state `undefined | Turn x`
<details>
</details>
=> fix(Granblue Fantasy): handle no alive boss

websites/U/U-NEXT/U-NEXT.json, websites/U/U-NEXT/functions/fetchLiveMetadata.ts, websites/U/U-NEXT/functions/fetchMetadata.ts, websites/U/U-NEXT/metadata.json, websites/U/U-NEXT/package-lock.json, websites/U/U-NEXT/package.json, websites/U/U-NEXT/presence.ts, websites/U/U-NEXT/types.ts
Add a presence for the Japanese VOD service U-NEXT.
This was created on a Netflix basis
Resolves: https://github.com/PreMiD/Presences/issues/7081
<details>
</details>
=> feat(U-NEXT): add activity

websites/P/Prime Video/metadata.json
fix #9058 
Change regex to include only Prime-related links and no longer include links such as amazon.com only
<details>
Example of a URL captured :
</details>
=> fix(Prime Video): change regex

@types/premid/index.d.ts
Allow setting largeImageText for listening activity types as Discord fixed design inconsistencies across mobile & desktop versions with it now consistently showing as a third line
=> feat(types): allow setting largeImageKey for listening activites

websites/C/Claude/Claude.json, websites/C/Claude/metadata.json, websites/C/Claude/package-lock.json, websites/C/Claude/package.json, websites/C/Claude/presence.ts
Resolves: https://github.com/PreMiD/Presences/issues/9018
<details>
</details>
=> feat(Claude): add activity

@types/premid/index.d.ts, websites/D/Disney+/metadata.json, websites/D/Disney+/presence.ts, websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
closes #9146
Update multiple activities and allow setting largeImageText for `Watching`.
YouTube music by default doesn't show the title but has an option
Disney+ got a lot of niche features, see Screenshot
<details>
</details>
=> chore: update activities

websites/F/Freek/metadata.json, websites/F/Freek/presence.ts
This pr implements the following:
- Implements season and episode details through largeImageText to utilise the Discord functionality of it.
<details>
*Looking at this I am questioning how they have the exact same episode length 🤔*
</details>
=> feat(Freek): implement season and episode text through largeImageText

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
Utilize `largeImageText` for album name, following Spotify's semantics
<details>
</details>
=> feat(YouTube Music): utilize `largeImageText` for albums

websites/A/AnimeLib/metadata.json, websites/A/AnimeLib/presence.ts
feat(AnimeLib): title as presence setting
<details>
</details>
=> chore(AnimeLib): cache current dub

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
=> fix(YouTube Music): only set largeImageText when needed

websites/B/Brave Search/Brave Search.json, websites/B/Brave Search/metadata.json, websites/B/Brave Search/presence.ts
Making Brave Search use strings to be a little multilanguage
<details>
</details>
=> feat(Brave Search): use strings

websites/K/kisskh/metadata.json, websites/K/kisskh/presence.ts
Resolves #7249 
<details>
</details>
=> feat(kisskh): add activity

websites/Y/YouTube Music/metadata.json, websites/Y/YouTube Music/presence.ts
This fixes the YT:M pressence to work when playing in audio-only mode, when this happens, YT:M mounts an audio element, not video element, breaking the pressence
<details>
</details>
=> fix(YT:M): support for audio-only playback

.github/workflows/assets-updater.yml, cli/src/classes/AssetsManager.test.ts, cli/src/classes/AssetsManager.ts, cli/src/commands/updateAssets.ts, cli/src/util/log.ts
This pull request includes significant changes to the workflow configuration and the `AssetsManager` class, along with updates to the `updateAssets` command. The most important changes involve modifying the workflow triggers, enhancing the asset versioning process, and simplifying the `updateAssets` command by removing pull request specific logic.
* [`.github/workflows/assets-updater.yml`](diffhunk://#diff-07c679f10bffd54861ad48e7d7629fb050a37f36e751eaef128ecc9e58102392L4-L15): Changed the workflow trigger from pull request events to push events on the main branch and specific file paths.
* [`cli/src/classes/AssetsManager.ts`](diffhunk://#diff-e1a5bb40359efc5a6ffb6bc1fe5186a9e2794df3c431726c3f8bdc8ff86eb0beR443-R461): Added logic to increment the version in `metadata.json` when assets are …
=> fix(update-assets): run on push instead of pr

websites/L/Leboncoin/metadata.json, websites/L/Leboncoin/presence.ts
This PR introduces several improvements and fixes related to the LeBonCoin presence integration. The changes include new presence support for various LeBonCoin pages (almost all of them ig), refinements to the detection of prices and advertisers, and fixes for translation issues. Additionally, minor refactors and cleanup were performed.
<details>
<summary>Changes: </summary>
- **Added support**  
- Added detection for the homepage (`/`) with the state "Page d'accueil".
- Added detection for boutique pages, displaying the boutique name (`/boutique`).
- Added detection for the "Favorites" page on LeBonCoin (`/favorites`).
- Set a generic "Explore" presence for other unknown pages.
- **Fixed presences**
- Added `/profile` alias to deprecated `/profil`.
- Fixed CSS queries for profiles …
=> feat(Leboncoin): fix and improve pratically everything

websites/V/VLC/metadata.json, websites/V/VLC/presence.ts
This adds the "Type" variable from the xml, which detects whether the currently loaded file is a Audio or Video, then switches the current ActivityType based on this. 
I was finished working on putting the Album art as the "largeImageKey", but was gonna wait before putting it in, since I had to modernize the presence.ts might as well implement that as well.
- [ x ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ x ] I linted the code by running `yarn format`
- [ x ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>
=> feat(VLC): Add support for "Watching" and "Listening" statuses and add Album art as largeImageKey.

.github/workflows/assets-updater.yml, .github/workflows/pmd.yml, .github/workflows/release.yml
This pull request includes changes to the workflow configuration files to update the names of the workflows for better clarity.
Workflow name updates:
* [`.github/workflows/assets-updater.yml`](diffhunk://#diff-07c679f10bffd54861ad48e7d7629fb050a37f36e751eaef128ecc9e58102392L1-R1): Changed the workflow name from `pmd` to `Assets Updater`.
* [`.github/workflows/pmd.yml`](diffhunk://#diff-be8f5db58413faadcbdf204b62bd366ed47d9f86f86b184c621fb4f50f885bf0L1-R1): Changed the workflow name from `pmd` to `Validate`.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L1-R1): Changed the workflow name from `pmd` to `Release`.
=> chore: improve GitHub workflow file names

websites/J/JSR/metadata.json, websites/J/JSR/presence.ts
Add the JSR presence for https://jsr.io.
<details>
</details>
=> feat(JSR): add JSR presence

websites/E/e-typing/metadata.json, websites/E/e-typing/presence.ts
Add the e-typing presence for https://www.e-typing.ne.jp/.
<details>
</details>
=> feat(e-typing): add e-typing presence

websites/D/Deezer/metadata.json, websites/D/Deezer/presence.ts
This PR updates the activity type for Deezer from "Game" to "Listening" to better reflect its purpose as a music streaming platform.
<details>
</details>
=> refactor(Deezer): change activity type from game to listening

websites/P/Pi Fansubs/metadata.json, websites/P/Pi Fansubs/presence.ts
Resolves #9366 
<details>
</details>
=> feat(Pi Fansubs): Movie or TV Show as activity name

websites/A/AnimeLib/metadata.json, websites/A/AnimeLib/presence.ts
chore(AnimeLib): remove deprecated
chore(AnimeLib): modify and update settings
<details>
Note: Kodik player
Note: AnimeLib player
Note: Anime homepage
Now "titleAsPresence" setting is hidden when privacy mode is enabled, also renamed the setting's name
</details>
=> feat(AnimeLib): support for licensed animes

cli/package-lock.json, cli/package.json, cli/src/commands/bump.ts, cli/src/commands/new.ts, cli/src/index.ts, cli/src/util/getSingleActivity.ts, cli/src/util/mapActivityToChoice.ts, package-lock.json
Closes #9402
Hi, I'm a PreMiD fan and also the maintainer of [inquirer](https://github.com/SBoudrias/Inquirer.js) project. This PR updated the old `inquirer` to the modern `@inquirer/prompts`.
- Updated the `inquirer` dependency to our modern `@inquirer/prompts`.
- Added a `process.on('exit')` event listener to the `index.ts` to [handle the <kbd>ctrl+c</kbd> gracefully](https://github.com/SBoudrias/Inquirer.js?tab=readme-ov-file#handling-ctrlc-gracefully).
- Bumped `pmd` version to `2.1.0`
- Updated root `package-lock.json` with `npm install`
=> chore: upgrade inquirer dependency

.github/PULL_REQUEST_TEMPLATE.MD
Update the `yarn format` to `npm run lint` in PR template
PR #9370 seems to have been reverted, idk why.
<details>
</details>
=> chore: update lint command in PR template

websites/F/Facebook/Facebook.json, websites/F/Facebook/metadata.json, websites/F/Facebook/presence.ts
Resolves #9388 
- Added string to word things differently;
- Add more settings for videos. Choose to set detail/state out of 4 options;
- Import ActivityType & getTimestampsFromMedia;
- Sort strings;
- Remove deprecated language in getstrings;
- Add section names to name instead of a prefix in details;
- Add support for videos on someone's profile;
- Add watching type to videos;
<details>
</details>
=> feat(Facebook): add more settings & more video types

websites/S/Streaming+/metadata.json, websites/S/Streaming+/presence.ts
Added [Streaming+](https://eplus.jp/sf/streamingplus) presence.
<details>
</details>
=> feat(Streaming+): add presence

websites/E/Estácio/iframe.ts, websites/E/Estácio/metadata.json, websites/E/Estácio/presence.ts, websites/E/Estácio/utils/index.ts
Adds Estácio integration to PreMiD, allowing activity display on Discord.
<details>
</details>
=> feat(Estácio): add activity

websites/C/Crowdin/metadata.json, websites/C/Crowdin/presence.ts
fix: editor now shows language & file currently being edited
- [X ] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [X ] I linted the code by running `npm run lint`
- [ X] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>
=> fix: editor now shows language & file currently being edited

.github/ISSUE_TEMPLATE/bug_report.yml
This pull request updates the bug report issue template to improve clarity, accessibility, and relevance. Key changes include reformatting text for better readability, updating field descriptions, and reorganizing the structure of input fields.
* Updated text in the `description` and `body` sections to use consistent quotation marks and Markdown formatting for better readability. For example, added bold emphasis and line breaks in the introductory instructions. [[1]](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL1-R9) [[2]](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL18-R20)
* Replaced the `os` field with a `country` field to gather region-specific information, including a new placeholder and description.
* Updated …
=> chore: add country to bug_report.yml

websites/K/Khan Academy/metadata.json, websites/K/Khan Academy/presence.ts
Fixed Khan Academy presence after it had been abandoned by original author for 3+ years
<details>
</details>
=> feat(Khan Academy): fix and update presence

websites/M/Microsoft Learn/metadata.json, websites/M/Microsoft Learn/presence.ts
Improves the Microsoft Learn presence by adding explicit button removal for pages where buttons are not needed, fixing a typo, and maintaining existing functionality. Ensures buttons are only shown for specific routes (`/training/paths/`, `/collections/`, `/challenges/`, `/plans/`, `/courses/`, `/users/`) when `show-button` is enabled and `privacy` is disabled. Corrects "Challange" to "Challenge" for consistency.
- **feat**: Add new Microsoft Learn Presence
- **fix**: update homepage URL check to use regex for better matching
- **fix**: remove redundant translations and update thumbnail URL
- Tested on `/training/paths/`, `/users/`, `/challenges/`, `/` with `show-button` and `privacy` toggled.
- Verified buttons appear only on intended pages and are absent on others (e.g., homepage, …
=> feat(Microsoft Learn): add new presence

websites/S/Simulator Radio/metadata.json, websites/S/Simulator Radio/presence.ts
SimulatorRadio's API does not release listener count so I removed it. These issues were in the API part where it attempted to request listener count, making the listener count come out as: undefined.
</details>
=> fix(Simulator Radio): remove listener count

websites/S/SoundCloud/metadata.json, websites/S/SoundCloud/presence.ts
Replaced a left over discord asset key with the logo link
<details>
</details>
=> fix(SoundCloud): replace asset key with link

cli/package.json, cli/src/util/getDiscordUser.ts
Adds a fallback username for `getDiscordUser` which is used if the API is broken
=> feat(cli): add fallback username to discord username api

@types/premid/index.d.ts, premid/src/index.ts
Adds general.json keys to type of `getStrings` value to allow for type hints for general strings. It still allows for custom presence strings to be used.
Since this relies on importing types, wrapped existing types in `declare global`
=> refactor: add general strings type hints to Presence#getStrings

websites/M/movie-web/metadata.json, websites/M/movie-web/presence.ts
Updates the instance URLs and hopefully displays the page title instead of "movie-web"
=> chore(movie-web): Update urls and meta

websites/A/AnimeKai/metadata.json, websites/A/AnimeKai/presence.ts
feat(AnimeKai):
Add functionality when syncing with Anilist
Add functionality when looking at upcoming animes
Add functionality when in MAL/AL Export
Add functionality when looking at notifications (Small change from #9674)
- Shows 'Looking at Community Notifications' if on community notifications
- Shows 'Looking at Anime Notifications' if on anime notifications
- [✅] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [✅] I linted the code by running npm run lint
- [✅] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)
=> feat(AnimeKai): Update Presence functions

websites/#/巴哈姆特動畫瘋/metadata.json, websites/#/巴哈姆特動畫瘋/presence.ts
- Displaying the anime title directly as the presence name.
- Updating the presence image to use the anime cover art directly.
- Modifying presence details to show the anime rating and watch count.
- Add anime party support
<details>
</details>
=> feat(巴哈姆特動畫瘋): update activity image and details

websites/H/HBO Max/metadata.json, websites/H/HBO Max/presence.ts
Max has been shut down, going back to it's old HBO Max name.
<details>
</details>
=> feat(HBO Max): add presence and remove the old Max

websites/M/ManhwaWeb/metadata.json, websites/M/ManhwaWeb/presence.ts
Hi, I'm elAsksito!
This PR introduces a new activity for ManwhaWeb, a site I personally enjoy for reading manga and manhwas.
The activity detects when a user is reading or browsing on the site and displays relevant rich presence information.
<details>
</details>
=> feat(ManwhaWeb): add activity

websites/T/Twitch/metadata.json, websites/T/Twitch/presence.ts
When in Twitch's mod view, the name of the streamer is not visible, this fixes that, as well as closes https://github.com/PreMiD/Activities/issues/9802
<details>
Before
After
</details>
=> fix(Twitch): fix streamer title in mod view

websites/O/OpenFront.io/metadata.json, websites/O/OpenFront.io/presence.ts
Displays current status while playing OpenFront, including when in lobby, loading players, or in-game.
<details>
</details>
=> feat(OpenFront.io): add activity

websites/W/WatchPeopleLive/metadata.json, websites/W/WatchPeopleLive/presence.ts
Adds a new PreMiD presence for [WatchPeopleLive.tv](https://watchpeoplelive.tv/), a content-sharing community focused on real-life footage, discussions, and media. This activity supports detection of user context across the platform:
- Main page (/) displays as “Viewing the main page”.
- Section pages (e.g., /h/Animals) show the current section being browsed.
- Post pages (e.g., /h/nature/post/352201/new-hole-discovered-hnature) display the post title, section, and post ID.
All paths are parsed dynamically from the URL, and titles are humanized by replacing dashes with spaces.
<details>
</details>
=> feat(WatchPeopleLive): add activity

websites/M/Mangafire/metadata.json, websites/M/Mangafire/presence.ts
This plugin adds [Mangafire.to](https://mangafire.to/) support to PreMiD, allowing users to display their manga reading activity in their Discord Rich Presence.
It detects and updates your activity based on the page you're currently viewing, including:
- Home, type/genre, filter, and update pages
- Manga detail pages, showing the title, authors, and status
- Reading pages, displaying the current manga being read
It also dynamically fetches manga cover images to display in your activity, offering a more immersive and personalized presence.
<details>
</details>
=> feat(Mangafire): add activity

websites/H/Hdfilmcehennemi/iframe.ts, websites/H/Hdfilmcehennemi/metadata.json, websites/H/Hdfilmcehennemi/presence.ts
This PR adds playback progress (timestamp) support to the **Hdfilmcehennemi** presence, allowing Discord to display how far the user is into the video.
Special thanks to [@DxriaaaN](https://github.com/DxriaaaN) for assisting with the [iframe integration logic](https://github.com/PreMiD/Activities/commit/7c745c04c247fe1676325a6805bd0f621a06f1d5).  
Their contribution was crucial, as the site uses a nested iframe structure for video playback, which made direct access to the timestamp more complex.
Please let me know if anything needs adjustment. I'm happy to make changes!
<details>
</details>
=> feat(Hdfilmcehennemi): add activity

websites/D/Deezer/metadata.json, websites/D/Deezer/presence.ts
This PR updates the main presence status for the Deezer activity to show the artist being listened to, mirroring Discord's native Spotify integration.
Previously, the status in the user list was always static and simply showed "Listening to **Deezer**".
With this change, the status now dynamically displays the main artist. For example, when listening to the song "Type Shit":
**Before:**
> Listening to **Deezer**
**After:**
> Listening to **Future**
<details>
</details>
=> feat(Deezer): extract main artist name for presence data

websites/W/Wplace/metadata.json, websites/W/Wplace/presence.ts
New privacy settings for wplace: users can now hide their coordinates and country, disabling coordinates disables the country, but they can leave the country displayed without coordinates if they wish (not the other way around because it's useless and it doesn't look good)
<details>
I just broke my premid extension but trust me it works really well, I also tested using logs
</details>
=> fix(Wplace): add privacy settings

websites/S/Sky Sports/metadata.json, websites/S/Sky Sports/presence.ts
Added a new presence for Sky Sports, a sports news coverage and streaming website that allows users to watch Live TV through a dedicated player downloadable through the site. The presence has support for all news categories and previewing live channels.
<details>
Privacy mode:
</details>
=> feat(Sky Sports): add presence

websites/M/Monkeytype/metadata.json, websites/M/Monkeytype/presence.ts
This PR ensures live stats are displayed consistently and accurately.
- Fixed `undefined` values for WPM and accuracy in Monkeytype live stats
- Corrected timestamp to show only the time instead of time + session time to avoid duplicate values
- Added loading state to prevent stats from flashing as `undefined` on reload
<details>
Original:<br>
Fixed:<br>
</details>
=> fix(monkeytype): resolve undefined stats, correct test time, add loading state

websites/D/Dicoding/metadata.json, websites/D/Dicoding/presence.ts
Add new Dicoding activity integration.
This activity displays the current course/module being viewed by the user.
<details>
</details>
=> feat(Dicoding): add activity

websites/N/NeetCode/metadata.json, websites/N/NeetCode/presence.ts
Added Discord Rich Presence support for NeetCode.io, a coding interview preparation platform that helps developers prepare for technical interviews.
**Features implemented:**
- Homepage and general browsing detection
- Course viewing with dynamic course names extracted from URLs
- Individual lesson support with lesson titles
- Practice problems with category detection (Blind 75, NeetCode 150, NeetCode 250, Core Skills, System Design, etc.)
- Individual problem solving with problem names
- Quiz taking with quiz titles extracted from URLs
- Roadmap following detection
- Multi-language descriptions (English, Japanese, Korean, Indonesian, Chinese)
- Proper URL matching and content extraction for all major NeetCode sections
**Supported pages:**
- Homepage (`/`, `/home`)
- Courses …
=> feat(NeetCode): add activity 

websites/P/Peacock/metadata.json, websites/P/Peacock/presence.ts
Peacock showed Playing as its activity type before, I imported the activity th
<details>
</details>
=> feat(Peacock): change activity type to watching

websites/M/Mangalib/api/lib.ts, websites/M/Mangalib/api/models/anime.ts, websites/M/Mangalib/api/models/manga.ts, websites/M/Mangalib/api/models/ranobe.ts, websites/M/Mangalib/api/utils.ts, websites/M/Mangalib/metadata.json, websites/M/Mangalib/presence.ts
feat(Mangalib): display covers on licensed titles
fix(Mangalib): display covers on teams
chore(Mangalib): remove unnecessary type imports
<details>
</details>
=> feat(Mangalib): new mirror

websites/M/Mapple.tv/metadata.json
- Updated `url` field to accept multiple domains (`mapple.tv`, `mapple.mov`, `mapple.uk`)
- Bumped version to 1.0.2
=> fix(mapple.tv): update support for additional domains

websites/W/WaniKani/metadata.json, websites/W/WaniKani/presence.ts
Website changes broke the activity, I fixed the outdated selectors and added an option to hide the activity when there are no reviews or lessons left
<details>
</details>
=> feat(Wanikani): additional setting and bugfixes

websites/Z/Zaiko/metadata.json, websites/Z/Zaiko/presence.ts
Prevent query parameters from being appended to button URLs.
This avoids attaching unnecessary parameters (e.g., `utm_source`), reducing analytics noise and preventing confusion for site administrators.
It also mitigates the risk of exposing sensitive tokens (e.g., login tokens, payment callback tokens) if they are present in the URL.
<details>
Before:  
After:  
</details>
=> chore(Zaiko): remove url query parameters from button

README.md
The previous link pointed to /dev/presence which returned 404. Now it points to the main documentation page.
<details>
</details>
=> docs(readme): update documentation link to avoid 404
