PreMiD/Activities

- websites/P/PreMiD/dist/metadata.json
- websites/P/PreMiD/presence.ts
> PreMiD Presence update

- websites/N/NativShark/dist/metadata.json
- websites/N/NativShark/presence.ts
These are some minor changes to reflect the newest URL changes of NativShark, as they're working on their platform.
> NativShark v1.0.1: Keep url structure up to date with website

- websites/E/Exaroton/dist/metadata.json
- websites/E/Exaroton/presence.ts
- websites/E/Exaroton/tsconfig.json
Added a presence for [Exaroton](https://exaroton.com) - the paid service of [Aternos](https://aternos.org).
Working proof:
> Add presence for Exaroton

- websites/T/Tidal/dist/metadata.json
- websites/T/Tidal/presence.ts
**Tidal**
Version: **1.0.8 -> 2.0.0**
**Changes:**
- Rewrited whole presence.
- Added support for videos.
- Added support for browsing.
- Added support for multiLang & Privacy Mode (ty @Bas950 for your code).
- Changed owner of presence since formal owner has not access to Tidal anymore.
<details>
</details>
> ✨ Tidal: Rewrite Presence

- websites/T/Tidal/dist/metadata.json
- websites/T/Tidal/presence.ts
**Tidal**
Version: **2.0.0 -> 2.0.1**
**Changes:**
- Add repeat & repeatSingle button and text
<details>
</details>
> ✨ Tidal: Add Repeat check

- websites/T/Telegram/dist/metadata.json
- websites/T/Telegram/presence.ts
> Add "Show name" option to Telegram presence

- websites/S/SuperiorServers.co/dist/metadata.json
- websites/S/SuperiorServers.co/presence.ts
- websites/S/SuperiorServers.co/tsconfig.json
SuperiorServers.co presence
proof:
> SuperiorServers.co Presence release

- websites/L/LinkedIn/dist/metadata.json
- websites/L/LinkedIn/presence.ts
- websites/L/LinkedIn/tsconfig.json
First of all, merry Christmas, _a little late_, and if we don't get the chance to talk again, happy new year! :3
I made a huge presence for [LinkedIn](https://www.linkedin.com/), the work-related social media that we all know.
This one, like my previous presence (Jira Software), it's made up of a LOT of pages, subpages and sections, so the screenshots will be quite a lot. sry.
LinkedIn offers others services like Salary (which is not supported in my country, Italy..sad.) and Learning (which needs a premium account)..these services will be implemented in the presence asap.
- Presence settings: https://i.imgur.com/oLHeAcU.png
- Homepage: https://i.imgur.com/GUaifAH.png
- Hashtag subsection: https://i.imgur.com/Wl39c89.png
- Follow subsection:
- Suggestions subsection: …
> LinkedIn - Website

- websites/M/MangaTube/dist/metadata.json
- websites/M/MangaTube/presence.ts
did a few hours ago a mistake....
so now i guess everything is fine
Changes :
Bump Version
Serieslist and more
Fixes:
Showing Manga
proof pic:
> M-T Update

- websites/E/Exxen/dist/metadata.json
- websites/E/Exxen/presence.ts
- websites/E/Exxen/tsconfig.json
> 💨Added Exxen Presence

- websites/V/VRCArena/dist/metadata.json
- websites/V/VRCArena/presence.ts
- websites/V/VRCArena/tsconfig.json
VRCArena is a populair site, used by many VRChat users.
It stores assets, species, animations etc.
**Proof that it works:**
> VRCArena - New precense

- websites/R/Ryou Flashcards/dist/metadata.json
- websites/R/Ryou Flashcards/presence.ts
> Bugfix for Ryou Flashcards presence

- websites/M/Monkeytype/dist/metadata.json
Adding new URLs since the website redirects users
> MonkeyType: Adding new URLs

- desktop.ini
- websites/N/Novel Mania/dist/metadata.json
- websites/N/Novel Mania/presence.ts
**Home**
**Reading Chapter**
**Novel Index**
**News**
> Novel Mania Bugfix

- websites/V/VRCArena/dist/metadata.json
- websites/V/VRCArena/presence.ts
- **Added** a status for asset creation
- **Added** the requests page to the precense
- **Changed** "Viewing asset" to "Looking at an asset"
- **Changed** "About page" to "Browsing about page"
> VRCArena Patch 01

- websites/C/Coinbase/dist/metadata.json
- websites/C/Coinbase/presence.ts
- websites/C/Coinbase/tsconfig.json
- websites/L/LoL Esports/dist/metadata.json
- websites/L/LoL Esports/presence.ts
> Created Presence for Coinbase and made an update to LoL Esports presence

- websites/H/HackerRank/dist/metadata.json
- websites/H/HackerRank/presence.ts
- websites/H/HackerRank/tsconfig.json
This PR adds [HackerRank ](https://www.hackerrank.com/ )presence
Screenshots:
> add HackerRank 

- websites/R/REYFM/dist/metadata.json
- websites/R/REYFM/presence.ts
> REYFM choose logo.

- websites/E/Eldiru/dist/metadata.json
- websites/E/Eldiru/presence.ts
- websites/E/Eldiru/tsconfig.json
Eldiru is a Moodle-based online learning management system for Jenderal Soedirman University students.
Since this presence is college-spesific, I'm not sure if this will be accepted. But I will be very happy if this presence is listed in Presence Store so that my friends can easily add this to their browsers.
Anyway, thank you for your attention.
Images:
> Add Eldiru

- websites/B/Brick Hill/dist/metadata.json
- websites/B/Brick Hill/presence.ts
- websites/B/Brick Hill/tsconfig.json
> Add Brick Hill

- websites/M/Monkeytype/dist/metadata.json
- websites/M/Monkeytype/presence.ts
Hi, i am the developer of Monkeytype and decided to add PreMiD support.
I noticed it was already started by @drull1000 so I expanded on it. I moved the original author to the contributor's list, as well as updated the clientid with his permission.
> Updated Monkeytype

- websites/V/V LIVE/dist/metadata.json
- websites/V/V LIVE/presence.ts
Had to move the /my/ stuff up before the `/channel/(\\w*\\d*)/my/` or else it would never show when you are on channel/my
> 🐛 Bug fix for V LIVE

- websites/R/RealLifeGTAV/dist/metadata.json
- websites/R/RealLifeGTAV/presence.ts
> Updated - RealLifeGTAV

- websites/J/Joyn/dist/metadata.json
- websites/J/Joyn/presence.ts
- websites/J/Joyn/tsconfig.json
> Add Joyn.de

- websites/H/Human Benchmark/dist/metadata.json
- websites/H/Human Benchmark/presence.ts
- websites/H/Human Benchmark/tsconfig.json
**Proof of working:** (these are a few miscellaneous screenshots of what shows on what tests etc)
> Added Human Benchmark

- websites/U/Undercards/dist/metadata.json
- websites/U/Undercards/presence.ts
- websites/U/Undercards/tsconfig.json
> Add Undercards game

- websites/G/Grailed/dist/metadata.json
- websites/G/Grailed/presence.ts
> grailed update

- websites/G/Game-Linter/dist/metadata.json
- websites/G/Game-Linter/presence.ts
- websites/G/Game-Linter/tsconfig.json
> Added the website game-linter.com

- websites/H/Hypixel API Reborn/dist/metadata.json
- websites/H/Hypixel API Reborn/presence.ts
- websites/H/Hypixel API Reborn/tsconfig.json
> Add Hypixel API • Reborn documentation

- websites/T/Twitter/dist/metadata.json
- websites/T/Twitter/presence.ts
Requested by @Alanexei himself for me to take it over.
Will update Soundcloud soon and then take it over.
> Twitter | Changing author

- websites/J/Joyn/dist/metadata.json
- websites/J/Joyn/presence.ts
> Presence Update: Joyn

- @types/premid/index.d.ts
- websites/N/Netflix/dist/metadata.json
- websites/N/Netflix/presence.ts
> Netflix update and add buttons

- websites/P/pays.host/dist/metadata.json
- websites/P/pays.host/presence.ts
- websites/P/pays.host/tsconfig.json
> Added pays.host presence

- websites/E/Exaroton/dist/metadata.json
exaroton is supposed to not be capitalized according to its own branding rules.
> Exaroton -> exaroton

- websites/G/Gunivers/dist/metadata.json
- websites/G/Gunivers/presence.ts
- websites/G/Gunivers/tsconfig.json
- websites/K/KaniShiel/dist/metadata.json
- websites/K/KaniShiel/presence.ts
- websites/K/KaniShiel/tsconfig.json
I love PreMiD so I tried to implemented the organisations' web sites, I'm in.
> Added gunivers.net network and kanishiel.com

- websites/S/Salty Bet/dist/metadata.json
- websites/S/Salty Bet/presence.ts
- websites/S/Salty Bet/tsconfig.json
> Added Salty Bet (www.saltybet.com)

- websites/P/PERPHeads/dist/metadata.json
- websites/P/PERPHeads/presence.ts
- websites/P/PERPHeads/tsconfig.json
> Added - perpheads.com

- websites/A/AniTube/dist/metadata.json
- websites/A/AniTube/presence.ts
- websites/A/AniTube/tsconfig.json
> Added AniTube Presence

- websites/G/Gunivers/dist/metadata.json
- websites/G/Gunivers/presence.ts
- websites/K/KaniShiel/dist/metadata.json
- websites/K/KaniShiel/presence.ts
I know that these have just been accepted but I added a few thing : small images for the precence and privacy option 
**Proof that the changes work :**
*For gunivers :*
I added this little image when you are on the workspace
I also forget to add the presence when your looking for a user on the main website
I added a privacy mode that remove all the presence and set your status the same everywhere
*For kanishiel :* 
I added images for the dashboard 
And for the werewolves roles 
I added two type of privacy : one which hide the server you're editing 
And an other that remove all the presence and set your status the same everywhere
Oh and for gunivers, I have registered the url status.gunivers.net but after I speak about this presence with the website owner, he move it to another website so …
> Updated of kanishiel.com and gunivers.net

- websites/S/Salty Bet/dist/metadata.json
- websites/S/Salty Bet/presence.ts
Found an issue when closing and reopening the website, the presence didn't refresh right away so I added a check to keeping it alive.
> Updated Salty Bet presence.ts

- websites/P/PERPHeads/dist/metadata.json
- websites/P/PERPHeads/presence.ts
> Update PERPHeads presence.ts

- websites/A/Anontpp/dist/metadata.json
- websites/B/Board Game Online/dist/metadata.json
- websites/B/Byte/dist/metadata.json
- websites/C/Change/dist/metadata.json
- websites/C/CoolMathGames/dist/metadata.json
- websites/D/Deezer/dist/metadata.json
- websites/D/Duolingo/dist/metadata.json
- websites/D/dailymotion/dist/metadata.json
- websites/G/Google Domains/dist/metadata.json
- websites/H/Hulu/dist/metadata.json
- websites/H/hanime/dist/metadata.json
- websites/K/Kahoot/dist/metadata.json
- websites/M/Metastream/dist/metadata.json
- websites/O/openrec/dist/metadata.json
- websites/O/osu!ppy/dist/metadata.json
- websites/P/Pandora/dist/metadata.json
- websites/P/PartydoosMediaGroup/dist/metadata.json
- websites/S/Shazam/dist/metadata.json
- websites/S/SoloLearn/dist/metadata.json
- websites/T/TheSite/dist/metadata.json
- websites/U/UserBenchmark/dist/metadata.json
- websites/W/W3Schools/dist/metadata.json
I will go through each and every presence and individually test them over the period of this week, as well as going through and seeing exactly what needs fixing in terms of opened bugs and issues. More PRs to come. 
I am also already aware of some that are bugged. these will be hopefully (ideally) fixed in a PR later today if not tomorrow.
Commits are made clear which Presences are whose and which ones for ease of viewing.
Please let me know if any changes needed to said metadata.json files.
> Transfers of Presences to myself from Alanexei and TheSlowly

- websites/K/Keymash/dist/metadata.json
- websites/K/Keymash/presence.ts
- websites/K/Keymash/tsconfig.json
Due to last pull request the version has been changed to 1.0.0 and the service name matches the folder contents and here is the screenshot of viewing a profile page.
> Add Keyma.sh

- websites/K/Kickassanime/dist/metadata.json
- websites/K/Kickassanime/iframe.ts
- websites/K/Kickassanime/presence.ts
- websites/K/Kickassanime/tsconfig.json
All screenshots are of mapped out pages
I chose not to add the settings page in but I can add it on request
Timestamps work as expected
Resolves #834
> ✍ Added kickassanime presence

- websites/A/atomicradio/dist/metadata.json
- websites/A/atomicradio/presence.ts
- websites/A/atomicradio/tsconfig.json
We would like to make the **atomicradio** Presence available in the PreMiD Store. We are a web radio station from Hamburg in Germany.
> Add atomicradio presence 📜

- websites/Y/YouTube Music/dist/metadata.json
- websites/Y/YouTube Music/presence.ts
Add a check to `getAuthorString()` to have the year displayed only on channels, and not on user library uploads.
Prevents library uploads having the last four characters of the title be repeated.
> youtube music: check if song is from channel

- websites/D/DeviantArt/dist/metadata.json
- websites/D/DeviantArt/presence.ts
- websites/F/Fandom/dist/metadata.json
- websites/F/Fandom/presence.ts
- websites/G/Gamepedia/dist/metadata.json
- websites/G/Gamepedia/presence.ts
- websites/G/GeoGuessr/dist/metadata.json
- websites/G/GeoGuessr/presence.ts
- websites/M/ManiaExchange/dist/metadata.json
- websites/M/ManiaExchange/presence.ts
- websites/O/Outline/dist/metadata.json
- websites/O/Outline/presence.ts
- websites/T/TrackMania Exchange/dist/metadata.json
- websites/T/TrackMania Exchange/presence.ts
- websites/T/Typeracer/dist/metadata.json
- websites/T/Typeracer/presence.ts
- websites/W/Wikiwand/dist/metadata.json
- websites/W/Wikiwand/presence.ts
Here's one of the biggest update waves for this year from me. I might be busy in the next months, so I need to get this done sooner or later.
This PR updates all presence by me except from the Wikimedia presences. Few of them might be minor, but some consists of major bug fixes and new page support. There's just a heck of a lot of improvements from the last time I updated them. I hope I don't miss some new requirements and features on this repository/project. 
Except that button feature. That might be included in another PR when later, many presences are using it.
Wikimedia presences will be updated in the future.
This PR includes updates to the following presences:
- DeviantArt (1.2.0)
- Fandom (1.2.0)
- Gamepedia (1.2.0)
- GeoGuessr (1.2.6)
- ManiaExchange (1.2.6)
- Outline (1.0.3)
- …
> Update multiple presences (28/01/2021)

- websites/C/Cuevana 3/dist/metadata.json
- websites/C/Cuevana 3/iframe.ts
- websites/C/Cuevana 3/presence.ts
- websites/C/Cuevana 3/tsconfig.json
- websites/S/Salty Bet/dist/metadata.json
- websites/S/Salty Bet/presence.ts
> Added Cuevana 3 Presence and Salty Bet bugfixes

- websites/M/Musixmatch/dist/metadata.json
- websites/M/Musixmatch/presence.ts
- websites/M/Musixmatch/tsconfig.json
This PR adds presence for Musixmatch.
Closes #2605
> Add Musixmatch

- websites/A/Anime4up/dist/metadata.json
- websites/B/Blkom/dist/metadata.json
Transferring the ownership of my presences to my new alt.
> Transferring the ownership of my presences to my new alt

- websites/Y/YummyAnime/dist/metadata.json
- websites/Y/YummyAnime/iframe.ts
- websites/Y/YummyAnime/presence.ts
Note: This is a really outdated Presence and as it stands the website has a completely new page layout which it seems this Presence does not handle (so someone will have to go through and map out every new page and add all the else statements as such).
However, I've committed a fix for the bug at the footer of this PR (which was on my TODO list). 
Below are screenshots of the page when you are now watching an anime (which was broken due to outdated code). 
I also fixed all potential Codacy issues (ie merge consts, prefer const and let).
Resolves #2889
> 🐛Fixed Yummyanime bug

- .vscode/extensions.json
- websites/M/Magister/dist/metadata.json
- websites/M/Magister/presence.ts
- websites/M/Magister/tsconfig.json
I've written a presence for the most popular (yet the worst) student information system in the Netherlands, Magister 6. This is my first pull request for this repository, so please tell me if I did anything wrong 😬
> Magister Presence

- websites/A/Animelon/dist/metadata.json
- websites/A/Animelon/iframe.ts
- websites/A/Animelon/presence.ts
- websites/A/Animelon/tsconfig.json
**Screenshots of working (with what page screenshot is from)**
Link (all links are https://animelon.com/) | Image
|-------|-----------------------------------|
homepage | ![LzyiqPMO3B](https://user-images.githubusercontent.com/34070194/106769686-22ea1c80-6635-11eb-83a3-f5ec09ee6b9c.png)
series | ![pBZkzSZF2q](https://user-images.githubusercontent.com/34070194/106769742-3301fc00-6635-11eb-8880-3bd24e6d0a1e.png)
video | ![sngHB9qUSi](https://user-images.githubusercontent.com/34070194/106769773-3ac1a080-6635-11eb-8e9c-757487492fcb.png)
Resolves #2884
> ✍ Add Animelon Presence

- websites/W/WoolyPooly/dist/metadata.json
Presence description from translations on the site.
> Added description languages

- websites/B/Binance/dist/metadata.json
- websites/B/Binance/presence.ts
- websites/B/Binance/tsconfig.json
Website: [Binance](https://www.binance.com/)
> Add Binance presence

- websites/W/WoolyPooly/dist/metadata.json
- websites/W/WoolyPooly/presence.ts
Show current page coin info
Fix for working in light mode
> Update WoolyPooly - cion details

- websites/B/Bots For Discord/dist/metadata.json
- websites/B/Bots For Discord/presence.ts
- websites/B/Bots For Discord/tsconfig.json
> botsfordiscord.com added

- websites/A/Altearn/dist/metadata.json
- websites/A/Altearn/presence.ts
- websites/A/Altearn/tsconfig.json
- websites/B/BuildTheEarth/dist/metadata.json
- websites/B/BuildTheEarth/presence.ts
- websites/B/BuildTheEarth/tsconfig.json
This time with Altearn.xyz with 2 mounth
> Proof it's working : 
Altearn.xyz 
without 
and with the privacy mode 
(This website was realy easy because with the website construction I can just see that page your looking with the window title)
BuildTheEarth.net
without 
and with Hide map position 
(I'm realy proud of the follow with the map)
and finaly with privacy mode
> Added Altearn.xyz and BuildTheEarth.net

- websites/G/Gogoanime/dist/metadata.json
> Update gogoanime url extension [so] -> [sh]

- .resources/README.MD
- websites/H/Hytale/dist/metadata.json
- websites/H/Hytale/presence.ts
- websites/H/Hytale/tsconfig.json
This presence covers every page on the Hytale website (https://hytale.com)
Also fixed some odd spaces in .resources/README.md cuz that's annoying
Here are a few screenshots (not all pages are included but they have all been tested) https://imgur.com/a/rLl4iw2
> New presence for the Hytale website

- websites/D/Discord/dist/metadata.json
- websites/D/Discord/presence.ts
- websites/G/Genius/dist/metadata.json
- websites/G/Genius/presence.ts
- websites/N/NameMC/dist/metadata.json
- websites/N/NameMC/presence.ts
- websites/N/Netflix/dist/metadata.json
- websites/N/Netflix/presence.ts
- websites/T/TikTok/dist/metadata.json
- websites/T/TikTok/presence.ts
- websites/T/Twitch/dist/metadata.json
- websites/T/Twitch/presence.ts
- websites/T/Twitter/dist/metadata.json
- websites/T/Twitter/presence.ts
- websites/Y/YouTube/dist/metadata.json
- websites/Y/YouTube/presence.ts
Strings not released yet screenshots will look like:
> Presence updates

- websites/D/DreamSub/dist/metadata.json
Updated and fixed metadata.json file (Changed DreamSub domain)
> 🐛FIX: metadata.json file

- websites/T/TheSite/dist/metadata.json
Proof of working on calmx.site:
> ✏️ Add support for calmx.site

- websites/M/Marktplaats/dist/metadata.json
- websites/M/Marktplaats/presence.ts
- websites/M/Marktplaats/tsconfig.json
> Added Marktplaats

- websites/D/Destiny Item Manager/dist/metadata.json
- websites/D/Destiny Item Manager/presence.ts
- websites/D/Destiny Item Manager/tsconfig.json
[Destiny Item Manager](https://app.destinyitemmanager.com/) presence
> Added Destiny Item Manager presence

- websites/H/Hypixel Studios/dist/metadata.json
- websites/H/Hypixel Studios/presence.ts
- websites/H/Hypixel Studios/tsconfig.json
- websites/H/Hytale/dist/metadata.json
- websites/H/Hytale/presence.ts
Hypixel Studios recently released their brand new website https://hypixelstudios.com and I made a presence for it! Here are the screenshots: https://imgur.com/a/rHFQDTr
Also added a page I missed on the Hytale Presence: https://i.imgur.com/BB0SwGJ.png
> Add Hytale page and new Hypixel Studios presence

- websites/L/LoL Esports/dist/metadata.json
- websites/R/Riot Games/dist/metadata.json
- websites/R/Riot Games/presence.ts
- websites/R/Riot Games/tsconfig.json
> Riot games presence added and made translation changes to LoL Esports

- websites/G/Gogoanime/dist/metadata.json
> URL updated | GogoAnime.so

- websites/M/MKPC/dist/metadata.json
- websites/M/MKPC/presence.ts
- websites/M/MKPC/tsconfig.json
Ive added a presence for MKPC. Proof:
> Add MKPC presence

- websites/M/Marktplaats/dist/metadata.json
- websites/M/Marktplaats/presence.ts
> Marktplaats Updated from 1.0.1 to 1.0.2

- websites/M/Mediafire/dist/metadata.json
- websites/M/Mediafire/presence.ts
- websites/M/Mediafire/tsconfig.json
Resolves #3022
_PLEASE DARK DONT RUIN THIS PR LIKE THE OTHER ONES PLS_
> Added Mediafire 1.0.0

- websites/A/Agar.io/dist/metadata.json
- websites/A/Agar.io/presence.ts
- websites/J/Jet Set Radio Live/dist/metadata.json
- websites/J/Jet Set Radio Live/presence.ts
- websites/N/Newgrounds/dist/metadata.json
- websites/N/Newgrounds/presence.ts
- websites/Q/Quizlet/dist/metadata.json
- websites/Q/Quizlet/presence.ts
- websites/S/StoryFire/dist/metadata.json
- websites/S/StoryFire/presence.ts
The following presences have been updated to feature button functionality:
<details>
<summary>Agar.io - You can now join parties from a button</summary>
</details>
<details>
<summary>Jet Set Radio Live</summary>
</details>
<details>
<summary>Newgrounds</summary>
</details>
<details>
<summary>Quizlet</summary>
</details>
<details>
<summary>StoryFire</summary>
</details>
> Update 5 presences to use buttons

- websites/C/CatchPlay/dist/metadata.json
- websites/C/CatchPlay/presence.ts
Updating catchplay, now with button.
> Catchplay Update

- websites/V/VRCArena/dist/metadata.json
- websites/V/VRCArena/presence.ts
I quickly added buttons that got introduced in the latest PreMiD update.
**Screenshot:**
> VRCArena: added basic buttons

- websites/R/R6Stats/dist/metadata.json
- websites/R/R6Stats/presence.ts
- websites/R/R6Stats/tsconfig.json
Presence for [R6Stats](https://r6stats.com/)
> Added R6Stats presence

- websites/0-9/4anime/dist/metadata.json
- websites/0-9/4anime/presence.ts
- websites/P/Pokémon Showdown/dist/metadata.json
- websites/P/Pokémon Showdown/presence.ts
- websites/S/surviv.io/dist/metadata.json
- websites/S/surviv.io/presence.ts
- Added "Spectate" button to Pokémon Showdown
- Added "Join Game" button to surviv.io
- Added "Episode" & "Series" buttons to 4anime
- Got rid of my locally defined `getTimestamps` in 4anime in favor of the `Presence` class one
> Added Buttons & small changes

- websites/L/LoL Esports/dist/metadata.json
- websites/L/LoL Esports/presence.ts
- websites/R/Riot Games/dist/metadata.json
- websites/R/Riot Games/presence.ts
Added Button function to LoL Esports presence, made minor changes to Riot Games Presence
> LoLEsports Update + Riot Games Update

- websites/M/Multporn/dist/metadata.json
- websites/M/Multporn/presence.ts
- Added Setting to Enable Button
- Added Button leading to whatever page you currently browse
- Bumped Ver Number to 1.0.2
> Multporn Presence Update: 1.0.2 Basic "Read Along" Button

- websites/C/Cuevana 3/dist/metadata.json
- websites/C/Cuevana 3/presence.ts
- websites/S/Salty Bet/dist/metadata.json
- websites/S/Salty Bet/presence.ts
> SaltyBet and Cuevana3 button update 

- websites/D/Discord Templates/dist/metadata.json
- websites/D/Discord Templates/presence.ts
This update introduces:
- Buttons: View a template or a user profile with a single click (can be deactivated from presence settings).
- Privacy Settings: For those who don't like to show which template they're looking for (enabled by default).
- Fix the old logo and thumbnail.
- Add some alternative names.
> ✨ Update Discord Templates presence!

- websites/W/Wallhaven/dist/metadata.json
- websites/W/Wallhaven/presence.ts
- websites/W/Wallhaven/tsconfig.json
features:
- searching, top list, random & latest
- viewing wallpaper
- open wallpaper button (could not test it yet, only on canary discord?)
- reading forum/thread/board
> added wallhaven.cc

- websites/V/VidCloud9/dist/metadata.json
- websites/V/VidCloud9/iframe.ts
- websites/V/VidCloud9/presence.ts
Fixed all the errors left in the previous build.
Proof:
Settings Proof:
> VidCloud9 Update

- websites/Y/YouTube/dist/metadata.json
- websites/Y/YouTube/presence.ts
Displays 'Watch Stream' in Discord buttons instead of 'Watch Video' on a live-stream
> ✨ Show 'Watch Stream' on YT Stream

- websites/B/bol.com/dist/metadata.json
- websites/B/bol.com/presence.ts
- websites/B/bol.com/tsconfig.json
- websites/T/Trello/dist/metadata.json
Added a [bol.com](https://www.bol.com) presence (#881)
> bol.com presence

- websites/M/MALL.TV/dist/metadata.json
- websites/M/MALL.TV/presence.ts
- websites/M/MALL.TV/tsconfig.json
Presence for Czech/Slovak video service MALL.TV.
**Features:**
- Browsing (for homepage)
- Browsing (for channels, categories, search results)
- Playing video (with buttons)
- Playing live video
- Paused video
**Note about localization:** Buttons are not localized to Czech/Slovak now as I use general strings and its translations are waiting for approval.
> ✨Add presence: MALL.TV

- websites/D/Disney+/dist/metadata.json
- websites/D/Disney+/presence.ts
Big update for the Disney+ presence including:
* Refactoring
* Added settings
* Buttons!
* Support for the Disney+ GroupWatch feature
* New thumbnail and lots more descriptions in different languages
> Disney+: big update

- websites/V/Vidstreaming/dist/metadata.json
- websites/V/Vidstreaming/iframe.ts
- websites/V/Vidstreaming/presence.ts
Proof:
Without video time:
Without time elapsed:
Notes:
I noticed that when I tried clicking the buttons I had to refresh or move to another page. Might be an issue with my system tho.
Last merge did something random to my code, so I had to completely refork the code.
> Update for Vidstreaming

- websites/C/Cuevana 3/dist/metadata.json
- websites/C/Cuevana 3/iframe.ts
- websites/C/Cuevana 3/presence.ts
- websites/S/Salty Bet/dist/metadata.json
- websites/S/Salty Bet/presence.ts
- websites/T/Tetr.io/dist/metadata.json
- websites/T/Tetr.io/presence.ts
- websites/T/Tetr.io/tsconfig.json
> TETR.IO presence, Saltybet settings update and Cuevana3 button fix

- websites/H/HBO Max/dist/metadata.json
- websites/H/HBO Max/presence.ts
Fixes issues with the timestamps
> 🐛 Bug fixes with HBO MA

- websites/N/Nettruyen/dist/metadata.json
- websites/N/Nettruyen/presence.ts
- websites/N/Nettruyen/tsconfig.json
- websites/Y/Yoakemoe/dist/metadata.json
- websites/Y/Yoakemoe/presence.ts
> Update yoake.moe presence

- websites/C/Codenames/dist/metadata.json
- websites/C/Codenames/presence.ts
- websites/C/Codenames/tsconfig.json
- websites/T/TikTok/dist/metadata.json
- websites/T/TikTok/presence.ts
> added Codenames & Bug fixes for TikTok

- websites/I/iQIYI/dist/metadata.json
- websites/I/iQIYI/presence.ts
- websites/L/Line TV/dist/metadata.json
- websites/L/Line TV/presence.ts
- websites/L/Line TV/tsconfig.json
- websites/V/Viu/dist/metadata.json
- websites/V/Viu/presence.ts
- websites/V/Viu/tsconfig.json
Resolves #2124 
Resolves #2898 
Might as well add more pages to these Presences
> Fix iQIYI | new presence for Line TV | new presence for Viu

- websites/S/Sinefy/dist/metadata.json
- websites/S/Sinefy/iframe.ts
- websites/S/Sinefy/presence.ts
- websites/S/Sinefy/tsconfig.json
Another Turkish video streaming service, on request.
> 🔥 Sinefy Presence

- websites/J/Jstris/dist/metadata.json
- websites/J/Jstris/presence.ts
With signed in:
Without signed in:
Buttons with Sign In:
Buttons without Sign In:
> Bump Jstris Ver to 1.1.2 - Emergency Hotfix to Fix Presence for Non-Signed in Users.

- websites/S/Speedtest/dist/metadata.json
- websites/S/Speedtest/presence.ts
- websites/S/Speedtest/tsconfig.json
Hello, I made a presence for https://www.speedtest.net/
> Add Speedtest presence

- websites/K/Kijk/dist/metadata.json
- websites/K/Kijk/presence.ts
- websites/K/Kijk/tsconfig.json
Resolves #3047 
Added kijk basic functionality:
- Added Browsing
- Added Homepage
- Added Watching Tv Shows
- Added Watching Movies
- Added Watching Missed Tv Shows
> 🎈Added Kijk (1.0.0)

- websites/R/RealLifeGTAV/dist/metadata.json
- websites/R/RealLifeGTAV/presence.ts
> Real life gtav

- websites/D/Dizimag/dist/metadata.json
- websites/D/Dizimag/presence.ts
> Dizimag RPC Update, buttons added.

- websites/L/Liebe Schnee Hiver/dist/metadata.json
- websites/L/Liebe Schnee Hiver/presence.ts
- websites/L/Liebe Schnee Hiver/tsconfig.json
> 🎉 Liebe Schnee Hiver Presence!

- websites/B/Bounce/dist/metadata.json
- websites/B/Bounce/presence.ts
- websites/R/Repeat/dist/metadata.json
- websites/R/Repeat/presence.ts
finally a pull request that doesnt have a load of file changes I DIDNT DO reeeeeee
> repeat and bounce

- websites/V/Vidstreaming/dist/metadata.json
- websites/V/Vidstreaming/presence.ts
Added Buttons:
Note: For some reason elapsed time doesn't work with buttons. I think I just have a bad installation of PreMiD.
> Added Buttons

- .github/workflows/SV.yml
> Revert "🔼 Bump PreMiD/changed-files from v3 to v3.2.1"

- websites/S/Sezonluk Dizi/dist/metadata.json
- websites/S/Sezonluk Dizi/iframe.ts
- websites/S/Sezonluk Dizi/presence.ts
- websites/S/Sezonluk Dizi/tsconfig.json
- websites/S/Sinefy/dist/metadata.json
- websites/S/Sinefy/iframe.ts
- websites/S/Sinefy/presence.ts
- websites/T/TRanimeizle/dist/metadata.json
- websites/T/TRanimeizle/iframe.ts
- websites/T/TRanimeizle/presence.ts
- websites/T/TRanimeizle/tsconfig.json
Another Turkish video streaming and TV series website.
A Turkish anime listing and watching platform. This PR closes #2273 made by the website author @tranimeizle (I believe).
It wasn't displaying timestamps. It does now.
> 🔥 Sezonluk Dizi and TRanimeizle Presences - Fixes for Sinefy Presence

- websites/C/Coub/dist/metadata.json
- websites/C/Coub/presence.ts
- rewritten anything + structure
- updated selectors
- old client id removed (did not work, user banned?)
- updated resources (images)
- ~~added support for [coub-bridge](https://github.com/Venipa/coubdl-bridge), download directly via custom scheme (default setting is set to disabled)~~
- show youtube source button & watch coub video button
> coub.com: fixed/updated & rewritten

- websites/V/Void Bots/dist/metadata.json
- websites/V/Void Bots/presence.ts
- websites/V/Void Bots/tsconfig.json
View on Home Page: [Image](https://discord.mx/i/ZIFBiPfKVK.png "Original Image Link")
View on Bot Page: [Image](https://discord.mx/i/lU0niIhjSV.png "Original Image Link")
View on User Page: [Image](https://discord.mx/i/mdk78lkIxJ.png "Original Image Link")
> Add Void Bots

- websites/D/Discord BotList/dist/metadata.json
- websites/D/Discord BotList/presence.ts
- websites/D/Discord BotList/tsconfig.json
**View on Main Page:**
**View on Profile Page:**
**View on Bot Page:**
**View on Vote Page:**
**There are 8 more sites but this would be too Long!**
> Added Discord BotList

- websites/W/WatchMojo/dist/metadata.json
- websites/W/WatchMojo/iframe.ts
- websites/W/WatchMojo/presence.ts
- websites/W/WatchMojo/tsconfig.json
Has own strings because it is a sort of "Partnered" presence.
> ✨ WatchMojo

- websites/G/Google Fonts/dist/metadata.json
- websites/G/Google Fonts/presence.ts
Hi, I closed my previous PR because I messed up something but nevermind, merge conflicts should be fixed
Thank you
> Updated Google Fonts presence

- websites/K/Kryptonia/dist/metadata.json
- websites/K/Kryptonia/presence.ts
- websites/K/Kryptonia/tsconfig.json
Added presence for kryptonia.fr, a French minecraft server.
https://i.imgur.com/yqkNyqc.png
https://i.imgur.com/gnwVs7C.png
> ✨ Added Kryptonia

- websites/J/Jellyfin/dist/metadata.json
- websites/J/Jellyfin/presence.ts
There've been some changed in the frontend and the video playback has to be updated, the other features work ok.
Proof of video playback
> 👽 Updated video playback parser for Jellyfin 10.7.0

- websites/T/Trackmania.io/dist/metadata.json
- websites/T/Trackmania.io/presence.ts
- websites/T/Trackmania.io/tsconfig.json
Added Trackmania.io presence - a website displaying live informations on Trackmania video game
Created for #3233
> Create Trackmania.io presence

- websites/D/Disney+/dist/metadata.json
- websites/D/Disney+/presence.ts
The presence now works for Hotstar again since I was the big dumb.
> Disney+: fix button in Hotstar presence

- websites/J/jut.su/dist/metadata.json
- websites/J/jut.su/presence.ts
- websites/J/jut.su/tsconfig.json
Added presence for jut.su - Russian anime website
> Add jut.su presence

- websites/T/TruckersMP/dist/metadata.json
- websites/T/TruckersMP/presence.ts
##Change log:
- Supported unsupported pages; 
- Added buttons; 
- Fixed poor code; 
- Assigned the presence to myself as nobody owned it before
Proof with and without buttons setting enabled, let me know if you want anymore.
> 🆕 TruckersMP Update

- websites/A/Anime Planet/dist/metadata.json
- websites/A/Anime Planet/iframe.ts
- websites/A/Anime Planet/presence.ts
> [Update] Anime Planet Presence

- websites/T/TruckersFM/dist/metadata.json
- websites/T/TruckersFM/presence.ts
Added elapsed time to TFM presence
Added buttons for listening and Spotify of the track.
Evidence of testing:
> Added timestamp & buttons to TFM presence

- websites/P/Prambors Radio/dist/metadata.json
- websites/P/Prambors Radio/presence.ts
> feat(Prambors Radio): add button and support for the new streaming page

- websites/B/Blockbench/dist/metadata.json
- websites/B/Blockbench/presence.ts
Fixed showing the wrong model when streamer mode is on.
> fix(blockbench): model type bug

- websites/#/巴哈姆特/dist/metadata.json
- websites/#/巴哈姆特動畫瘋/dist/metadata.json
- websites/#/网易云音乐/dist/metadata.json
- websites/0-9/4chan/dist/metadata.json
- websites/0-9/7plus/dist/metadata.json
- websites/0-9/8muses/dist/metadata.json
- websites/0-9/9GAG/dist/metadata.json
- websites/0-9/9anime/dist/metadata.json
- websites/A/Astr.io/dist/metadata.json
- websites/S/Sickipedia/dist/metadata.json
- websites/S/Sickipedia/presence.ts
- websites/S/Sickipedia/tsconfig.json
hope this is enough images HHAHHA
> New presence - Sickipedia & Irish Descriptions Added

- websites/D/Discord Templates/dist/metadata.json
- websites/D/Discord Templates/presence.ts
template names are now working
> fix: discord templates presence

- websites/H/Hd-Streams/dist/metadata.json
- websites/H/Hd-Streams/iframe.ts
- websites/H/Hd-Streams/presence.ts
- websites/H/Hd-Streams/tsconfig.json
(Series, same like movies except the view series button)
> hd-streams.org

- websites/S/Simulator Radio/dist/metadata.json
- websites/S/Simulator Radio/presence.ts
- New images for the store
- Added some more tags
- Set the metadata schema
- Updated to support something upcoming
- Some general cleanup bits
> Simulator Radio General Maintenance

- websites/M/Mugzone/dist/metadata.json
- websites/M/Mugzone/presence.ts
- websites/M/Mugzone/tsconfig.json
> New presence - Mugzone

- websites/A/Aranzulla.it/dist/metadata.json
Few changes/fixes.
We noticed sometimes, though rarely when saving a file, the version would bump but the translation would not be added. This is a temporary solution to that.
> ✨ One singular Irish translation for the bois

- websites/H/HentaiZ/dist/metadata.json
- websites/H/HentaiZ/iframe.ts
- websites/H/HentaiZ/presence.ts
- websites/H/HentaiZ/tsconfig.json
> HentaiZ Presence

- websites/B/bilibili/dist/metadata.json
- websites/B/bilibili/presence.ts
On bilibili there are some div class changes and i tried to fix it. Now it works properly.
See the pics:
> Presence Bilibili: Fixed the Video playing and pause problems.

- websites/A/AnimeKisa/dist/metadata.json
- websites/A/AnimeKisa/iframe.ts
- websites/A/AnimeKisa/presence.ts
Should resolve #2590, resolve #3288, and resolve #3371. Replaced the presence's `getTimestamps` function in favor of the one in the `Presence` class.
> Fix AnimeKisa Presence

- websites/M/Mixcloud/dist/metadata.json
- websites/M/Mixcloud/presence.ts
Mixcloud didn't work at all because of wrong if/else and typescript errors (eg. tried to access variables which were not available).
Also refactored the code to not use hashed class names, which were changed after a new mixcloud-deploy. I updated the presence to use more generic class names which should not change soon. Tested it with normal mixcloud music and live streams.
The added contributor MilMike is me in discord.
> Fixed and updated Mixcloud Presence

- websites/S/Snipes/dist/metadata.json
- websites/S/Snipes/presence.ts
- websites/S/Snipes/tsconfig.json
> Added SNIPES presence

- websites/W/Worldhideaway/dist/metadata.json
- websites/W/Worldhideaway/presence.ts
- websites/W/Worldhideaway/tsconfig.json
Resolves #3101 
Added Full Website Functionality.
> 🌎Added WorldHideaway Presence

- websites/S/SyncTube/dist/metadata.json
- websites/S/SyncTube/presence.ts
- websites/S/SyncTube/tsconfig.json
> SyncTube presence

- websites/A/Armorgames/dist/metadata.json
- websites/A/Armorgames/presence.ts
- websites/A/Armorgames/tsconfig.json
Added All pages for main domain!
Resolves #2168
> ⚔Added Armorgames (V1.0.0)

- websites/R/Rádio Animu/dist/metadata.json
- websites/R/Rádio Animu/iframe.ts
- websites/R/Rádio Animu/presence.ts
Just changing to the new logo, adding support to a new page. ~~and adding a button that redirects to the website when the stream is playing.~~
> Updated Rádio Animu Presence

- websites/T/Tesla/dist/metadata.json
- websites/T/Tesla/presence.ts
- websites/T/Tesla/tsconfig.json
> Tesla Presence

- websites/T/Tesla/dist/metadata.json
> Update metadata.json | Tesla

- websites/G/Glimesh/dist/metadata.json
- websites/G/Glimesh/presence.ts
- websites/G/Glimesh/tsconfig.json
New Presence: For [Glimesh.tv](https://glimesh.tv/)
Tested for any bugs and such, and should all be fixed! :)
> [New Presence] Glimesh Presence v1.0.0

- websites/T/Tesla/dist/metadata.json
- websites/T/Tesla/presence.ts
https://github.com/PreMiD/Presences/runs/2291858848?check_suite_focus=true#step:7:20
Proof:
> Fixed TSC errors/warnings | Tesla presence

- websites/P/Plex/dist/metadata.json
- websites/P/Plex/presence.ts
Updated DOM selectors for the Plex presences for the [latest Plex web build as of April 11th, 2021](https://forums.plex.tv/t/plex-web/20528/351).
**Done the following:**
- Updated DOM selectors
- Added Swedish translation
> Updated presence for Plex to work with 4.55.0

- websites/M/Monos Chinos/dist/metadata.json
- websites/M/Monos Chinos/presence.ts
**Name:**
Monos Chinos
**Changes:**
- Added new website url in metadata presence
**Screenshots:**
> Updated Monos chinos presence

- websites/S/Scantrad/dist/metadata.json
- websites/S/Scantrad/presence.ts
- websites/S/Scantrad/tsconfig.json
Hey, I'm adding Scantrad presence, here are the proofs that the presence works perfectly:
- https://i.imgur.com/zDnHRWj.png
- https://i.imgur.com/E7gKtp2.png
> Added Scantrad presence

- websites/D/Disney+/dist/metadata.json
- websites/D/Disney+/presence.ts
Added a privacy mode, also updated the thumbnail.
**Screenshots:**
> Disney+: add privacy mode

- websites/J/JAVX/dist/metadata.json
- websites/J/JAVX/presence.ts
After a short period of use, I want my Presence to have a little more information such as **current page number**, **current episode**... so I decided to make this update.
Proof of working:
| Lines | Page Name | Image |
| :---: | :---: | :---: |
| 83 - 85 | Home Page | ![home](https://user-images.githubusercontent.com/82100896/114493392-ad0dbd00-9c44-11eb-8a90-65f33ac16f9b.png) |
| 86 - 93 | Search Page | ![search1](https://user-images.githubusercontent.com/82100896/114493500-dcbcc500-9c44-11eb-8b5c-f695c2a795ed.png) ![search2](https://user-images.githubusercontent.com/82100896/114493555-f65e0c80-9c44-11eb-9d32-30216546bfa3.png) |
| 94 - 98 | Sign In / Up | ![signin](https://user-images.githubusercontent.com/82100896/114494262-41c4ea80-9c46-11eb-835f-9b7ec34edcb8.png) |
| 99 - 104 | …
> Update JAVX v1.1.0

- websites/H/Hypixel Studios/dist/metadata.json
- websites/H/Hypixel Studios/presence.ts
Fixed this issue:
Added this page:
> Hypixel Studios: Added "Our Team" page and fixed a bug with jobs page

- websites/A/AnimeDigitalNetwork/dist/metadata.json
- websites/A/AnimeDigitalNetwork/presence.ts
Resolves #2682
- Deleted Subtitles, cause not working and couldn't be fixed,
- Removed old DOMs & added new ones for Title.
> AnimeDigitalNetwork Presence Fixed

- websites/G/Gogoanime/dist/metadata.json
- websites/G/Gogoanime/presence.ts
https://user-images.githubusercontent.com/33565739/114619230-f85eb480-9cb2-11eb-9bed-ea57b6aed669.png
https://user-images.githubusercontent.com/33565739/114619417-38be3280-9cb3-11eb-9558-6c9051d4f40f.png
https://user-images.githubusercontent.com/33565739/114619519-52f81080-9cb3-11eb-8601-dcb5fa4d9fd1.png
> [Gogoanime presence] fixed subdomain issue

- websites/M/MKPC/dist/metadata.json
- websites/M/MKPC/presence.ts
Hello PreMiD reviewer team! 
I have updated the mkpc presences, feel free to tell me if i need to improve anything! 
proof:
> bug fixes and improvement | MKPC

- websites/T/Trackmania.io/dist/metadata.json
- websites/T/Trackmania.io/presence.ts
- Changes on Track Of The Day Leaderboard
- Add single map leaderboard
> Update Trackmania.io 

- websites/A/atomicradio/dist/metadata.json
- websites/A/atomicradio/presence.ts
We made a small change to the atomicradio Presence. From now on, users will be automatically reconnected to our Websocket when the connection fails.
> Small improvements to the atomicradio Presence

- websites/P/Prime Video/dist/metadata.json
- websites/P/Prime Video/presence.ts
I have added the support for Watchparty at Prime Video service.
The presence acts like while normal watching.
> Prime Video watchparty support

- websites/A/Aniorb/dist/metadata.json
- websites/A/Aniorb/iframe.ts
- websites/A/Aniorb/presence.ts
- websites/A/Aniorb/tsconfig.json
My old PR request was closed because site had updates. So site updated and this is the new Aniorb presence.
> Aniorb Presence V2.0

- websites/W/Wolfram Alpha/dist/metadata.json
- websites/W/Wolfram Alpha/presence.ts
- websites/W/Wolfram Alpha/tsconfig.json
I created Wolfram Alpha presence :)
Here are the proof the presence is working :
-https://i.imgur.com/PBJxtZu.png
-https://i.imgur.com/fPMZuSx.png
-https://i.imgur.com/AJXzJLl.png
> Added Wolfram Alpha presence

- websites/P/Prime Video/dist/metadata.json
- websites/P/Prime Video/presence.ts
I have add handling custom quote marks (`„ ”`) in some page languages and handling title-arts of some series (e.g `The Man in High Castle`)
> PrimeVideo: Handle search and title-art edge cases

- websites/A/Anicloud/dist/metadata.json
- websites/A/Anicloud/iframe.ts
- websites/A/Anicloud/presence.ts
- websites/A/Anicloud/tsconfig.json
> New Presence "AniCloud"

- websites/Y/YouTube/dist/metadata.json
- websites/Y/YouTube/presence.ts
Resolves #3157
Regardless of the YouTube's language, check if video is unlisted and not assign buttons to presence.
(Random language I picked from lang list:)
> Youtube: unlisted videos doesn't have buttons

- websites/P/Photopea/dist/metadata.json
- websites/P/Photopea/presence.ts
> [Photopea] fix: #3465

- websites/B/Bunpro/dist/metadata.json
- websites/B/Bunpro/presence.ts
- websites/B/Bunpro/tsconfig.json
> Bunpro presence

- websites/G/Genius/dist/metadata.json
- websites/G/Genius/presence.ts
> [Genius] fix: lyrics

- websites/H/Hoyolab/dist/metadata.json
- websites/H/Hoyolab/presence.ts
- websites/H/Hoyolab/tsconfig.json
Fully working Hoyolab.com presence with all features.
resolve #3590
> Added Hoyolab presence

- websites/S/Score Saber/dist/metadata.json
- websites/S/Score Saber/presence.ts
- websites/S/Score Saber/tsconfig.json
New Presence for [Scoresaber.com](https://Scoresaber.com)
> New Presence Score Saber

- websites/K/KissAsian/dist/metadata.json
- websites/K/KissAsian/iframe.ts
- websites/K/KissAsian/presence.ts
> [KissAsian] fix and small refactor

- websites/S/Scantrad/dist/metadata.json
- websites/S/Scantrad/presence.ts
> [Scantrad] fix: not showing title and chapter of manga

- websites/G/Google Drive/dist/metadata.json
- websites/G/Google Drive/presence.ts
Uses new logo, some cleanup to states.
Will now replace /u/number  from urls when logged into multiple accounts.
> 📁 Google drive changes

- websites/S/Snipes/dist/metadata.json
- websites/S/Snipes/presence.ts
> Support for Snipes Belgium & Switzerland | SNIPES presence

- websites/Y/YouTube/dist/metadata.json
- websites/Y/YouTube/presence.ts
Change the way how to check if video is unlisted
Related to PR #3569
> [YouTube] No buttons for unlisted videos in playlist

- websites/S/SeriManga/dist/metadata.json
- websites/S/SeriManga/presence.ts
- websites/S/SeriManga/tsconfig.json
Fully working Serimanga.com presence.
resolve #3518
Screenshots:
> Added SeriManga presence

- websites/V/Viki/dist/metadata.json
- websites/V/Viki/presence.ts
> Update Viki Presence

- websites/B/BeatSaver/dist/metadata.json
- websites/B/BeatSaver/presence.ts
- websites/B/BeatSaver/tsconfig.json
New presence for [BeatSaver](https://beatsaver.com)
> New Presence BeatSaver

- websites/O/Odysee/dist/metadata.json
- websites/O/Odysee/presence.ts
- websites/O/Odysee/tsconfig.json
> [Odysee] Create presence for odysee.com

- websites/M/MangaSee/dist/metadata.json
- websites/M/MangaSee/presence.ts
- websites/M/MangaSee/tsconfig.json
Fully functional MangaSee123.com presence.
resolve #3445
Screenshots:
Settings off screenshots:
Buttons and icons:
Entries numbers: (on and off):
> Added MangaSee presence

- websites/B/BetterAnime/dist/metadata.json
- websites/B/BetterAnime/presence.ts
- websites/B/BetterAnime/tsconfig.json
> feat: BetterAnime

- websites/A/atomicradio/dist/metadata.json
Due to a small mistake on our side, our images were deleted from Imgur. We have uploaded the images again and replaced them in the metadata.json.
> Small improvement to the atomicradio Presence

- websites/G/Google Meet/dist/metadata.json
Icon updated on Discord dev portal and metadata.json
> Google Meet: Icon update

- websites/P/Platzi/dist/metadata.json
- websites/P/Platzi/presence.ts
- websites/P/Platzi/tsconfig.json
This presence is for platzi.com, one of the largest providers of online education in latam, the presence is 100% in Spanish, I read in the guidelines that it had to be in a primary language, if necessary, I can add the translations , but + 95% of platzi courses are only available in Spanish.
It has +190 icons in assets of the corresponding courses on the platform
Images of the presence working:
> Added Platzi.com presence

- websites/C/Crunchyroll/dist/metadata.json
- websites/C/Crunchyroll/presence.ts
> Added Manga To Crunchyroll & Added Watch Episode Buttons

- websites/C/CNN/dist/metadata.json
- websites/C/CNN/presence.ts
- websites/C/CNN/tsconfig.json
> Added CNN presence

- websites/A/Apple/dist/metadata.json
- websites/A/Apple/presence.ts
Proof:
https://github.com/PreMiD/Presences/pull/3660
> Updated Apple presence

- websites/R/Rabbit's BS Viewer/dist/metadata.json
- websites/R/Rabbit's BS Viewer/presence.ts
- websites/R/Rabbit's BS Viewer/tsconfig.json
Add Presence for [Rabbit's BS Viewer](https://skystudioapps.com/bs-viewer/)
Resolves #2568
> Add Rabbit's BS Viewer Presence

- websites/A/AnimeDigitalNetwork/dist/metadata.json
- websites/A/AnimeDigitalNetwork/presence.ts
> Fixed Anime Digital Network Presence

- websites/W/WebtoonXYZ/dist/metadata.json
- websites/W/WebtoonXYZ/presence.ts
- websites/W/WebtoonXYZ/tsconfig.json
Fully working webtoon.xyz presence.
resolve #3581
Screenshots:
All settings work too
> Added Webtoon.xyz presence

- websites/P/PornHub/dist/metadata.json
Presence was never version bumped
> Bump Version

- websites/D/Dumpert/dist/metadata.json
- websites/D/Dumpert/presence.ts
- websites/D/Dumpert/tsconfig.json
> Added Dumpert Presence! (Finally)

- websites/E/Emby/dist/metadata.json
- websites/E/Emby/presence.ts
Resolves #3703 
Synced Emby presence with latest Jellyfin features:
- Added TS types
- Fixed media medadata obtention
- Migrated to Presence helpers to get timestamps and display logs
- Added settings to show and hide timestamps, both general and for media playback
Screenshot proofs:
Disabled media timestamps
> Upgrade Emby presence

- websites/K/Kijk/dist/metadata.json
Changed $Schema to 1.3
Added Different Url
> Updated Kijk's Metadata

- websites/R/Read Manga Online/dist/metadata.json
- websites/R/Read Manga Online/presence.ts
- websites/R/Read Manga Online/tsconfig.json
> Added Read Manga Online | readm.org Presence

- websites/A/AnimeDigitalNetwork/dist/metadata.json
- websites/A/AnimeDigitalNetwork/presence.ts
> Fixed ADN once again.

- websites/D/DramaCool/dist/metadata.json
- websites/D/DramaCool/presence.ts
- websites/I/iQIYI/dist/metadata.json
- websites/I/iQIYI/presence.ts
> fix(DramaCool, iQIYI): fixed the video page & added fallback for language

- websites/D/Discord/dist/metadata.json
Updated the logo for the Discord presence.
> Update Discord logo

- websites/A/Apple Music/dist/metadata.json
- websites/A/Apple Music/presence.ts
Proof:
(changed old logo to new logo https://github.com/PreMiD/Presences/issues/3060)
> Updated Apple Music presence

- websites/D/Discord/dist/metadata.json
- websites/H/HITMAPS/dist/metadata.json
- websites/H/HITMAPS/presence.ts
- websites/H/HITMAPS/tsconfig.json
- websites/N/Netflix/dist/metadata.json
Added a presence for HITMAPS™. This is a website that has detailed, interactive maps for the HITMAN™ series.
https://www.hitmaps.com, https://roulette.hitmaps.com
> Added HITMAPS presence & Updated Netflix icon

- websites/I/Invidious/dist/metadata.json
added "iteroni.com" as invidious instance
> Update metadata.json on invidious presence

- websites/D/Daily Wire/dist/metadata.json
- websites/D/Daily Wire/presence.ts
- websites/D/Daily Wire/tsconfig.json
Proof:
https://github.com/PreMiD/Presences/issues/3743
> Added Daily Wire presence

- websites/W/Wizarding World/dist/metadata.json
- websites/W/Wizarding World/presence.ts
- websites/W/Wizarding World/tsconfig.json
Proof:
https://github.com/PreMiD/Presences/issues/3658
> Added Wizarding World presence

- websites/D/Discords.com/dist/metadata.json
- websites/D/Discords.com/presence.ts
- websites/D/Discords.com/tsconfig.json
Here some images of the presence working:
Previous PR #3767
> Added discords.com presence.

- websites/Z/ZombsRoyale.io/dist/metadata.json
- websites/Z/ZombsRoyale.io/presence.ts
- websites/Z/ZombsRoyale.io/tsconfig.json
> New Presence: ZombsRoyale.io

- websites/D/DscJobs/dist/metadata.json
- websites/D/DscJobs/presence.ts
Proof of taking over ownership:
Proof of presence working:
> Updated DscJobs presence.

- websites/R/Reddit/dist/metadata.json
- websites/R/Reddit/presence.ts
> Reddit Presence While Logged Out Fixed

- websites/H/Hitomi/dist/metadata.json
- websites/H/Hitomi/presence.ts
- websites/H/Hitomi/tsconfig.json
There are many redundant commit messages.
I think it would be better to merge after squash.
Also, I am new to TypeScript.
If you have any changes, please let us know.
Thank you for your time.
> feat(Hitomi): add Hitomi presences

- websites/L/Line TV/dist/metadata.json
- websites/L/Line TV/presence.ts
- websites/M/Microsoft Teams/dist/metadata.json
- websites/M/Microsoft Teams/presence.ts
- websites/N/Naver/dist/metadata.json
- websites/N/Naver/presence.ts
- *Author's account was deleted*
> fix(Microsoft Teams): yes, perf(Line TV): faster, feat(Naver): Naver Cafe

- websites/D/Discord.style/dist/metadata.json
- websites/D/Discord.style/presence.ts
- websites/D/Discord.style/tsconfig.json
Previous pr by another user: #3604
Proof of presence working:
> Added discord.style presence.

- .github/CONTRIBUTING.md
I decided to change my username from Alanexei to my real identity, propagating the changes here.
> Username Change - Guidelines

- util/tools/auto/schemaValidator.ts
> feat(SV): add invalid JSON error

- util/tools/auto/schemaValidator.ts
> feat(SV): folder == service

- .eslintrc.json
- util/tools/auto/tsconfig.auto.json
Assuming bumping other ts versions to 2021 should be done
> ⬆️ Bump All TS Version

- tsconfig.json
> Revert TS target to ES2020

- .github/CONTRIBUTING.md
> docs(Guidelines): update guidelines

- .github/workflows/SV.yml
Read title
You're welcome @Slowlife01
> ci: fix SV not running

- package.json
- util/tools/auto/schemaValidator.ts
> feat(SV): annotation

- .github/ISSUE_TEMPLATE/bug_report.yml
> feat(bug_report): add page url input

- util/tools/auto/schemaValidator.ts
> refactor(schemaValidator)

- @types/premid/index.d.ts
<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
</details>
> feat(Types): allow passing of type in getSetting

- util/tools/auto/schemaValidator.ts
Removes the extra service name, and changes group title to red text
> refactor(SV): change log style

- util/tools/auto/syntaxEnforcer.ts
Can this bitch FINALLY BE FIXED?
<details>
<summary> Proof to proving the creation/modification working </summary>
<br>
</details>
> fix(SE): bump metadata-only changes

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/service_request.yml
Added so we can start the transition back to issues!
> feat: add issue template

- util/tools/auto/schemaValidator.ts
now check metadata if make change to presence and doesn't make change to metadata
> feat(schemaValidator): now check metadata if make change to presence file

- util/tools/auto/schemaValidator.ts
> fix(schemaValidator): fix regex for array property

- package.json
- yarn.lock
> revert: "chore(deps-dev): bump chalk from 4.1.2 to 5.0.1"

- .github/CODEOWNERS
- .github/workflows/SE.yml
- Update CODEOWNERS to request @PreMiD/administrators instead of Bas all the time
- Change SE cron to once a week (Every Sunday @ 00:00)
- Does not need to be as frequent as it currently is - ts files shouldn't be merged with errors so all it is now is EOF lines
> workflow: change SE cron to once a week

- .husky/commit-msg
Fixed Husky hopefully
</details>
> chore: fix husky

- .github/workflows/SE.yml
- util/tools/util.ts
I forgot I can't just change the types, there's an actual function...
Also added the chore label in the CI
> fix: why am I so incredibly stupid

- websites/D/Destiny.gg/dist/metadata.json
Signed-off-by: Rhys <64903135+EncryptedDev@users.noreply.github.com>
> chore(Destiny): change author as requested

- websites/M/Marktplaats/dist/metadata.json
- websites/M/Marktplaats/presence.ts
Added settings
Made fixes
Better code performance (Removed regex in Metadata.json due to it not being used)
<details>
</details>
> feat(Marktplaats): settings, fixes and perf

- .gitignore
There's not much to describe, is there?
[About .idea](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-)
> chore(Gitignore): add .idea

- websites/D/Discord/dist/metadata.json
- websites/D/Discord/presence.ts
Fixed once again showing the @username when dming someone
Resolves #6474
<details>
</details>
> fix(Discord): dm username

- websites/C/Crunchyroll/dist/metadata.json
- websites/C/Crunchyroll/presence.ts
Added cover
Resolves #6087
<details>
</details>
> feat(Crunchyroll): add cover

- websites/M/MEGA/dist/metadata.json
- websites/M/MEGA/presence.ts
Rewrite the presence for better quality & fix for it to work for everything once again.
Took over ownership:
<details>
</details>
> refactor(Mega): rewrite & fixes

- websites/P/Picarto/dist/metadata.json
- websites/P/Picarto/presence.ts
Due to new style site, the querySelectors used for the presence were not working anymore. I've patched it.
close #3384 
<details>
</details>
> fix(Picarto): fix presence not showing

- websites/H/HentaiVN/dist/metadata.json
> chore(HentaiVN): change domain

- websites/S/Snapchat/dist/metadata.json
- websites/S/Snapchat/presence.ts
- websites/S/Snapchat/tsconfig.json
<details>
<details>
<summary>Settings</summary>
</details>
</details>
> feat(Snapchat): add presence

- websites/R/Raven Code/dist/metadata.json
- websites/R/Raven Code/presence.ts
Presence is currently down because the bot has been deleted. ID will be changed with a new bot.
<details>
</details>
> fix(Raven Code): change client id

- websites/0-9/9anime/dist/metadata.json
- websites/0-9/9anime/presence.ts
Fixes #6489 
<details>
</details>
> feat(9anime): website update

- websites/Z/Zoro/dist/metadata.json
- websites/Z/Zoro/presence.ts
Fixes #6427, the episode number were not showing.
Regarding the glitch of time elasped/remaining, I've found no bugs so I think it was just a temp problem.
close #6427
<details>
</details>
> fix(Zoro.to): fix episode not showing

- websites/A/Airbnb/dist/metadata.json
- websites/A/Alura/dist/metadata.json
- websites/C/CodinGame/dist/metadata.json
- websites/D/Destiny.gg/dist/metadata.json
- websites/D/Discord Turkiye/dist/metadata.json
- websites/D/dod Games/dist/metadata.json
- websites/H/HentaiVN/dist/metadata.json
- websites/H/Homestuck^2/dist/metadata.json
- websites/M/Minesweeper/dist/metadata.json
- websites/O/OpenStreetMap/dist/metadata.json
- websites/R/Raven Code/dist/metadata.json
- websites/S/Serializd/dist/metadata.json
- websites/S/Speedtest/dist/metadata.json
- websites/T/Trakt/dist/metadata.json
- websites/V/vscode.dev/dist/metadata.json
- websites/W/Wbijam/dist/metadata.json
- websites/Z/ZARP Gaming/dist/metadata.json
*beep boop* I've prettified and refactored some Presences and sorted all metadata files...
> refactor: monthly SE

- websites/S/Sitting on Clouds Radio/dist/metadata.json
- websites/S/Sitting on Clouds Radio/presence.ts
Mentionned in #2687.
Since the url has also changed, i've updated the metadata.
Plus, I've added a slideshow for a better showing of informations about the current song playing.
close #2687 
<details>
</details>
> fix(sitting on clouds radio): fix presence not working

- websites/C/Cosmote TV/dist/metadata.json
- websites/C/Cosmote TV/presence.ts
Rewrote the presence to improve the code. Also: improved series info and timestamps, channel logos now apply from the image src, and added settings.
<details>
</details>
> refactor(COSMOTE TV): recode & improve functionality

- websites/H/HBO Max/dist/metadata.json
- websites/H/HBO Max/presence.ts
Closes #6506
Closes #6495
<details>
</details>
> feat(HBO Max): fix for new UI and support more pages

- websites/M/Merriam-Webster/dist/metadata.json
- websites/M/Merriam-Webster/presence.ts
- websites/M/Merriam-Webster/tsconfig.json
Added a presence for [Merriam-Webster](https://www.merriam-webster.com/)
Resolves https://github.com/PreMiD/Presences/issues/5480
Attached are a few possible scenarios, there are many more.
<details>
</details>
> feat(Merriam-Webster): add presence

- websites/N/Neovel/dist/metadata.json
- websites/N/Neovel/presence.ts
One of the buttons displayed was "Go to book page", changed to "View Book" according to the other buttons
<details>
</details>
> fix(Neovel): fix wrong typo

- websites/0-9/9anime/dist/metadata.json
- websites/0-9/9anime/presence.ts
> fix(9anime): undefined episode name

- websites/A/Alura/dist/metadata.json
Signed-off-by: Madson Mendes <50425778+MadsonMendes@users.noreply.github.com>
Changed author's name in metadata.json
- [X ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>
> chore(Alura): change author

- websites/Y/YouTube Music/dist/metadata.json
- websites/Y/YouTube Music/presence.ts
As the title says, I completely recoded the YouTube Music Presence, while doing so I also added a lot more features to the actual Presence.
Fixes #5749 ?
Fixes #6421
Implements #6226
Can't test if this fixes #5870 - @Vlad-Games
<details>
</details>
> refactor(YouTube Music): recode presence

- websites/D/Discord ID/dist/metadata.json
- websites/D/Discord ID/presence.ts
- websites/D/Discord ID/tsconfig.json
Added presence for Discord.id
<details>
</details>
> feat(Discord ID): add presence

- websites/B/Backloggd/dist/metadata.json
- websites/B/Backloggd/presence.ts
- websites/B/Backloggd/tsconfig.json
This is a presence for Backloggd that resolves [this](https://github.com/PreMiD/Presences/issues/6465) issue.
<details>
</details>
> feat(Backloggd): add presence

- websites/U/UKTV/dist/metadata.json
- websites/U/UKTV/presence.ts
- websites/U/UKTV/tsconfig.json
Resolves #6514 
Added presence, with privacy, buttons and cover settings.
<details>
</details>
> feat(UKTV): add presence

- websites/C/CDKeys/dist/metadata.json
- websites/C/CDKeys/presence.ts
Added buttons, cover & refactored
<details>
</details>
> feat(CDKeys): buttons, cover & refactor

- websites/B/bs.to/dist/metadata.json
- websites/B/bs.to/presence.ts
I've added support for multi-domains as requested in #5302.
Resolves #5302
<details>
</details>
<details>
<summary> Proof showing the regExp is working with regex101.com/ </summary>
</details>
> feat(bs.to): add multi-domains support

- websites/J/jut.su/dist/metadata.json
- websites/J/jut.su/presence.ts
Resolves #6569
<details>
</details>
> feat(jut.su): took over ownership

- websites/L/LookMovie/dist/metadata.json
- websites/L/LookMovie/presence.ts
Changed the domains and added an extra one due to the old one not working anymore
<details>
</details>
> feat(Lookmovies): add domains and cover

- websites/D/DramaCool/dist/metadata.json
- websites/D/DramaCool/presence.ts
Add more support for different domain their elements. E.g. [new site ](https://www1.dramacool.ac/)
Resolves #6486
<details>
</details>
> feat(Dramacool): more domain support

- websites/A/animepahe/dist/metadata.json
- websites/A/animepahe/presence.ts
Resolves #6584 by redoing the getStrings() function in the presence file, the check to avoid useless calls to it was missing.
<details>
</details>
> fix(animepahe): fix getStrings constantly call

- websites/W/WhatsApp/dist/metadata.json
- websites/W/WhatsApp/presence.ts
Replaced the elements with ones that work rn 
Resolves #6591
<details>
</details>
> fix(Whatsapp): shown elements

- websites/N/Neovel/dist/metadata.json
- websites/N/Neovel/presence.ts
- Add regExp to avoid useless list in the "url" metadata, I've removed the previous URLs to only keep `neovel.io`, the others are handled by the regExp. It's to avoid sensitive case like the site adds new URLs for new languages.
- Add showCover setting since it's frequently asked to the others presences, so I've anticipated a potential feature request.
<details>
</details>
<details>
<summary> Proof showing the regExp is working as expected </summary>
</details>
<details>
<summary> Proof showing everything works fine after the change requested by Encrypted </summary>
</details>
> feat(Neovel): add regExp and showCover setting

- websites/G/Gmail/dist/metadata.json
- websites/G/Gmail/presence.ts
Refactoring the whole presence by redoing the codebase and adding the localization. I'll add a changelog section for better explanation on some choices.
**I've taken inspiration of PR #5568 by @EncryptedDev on some points, but there's some changes**
- I've added an `pages` Record of strings to avoid long if/else statements or switch/case statements.
> - However, I've decided to not do a for loop since it could be less faster than an access to the object, so there's some if/else, but I think 5 of them is fine
- Also, I found out that there's no localization for when you're viewing your inbox, so I've guessed it was the "primary category", but I'm not sure, so I would like to know if there's a change needed here.
- I've added privacy setting to show or not the label currently viewed, I've …
> refactor(Gmail): redoing codebase and add localization

- websites/N/Novelfull/dist/metadata.json
- websites/N/Novelfull/presence.ts
Added buttons & covers with settings & perf.
<details>
</details>
> feat(Novelfull): add buttons & cover & perf

- websites/E/e621/dist/metadata.json
- websites/E/e621/presence.ts
#6599 & #6600 have almost the same code. Reviewing #6600 is enough, I will change for both the PRs.
Added cover with settings _(auto disabled due to nsfw profiles pictures being possible)_ & perf
<details>
</details>
> feat(E621): add cover & perf

- websites/E/e926/dist/metadata.json
- websites/E/e926/presence.ts
#6599 & #6600 have almost the same code. Reviewing #6600 is enough, I will do changes for both the PRs at the same time.
Added cover with settings _(auto enabled due to NO NSFW content)_ & perf
<details>
</details>
> feat(E926): add cover & perf

- websites/D/Dumpert/dist/metadata.json
- websites/D/Dumpert/presence.ts
add cover with settings & perf
<details>
</details>
> feat(Dumpert): add cover with settings & perf

- websites/0-9/7plus/dist/metadata.json
- websites/0-9/7plus/presence.ts
Added covers, buttons & privacy with settings 
<details>
</details>
> feat(7plus): add covers, buttons, privacy mode & perf

- websites/W/WhatsApp/dist/metadata.json
- websites/W/WhatsApp/presence.ts
Show details when the privacy settings are on.
<details>
</details>
> feat(WhatsApp): show details on default

- websites/W/WayBack Machine/dist/metadata.json
- websites/W/WayBack Machine/presence.ts
Changed all changeable ifs to switch & changed the way it checks if buttons.
<details>
</details>
> refactor(WayBack Machine): switch & better button check

- websites/Y/Yahoo Mail/dist/metadata.json
- websites/Y/Yahoo Mail/presence.ts
Ddd privacy mode & more details even when using privacy mode
<details>
</details>
> feat(Yahoo Mail): add privacy mode & more details

- websites/S/Simplyaweeb/dist/metadata.json
- websites/S/Simplyaweeb/iframe.ts
- websites/S/Simplyaweeb/presence.ts
- websites/S/Simplyaweeb/tsconfig.json
Resolves #5233 by adding the requested presence.
<details>
</details>
> feat(Simplyaweeb): add new presence

- websites/S/SoundCloud/dist/metadata.json
- websites/S/SoundCloud/presence.ts
Resolves #6611 by adding the requested setting.
<details>
</details>
> feat(Soundcloud): add showButtons setting

- websites/A/Armorgames/dist/metadata.json
- websites/A/Armorgames/presence.ts
Refactor & add settings for buttons
<details>
</details>
> feat(Armorgames): add buttons setting & perf

- websites/W/Worldhideaway/dist/metadata.json
- websites/W/Worldhideaway/presence.ts
Added covers, buttons & privacy mode with their settings & perf.
<details>
<!-- 
Screenshots of the presence settings (if applicable) and at least TWO screenshots of the presence displaying correctly
Including these screenshots will assist the reviewing processes thus speeding up the process of the pull request being merged
--
</details>
> feat(WorldHideaway): add covers, buttons & privacy mode

- websites/Q/Q-dance/dist/metadata.json
- websites/Q/Q-dance/presence.ts
Added buttons & added settings for cover, buttons & privacy
<details>
</details>
> feat(Q-Dance): add buttons, multi lang with settings

- websites/A/AniMixPlay/dist/metadata.json
- websites/A/AniMixPlay/presence.ts
Resolves #6590 
<details>
</details>
> fix(AniMixPlay): fix empty parentheses

- websites/E/Epic Games/dist/metadata.json
- websites/E/Epic Games/presence.ts
Added covers, buttons & privacy with settings. Fixed the presence being broken.
<details>
</details>
> feat(Epic Games): cover, buttons, privacy & fixes

- websites/V/Videoland/dist/metadata.json
- websites/V/Videoland/presence.ts
Added buttons, cover & privacy settings & refactor of the old code
<details>
</details>
> feat(Videoland): buttons, cover & privacy settings

- websites/Y/YouTube Music/dist/metadata.json
Update Chinese descriptions to [#6518 `d50df4d2`](https://github.com/PreMiD/Presences/pull/6518/files#diff-d50df4d2c34c366a0e4b513a2db6dd10513a7d62b2aa40eba7ada9e093d295caL15)
> feat(YouTube Music): Update presence descriptions 

- websites/L/Los Angeles Times/dist/metadata.json
- websites/L/Los Angeles Times/presence.ts
- websites/L/Los Angeles Times/tsconfig.json
> feat(Los Angeles Times): add presence

- websites/N/Neovel/dist/metadata.json
- websites/N/Neovel/presence.ts
Suggestion of @DarkVillager to put only one if statement for settings at the end of the code file to avoid repetition and having a better readability.
<details>
</details>
> chore(Neovel): change if statements for settings

- websites/A/Animea/dist/metadata.json
- websites/A/Animea/iframe.ts
- websites/A/Animea/presence.ts
- websites/A/Animea/tsconfig.json
Resolves #6151 by adding the requested presence.
<details>
</details>
> feat(Animea): add new presence

- websites/O/OpenSea/dist/metadata.json
- websites/O/OpenSea/presence.ts
- websites/O/OpenSea/tsconfig.json
Added a presence for OpenSea
resolves #5235
<details>
</details>
> feat(OpenSea): add presence

- websites/V/VLC/dist/metadata.json
- websites/V/VLC/presence.ts
Resolves #6632 
<details>
</details>
> fix(VLC): fix error on display of track number

- websites/K/Kijk/dist/metadata.json
- websites/K/Kijk/presence.ts
Added cover, fixes & switches.
<details>
</details>
> feat(Kijk): cover, fixes & switches

- websites/M/MangaFreak/dist/metadata.json
- websites/M/MangaFreak/presence.ts
- websites/M/MangaFreak/tsconfig.json
Resolves #5255 by adding the requested presence.
<details>
</details>
> feat(MangaFreak): add presence

- websites/C/Crunchyroll/dist/metadata.json
- websites/C/Crunchyroll/presence.ts
- Remove useless await in front of `strings` variable
- Resolves #6635 (and probably Resolves #6662) by correcting wrong querySelectors.
- Fix the whole manga part by correcting querySelectors.
- Add support for the "series" page when you're viewing an anime page for example on the beta version of the website.
- Change if statement for the showCover setting, now at the end of the file.
- Add multiple location variable like href and pathname to avoid repetition.
- Remove useless checks
- Simplification of some code parts
<details>
</details>
> feat(Crunchyroll): add series page support and multiples fix

- websites/O/Otakudesu/dist/metadata.json
Signed-off-by: Aliciazation <73327361+Aliciazation@users.noreply.github.com>
<details>
</details>
> fix(Otakudesu): update domain

- websites/V/VRV/dist/metadata.json
- websites/V/VRV/iframe.ts
- websites/V/VRV/presence.ts
- Resolves #4809 by adding a iFrameRegExp in the metadata, forcing PreMid to get the right iframe for the video element
- Fix error on `presence.ts`, currentTime and duration were not correctly getted.
- Add five settings : multilanguage, Show Timestamps, Show Cover, Show Buttons, Show Search
- Add feature : display what user is searching if setting enabled
- Add feature : display cover of what the user is currently viewing if setting enabled
- Add feature : display buttons to series or episodes if setting enabled.
- Add feature : users can remove timestamps
- Refactoring the localization of the presence and adding 7 localized strings to it
- Refactoring the whole `presence.ts` by removing `if/else` in favor of `switch/case` and redoing structure to avoid duplicate code.
@Bas950 I would …
> refactor(VRV): change code structure and more

- websites/T/Tellingtone/dist/metadata.json
- websites/T/Tellingtone/presence.ts
- websites/T/Tellingtone/tsconfig.json
Add new presence for the Website Tellingtone.
<details>
</details>
> feat(Tellingtone): add presence

- websites/D/Dizilla/dist/metadata.json
- websites/D/Dizilla/presence.ts
Added second domain as stated in issue and fixed small buggs.
Resolves #6625
<details>
</details>
> feat(Dizilla): new domain & fix bugs

- websites/G/globoplay/dist/metadata.json
- websites/G/globoplay/presence.ts
This pull request will update the globoplay to abide by the various changes that happened throughout the past two years, such as podcasts, additional live channels from Telecine and Premiere, and various rebrands through its already existing ones [Mais na Tela becoming Modo Viagem; Rede Globo => TV Globo; Gloob, Multishow, sportv and GloboNews getting revamped logos.
It also fixes various issues such as the episode titles on ``/v/``, search queries on ``/busca/``, category names on ``/categoria/`` now being picked up again, and now, when watching a movie, only being shown on ``state`` (instead of having its text duplicated and showing on both ``details`` and ``state``).
There's also the temporary removal of the Big Brother live camera channel, not only because the edition is over and it's …
> feat(globoplay): adding support for podcasts, Telecine/STARZPLAY integration and some rebrands and fixes.

- websites/M/Messenger/dist/metadata.json
- websites/M/Messenger/presence.ts
- Resolves #6640
<details>
</details>
> fix(Messenger): fix wrong querySelector causing call bug

- websites/A/Animes Vision/dist/metadata.json
- websites/A/Animes Vision/presence.ts
Resolves #6051 by recoding the whole presence and changing the URL.
- Change the url to `animes.vision`
- Change if statements to switch
- Fix querySelectors
- Fix localization support
- Add settings show timestamps/cover/buttons
<details>
</details>
> refactor(Animes Vision): recode the whole presence

- websites/S/Sparknotes/dist/metadata.json
- websites/S/Sparknotes/presence.ts
Resolves #5805 by correcting the querySelector.
<details>
</details>
> fix(Sparknotes): fix bad display

- websites/M/Musixmatch/dist/metadata.json
- websites/M/Musixmatch/presence.ts
Musixmatch presence rewrite: add support for curators.musixmatch.com (curators missions and lyrics editor), dynamic covers in presence (/artist and /lyrics) and more
<details>
</details>
> feat(Musixmatch): presence rewrite

- websites/D/Dizilla/dist/metadata.json
Changed regex to not match anything that doesn't need to be matched.
<details>
</details>
> fix(Dizilla): faulty regex

- websites/D/Deno/dist/metadata.json
- websites/D/Deno/presence.ts
Rewrote the presence: 
- Added more domains
- Added settings
- Easier maintainability
<details>
</details>
> feat(Deno): rewrite & more functions with settings

- websites/T/TV Time/dist/metadata.json
- websites/T/TV Time/presence.ts
Recoded the presence & added buttons, covers, privacy with their relevant settings.
<details>
</details>
> feat(TV Time): recode & add buttons, covers & privacy

- websites/H/HBO GO/dist/metadata.json
- Resolves #6703 
<details>
</details>
> feat(HBO GO): add new URL for Thailand

- websites/P/Patreon/dist/metadata.json
- websites/P/Patreon/presence.ts
- websites/P/Patreon/tsconfig.json
- Resolves #5334 by creating the requested presence
<details>
</details>
> feat(Patreon): add presence

- websites/T/Tubi/dist/metadata.json
- websites/T/Tubi/presence.ts
Added Buttons, Covers, Privacy & Multi lang with settings, added live video & refactored
<details>
</details>
> feat(Tubi): multilang, buttons, covers, privacy & refactor

- websites/A/Alura/dist/metadata.json
- websites/A/Alura/presence.ts
When watching the course videos, the presence was not working properly.
Included the status that shows when the user is watching videos.
<details>
Old presence, showing no status when watching videos
New presence, show correct status with timestamp
</details>
> feat(Alura): included presence when watching videos

- websites/N/NameMC/dist/metadata.json
- websites/N/NameMC/presence.ts
Remove useless await for strings since the function getStrings is already awaited.
<details>
</details>
> chore(NameMC): remove useless await

- websites/L/LookMovie/dist/metadata.json
- websites/L/LookMovie/presence.ts
Added multilang, privacy, buttons & more sites support.
<details>
</details>
> feat(LookMovie): more site support & more settings

- websites/P/Picarto/dist/metadata.json
Signed-off-by: LeviSnoot <hello@levi.land>
Current metadata for Picarto is out of date, I added an up to date logo, thumbnail and changed the color to the teal that Picarto uses in their accents.
<details>
</details>
> fix(Picarto): updated logo, thumbnail and color

- websites/G/Genshin Impact Map/dist/metadata.json
- websites/G/Genshin Impact Map/presence.ts
Genshin impact 3.0 Release (Aug 24, 2022)
- https://github.com/PreMiD/Presences/issues/6715
<details>
</details>
> feat(Genshin Impact Map): add random preview & update data

- websites/L/LiveLinkBio/dist/metadata.json
- websites/L/LiveLinkBio/presence.ts
Added multilang, removed old sites that were no longer working & rewrote the presence.
<details>
Offline sites:
Proof it's working:
</details>
> feat(LiveLinkBio): multilang, remove old sites & rewrite

- websites/T/Twitch/dist/metadata.json
- websites/T/Twitch/presence.ts
Resolve the privacy setting doesn't clear buttons on the presence.
<details>
</details>
> fix(Twitch): privacy setting doesn't clear buttons

- websites/A/AniList/dist/metadata.json
- websites/A/Animes Vision/dist/metadata.json
- websites/A/Artfight/dist/metadata.json
- websites/G/Gmail/dist/metadata.json
- websites/M/MangaDex/dist/metadata.json
- websites/M/MangaFreak/dist/metadata.json
- websites/S/SOAP2DAY/dist/metadata.json
- websites/S/Simplyaweeb/dist/metadata.json
- websites/S/Sitting on Clouds Radio/dist/metadata.json
- websites/V/VRV/dist/metadata.json
Since I'm french, I've decided to add french description for all the presences where I am owner or contributor.
<details>
</details>
> feat: add french translation for descriptions

- websites/T/The Odin Project/dist/metadata.json
- websites/T/The Odin Project/presence.ts
Used right Discord id, fixed tags and removed special characters.
> fix(The Odin Project): fix minor stuff

- websites/I/Instagram/dist/metadata.json
- websites/I/Instagram/presence.ts
Changed the profile element and changed the way it's used due to different formats
<details>
</details>
> fix(Instagram): profile element changed

- websites/T/Toyhouse/dist/metadata.json
- websites/T/Toyhouse/presence.ts
- websites/T/Toyhouse/tsconfig.json
Add a new presence for the website "Toyhouse".
<details>
</details>
> feat(Toyhouse): add presence

- websites/C/Craiyon/dist/metadata.json
- websites/C/Craiyon/presence.ts
- websites/C/Craiyon/tsconfig.json
Adds a presence for Craiyon (DALL E Mini)
<details>
</details>
> feat(Craiyon): add presence

- websites/S/Skype/dist/metadata.json
- websites/S/Skype/presence.ts
Adds multilang, privacy mode & fixes that occured due to bugs.
<details>
</details>
> feat(Skype): add multilang, privacy mode & fixes

- websites/R/Raven Code/dist/metadata.json
Logo change.
<details>
</details>
> feat(Raven Code): change logo

- websites/H/Heroku/dist/metadata.json
- websites/H/Heroku/presence.ts
- websites/H/Heroku/tsconfig.json
Adds a Presence for Heroku.
Resolves #5275
<details>
</details>
> feat(Heroku): add presence

- websites/M/MetaBrainz/dist/metadata.json
- websites/M/MetaBrainz/presence.ts
- websites/M/MetaBrainz/tsconfig.json
Adds a new presence for the MetaBrainz and MetaBrainz community website
This PR is a part of #5460
<details>
</details>
> feat(MetaBrainz): add presence

- websites/A/Anime Sama/dist/metadata.json
- websites/A/Anime Sama/iframe.ts
- websites/A/Anime Sama/presence.ts
- websites/A/Anime Sama/tsconfig.json
Add new presence
<details>
</details>
> feat(Anime Sama): add presence

- websites/A/Animevietsub/dist/metadata.json
- websites/A/Animevietsub/presence.ts
- websites/A/Animevietsub/tsconfig.json
Added presence for Animevietsub
Took over after closed PRs #6773 #6769 #6768  #6775
<details>
</details>
> feat(Animevietsub): add presence

- websites/Y/YouTube/dist/metadata.json
- websites/Y/YouTube/presence.ts
Added youtube shorts support & thumbnails for community posts if changed in settings.
Resolves #6042
<details>
</details>
> feat(Youtube): add shorts support & com post thumbnail

- websites/A/AniList/dist/metadata.json
- websites/A/AniList/presence.ts
- add `buttons` in settings
- fix `/user` avatar 
- fix `/home` - it was showing nothing (See **screenshots**)
<details>
> **with buttons**
> **without buttons**
</br>
> **Before**
> **After**
</details>
> feat(AniList): add `buttons` setting and fix user avatar

- websites/F/FiveM/dist/metadata.json
- websites/F/FiveM/presence.ts
Added more features with their respective settings
<details>
</details>
> feat(FiveM): add privacy, buttons & covers

- util/tools/util.ts
This PR fixes the broken Schema Validation check.
> fix: incorrect path

- websites/W/Wolvesville/metadata.json
- websites/W/Wolvesville/presence.ts
> fix(Wolvesville): fix presence

- websites/0-9/5Mods/metadata.json
- websites/0-9/5Mods/presence.ts
Recoded the whole presence & added new features with their respective settings
<details>
</details>
> feat(5Mods): recoded presence with new features and settings

- websites/F/Facebook/metadata.json
- websites/F/Facebook/presence.ts
Added one more way to detect a profile to fix the profile not being recognised
<details>
</details>
> fix(Facebook): more profile detection

- websites/M/mod.io/metadata.json
- websites/M/mod.io/presence.ts
Adds presence for mod.io including blog, docs, and old site.
<details>
</details>
> feat(mod.io): add presence

- websites/D/D&D Beyond/metadata.json
> chore(D&D Beyond): remove discriminator from author in metadata

- websites/S/Snapchat/metadata.json
- websites/S/Snapchat/presence.ts
> fix(Snapchat): privacy mode bug

- websites/S/Skribbl.io/metadata.json
- websites/S/Skribbl.io/presence.ts
> chore(Skribbl.io): remove unused await

- websites/T/TruckersMP/metadata.json
- websites/T/TruckersMP/presence.ts
> chore(TruckersMP): update strings

- websites/U/Unicode Character Table/metadata.json
- websites/U/Unicode Character Table/presence.ts
Adds a presence for unicode-table.com
<details>
</details>
> feat(Unicode Character Table): add presence

- websites/T/The Eternal Jukebox/metadata.json
- websites/T/The Eternal Jukebox/presence.ts
Adds a presence for [The Eternal Jukebox](https://eternalbox.dev).
This PR resolves #6490
<details>
</details>
> feat(The Eternal Jukebox): add presence

- websites/H/Hyakanime/metadata.json
- websites/H/Hyakanime/presence.ts
I removed the dead links and replaced the ones that had changed link. I also removed the "Adulte" that was sometimes displayed on the anime link.
<details>
</details>
> fix(Hyakanime): fix links

- websites/H/Hero Forge/metadata.json
- websites/H/Hero Forge/presence.ts
Adds a presence for Hero Forge.
<details>
</details>
> feat(Hero Forge): add presence

- websites/T/Tebex/metadata.json
- websites/T/Tebex/presence.ts
Added tebex & store's with Buycraft/Tebex in it's domain
<details>
</details>
> feat(Tebex): add presence

- websites/P/Plex/metadata.json
- websites/P/Plex/presence.ts
Fixes #6862
<details>
</details>
> fix(Plex): invalid cover art

- websites/S/Spotify Podcasts/metadata.json
- websites/S/Spotify Podcasts/presence.ts
Fixes #6707 
<details>
</details>
> fix(Spotify Podcasts): not showing podcast

- websites/C/Color Coded Lyrics/metadata.json
- websites/C/Color Coded Lyrics/presence.ts
Adds a presence for colorcodedlyrics.com
This PR resolves #5309
<details>
</details>
> feat(Color Coded Lyrics): add presence

- websites/0-9/5etools/metadata.json
- websites/0-9/5etools/presence.ts
Adds a presence for 5etools.
<details>
</details>
> feat(5etools): add presence

- websites/H/Hoyolab/metadata.json
- websites/H/Hoyolab/presence.ts
I have updated the presence to works with the new version of hoyolab and add more subdomain support and add localization support to the presence
fixes #5260
<details>
</details>
> feat(Hoyolab):  add features

- websites/D/Desu-Online/iframe.ts
- websites/D/Desu-Online/metadata.json
- websites/D/Desu-Online/presence.ts
Adds a presence for Desu-Online.pl (polish anime site)
<details>
</details>
> feat(Desu-Online): add presence

- tsconfig.json
This PR enables sourceMap generation. This feature was never enabled with unknown reason? Enabling it will help Presence developers and or users with Presence errors diagnose these and fix them a lot easier or well possible in the first place.
Yes, it does make the compiled code of Presences bigger but ultimatively allows devs to debug when users are experiencing issues.
> feat: add sourcemaps

- websites/C/CloudConvert/metadata.json
- websites/C/CloudConvert/presence.ts
Adds a presence for CloudConvert
<details>
</details>
> feat(CloudConvert): add presence

- websites/T/The Weather Channel/metadata.json
- websites/T/The Weather Channel/presence.ts
* Adds a presence for The Weather Channel (weather.com)
* Resolves #5379
<details>
</details>
> feat(The Weather Channel): add presence

- websites/A/Anime Soul/metadata.json
- websites/A/Anime Soul/presence.ts
* See #6857
* Changed to a static page, as most details were moved to shoob.gg (#6891)
<details>
</details>
> feat(Anime Soul): change to static site

- websites/E/ezGIF/metadata.json
- websites/E/ezGIF/presence.ts
Adds a presence for ezGIF
Resolves #6869
<details>
</details>
> feat(ezGIF): add presence

- websites/C/Craiyon/metadata.json
- websites/C/Craiyon/presence.ts
Adds generated images to the large image of the presence
<details>
</details>
> feat(Craiyon): add result images to presence status

- websites/B/Buienalarm/metadata.json
- websites/B/Buienalarm/presence.ts
Added a presence for Buienalarm
<details>
</details>
> feat(Buienalarm): add presence

- websites/S/Stake/metadata.json
- websites/S/Stake/presence.ts
Add a presence for the online casino Stake.com which displays browsing states, currently played games, balance, ...
Proof showing the creation/modification is working as expected
> feat(Stake): add presence

- websites/S/SteamDB/metadata.json
- websites/S/SteamDB/presence.ts
Optimised the code for better performance
<details>
</details>
> perf(SteamDB): optimised code

- websites/V/Videoland/metadata.json
- websites/V/Videoland/presence.ts
Added videoland v2 & removed videoland. (It still gets used to login that's why it's still in the domains)
<details>
Empty logo on 1st ss cuz its a gif and ss is of frame it disappears
</details>
> feat(Videoland): change to newer site version

- websites/0-9/9anime/metadata.json
- websites/0-9/9anime/presence.ts
Added the setting for not showing timestamps.
Resolves #6872
<details>
</details>
> feat(9anime): add timestamp setting

- websites/S/Shikimori/metadata.json
- websites/S/Shikimori/presence.ts
All code has been rewritten to switch-case. Added settings and buttons. There were also bugs on some sections that have been fixed.
Settings:
1. Private mode.
2. Show covers.
3. Show buttons.
<details>
</details>
> perf(Shikimori): rewritten all code and bugs fixed 

- tsconfig.json
> chore: fix tsconfig

- websites/A/Apple/metadata.json
.1 -> .2, not .1 -> .3
<details>
</details>
> fix(Apple): bump once

- websites/K/Kinopoisk/iframe.ts
- websites/K/Kinopoisk/metadata.json
- websites/K/Kinopoisk/presence.ts
> chore: test

- websites/F/Flat/metadata.json
- websites/F/Flat/presence.ts
* Continued from #6809 (applies formatting and suggestions)
* Adds a presence for flat.io
* Resolves #6758 
<details>
(Taken from linked PR)
</details>
> feat(Flat): add presence

- websites/A/Audible/metadata.json
Add multi-domain name support using RegEx functionality.
+ Resolves #6860 
<details>
</details>
> fix(Audible): multi-domain name support

- websites/G/Google Earth/metadata.json
- websites/G/Google Earth/presence.ts
* Adds a presence for Google Earth
* Resolves #5373
<details>
</details>
> feat(Google Earth): add presence

- websites/J/JoJo's Bizarre Encyclopedia/metadata.json
- websites/J/JoJo's Bizarre Encyclopedia/presence.ts
Changelog:
- Added option to disable buttons.
- Added action: "purge"
- Fixed capitalization of some strings.
- Fixed bugs where it wouldn't always say if you were editing a page.
- Fixed bugs related to display of viewing history.
<details>
</details>
> feat(JoJo's Bizarre Encyclopedia): update presence 

- websites/#/网易云音乐/metadata.json
- websites/#/网易云音乐/presence.ts
- websites/S/Stake/metadata.json
> fix(NetEase Cloud Music): fix and improve usage

- websites/C/Caards/metadata.json
- websites/C/Caards/presence.ts
Yearly update of some of my presences. 
Version 1.0.12, updates and/or implements the following (Extremely small update, however planning on implementing some other features in the future.): 
- Updated static page system (now using a record)
I apologise if something is incorrect. I haven't used PreMiD in a long time. 
*Update on Discords.com: I am currently still working on a massive update for it... (fixing bio, implementing bots, etc.) Fun times haha 😆*
<details>
<summary>Static record system (and other stuff working)</summary>
</details>
> fix(Caards): update presence

- websites/W/WebProfiles/metadata.json
- websites/W/WebProfiles/presence.ts
Yearly update of some of my presences.
Version 1.1.0, updates and/or implements the following:
- New static record system
- Updated text content for /u/ path.
I apologise if something is incorrect. I haven't used PreMiD in a long time. 
<details>
<summary>Image of updated text content for /u/ path</summary>
</details>
> fix(WebProfiles): update presence

- websites/S/Sofi/metadata.json
- websites/S/Sofi/presence.ts
Adding a new presence of a Discord Card Game Bot called [SOFI](http://discord.gg/sofi).
- Website: https://sofi.gg/
<details>
> With Button
- https://cdn.discordapp.com/attachments/880479037066194964/1029024771373010944/unknown.png
- https://cdn.discordapp.com/attachments/880479037066194964/1029024919062855680/unknown.png
> Without Button
- https://cdn.discordapp.com/attachments/880479037066194964/1029025054840856576/unknown.png
> Privacy Mode
- https://cdn.discordapp.com/attachments/880479037066194964/1029025159308378132/unknown.png
</details>
> feat(Sofi): add presence

- websites/D/Discovery+/metadata.json
- websites/D/Discovery+/presence.ts
Added a presence for discovery+. (Some grammar may sound off due to them recognising my language as Dutch.)
<details>
</details>
> feat(Discovery+): add presence

- websites/D/Discord/metadata.json
- websites/D/Discord/presence.ts
This pull request implements, and/or fixes the following:
- Resolves #6977 
<details>
<summary>Discord status correctly showing server info</summary>
</details>
> fix(Discord): fix presence

- websites/R/RTL+/metadata.json
- websites/R/RTL+/presence.ts
*commits*
<details>
</details>
> fix(RTL+): presence not working

- websites/#/网易云音乐/metadata.json
- websites/A/Audible/metadata.json
- websites/C/Caards/metadata.json
- websites/D/Discohook/metadata.json
- websites/D/Discord.style/metadata.json
- websites/D/Discord/metadata.json
- websites/D/Discovery+/metadata.json
- websites/D/Dsc.gg/metadata.json
- websites/D/dアニメストア/metadata.json
- websites/F/Flat/metadata.json
- websites/F/Fly.io/metadata.json
- websites/G/Google Earth/metadata.json
- websites/J/JoJo's Bizarre Encyclopedia/metadata.json
- websites/K/Kinopoisk/metadata.json
- websites/L/LoL Esports/metadata.json
- websites/O/OK/metadata.json
- websites/R/RTL+/metadata.json
- websites/S/Sofi/metadata.json
- websites/W/WebProfiles/metadata.json
bump presences to fix CI for presences for the last 22 days; since my last bulk PR
should be the final time this is needed due to #6988
> chore: bump presences

- websites/R/Rust Lang Book/metadata.json
- websites/R/Rust Lang Book/presence.ts
presence for the official rust language book
<details>
</details>
> feat(Rust Lang Book): add presence

- websites/E/e-z/metadata.json
- websites/E/e-z/presence.ts
Updated the logo and banner to use the new ones and added some pages that were previously missing
<details>
</details>
> feat(e-z): new pages and logo update

- websites/C/Cuevana 3/metadata.json
- websites/C/Cuevana 3/presence.ts
The website changes host frequently, i just changed the host url to get presence working again.
<details>
</details>
> feat(Cuevana 3): Updated / Fixed Url

- package-lock.json
- websites/T/Tidal/presence.ts
After some updates on Tidal's side the presence stopped working as intended, this PR accounts for all the relevant changes.
<details>
</details>
> fix(Tidal): presence not working after updates

- websites/B/BeatLeader/iframe.ts
- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
Add presence for BeatLeader
<details>
</details>
> feat(BeatLeader): add presence

- websites/S/Shoob/metadata.json
- websites/S/Shoob/presence.ts
* Adds more static paths
* Adds buttons to some paths
* Adds profile information
<details>
</details>
> feat(Shoob): add paths and buttons

- websites/A/Animeflix/metadata.json
- websites/A/Apple/metadata.json
- websites/C/Cuevana 3/metadata.json
- websites/D/Discohook/metadata.json
- websites/D/dアニメストア/metadata.json
- websites/O/OK/metadata.json
- websites/S/Sofi/metadata.json
- websites/T/Tidal/metadata.json
- websites/Y/YomuMangás/metadata.json
> chore: run semid

- websites/D/Discogs/metadata.json
- websites/D/Discogs/presence.ts
* Adds a presence for Discogs.
* Resolves #5429
<details>
</details>
> feat(Discogs): add presence

- websites/S/Shoob/metadata.json
- websites/S/Shoob/presence.ts
Adds some changes, as requested by @TranukaKami 
* Adds buttons to the minigames and the shop
* Adds specific details about users
* Updates the thumbnail
<details>
</details>
> feat(Shoob): add card and user details

- tools/auto/presenceValidator.ts
> chore: fix presenceValidator

- websites/S/Stoodi/metadata.json
- websites/S/Stoodi/presence.ts
Created the presence for a Brazilian website focused on strengthening studies for the national high school exam
<details>
<kbd><img src="https://user-images.githubusercontent.com/59850361/202905281-e4f2aa3e-ac5b-470d-8d13-10770d9b5a49.png" /></kbd>
<br />
<kbd><img src="https://user-images.githubusercontent.com/59850361/202905102-398aa579-d97f-42bb-8ed6-fa5f7ef788e6.png" /></kbd>
<br />
<kbd><img src="https://user-images.githubusercontent.com/59850361/202905121-af732bd2-c874-4c0d-86cb-79d2382e5def.png" /></kbd>
<br />
<kbd><img src="https://user-images.githubusercontent.com/59850361/202905133-57ced6e7-7d24-4346-863c-f20bd3f8c5c5.png" /></kbd>
</details>
> feat(Stoodi): new presence

- websites/A/Apple Music/metadata.json
- websites/A/Apple Music/presence.ts
Fix #6938
Fix #7000
<details>
</details>
> fix(Apple Music): wrong timestamps

- websites/A/AnimeDao/iframe.ts
- websites/A/AnimeDao/metadata.json
- websites/A/AnimeDao/presence.ts
Add settings & fix bugs
<details>
</details>
> feat(AnimeDao): add settings & fix bugs

- websites/E/Epic Games/metadata.json
- websites/E/Epic Games/presence.ts
- websites/M/MUBI/metadata.json
- websites/M/MUBI/presence.ts
- websites/M/Marktplaats/metadata.json
- websites/M/Marktplaats/presence.ts
Removed unnecessary slice due to details/state already slicing it.
<details>
Unnecessary?
</details>
> perf: multiple presence remove unnecessary slice

- websites/I/IDLIX/iframe.ts
- websites/I/IDLIX/metadata.json
- websites/I/IDLIX/presence.ts
Resolves #5306
Resolves #6894
Added IDLIX presence.
Reason for regex is that the site changes ip every few days so the regex checks all public ips. I talked with @Bas950 about this.
It returns when it doesn't find the logo (so wrong site)
https://github.com/PreMiD/Presences/blob/ac19edda10a8f2f6442e8dd4a7797758f122f550/websites/I/IDLIX/presence.ts#L52-L60
<details>
</details>
> feat(IDLIX): add presence

- websites/M/MEE6/metadata.json
- websites/M/MEE6/presence.ts
Added support for the new site.
<details>
</details>
> feat(Mee6): new site support

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
fixed the detection of the new @ usernames in the url [e.g.](https://www.youtube.com/@PoliceActivity)
<details>
</details>
> fix(Youtube): @username channel detection

- websites/S/Spotify Podcasts/metadata.json
- websites/S/Spotify Podcasts/presence.ts
This pr fixes the following:
- Resolves #6415 & https://canary.discord.com/channels/493130730549805057/1051768123738570802 (any maybe other forum posts)
<details>
<summary>When listening to a podcast</summary>
</details>
<details>
<summary>Viewing a show</summary>
</details>
> fix(Spotify Podcasts): fix presence

- websites/S/Sezonluk Dizi/metadata.json
- websites/S/Sezonluk Dizi/presence.ts
Resolves #6999
Fixed elements & changed the domain.
<details>
</details>
> fix(Sezonluk Dizi): fix elements & change domain

- websites/I/I Love Music/metadata.json
- websites/I/I Love Music/presence.ts
Rewrote the presence due to it being reported as broken [here](https://discord.com/channels/493130730549805057/1053017115449368576).
<details>
</details>
> fix(I Love Music): rewrite presence

- websites/Y/Yugen Anime/iframe.ts
- websites/Y/Yugen Anime/metadata.json
- websites/Y/Yugen Anime/presence.ts
This pr implements, adds and or fixes the following:
- Resolves #7090 
- Resolves #5955
<details>
<summary>Watching an episode</summary>
</details>
<details>
<summary>Viewing a series/anime</summary>
</details>
<details>
<summary>Viewing a anime review</summary>
</details>
<details>
<summary>Watching a movie</summary>
</details>
> feat(Yugen Anime): add presence

- websites/0-9/1CAK/metadata.json
- websites/0-9/1CAK/presence.ts
Improved the performance for this presence.
<details>
</details>
> perf(1CAK): improve perf

- websites/F/FurAffinity/metadata.json
- websites/F/FurAffinity/presence.ts
optimized code
<details>
</details>
> perf(FurAffinity): optimize code

- websites/P/Pokéflix/iframe.ts
- websites/P/Pokéflix/metadata.json
- websites/P/Pokéflix/presence.ts
Add presence for [Pokéflix](https://www.pokeflix.tv/)
Resolves: #6991
Settings:
1. Multilanguage.
2. Privacy.
3. Show remaining viewing time.
4. Show buttons.
<details>
</details>
> feat(Pokéflix): add presence

- websites/T/Tempest Fansub/metadata.json
- websites/T/Tempest Fansub/presence.ts
> feat(TempestFansub): add presence

- websites/R/REYFM/metadata.json
- websites/R/REYFM/presence.ts
Signed-off-by: Sam Schumacher <38103916+HerrSammyDE@users.noreply.github.com>
<details>
</details>
> fix(REYFM): new domain

- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
Fixed leaderboard pages
Added empty pathname to switch
<details>
</details>
> fix(BeatLeader): fix leaderboard pages

- package-lock.json
- package.json
> chore(PMD): bump version

- websites/R/REYFM/metadata.json
- websites/R/REYFM/presence.ts
Resolves issue generated by #7108
n/a
<details>
</details>
> chore(REYFM): run prettier

- websites/P/Panda Novel/metadata.json
- websites/P/Panda Novel/presence.ts
Add presence for [Panda Novel](https://www.panda-novel.com)
* Resolves #7100  
<details>
| Home | Novel Page | Author Page | Searching |
| --- | --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/37224822/212610270-395e5afd-ccf0-490a-93be-bdb684682208.png) | ![image](https://user-images.githubusercontent.com/37224822/212610355-78103921-d63a-41c9-a247-c3e7ecf73e27.png) | ![image](https://user-images.githubusercontent.com/37224822/212610659-534db198-6729-476a-965a-1429c11c3dd6.png) | ![image](https://user-images.githubusercontent.com/37224822/212610554-03f320d7-ed8c-4f52-addd-1eeb8ac3256f.png)
</details>
> feat(Panda Novel): add presence

- websites/A/Anime Sama/metadata.json
- websites/A/Anime Sama/presence.ts
I've fixed the presence since it was not working anymore due to the website being updated to be more modern.
I set the version to *1.1.0* because it was mainly a redo of all the code.
<details>
</details>
> fix(Anime Sama): fix presence not working due to website change

- websites/A/Asura Scans/metadata.json
- websites/A/Asura Scans/presence.ts
Adds the Turkish branch domain to the presence.
<details>
</details>
> feat(Asura Scans): add turkish branch domain

- websites/J/jut.su/metadata.json
- websites/J/jut.su/presence.ts
> feat(jut.su): more paths, some grammar corrections, switch case

- websites/N/Nuxt.js/metadata.json
- websites/N/Nuxt.js/presence.ts
Optimised the code
<details>
</details>
> perf(Nuxt.js): optimize code

- .github/workflows/SchemaEnforcer.yml
Well, it should work :^)
<details>
</details>
> workflow(SchemaEnforcer): fix versions not getting bumped

- websites/C/ComicK/metadata.json
- websites/C/ComicK/presence.ts
- Resolves #7151 
- Simplify a lot the codebase : remove lot of useless tests since there's some queries that are constants but were tested + simplify a switch case with only change to `presenceData.details`
<details>
</details>
> refactor(ComickK): fix wrong website link and simplify code

- websites/S/Skribbl.io/metadata.json
- websites/S/Skribbl.io/presence.ts
* Updates the presence for the new UI
* Adds game details to the presence
<details>
</details>
> feat(Skribbl.io): update presence and add details

- websites/T/TRanimeizle/metadata.json
- websites/T/TRanimeizle/presence.ts
Resolves #7162 by changing the url
<details>
</details>
> fix(TRanimeizle): change metadata url

- websites/Z/Zerion/iframe.ts
- websites/Z/Zerion/metadata.json
- websites/Z/Zerion/presence.ts
Add presence for [Zerion](https://zerion.cc/)
* Resolves: #7163
Settings:
1. Multilanguage,
2. Privacy,
3. Show covers,
4. Show timestamps,
5. Show buttons.
<details>
| Home | Viewing serial page | Viewing Serial | Searching |
| --- | --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/37224822/216859523-7baeffd8-6481-4fae-831b-cce4afb12770.png) | ![image](https://user-images.githubusercontent.com/37224822/216857457-ce6c7ece-0c32-47a2-9c8f-30aa946c8373.png) | ![image](https://user-images.githubusercontent.com/37224822/216857508-3d144b2f-3061-4961-a363-8c1ec3d10ef4.png) | ![image](https://user-images.githubusercontent.com/37224822/216859595-8d67d5bf-9d45-4676-b55d-937da7d28510.png) | …
> feat(Zerion): add presence

- websites/S/Showtime/metadata.json
- websites/S/Showtime/presence.ts
Resolves #7180
Recode presence and add skyshowtime support
<details>
</details>
> feat(Showtime): recode presence and add skyshowtime support

- websites/Y/YouTube Music/metadata.json
- websites/Y/YouTube Music/presence.ts
Fixed it not being able to parse hours on the timestamp
<details>
</details>
> fix(YouTube Music): not parsing hours on timestamp

- websites/K/KickAssAnime/metadata.json
Resolves #7185
Changed regex to work with www[number].site.com e.g. www5.site.com
<details>
</details>
> fix(KickAssAnime): change regex

- websites/V/Voiranime/metadata.json
- websites/V/Voiranime/presence.ts
- fix url since voiranime website got a new one (and added a regexp to avoid future problem)
- add Record for static pages
- replace if statements by a Switch for better readabily
- simplify querySelectors
<details>
</details>
> refactor(Voiranime): redo codebase and fix url

- websites/V/Video Game Mods/metadata.json
- websites/V/Video Game Mods/presence.ts
Presence for Video Game Mods, a website for downloading mods for video games
Requested by issue #6663 
<details>
</details>
> feat(Video Game Mods): add presence

- websites/D/Discord/metadata.json
- websites/D/Discord/presence.ts
Change the incidentView string after https://github.com/PreMiD/Localization/pull/7263
<details>
n/a
</details>
> chore(Discord): change incidentView strings

- websites/S/Showtime/metadata.json
- websites/S/Showtime/presence.ts
Added a setting to change logos, Added a few tags & Added support for covers with the new change logo setting.
<details>
</details>
> feat(Showtime): add logo setting & add tags

- websites/R/R-a-d.io/metadata.json
- websites/R/R-a-d.io/presence.ts
Presence for [R/a/dio](https://r-a-d.io), an online radio focused on Japanese songs.
<details>
<summary> Screenshots </summary>
<details>
<summary>Playback stop</summary>
</details>
<details>
<summary>Playback start</summary>
</details>
<details>
<summary>News</summary>
</details>
<details>
<summary>Chat (IRC)</summary>
</details>
<details>
<summary>Searching</summary>
</details>
<details>
<summary>Last played songs</summary>
</details>
<details>
<summary>Queue</summary>
</details>
<details>
<summary>User favorites</summary>
</details>
<details>
<summary>Staff list</summary>
</details>
<details>
<summary>Song submission page</summary>
</details>
</details>
> feat(R/a/dio): add presence

- websites/T/Ticketer/metadata.json
- websites/T/Ticketer/presence.ts
A rich presence addon for ticketer. A ticket bot with a web dashboard for discord.
Proof showing the creation/modification is working as expected
> feat(ticketer): add presence

- websites/T/Tempest Fansub/metadata.json
- websites/T/Tempest Fansub/presence.ts
> fix(TempestFansub): domain update and some changes

- websites/M/MyAnimeList/metadata.json
- websites/M/MyAnimeList/presence.ts
* Fixes [an issue](https://discord.com/channels/493130730549805057/1081557390907949157) where the English/Japanese titles are not separated by a space.
* Improves the grammar of some texts
* Refactors code, removing duplicate code to match current repository standards better
* Adds buttons
<details>
</details>
> feat(MyAnimeList): add space between some titles and add buttons

- websites/I/Instagram/metadata.json
- websites/I/Instagram/presence.ts
Instagram logo was outdated so it was replaced with the brighter newer one
<details>
</details>
> fix(Instagram): update logo

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
Goes with: https://github.com/PreMiD/Localization/pull/7268
* Added the channel shorts/shorts page
* Added the homepage tags being used
* Added viewing videos sorted by the recent or popular on a channel
* Change youtube studio saying video's to content (cuz livestreams, shorts, etc.)
* Changed Assets used to an enum with imgur links
<details>
</details>
> feat(Youtube): add unsupported pages & optimize presence (for v2.5)

- websites/P/PaperMC/metadata.json
- websites/P/PaperMC/presence.ts
I created a Presence for PaperMC and HangarMC because I saw Modrinth had one and Spigot did, but Paper didn't. Here's a showcase of it in action! https://imgur.com/a/vRMgcjd
I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
I linted the code by running `yarn format`
The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
> feat(PaperMC): add presence

- websites/A/AnkiWeb/metadata.json
- websites/A/AnkiWeb/presence.ts
Creates a presence for [AnkiWeb](https://ankiweb.net)
<details>
</details>
> feat(AnkiWeb): add presence

- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
Added followed and settings page
Fixed small image lightshow not showing
Removed unnecessary code
<details>
</details>
> feat(BeatLeader): add unsupported pages & fixes

- websites/C/Chessly/metadata.json
- websites/C/Chessly/presence.ts
Adds a presence for [Chessly](https://chessly.com/).
<details>
</details>
> feat(Chessly): add presence

- websites/W/Wcostream/metadata.json
- websites/W/Wcostream/presence.ts
* Resolves #7247 
<details>
</details>
> fix(Wcostream): update urls and images

- websites/S/Scribd/metadata.json
- websites/S/Scribd/presence.ts
Added scribd presence
<details>
</details>
> feat(Scribd): add presence

- websites/C/Currys/metadata.json
- websites/C/Currys/presence.ts
Presence added for the website/retailer [Currys](https://www.currys.co.uk)
(closed old PR and made a new one. Needed to rework things, any old changed are shown on the closed pr)
<details>
</details>
> feat(Currys): add presence

- websites/H/Hacker News/metadata.json
- websites/H/Hacker News/presence.ts
* Adds a presence for [Hacker News](https://news.ycombinator.com/)
* Resolves #6791 
* Description is taken from Wikipedia
<details>
</details>
> feat(Hacker News): add presence

- websites/R/Rate My Professors/metadata.json
- websites/R/Rate My Professors/presence.ts
* Adds a presence for [Rate My Professors](ratemyprofessors.com)
<details>
</details>
> feat(Rate My Professors): add presence

- websites/F/Facebook/metadata.json
- websites/F/Facebook/presence.ts
Resolves #7216
Rewrote the presence & Added support for the domain web.facebook.com
<details>
</details>
> feat(Facebook): rewrite presence & add web.facebook.com support

- websites/V/Viu/metadata.json
- websites/V/Viu/presence.ts
> feat(Viu): cover art & support for new version

- websites/0-9/3388/metadata.json
- websites/0-9/3388/presence.ts
Add presence for 3388 (https://3388.to).
<details>
</details>
> feat(3388): add presence

- websites/G/Gogoanime/metadata.json
- websites/G/Gogoanime/presence.ts
- websites/S/Scribd/metadata.json
- websites/S/Scribd/presence.ts
Fixed the warnings for Scribd & Gogoanime
<details>
n/a
</details>
> fix: multiple presences fix warnings

- websites/B/BetterAnime/iframe.ts
- websites/B/BetterAnime/metadata.json
- websites/B/BetterAnime/presence.ts
This reverts commit c2837dcb314a314d68e5efd24b5dffae534cf809.
<details>
</details>
> revert: chore(BetterAnime): delete presence (#7191)

- websites/L/LiveLinkBio/metadata.json
- websites/L/LiveLinkBio/presence.ts
Added more details.
<details>
">
</details>
> feat(LiveLinkBio): add more details

- package-lock.json
- package.json
Update pmd to 1.1.2 so new contributors don't get issues.
> chore: update pmd & it's dependencies

- websites/0-9/9anime/iframe.ts
- websites/0-9/9anime/metadata.json
- websites/0-9/9anime/presence.ts
* Added video detection, instead of url detection due to changes in variants of 9anime
* Added button
* Added more title/episode options
<details>
</details>
> fix(9anime): fix presence

- websites/H/HentaiVN/metadata.json
> chore(HentaiVN): Change domain.

- websites/Y/YomuMangás/metadata.json
- websites/Y/YomuMangás/presence.ts
- Add site alternative names
- Update descriptions
- Update thumbnail
- Update tags
- Remove uneeded settings
- Remove uneeded pages
- Refactor code
<details>
- SFW Manga
- NSFW Manga (Show NSFW ON / Image is a placeholder)
- NSFW Manga (Show NSFW OFF) or Privacy Mode
</details>
> fix(YomuMangás): update presence to new version

- websites/A/AnimeVost/metadata.json
- websites/A/AnimeVost/presence.ts
Chore to remove the warnings AnimeVost gives.
<details>
</details>
> chore(AnimeVost): no one time variables

- websites/A/Aodesu/iframe.ts
- websites/A/Aodesu/metadata.json
- websites/A/Aodesu/presence.ts
- websites/H/HentaiVN/metadata.json
Aodesu is a website where you can watch anime in spanish dub or subtitled in spanish.
<details>
<h3>Viewing Home</h3>
<hr/>
<h3>Viewing Emitting</h3>
<hr/>
<h3>Viewing Anime Landing</h3>
<hr/>
<h3>Viewing Reproductor Playing</h3>
<hr/>
<h3>Viewing Reproductor Pause</h3>
<hr/>
<h3>Viewing Search</h3>
<hr/>
<h3>Viewing Settings > Appearance</h3>
<hr/>
<h3>Viewing Settings > Privacy</h3>
<hr/>
<h3>Viewing Register</h3>
<hr/>
<h3>Viewing Login</h3>
<hr/>
</details>
> feat(Aodesu): add presence

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
* Added conditional teneray operator (?) for if there's no youtubeTV uploader
* Put homepage at the top, so it doesn't check for textContents that don't exist and cause errors.
<details>
Error:
Proof for line of code:
</details>
> fix(Youtube): errors on brave

- websites/A/Animevietsub/metadata.json
- websites/N/Nettruyen/metadata.json
Change the url from animevietsub.cc to animevietsub.im
</details>
> fix(Animevietsub, Nettruyen): update url

- websites/T/Tempest Fansub/metadata.json
- websites/T/Tempest Fansub/presence.ts
> fix(TempestFansub): domain changes

- websites/B/Brain.fm/metadata.json
- websites/B/Brain.fm/presence.ts
Updates invalid querySelectors of the my.brain.fm page, so main functionality works again.
Resolves #7373
<details>
</details>
> fix(brain.fm): update querySelectors of my.brain.fm

- websites/B/BeatLeader/iframe.ts
- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
fix small images, added new ones
previewer got switched to a different one, replaced where possible removed what was unable to replace since new previewer is a unity webgl "game" in a canvas
reverted the replay logo back to the actual logo for that sub domain
<details>
</details>
> fix(BeatLeader): fix small images

- websites/C/ChatGPT/metadata.json
- websites/C/ChatGPT/presence.ts
Fixes enum
<details>
</details>
> chore(ChatGPT): fix enum merging

- websites/P/Perplexity/metadata.json
- websites/P/Perplexity/presence.ts
- websites/V/Viu/presence.ts
This pull request adds the Presence for Perplexity.ai.
Changes Made:
- Added Perplexity.ai Presence files to the /websites/P/Perplexity folder
Testing Done:
- Verified that the new Presence appears correctly in the Discord Activity (in Threads, Search and by switching trough)
<details>
</details>
> feat(Perplexity): add new presence

- websites/P/Paramount+/metadata.json
Change the author of the paramount+ presence
<details>
</details>
> chore: change author

- .github/workflows/AssetsUpdater.yml
- tools/auto/assetsUpdater.ts
- tools/classes/AssetsManager.ts
> feat(AssetsManager): improvements

- websites/F/feds/metadata.json
- websites/F/feds/presence.ts
> chore: update assets

- websites/M/Memrise/metadata.json
- websites/M/Memrise/presence.ts
> chore(Memrise): update assets

- websites/V/Voiranime/metadata.json
- websites/V/Voiranime/presence.ts
- Fixed missing settings in metadata.json
- Fixed error on anime info page
<details>
</details>
> fix(Voiranime): missing settings + anime info page fix

- websites/S/Sorryfield/metadata.json
- websites/S/Sorryfield/presence.ts
I added a presence for Sorryfield which a karaoke songs listing site. And it have an rythm game named "Java!".
<details>
</details>
> feat(Sorryfield): add new presence

- websites/P/Plex/metadata.json
- websites/P/Plex/presence.ts
Fix Plex Cover Art
Resolves https://github.com/PreMiD/Presences/issues/7337
</details>
> fix(Plex): Cover Images

- websites/P/PlayScrabble/metadata.json
- websites/P/PlayScrabble/presence.ts
* Adds a presence for playscrabble.com (blog, game, dictionary, etc)
* Resolves #7097
<details>
</details>
> feat(PlayScrabble): add presence

- websites/B/Bunpro/metadata.json
- websites/B/Bunpro/presence.ts
Updates the selectors and pathnames for the new Bunpro UI.
<details>
</details>
> fix(Bunpro): update selectors and pathnames

- websites/R/Rumble/metadata.json
- websites/R/Rumble/presence.ts
Adds a presence for rumble.com, a video sharing platform.
<details>
</details>
> feat(Rumble): add presence

- websites/P/PeaceScans/metadata.json
- websites/P/PeaceScans/presence.ts
> chore(PeaceScans): update assets

- websites/S/SimulatorHits/metadata.json
- websites/S/SimulatorHits/presence.ts
Updated the API to use the correct domain.
> fix(SimulatorHits): Update API Domain

- websites/A/Animevietsub/metadata.json
> chore(AnimeVietSub): change domain

- websites/G/galaxy/metadata.json
- websites/G/galaxy/presence.ts
A presence for [galaxy](https://galaxy.click)
<details>
<summary>Proof showing the creation/modification is working as expected</summary>
</details>
> feat(galaxy): add presence

- websites/G/galaxy/metadata.json
- websites/G/galaxy/presence.ts
- websites/S/SimulatorHits/metadata.json
> chore(galaxy): update assets

- websites/S/SimulatorHits/metadata.json
> chore(SimulatorHits): prettify files

- websites/M/myCANAL/metadata.json
- websites/M/myCANAL/presence.ts
I fixed the issue when browsing a live channel, the presence wasn't functionning properly. 
Resolves #7458 
<details>
<summary> Proof showing the creation/modification is working as expected </summary>  
</details>
> fix(MyCanal): changed new path to img tag

- websites/N/Navidrome/metadata.json
- websites/N/Navidrome/presence.ts
Added support for Navidrome, a self-hosted music streaming service.
<details>
Nothing Playing:
Playing:
Paused:
</details>
> feat(Navidrome): add presence

- websites/H/Holodex/iframe.ts
- websites/H/Holodex/metadata.json
- websites/H/Holodex/presence.ts
Resolves #7461
<details>
</details>
> feat(Holodex): add cover

- websites/T/Tempest Fansub/metadata.json
- websites/T/Tempest Fansub/presence.ts
>  feat(TempestFansub): website changes

- websites/#/アイドルマスターシャイニーカラーズ/metadata.json
- websites/#/アイドルマスターシャイニーカラーズ/presence.ts
> chore(アイドルマスターシャイニーカラーズ): Added tags and some codes for the latest version of this game

- websites/M/movie-web/metadata.json
- websites/M/movie-web/presence.ts
Added [movie-web.app](https://movie-web.app/), a small web app for watching your favourite movies and TV shows with no ads or popups.
<details>
</details>
> feat(movie-web): add presence

- websites/0-9/9anime/metadata.json
- websites/0-9/9anime/presence.ts
Fix issue that the wrong element is selected
Resolves #7497
<details>
</details>
> fix(9anime): fix issue with DOM selector

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
Surpasses #7511
<details>
</details>
> fix(YouTube): not working outside playlist

- websites/D/Doronime/metadata.json
- websites/D/Doronime/presence.ts
> chore(Doronime): update domain

- websites/F/fbox.to/metadata.json
- websites/F/fbox.to/presence.ts
Resolves #7431
<details>
</details>
> fix(Fbox): fix cover not loading

- websites/C/Cuevana 3/metadata.json
- websites/C/Cuevana 3/presence.ts
- Resolves #7454
- Fixed the presence
- Added regex for more domain support
- Added thumbnails + setting
- Added privacy & button settings
- Added support for more versions of the site
<details>
</details>
> fix(Cuevana): fix presence & add regex

- websites/B/bilibilitv/metadata.json
- websites/C/Cuevana 3/metadata.json
> chore: prettify files

- websites/F/FMovies/metadata.json
- websites/F/FMovies/presence.ts
- Resolves #7510
- Resolves #7211
- Fixed presence bugs
- Use less code
<details>
</details>
> fix(fmovies): fix presence bug

- websites/A/aha/metadata.json
- websites/A/aha/presence.ts
> feat(aha): add presence

- websites/K/KickAssAnime/iframe.ts
- websites/K/KickAssAnime/metadata.json
- websites/K/KickAssAnime/presence.ts
- Resolves #7520 (By supporting beta site version)
- Fix regex error
<details>
</details>
> chore(KickAssAnime): fix regex & support beta version

- websites/#/라프텔/metadata.json
- websites/#/라프텔/presence.ts
> chore(라프텔): update assets

- websites/Y/Yugen Anime/iframe.ts
- websites/Y/Yugen Anime/metadata.json
- websites/Y/Yugen Anime/presence.ts
- Change domain.
- Fix broken selectors.
- Add support for trending page.
<details>
</details>
> chore(Yugen Anime): change domain & selectors

- websites/B/bilibili/metadata.json
- websites/B/bilibili/presence.ts
classic plugins not working for the new version website, need update.
<details>
multiUploader
singleUploader
</details>
> fix(bilibili):  video title & upload name fix

- websites/D/Dumpert/metadata.json
- websites/D/Dumpert/presence.ts
- Changed ifs to switch statement
- Changed links to enum
- Implement privacy  in a better way (no more just browsing.)
<details>
</details>
> perf(Dumpert): improve presence code

- websites/P/Physics Wallah/metadata.json
- websites/P/Physics Wallah/presence.ts
I made a new presence for an online education platform named PhysicsWallah, which is based in india.
<details>
</details>
> feat(PhysicsWallah): new presence

- websites/P/Physics Wallah/metadata.json
- websites/P/Physics Wallah/presence.ts
> chore(Physics Wallah): update assets

- tools/auto/assetsUpdater.ts
- tools/classes/AssetsManager.ts
- websites/A/aniwave/metadata.json
- websites/A/aniwave/presence.ts
- websites/K/Kick/metadata.json
- websites/K/Kick/presence.ts
> fix(AssetManager): deleting should now actually work

- websites/F/FMovies/metadata.json
- websites/F/FMovies/presence.ts
chore(FMovies): fix bugs
<details>
</details>
> fix(FMovies): fix bugs

- websites/M/MoviesJoy/iframe.ts
- websites/M/MoviesJoy/metadata.json
- websites/M/MoviesJoy/presence.ts
- Resovles #7485 (this isn't NSFW)
- Resolves #5312
<details>
</details>
> feat(MoviesJoy): add presence

- websites/A/Anime-Odcinki/iframe.ts
- websites/A/Anime-Odcinki/metadata.json
- websites/A/Anime-Odcinki/presence.ts
- Add Anime-Odcinki presence
- Resolves #7548 
<details>
</details>
> feat(Anime-Odcinki): add presence

- package-lock.json
- package.json
- websites/F/Fire Emblem Heroes/metadata.json
- websites/F/Fire Emblem Heroes/util.ts
> chore(deps): update no-one-time-vars

- websites/B/Bunpro/metadata.json
- websites/B/Bunpro/presence.ts
Updates the selectors for Bunpro's dashboard v2 update.
<details>
</details>
> fix(Bunpro): update dashboard selectors

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
- Optimize code
- Fix issue that first short's uploader was incorrect
<details>
</details>
> fix(Youtube): fix & optimize yt-shorts

- websites/M/Moopa/metadata.json
- websites/M/Moopa/presence.ts
- Presence for [Moopa](https://moopa.live)
- Updating info dynamically on different pages
- Having buttons to see/watch currently playing anime/manga
- Have icon fallback to return logo if cover not available
- Have options to select what title language to show
<details>
</details>
> feat(Moopa): add presence

- websites/A/Asura Scans/metadata.json
* Adds the current temporary domain
<details>
</details>
> fix(Asura Scans): update domains

- websites/M/Moopa/metadata.json
- websites/M/Moopa/presence.ts
> chore(Moopa): update assets

- websites/C/Canvas/metadata.json
- websites/C/Canvas/presence.ts
- Resolves #7593
<details>
</details>
> feat(Canvas): hide course name in privacy mode

- websites/A/ANIMETV7/metadata.json
- websites/A/ANIMETV7/presence.ts
> chore(ANIMETV7): update assets

- websites/V/VRoid/metadata.json
- websites/V/VRoid/presence.ts
> chore(VRoid): update assets

- websites/A/Asura Scans/metadata.json
* Adds the new domain to the list. The website layout itself has not changed.
<details>
</details>
> fix(Asura Scans): add new domain

- websites/F/Fire Emblem Heroes/util.ts
- websites/M/Mahara-Tech/iframe.ts
- websites/M/Mahara-Tech/metadata.json
- websites/M/Mahara-Tech/presence.ts
- Added [Mahara-Tech](https://maharatech.gov.eg/) website presence, an academic website that provides too many free useful online courses about modern technology like programming and cyber security.
<details>
</details>
> feat(Mahara-Tech): add presence 

- websites/M/Mahara-Tech/metadata.json
- websites/M/Mahara-Tech/presence.ts
> chore(Mahara-Tech): update assets

- websites/M/movie-web/metadata.json
- websites/M/movie-web/presence.ts
> fix(movie-web): showing wrong episode number

- websites/S/SideQuest/metadata.json
- websites/S/SideQuest/presence.ts
Adds a presence for [SideQuest](https://sidequestvr.com).
<details>
</details>
> feat(SideQuest): add presence

- websites/W/watch.lonelil.com/metadata.json
- websites/W/watch.lonelil.com/presence.ts
Adds presence for [watch.lonelil.com](https://watch.lonelil.com/).
<details>
</details>
> feat(watch.lonelil.com): add presence

- websites/O/osu ppy/metadata.json
- websites/O/osu ppy/presence.ts
- This goes with https://github.com/PreMiD/Localization/pull/7285
- Add buttons with setting.
- Add multilang.
- Destructure variables.
<details>
</details>
> feat(osu!ppy): add buttons and multiLang

- websites/W/watch.lonelil.com/metadata.json
- websites/W/watch.lonelil.com/presence.ts
> chore(watch.lonelil.com): update assets

- websites/R/Radiko/metadata.json
- websites/R/Radiko/presence.ts
- Fix #6456
- Added Listen button
- Added Time visible switch
<details>
</details>
> feat(Radiko): add listen button

- websites/G/Genius/metadata.json
- websites/G/Genius/presence.ts
resolves #7616 
Just updating some query selectors.
<details>
</details>
> fix(Genius): change query selectors

- websites/W/Wcostream/metadata.json
resolves #7625
<details>
</details>
> fix(wcostream): update domain

- websites/F/FMovies/metadata.json
Fmovies has had there domain changed from fmovies.to to fmoviesz.to. I have changed the domain in the metadata.json
<details>
</details>
> fix(fmovies): domain changed

- websites/A/Anontpp/metadata.json
goplay/anontpp changed their domain from "goplay.ml" to "goplay.pw"
<details>
</details>
> fix(Anontpp): update domain to "goplay.pw"

- websites/O/OpenFING/metadata.json
- websites/O/OpenFING/presence.ts
> chore(OpenFING): update assets

- websites/V/v0/metadata.json
- websites/V/v0/presence.ts
Added the presence
<details>
</details>
> feat(v0): add presence

- websites/A/Asura Scans/metadata.json
* Also added a regex considering how often they are adding a new domain...
<details>
</details>
> fix(Asura Scans): update domain

- websites/G/GoAnimes/iframe.ts
- websites/G/GoAnimes/metadata.json
- websites/G/GoAnimes/presence.ts
add presence
<details>
<summary>Proof showing the creation/modification is working as expected</summary>
</details>
> feat(GoAnimes): add presence

- websites/O/OneTouchTV/iframe.ts
- websites/O/OneTouchTV/metadata.json
- websites/O/OneTouchTV/presence.ts
Resolves #7646
Added the presence
<details>
</details>
> feat(OneTouchTV): add presence

- websites/T/Trello/metadata.json
- websites/T/Trello/presence.ts
Just updating the Trello presence so it works again.
<details>
</details>
> fix(Trello): update query selectors

- websites/A/Akinator/metadata.json
- websites/A/Akinator/presence.ts
Add more functionallity & improve a bit of code
<details>
</details>
> feat(Akinator): add more functionallity

- websites/E/E-PAL/metadata.json
- websites/E/E-PAL/presence.ts
Resovles #7462
Added epal presence
<details>
</details>
> feat(E-Pal): add presence

- websites/I/ITVX/metadata.json
> chore(ITVX): update assets

- websites/E/E-PAL/metadata.json
- websites/E/E-PAL/presence.ts
> chore(E-PAL): update assets

- websites/S/Sosac/metadata.json
> chore(Sosac): update assets

- websites/P/Pixelmon Mod/metadata.json
- websites/P/Pixelmon Mod/presence.ts
- Add button
- Add custom small/large image with setting to change or disable
- If / elseif / else => Switch
<details>
</details>
> feat(Pixelmon Mod): add features & rewrite presence

- websites/D/Discord SFX/metadata.json
- websites/D/Discord SFX/presence.ts
- websites/P/Pixelmon Mod/metadata.json
> chore(Discord SFX): update assets

- websites/D/Discord.js/metadata.json
- Add tags that should have been there already (So u can find the presence.)
<details>
n/a
</details>
> fix(Discord.js): add tags

- websites/Y/YouTube/metadata.json
- websites/Y/YouTube/presence.ts
- Fixes an issue where the channel url was null in the button
- Probably resolves #6370
<details>
</details>
> fix(YouTube): fix channel url in button

- websites/N/Niantic Wayfarer/metadata.json
- websites/N/Niantic Wayfarer/presence.ts
- Updates the selectors for various things on the page
- Adds more details and images
- Moves assets to assets enum
<details>
</details>
> feat(Niantic Wayfarer): update selectors and add details

- websites/N/Niantic Wayfarer/metadata.json
> chore(Niantic Wayfarer): update assets

- websites/V/VtuberWiki/metadata.json
- websites/V/VtuberWiki/presence.ts
> chore(VtuberWiki): update assets

- websites/P/pass Culture/metadata.json
- websites/P/pass Culture/presence.ts
> chore(pass Culture): update assets

- websites/G/GitHub/metadata.json
- websites/G/GitHub/presence.ts
Resolve `undefined` issue while visiting a file or code
<details>
</details>
> fix(GitHub): resolve "undefined"

- websites/A/atomicradio/metadata.json
- websites/A/atomicradio/presence.ts
Added a presence for https://atomic.radio
<details>
<br>
</details>
> feat(atomicradio): add atomicradio presence

- websites/A/atomicradio/metadata.json
- websites/A/atomicradio/presence.ts
> chore(atomicradio): update assets

- websites/M/MonBureauNumérique/metadata.json
- websites/M/MonBureauNumérique/presence.ts
I've added a richpresence for "MonBureauNumérique", a digital working environment for certain French students.
<details>
PS: The Discord application has been renamed but the discord cache has not yet been updated. It will still say "MonBureauNumérique".
</details>
> feat(MonBureauNumerique): add MonBureauNumerique presence

- websites/#/ッツ Ebook Reader/metadata.json
- websites/#/ッツ Ebook Reader/presence.ts
Add presence for ッツ Reader
<details>
</details>
> feat(ッツ Reader): add presence

- websites/#/ッツ Ebook Reader/metadata.json
- websites/#/ッツ Ebook Reader/presence.ts
> chore(ッツ Ebook Reader): update assets

- websites/M/MonBureauNumérique/metadata.json
- websites/M/MonBureauNumérique/presence.ts
> chore(MonBureauNumérique): update assets

- websites/#/ッツ Ebook Reader/metadata.json
- websites/X/X.com/metadata.json
- websites/X/X.com/presence.ts
> chore(X.com): update assets

- websites/B/Bluesky/metadata.json
- websites/B/Bluesky/presence.ts
> chore(Bluesky): update assets

- websites/T/TwitCasting/metadata.json
- websites/T/TwitCasting/presence.ts
> fix(TwitCasting): update selector

- tools/classes/AssetsManager.ts
Updates the image regex to also detect query strings
> feat(AssetsManager): add detection of query strings on image assets

- websites/S/Spyke/metadata.json
- websites/S/Spyke/presence.ts
> chore(Spyke): update assets

- websites/D/Discord SFX/metadata.json
> chore(Discord SFX): format metadata

- websites/V/Vizjer/metadata.json
- websites/V/Vizjer/presence.ts
> chore(Vizjer): update assets

- websites/M/Marktplaats/metadata.json
- websites/M/Marktplaats/presence.ts
- Rewrote presence
- if/elseif/else => Switch
- Hostname check => Switch
<details>
</details>
> feat(Marktplaats): rewrite presence

- websites/M/Marktplaats/metadata.json
- websites/M/Marktplaats/presence.ts
> chore(Marktplaats): update assets

- websites/D/Deezer/metadata.json
- websites/D/Deezer/presence.ts
> chore(Deezer): refactor

- websites/J/Jackbox/games/Party Pack 10/awshirt2.ts
- websites/J/Jackbox/games/Party Pack 10/nopus-opus.ts
- websites/J/Jackbox/games/Party Pack 10/risky-text.ts
- websites/J/Jackbox/games/Party Pack 10/time-trivia.ts
- websites/J/Jackbox/games/Party Pack 10/us-them.ts
- websites/J/Jackbox/games/index.ts
- websites/J/Jackbox/metadata.json
- websites/J/Jackbox/presence.ts
- websites/J/Jackbox/util.ts
* Adds games from The Jackbox Party Pack 10
* Uses pd.premid.app for image uploads rather than bashupload.com, which may be less stable.
<details>
</details>
> feat(Jackbox): add party pack 10 games

- websites/J/Jackbox/games/Party Pack 10/awshirt2.ts
- websites/J/Jackbox/games/Party Pack 10/nopus-opus.ts
- websites/J/Jackbox/games/Party Pack 10/risky-text.ts
- websites/J/Jackbox/games/Party Pack 10/time-trivia.ts
- websites/J/Jackbox/games/Party Pack 10/us-them.ts
> chore(Jackbox): update assets

- websites/C/Character.AI/metadata.json
- websites/C/Character.AI/presence.ts
Add presence for Character.AI
Resolves #7573 
<details>
</details>
> feat(Character.AI): add presence

- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
Added extra setting for small images
Added extra setting for logos
Added animated logo to presence
Added legacy mode icons
Updated metadata
<details>
</details>
> feat(BeatLeader): more settings & legacy mode

- websites/F/Flightradar24/metadata.json
- websites/F/Flightradar24/presence.ts
> chore(Flightradar24): update assets

- websites/C/Character.AI/metadata.json
- websites/C/Character.AI/presence.ts
> chore(Character.AI): update assets

- websites/P/Poolsuite FM/metadata.json
- websites/P/Poolsuite FM/presence.ts
Add rich presence for the music website Poolsuite FM
<details>
</details>
> feat(Poolsuite FM): add presence

- websites/S/Smash Pros/metadata.json
- websites/S/Smash Pros/presence.ts
Add presence for Smash Pros, a skill based match making service for Super Smash Bros. Ultimate.
<details>
</details>
> feat(Smash Pros): add presence

- websites/P/Poolsuite FM/metadata.json
- websites/S/Smash Pros/metadata.json
- websites/S/Smash Pros/presence.ts
> chore(Smash Pros): update assets

- websites/P/Poolsuite FM/metadata.json
- websites/P/Poolsuite FM/presence.ts
> chore(Poolsuite FM): update assets

- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
> chore(BeatLeader): force imgur link for christmas asset

- websites/C/Character.AI/metadata.json
- websites/C/Character.AI/presence.ts
added support for /chat
resolves #7765
<details>
</details>
> fix(Character.AI): add /chat

- websites/B/BeatLeader/metadata.json
- websites/B/BeatLeader/presence.ts
> chore(BeatLeader): update assets

- websites/N/Niantic Wayfarer/metadata.json
- websites/N/Niantic Wayfarer/presence.ts
> fix(Niantic Wayfarer): update query selectors for new UI

- websites/V/Vizjer/metadata.json
added 2 new urls to iframe
</details>
> feat(Vizjer): add iframe urls

- websites/V/Vizjer/metadata.json
> chore(Vizjer): format metadata

- websites/D/Duolingo/metadata.json
- websites/D/Duolingo/presence.ts
- websites/V/VtuberWiki/metadata.json
> chore(Duolingo): update assets

- websites/X/X.com/metadata.json
- websites/X/X.com/presence.ts
> chore(X): update assets

- websites/C/Coursera/metadata.json
- websites/C/Coursera/presence.ts
> chore(Coursera): update assets

- websites/C/ChatGPT/metadata.json
- websites/C/ChatGPT/presence.ts
- Changed selectors for word/asked amounts
- Resolves #7800
<details>
</details>
> fix(ChatGPT): fix word/asked amount not being displayed

- websites/V/VtuberWiki/metadata.json
- websites/V/VtuberWiki/presence.ts
The VtuberWiki has added in a Sdk endpoint to allow people to get access to wrappers for the api
<details>
</details>
> feat(VtuberWiki): add the new sdk endpoint

- websites/R/Reaper Scans/metadata.json
Original domain is temporarily down, add current temporary domain
<details>
</details>
> feat(Reaper Scans): add new domain

- websites/N/Netflix/metadata.json
- websites/N/Netflix/presence.ts
- Fix netflix presence for Alpha/Beta extension. (Kinda unsure if this code's quality is high enough lol)
- Resolves #7260 
<details>
</details>
> fix(Netflix): fix presence for alpha/beta extension

- websites/D/Duolingo/metadata.json
- websites/D/Duolingo/presence.ts
- websites/D/Duolingo/util.ts
+ added alphabet pages. resolves #7787
+ added practice pages
+ added all colors to progress bar
+ improved user page handling
+ improved lesson state handling
> feat(Duolingo): v3.2.0
