Dream_Animes/metadata.json
=> congrats fror, you forgot to replace something

XVideos/dist/metadata.json, XVideos/dist/presence.js, XVideos/presence.ts, XVideos/tsconfig.json
Add XVideos Presence for PreMiD.
=> Add XVideos Presence.

RedTube/dist/metadata.json, RedTube/dist/presence.js, RedTube/presence.ts, RedTube/tsconfig.json
Add RedTube Presence to PreMiD.
=> Add RedTube Presence.

HBO GO/dist/metadata.json, HBO GO/dist/presence.js, HBO GO/presence.ts, HBO GO/tsconfig.json
closes https://github.com/PreMiD/Presences/issues/54
=> Add HBO GO Presence to PreMiD [requested presence].

RedTube/dist/metadata.json
=> :sparkles: Updated.

Instagram/dist/metadata.json, Instagram/dist/presence.js, Instagram/presence.ts, Instagram/tsconfig.json
Really simple presence for the (also really simple) Instagram Website
=> Instagram Presence

Instagram/dist/presence.js
Fixed code that VSCode didn't save somehow :/
=> Instagram Post Author Fix

plug.dj/dist/metadata.json, plug.dj/dist/presence.js, plug.dj/presence.ts, plug.dj/tsconfig.json
Added Presence for plug.dj, which is a website where users can listen to songs with other users and chat.
=> plug.dj Presence

Deezer/dist/metadata.json, Deezer/dist/presence.js, Deezer/presence.ts, Deezer/tsconfig.json
First version of the Deezer presence, ready to be deployed.
=> add: deezer presence

XVideos/dist/metadata.json
=> :sparkles: Removed URL array.

SoundCloud/dist/metadata.json, SoundCloud/dist/presence.js, SoundCloud/presence.ts, SoundCloud/tsconfig.json
This version is ready to be deployed.
=> add: soundcloud presence

Hulu/dist/metadata.json, Hulu/dist/presence.js, Hulu/presence.ts, Hulu/tsconfig.json
This version is ready to be deployed.
=> add: hulu presence [requested]

GitHub/dist/metadata.json, GitHub/dist/presence.js, GitHub/presence.ts, GitHub/tsconfig.json
Exactly 360 lines of code OwO.
Issue: https://github.com/PreMiD/Presences/issues/44
=> :unicorn: Add GitHub Presence to PreMiD [requested presence].

MyAnimeList/dist/metadata.json, MyAnimeList/dist/presence.js, MyAnimeList/presence.ts, MyAnimeList/tsconfig.json
Added presence for the Anime/Manga database & community "MyAnimeList"
=> MyAnimeList Presence

ToradorAPI/dist/metadata.json, ToradorAPI/dist/presence.js, ToradorAPI/presence.ts, ToradorAPI/tsconfig.json
Presence for my website "ToradorAPI" named after the API which it's based on. The purpose of this website is to show you random images or fanart from the anime Toradora.
I'll redo parts of the code in the future to make the presence's code better and make it display some more information like e.g. how many images there are.
=> ToradorAPI

nekos.life/dist/metadata.json, nekos.life/dist/presence.js, nekos.life/presence.ts, nekos.life/tsconfig.json
Really simple nekos.life presence
=> nekos.life Presence

twist.moe/dist/metadata.json, twist.moe/dist/presence.js, twist.moe/presence.ts, twist.moe/tsconfig.json
https://github.com/PreMiD/Presences/issues/9 - donator priority.
=> :star: Add twist.moe Presence to PreMiD [requested presence].

GitHub/dist/metadata.json
=> Updated the logo >_<

MangaRock/dist/metadata.json, MangaRock/dist/presence.js, MangaRock/presence.ts, MangaRock/tsconfig.json
Closes https://github.com/PreMiD/Presences/issues/38
=> :sparkles: Add MangaRock Presence to PreMiD [requested presence].

SimplyHentai/dist/metadata.json, SimplyHentai/dist/presence.js, SimplyHentai/presence.ts, SimplyHentai/tsconfig.json
=> :sparkles: Add Simply Hentai Presence to PreMiD.

Twitch/dist/metadata.json, Twitch/dist/presence.js, Twitch/presence.ts, Twitch/tsconfig.json
Squads, live videos, videos, and clips have been fixed and added. Browsing (should) display correctly, contact me if there are issues. This version is ready to be deployed.
=> fixed: twitch presence display // added: squad and clips

WIMS/dist/metadata.json, WIMS/dist/presence.js, WIMS/presence.ts, WIMS/tsconfig.json
This was a pain and it's poorly coded. WIMS doesn't get changed a lot anymore so it should be fine for quite a while.
=> Added WIMS Presence

Arena of Kings/dist/metadata.json, CrunchyRoll/dist/metadata.json, Deezer/dist/metadata.json, Dream Animes/dist/metadata.json, FiPlay/dist/metadata.json, GitHub/dist/metadata.json, HBO GO/dist/metadata.json, HentaiHaven/dist/metadata.json, Hulu/dist/metadata.json, Instagram/dist/metadata.json, MangaRock/dist/metadata.json, Mixer/dist/metadata.json, MyAnimeList/dist/metadata.json, Netflix/dist/metadata.json, PornHub/dist/metadata.json, RedTube/dist/metadata.json, SimplyHentai/dist/metadata.json, SoundCloud/dist/metadata.json, ToradorAPI/dist/metadata.json, Twitch/dist/metadata.json, VK/dist/metadata.json, WIMS/dist/metadata.json, XVideos/dist/metadata.json, YouTube Music/dist/metadata.json, YouTube/dist/metadata.json, nekos.life/dist/metadata.json, plug.dj/dist/metadata.json, twist.moe/dist/metadata.json
thanks to @Viruzaum and @Nightdavisao for helping me on this
=> a whole brazilian portuguese translation of the presence store descriptions

Netflix/dist/metadata.json, YouTube Music/dist/metadata.json
=> fruxh broke my pr

Arena of Kings/dist/metadata.json, FiPlay/dist/metadata.json, HBO GO/dist/metadata.json, Hulu/dist/metadata.json, Mixer/dist/metadata.json, Netflix/dist/metadata.json, RedTube/dist/metadata.json, SoundCloud/dist/metadata.json, ToradorAPI/dist/metadata.json, VK/dist/metadata.json, WIMS/dist/metadata.json, YouTube Music/dist/metadata.json, YouTube/dist/metadata.json, nekos.life/dist/metadata.json, plug.dj/dist/metadata.json, twist.moe/dist/metadata.json
Fixed some pt_BR descriptions btw
=> ⭐️ Fixed alignment and added French description to all remaining presences

Reddit/metadata.json, Reddit/presence.js
=> Added Reddit Presence

KissAnime/dist/iframe.js, KissAnime/dist/metadata.json, KissAnime/dist/presence.js, KissAnime/iframe.ts, KissAnime/presence.ts, KissAnime/tsconfig.json, dlive/dist/metadata.json, dlive/dist/presence.js, dlive/presence.ts, dlive/tsconfig.json
=> :sparkles: Add KissAnime Presence to PreMiD [requested presence].

Union Mangas/dist/metadata.json, Union Mangas/dist/presence.js, Union Mangas/presence.ts, Union Mangas/tsconfig.json
=> Added Union Mangas Presence

Deezer/dist/metadata.json, Twitch/dist/metadata.json
Changed the logo and thumbnail for both, as well as the tags and versions.
=> ♻️ Updated Deezer and Twitch Metadata

Mixcloud/dist/metadata.json, Mixcloud/dist/presence.js, Mixcloud/presence.ts, Mixcloud/tsconfig.json
close #63 
This is my first PR on this repo. Please comment anything if there is a problem.
This does not include media control. Because the site itself has it.
=> Add Mixcloud

GitHub/dist/metadata.json, GitHub/dist/presence.js, GitHub/presence.ts
Pull requests, issues, insights and projects are now displayed on the presence. Also, when you are uploading files it's displayed.
=> :sparkles: Updated GitHub Presence.

niconico/dist/metadata.json, niconico/dist/presence.js, niconico/presence.ts, niconico/tsconfig.json
close #4 
Please Add English description to `metadata.json`.
=> Add niconico Presence

niconico/dist/metadata.json
=> niconico english metadata translation

dAnimeStore/dist/metadata.json, dAnimeStore/dist/presence.js, dAnimeStore/presence.ts, dAnimeStore/tsconfig.json
Japanese not piracy anime streaming service like Crunchyroll.
Probably only available from Japan.
=> Add dアニメストア

CrunchyRoll/dist/iframe.js, CrunchyRoll/dist/metadata.json, CrunchyRoll/dist/presence.js, CrunchyRoll/iframe.ts, CrunchyRoll/presence.ts
Closes #144 
Sorry for the late response.
=> :bug: Fixed a bug.

Newgrounds/dist/iframe.js, Newgrounds/dist/metadata.json, Newgrounds/dist/presence.js, Newgrounds/iframe.ts, Newgrounds/presence.ts, Newgrounds/tsconfig.json
=> :sparkles: Add Newgrounds Presence to PreMiD [requested presence].

BraniTube/dist/metadata.json, BraniTube/dist/presence.js, BraniTube/presence.ts, BraniTube/tsconfig.json
=> :sparkles: Add BraniTube Presence to PreMiD.

dailymotion/dist/metadata.json, dailymotion/dist/presence.js, dailymotion/presence.ts, dailymotion/tsconfig.json, osu!ppy/dist/metadata.json, osu!ppy/dist/presence.js, osu!ppy/presence.ts
added a dailymotion.com presence and solved a osu!ppy state bug (+ added 2 missing paths).
=> added dailymotion support

Steam/dist/metadata.json, Steam/dist/presence.js, Steam/presence.ts, Steam/tsconfig.json
=> :sparkles: Add Steam Presence to PreMiD [donator priority].

CrunchyRoll/dist/metadata.json
If this isn't working, something else might be broken :|
=> :bug: Something might be wrong.

Mixer/dist/presence.js, Mixer/presence.ts
Rewrote the mixer presence to include more features, hopefully fixed some issues.
=> ♻️ Updated Mixer Presence

Roblox/dist/metadata.json, Roblox/dist/presence.js, Roblox/presence.ts, Roblox/tsconfig.json
=> :sparkles: Add Roblox Presence to PreMiD [requested presence].

Webtoon/dist/metadata.json, Webtoon/dist/presence.js, Webtoon/presence.ts, Webtoon/tsconfig.json
=> Added Webtoon presence

Arena of Kings/dist/metadata.json, BraniTube/dist/metadata.json, Change/dist/metadata.json, CrunchyRoll/dist/metadata.json, Deezer/dist/metadata.json, Derpibooru/dist/metadata.json, Dream Animes/dist/metadata.json, Duolingo/dist/metadata.json, FiPlay/dist/metadata.json, GitHub/dist/metadata.json, Google Play Music/dist/metadata.json, HentaiHaven/dist/metadata.json, Hulu/dist/metadata.json, Instagram/dist/metadata.json, KissAnime/dist/metadata.json, MangaRock/dist/metadata.json, Mixcloud/dist/metadata.json, Mixer/dist/metadata.json, MyAnimeList/dist/metadata.json, Netflix/dist/metadata.json, Newgrounds/dist/metadata.json, Pandora/dist/metadata.json, PornHub/dist/metadata.json, Reddit/dist/metadata.json, dAnimeStore/dist/metadata.json, dailymotion/dist/metadata.json, dlive/dist/metadata.json, nekos.life/dist/metadata.json, niconico/dist/metadata.json, plug.dj/dist/metadata.json
I hope this doesn't break anything with Bas950's dutch translations, as we basically did them at the same time
=> German translations for most of the presence description.

NPM Package Registry/dist/metadata.json, NPM Package Registry/dist/presence.js, NPM Package Registry/presence.ts, NPM Package Registry/tsconfig.json
Untested, as I can't load custom presences at the moment. Some parts tested using dev console and should work though.
=> npmjs.org Presence

NPM Package Registry/dist/metadata.json
fixed stupidity in my metadata file
=> f i x e d   s t u p i d i t y

Yay Animes/dist/metadata.json, Yay Animes/dist/presence.js, Yay Animes/presence.ts, Yay Animes/tsconfig.json
=> Added Yay Animes presence

PonyvilleFM/dist/metadata.json, PonyvilleFM/dist/presence.js, PonyvilleFM/presence.ts
I have no idea what happened, but the presence didn't work (even though I could've sworn it did). Must be because I'm half asleep. 😛
=> This fixes this, and that fixes that

V LIVE/dist/metadata.json, V LIVE/dist/presence.js, V LIVE/presence.ts, V LIVE/tsconfig.json
=> Added V LIVE presence

Jet Set Radio Live/dist/metadata.json, Jet Set Radio Live/dist/presence.js, Jet Set Radio Live/presence.ts, Jet Set Radio Live/tsconfig.json
this one actually works i promise 😅
=> Add Jet Set Radio Live presence

kshow123/dist/iframe.js, kshow123/dist/metadata.json, kshow123/dist/presence.js, kshow123/iframe.ts, kshow123/presence.ts, kshow123/tsconfig.json
=> Added Kshow123 Presence

kshow123/dist/metadata.json, kshow123/iframe.ts, viki/dist/metadata.json, viki/dist/presence.js, viki/presence.ts, viki/tsconfig.json
Added Viki Presence and added extra video service to Kshow123
=> Added Viki Presence and added extra video service to Kshow123

Anime4You/dist/metadata.json, Anime4You/dist/presence.js, Anime4You/presence.ts, Anime4You/tsconfig.json
Due to current PreMiD Limitations, there is no information of time left and pause/play status yet, but I'll add that once Beta 3 is out.
=> Anime4You Presence

Discord/dist/metadata.json, Discord/dist/presence.js, Discord/presence.ts, Discord/tsconfig.json
Should (only) be used for dev portal and other, altough normal discord also works. Note: You need discord app open for it to work.
=> Discord Presence

Discord/dist/metadata.json, Discord/dist/presence.js, Discord/presence.ts
Added support for Discord Developer Teams and support for "typing" on a Discord server.
=> :sparkles: Discord Update

Skype/dist/metadata.json, Skype/dist/presence.js, Skype/presence.ts, Skype/tsconfig.json
=> :star: Added Skype Presence

Skype/dist/metadata.json, Skype/dist/presence.js, Skype/presence.ts
=> Skype added bot support

Amazon/dist/metadata.json, Amazon/dist/presence.js, Amazon/presence.ts, Amazon/tsconfig.json
=> Amazon presence

AliExpress/dist/metadata.json, AliExpress/dist/presence.js, AliExpress/presence.ts, AliExpress/tsconfig.json
=> AliExpress

Mixer/dist/presence.js, Mixer/presence.ts, NameMC/dist/metadata.json, Showtime/dist/metadata.json
Mixer: Updated classes to get it to work again until creator takes a look at it
Showtime: Changed Logo
NameMC: Changed Logo + removed an unused URL
=> Fixed Mixer + minor edits

Spotify/dist/metadata.json, Spotify/dist/presence.js, Spotify/presence.ts, Spotify/tsconfig.json
Requested by Nath#0095 on Discord.
Note: Show only if you are listening to a podcast or if you are not and not listening to a song, it shows page info. To show normal songs use the Spotify x Discord connection.
=> Spotify presence

kshow123/dist/iframe.js, kshow123/dist/metadata.json, kshow123/dist/presence.js, kshow123/iframe.ts, kshow123/presence.ts
=> Kshow123 iFrame fix

Dream Animes/dist/metadata.json, Dream Animes/dist/presence.js, Dream Animes/presence.ts, Dream Animes/tsconfig.json
Now it works in the new beta. (probably)
=> Remade Dream Animes

Discord/dist/metadata.json, Discord/dist/presence.js, Discord/presence.ts
- [BUG - FIXED] It's not showing which channel / DMs you are viewing. (Reported by KorpeZ#9999)
- [ADDED] Now shows if you are voice connected. (Suggested by KorpeZ#9999)
=> Discord presence update

ESL/dist/metadata.json, ESL/dist/presence.js, ESL/presence.ts, ESL/tsconfig.json
=> ESL presence

ESL/dist/metadata.json, ESL/dist/presence.js, ESL/presence.ts
- [ADDED] www.schulmeisterschaft.de
- [ADDED] Shop now says what you are looking at.
- [BUG - FIXED] Team and Players not showing the right way.
- [BUG - FIXED] News saying ESL Pro instead of ESL News.
- [BUG - FIXED] Forum main page not showing.
All thanks to: Fruxh#3282
=> ESL update

Webtekno/dist/metadata.json, Webtekno/dist/presence.js, Webtekno/presence.ts, Webtekno/tsconfig.json
Webtekno is a very popular (also has many awards) technology and news blog. It's one of the biggest technology blogs in Turkey, _their YouTube account has ~3 million subscribers_. This presence adds many options while you're surfing on their website.
**Looking at home-page:**
**Looking at other pages:**
**Searching for something:**
**Reading a post:**
**Watching a video post:**
PS: It is all in Turkish since it's a Turkish blog.
=> Added Webtekno, a popular Turkish technology blog.

duelingnexus/metadata.json, duelingnexus/presence.js
pull request for http://duelingnexus.com presence, its a yugioh sim.
=> added duelingnexus  presence files

Reddit/dist/metadata.json, Reddit/dist/presence.js, Reddit/presence.ts
=> Remade some things in Reddit presence and added support for oldReddit

Glitch/metadeta.json, Glitch/presence.js
I made this presence for glitch.com, it has a presence for every page, and subdomain pages!
=> New Presence: glitch.com

Bounce/dist/metadata.json, Bounce/dist/presence.js, Bounce/presence.ts
* Changed Logo to https://wearebounce.net/branding/LogoIconColour.png
* Updated song info, to use the API.
* Updated client ID, to my application, to use main bounce logo on status
=> Updated Bounce Presence

Disney+/dist/metadata.json, Disney+/dist/presence.js, Disney+/presence.ts, Disney+/tsconfig.json
Disney+ is Disney's streaming service which is currently available in The Netherlands as a beta trial for free until November 12th, which is when the service will officially launch in the United States and Canada as well.
=> Disney+ presence

LookMovie/dist/metadata.json, LookMovie/dist/presence.js, LookMovie/presence.ts, LookMovie/tsconfig.json
=> Added LookMovie presence

Duolingo/dist/metadata.json, Duolingo/dist/presence.js, Duolingo/presence.ts
=> fix duolingo "replace of undefined"

Dueling Nexus/dist/presence.js, Giphy/dist/metadata.json, Giphy/dist/presence.js
+ Giphy presence
- smallimagetext for Dueling nexus from "in game" to page url
=> Created Giphy rich presence and updated Duelingnexus rich presence

YouTube/dist/metadata.json, YouTube/dist/presence.js, YouTube/presence.ts
=> Add Youtube embed support

ComedyCentral/dist/metadata.json, ComedyCentral/dist/presence.js, ComedyCentral/presence.ts, ComedyCentral/tsconfig.json
Quick and easy presence for watching shows on [Comedy Central](https://cc.com/)!
`Lacking#0001` (`132693143173857281`)
=> Add Comedy Central Presence

Duolingo/dist/metadata.json, Duolingo/dist/presence.js, Duolingo/presence.ts
=> add some things to duolingo

Duolingo/dist/metadata.json, Duolingo/dist/presence.js, Duolingo/presence.ts
=> duolingo - "else"

Yu-Gi-Oh Top Decks/dist/metadata.json, Yu-Gi-Oh Top Decks/dist/presence.js, wikiHow/dist/metadata.json, wikiHow/dist/presence.js
yugioh topdecks is a top deck database
=> new Presence YuGiOh topdecks and wikiHow

Dueling Nexus/dist/metadata.json, Dueling Nexus/dist/presence.js, Fanfiction/dist/metadata.json, Fanfiction/dist/presence.js
+ Added fanfiction presence.
+ Added timestamps in duelingnexus.
=> Fanfiction Presence and Duelingnexus Update

Hangout Hotel/dist/metadata.json, Hangout Hotel/dist/presence.js
The owners at Hangout Hotel, asked me to make a rich presence for their habbo fansite, so here it is :)
=> New Presence - Hangout Hotel

Streamable/dist/metadata.json, Streamable/dist/presence.js, Streamable/presence.ts, Streamable/tsconfig.json
Quick and easy presence for watching videos on Streamable!
`Lacking#0001` (`132693143173857281`)
=> Add Streamable Presence

Gfycat/dist/metadata.json, Gfycat/dist/presence.js, Gfycat/presence.ts, Gfycat/tsconfig.json
Presence for [Gfycat](https://gfycat.com/)!
=> Add Gfycat Presence

NON-STOP NYAN CAT!/dist/metadata.json, NON-STOP NYAN CAT!/dist/presence.js, NON-STOP NYAN CAT!/presence.ts, NON-STOP NYAN CAT!/tsconfig.json
Presence for [NON-STOP NYAN CAT!](http://www.nyan.cat) because what else do you do at 3 AM on a Tuesday
=> Add NON-STOP NYAN CAT! presence

All The Flavors/dist/metadata.json, All The Flavors/dist/presence.js
its a recipe and DIY site
here are 5 presences but the code can generate presence for every url this site has.
=> Added All The Flavors 

Fmovies/dist/iframe.js, Fmovies/dist/metadata.json, Fmovies/dist/presence.js, Fmovies/iframe.ts, Fmovies/presence.ts, Fmovies/tsconfig.json
=> Fmovies support

9anime/dist/iframe.js, 9anime/dist/metadata.json, 9anime/dist/presence.js, 9anime/iframe.ts, 9anime/presence.ts, 9anime/tsconfig.json
=> Add 9anime support

Duolingo/dist/metadata.json, Duolingo/dist/presence.js, Duolingo/presence.ts
> this is last pull request to duolingo, _i promise._
=> last patch to duolingo

Edge Me Please/dist/metadata.json, Edge Me Please/dist/presence.js
as a gift for **fror senpai** .  It has custom dialogue for each instruction the site gives
=> created Edge me PLS

TCRF/dist/metadata.json, TCRF/dist/presence.js
TCRF site presence. it also fulfills presence request issue https://github.com/PreMiD/Presences/issues/290
=> added TCRF presence 

Giphy/dist/metadata.json, Google Drive/dist/metadata.json
=> epic changes (part 1)

TugaStrikes/dist/metadata.json, wikiHow/dist/metadata.json
=> epic changes (part 2)

Akinator/dist/metadata.json, Akinator/dist/presence.js, Anime News Network/dist/metadata.json, Anime News Network/dist/presence.js
it shows almost all presences. if i missed something, i will update them.
It's made with for the presence request https://github.com/PreMiD/Presences/issues/301
=> Added Anime News Network and Akinator

IMDb/dist/metadata.json, IMDb/dist/presence.js, IMDb/presence.ts, IMDb/tsconfig.json
Hi, this is a presence for IMDb written with TypeScript.
Screenshots:
=> Added IMDb presence

Neox Scanlator/dist/metadata.json, Neox Scanlator/dist/presence.js, Neox Scanlator/presence.ts, Neox Scanlator/tsconfig.json
=> Added Neox Scanlator Presence

GBAtemp.net/dist/metadata.json, GBAtemp.net/dist/presence.js, GBAtemp.net/presence.ts, GBAtemp.net/tsconfig.json
Presence for GBAtemp.net, basically just a forum where people discuss console hacks, among other things.
Cue (some of) the screenshots:
=> Add GBAtemp.net presence

DirtMC/dist/metadata.json, DirtMC/dist/presence.js, DirtMC/presence.ts, DirtMC/tsconfig.json, MEE6/dist/metadata.json, MEE6/dist/presence.js, MEE6/presence.ts, MEE6/tsconfig.json, The Archon/dist/metadata.json, The Archon/dist/presence.js, The Archon/presence.ts, The Archon/tsconfig.json
MEE6 presence closes: https://github.com/PreMiD/Presences/issues/432
=> DirtMC, The Archon and MEE6 presence

UpBeatRadio/dist/presence.js
Added it show it shows the song currently playing when your on the homepage
=> Added song when your on the homepage

JioCinema/dist/metadata.json, JioCinema/dist/presence.js, JioCinema/presence.ts, JioCinema/tsconfig.json
=> Added JioCinema presence

Viaplay/dist/metadata.json, Viaplay/dist/presence.js, Viaplay/presence.ts, Viaplay/tsconfig.json
=> Added Viaplay presence

Edge Me Please/dist/metadata.json, Just Light Novels/dist/metadata.json, Just Light Novels/dist/presence.js
on request of a discord user 
i expect it to have presence for each kind of links this site have
=>  added Just Light Novels

Twitch/dist/metadata.json, Twitch/dist/presence.js, Twitch/presence.ts
Presence after fix: 
closes #470
=> Fixed issue https://github.com/PreMiD/Presences/issues/470

tuga.tv/dist/iframe.js, tuga.tv/dist/metadata.json, tuga.tv/dist/presence.js, tuga.tv/iframe.ts, tuga.tv/presence.ts, tuga.tv/tsconfig.json
Requested by !!PãoCaro!!#4076
If anyone can find a better logo, please send me.
=> Added tuga.tv presence

GittiGidiyor/dist/metadata.json, GittiGidiyor/dist/presence.js, GittiGidiyor/presence.ts, GittiGidiyor/tsconfig.json, Hepsiburada/dist/metadata.json, Hepsiburada/presence.ts, Lichess/dist/metadata.json, Lichess/dist/presence.js, Lichess/presence.ts, Lichess/tsconfig.json, Medium/dist/metadata.json, Medium/dist/presence.js, Medium/presence.ts, Medium/tsconfig.json, Webtekno/dist/presence.js, Webtekno/presence.ts, n11.com/dist/presence.js, n11.com/presence.ts
This going to be an _another_ really LONG pull request. Just keep upvoting :^) Also, there are some notes at the end, if you don't want to read the whole text, just skip to the end and read the notes (yeah, you have to read something at the end).
`ADDED` GittiGidiyor, a Turkish shopping website which is owned by eBay.
`ADDED` Medium, a very popular online publishing platform (there's a note about this at the end).
`ADDED` Lichess, an online all-free chess game.
`EDITED` n11.com, deleted some lines and made the file smaller.
`EDITED` Hepsiburada, deleted some lines and made the file smaller.
`EDITED` Webtekno, deleted some lines and made the file smaller.
This is an another Turkish shopping website which is owned by eBay. I didn't release this with the other Turkish shopping services …
=> Added, GittiGidiyor, Medium, Lichess and Edited Some Old Files!

Medium/dist/metadata.json
And they were so stupid; whatsapp? lmao, no.
=> Updated Medium's metadata, CUZ I FORGOT SOME THINGS.

Chaturbate/dist/metadata.json, Chaturbate/dist/presence.js, Chaturbate/presence.ts, Chaturbate/tsconfig.json
=> Chaturbate support

Game Jolt/dist/metadata.json, Game Jolt/dist/presence.js, Game Jolt/presence.ts, Game Jolt/tsconfig.json
Game Jolt is a really cool indie game publishing site. Most of the YouTubers/streamers find indie games from here and play for free/just a little money. This service was requested [here](https://github.com/PreMiD/Presences/issues/277) by @daiocu _28 DAYS AGO, sorry dude._
**Viewing homepage:**
**Viewing a game:**
**Viewing other pages:**
**Browsing games by tag:**
**Searching:**
➡️ **Searching for a game:**
➡️ **Searching for a user:**
~~_YAY, I'M A HELPFUL PERSON ^-^ <3_~~ 
closes #277
=> Added Game Jolt, was requested before.

AniList/dist/presence.js, AniList/presence.ts, AnimeDao/dist/iframe.js, AnimeDao/dist/metadata.json, AnimeDao/dist/presence.js, AnimeDao/iframe.ts, AnimeDao/presence.ts, AnimeDao/tsconfig.json
`ADDED` AnimeDao presence. closes #376 
`EDITED`  AniList, fixed my broken english, changed how strings are concatenated and cleaned up the code a bit. closes #319
=> Added AnimeDao and changed some things in AniList

AnimeFLV/dist/iframe.js, AnimeFLV/dist/metadata.json, AnimeFLV/dist/presence.js, AnimeFLV/iframe.ts, AnimeFLV/presence.ts, AnimeFLV/tsconfig.json
Actually, i also added the small icons for searching, playing and pause.
=> Added AnimeFLV Presence

HepBoat/dist/metadata.json, HepBoat/dist/presence.js, HepBoat/presence.ts, HepBoat/tsconfig.json
Quick and simple presence for the [HepBoat Dashboard](https://mod.teamhydra.dev/)
`Lacking#0001` (`132693143173857281`)
=> Add HepBoat Presence

dizilab/dist/iframe.js, dizilab/dist/metadata.json, dizilab/dist/presence.js, dizilab/iframe.ts, dizilab/presence.ts, dizilab/tsconfig.json, filmmodu/dist/metadata.json, filmmodu/dist/presence.js, filmmodu/presence.ts, filmmodu/tsconfig.json, wikiHow/dist/metadata.json, wikiHow/dist/presence.js
_Moving this to the top because it took my 4 hours and it looks SO GOOD k thx._
Alright, now I know that iframes are way more harder than the usual way of creating a presence, well now I also know how to create them. So, next time I'll be the fastest fuc... ;)
~~_Just to note, it looks amazing. I included tons of features. And this closes #514._~~
**Viewing home page:**
**Viewing other pages:**
**Searching for something:**
**Searching for something under a category (category name is inside the brackets):**
**Viewing a user's profile:**
**Viewing an actor's profile:**
**Viewing a series' profile:**
**Watching an episode:**
**Watching something from different players/alternatives:**
**_Watching something but the video is paused:_**
filmmodu is a Turkish service that provides latest movies. …
=> Fixed wikiHow | Added filmmodu and dizilab presence!

Game Jolt/dist/metadata.json, dizilab/dist/presence.js, dizilab/presence.ts
Just fixed something in dizilab presence and edited Game Jolt's metadata file. dizilab was having issues when you're browsing through the archive section and I just added Turkish description to the Game Jolt's metadata file. _Only because every presence of mine has Turkish description and this looks awful between others._
Before:
After (yes, big change):
=> Updated dizilab and Game Jolt!

Radio.net/dist/metadata.json, Radio.net/dist/presence.js
**What's the name of the service?**
Radio.net
**What should the Presence display?**
Informations about the current playing radio station
**Why do you want support for this service?**
I'm in knowledge of this service for a long time but most people I met didn't know it is existing.
**Are you able to provide an image for the service? (512x512 minimum)**
=> Added Radio.net

Radio.net/dist/metadata.json, Radio.net/dist/presence.js
Podcasts on Radio.net will now be correctly displayed & fixed the problem with changing song (browsingStamp resetted each time).
Sample on how podcasts will be displayed like:
=> ⭐ Added podcast support & fixed the browsingStamp

animeflix/dist/metadata.json, animeflix/dist/presence.js
=> Add animeflix.io

GBF/dist/metadata.json, GBF/dist/presence.js, GBF/presence.ts, GBF/tsconfig.json
First presence for a game that I'm playing a lot
=> Add Granblue Fanstasy presence

#TeamTrees/dist/metadata.json, #TeamTrees/dist/presence.js, #TeamTrees/presence.ts, #TeamTrees/tsconfig.json
=> :star: #TeamTrees

Jackbox/dist/metadata.json, Jackbox/dist/presence.js
Presence for Jackbox written in javascript
Screenshots:
=> Add Jackbox.tv presence

Discord/dist/metadata.json, Discord/dist/presence.js, Discord/presence.ts
=> Discord invites

YouTube/dist/metadata.json, YouTube/dist/presence.js, YouTube/presence.ts
=> Youtube Overhaul

SCP Wiki/dist/metadata.json, SCP Wiki/dist/presence.js
=> Add SCP Wiki

Codeforces/dist/metadata.json, Codeforces/dist/presence.js, Codeforces/presence.ts, Codeforces/tsconfig.json
=> Added Codeforces presence

AnimeWorld/dist/metadata.json, Funimation/dist/iframe.js, Funimation/dist/metadata.json, Funimation/dist/presence.js, Funimation/iframe.ts, Funimation/presence.ts, Funimation/tsconfig.json, VRV/dist/iframe.js, VRV/dist/metadata.json, VRV/dist/presence.js, VRV/iframe.ts, VRV/presence.ts, VRV/tsconfig.json, VVVVID/dist/metadata.json, VVVVID/dist/presence.js, VVVVID/presence.ts, VVVVID/tsconfig.json, Valtox Gaming Group/dist/metadata.json, Valtox Gaming Group/dist/presence.js, Valtox Gaming Group/presence.ts, Valtox Gaming Group/tsconfig.json, YouTube/dist/metadata.json, YouTube/dist/presence.js, YouTube/presence.ts, 巴哈姆特動畫瘋/dist/metadata.json, 巴哈姆特動畫瘋/dist/presence.js, 巴哈姆特動畫瘋/presence.ts, 巴哈姆特動畫瘋/tsconfig.json
[Updated] AnimeWorld logo has been changed.
[Added] VVVVID
closes https://github.com/PreMiD/Presences/issues/22
[Updated] Youtube error when searching has been fixed.
[Added] Valtox Gaming Group
[Added] VRV
closes https://github.com/PreMiD/Presences/issues/27
[Added] Funimation
closes https://github.com/PreMiD/Presences/issues/35
[Added] 巴哈姆特動畫瘋
closes https://github.com/PreMiD/Presences/issues/45
=> Doing the requests (Part 2)

Anghami/dist/metadata.json, Anghami/dist/presence.js, Anghami/presence.ts, Anghami/tsconfig.json
=> 🎉 Anghami support

YouTube/dist/metadata.json, YouTube/dist/presence.js, YouTube/presence.ts
Hopefully last youtube fix for the channel not showing correctly, also removed console log.
=> youtube fix

TruckSimFM/dist/metadata.json, TruckSimFM/dist/presence.js, TruckSimFM/presence.ts, TruckSimFM/tsconfig.json, TruckStopRadio/dist/metadata.json
=> TSFM and TSR category change

Bandcamp/dist/metadata.json, Bandcamp/dist/presence.js, Bandcamp/presence.ts, Bandcamp/tsconfig.json, Power Radio/dist/metadata.json, Power Radio/dist/presence.js, Power Radio/presence.ts, Power Radio/tsconfig.json
[Added] Bandcamp
closes https://github.com/PreMiD/Presences/issues/464
=> Bandcamp and Power Radio

4anime/dist/metadata.json, 4anime/dist/presence.js, 4anime/presence.ts, 4anime/tsconfig.json
Just [twist.moe](https://twist.moe/)'s presence altered to work for [4anime](https://4anime.to/).
=> Add 4anime presence

dizilab/dist/presence.js, dizilab/presence.ts
=> Fixed episode/show name not showing.

Discord/dist/metadata.json, Discord/dist/presence.js, Discord/presence.ts, GameStar/dist/metadata.json, GameStar/dist/presence.js, GameStar/presence.ts, GameStar/tsconfig.json, TuMangaOnline/dist/metadata.json, TuMangaOnline/dist/presence.js, TuMangaOnline/presence.ts, TuMangaOnline/tsconfig.json, Tumblr/dist/metadata.json, Tumblr/dist/presence.js, Tumblr/presence.ts, Tumblr/tsconfig.json, anime47/dist/iframe.js, anime47/dist/metadata.json, anime47/dist/presence.js, anime47/iframe.ts, anime47/presence.ts, anime47/tsconfig.json
[UPDATED] Discord
Now doesn't show invite link untill presence settings is a thing.
Suggested by CRUGG#0001 
[ADDED] Tumblr
closes https://github.com/PreMiD/Presences/issues/468
[ADDED] GameStar
closes https://github.com/PreMiD/Presences/issues/475
[ADDED] TuMangaOnline
closes https://github.com/PreMiD/Presences/issues/477
[ADDED] anime47
closes https://github.com/PreMiD/Presences/issues/482
=> Doing the requests (Part 4)

Animes Online/dist/metadata.json, Animes Online/dist/presence.js, Animes Online/presence.ts, Animes Online/tsconfig.json, FreightFM/dist/metadata.json, FreightFM/dist/presence.js
[ADDED] Animes Online
closes https://github.com/PreMiD/Presences/issues/495
[ADDED] FreightFM (Partner)
=> Animes Online and FreightFM (Partner)

CONTRIBUTING.md
whoever merges this please inform the presence developers about it.
=> Updated guidelines to comply with the new rules

Game Jolt/dist/metadata.json, Hepsiburada/dist/metadata.json, Webtekno/dist/metadata.json, dizilab/dist/metadata.json, filmmodu/dist/metadata.json, n11.com/dist/metadata.json
Well yeah, seems like the system doesn't like me now. This should fix my updates. Ty.
=> Updated version strings of some of my presences.

FlipAnim/dist/metadata.json, FlipAnim/dist/presence.js, FlipAnim/presence.ts, FlipAnim/tsconfig.json, Sdarot.TV/dist/metadata.json, Sdarot.TV/dist/presence.js, Sdarot.TV/presence.ts, Sdarot.TV/tsconfig.json, Skillshare/dist/metadata.json, Skillshare/dist/presence.js, Skillshare/presence.ts, Skillshare/tsconfig.json, Vui Ghê/dist/metadata.json, Vui Ghê/dist/presence.js, Vui Ghê/presence.ts, Vui Ghê/tsconfig.json
[ADDED] Sdarot.TV
closes https://github.com/PreMiD/Presences/issues/496
[ADDED] Vui Ghê
closes https://github.com/PreMiD/Presences/issues/577
[ADDED] FlipAnim
closes https://github.com/PreMiD/Presences/issues/580
[ADDED] Skillshare
closes https://github.com/PreMiD/Presences/issues/583
=> Doing the requests (Part 6 - Final (for now))

CODEOWNERS
I changed my account name, so I am making the changes to the codeowners.md file.
=> Update Account Name

osu!gatari/dist/metadata.json, osu!gatari/dist/presence.js, osu!gatari/presence.ts, osu!gatari/tsconfig.json
=> :star: gatari incmong!!!

surviv.io/dist/metadata.json, surviv.io/dist/presence.js, surviv.io/presence.ts, surviv.io/tsconfig.json
=> Added surviv.io presence

FimFiction/dist/metadata.json, FimFiction/dist/presence.js, FimFiction/presence.ts, FimFiction/tsconfig.json, Time.is/dist/metadata.json, Time.is/dist/presence.js, Time.is/presence.ts, Time.is/tsconfig.json
[ADDED] Time.is
Requested by Raffael#7777
[ADDED] FimFiction
Requested by Timeraa#7947
=> Time.is & FimFiction

Valtox Gaming Group/dist/metadata.json, Valtox Gaming Group/dist/presence.js, Valtox Gaming Group/presence.ts
=> Valtox update

dizilab/dist/metadata.json, dizilab/dist/presence.js, dizilab/presence.ts
Looks like dizilab also offers inner video players (not iframed from other sources) for some shows. And thanks to #615 now I know that. This closes #615.
=> Updated dizilab, now works when there's a non-iframed video!

Google Play Music/dist/metadata.json, Google Play Music/dist/presence.js, Google Play Music/presence.ts
=> Google play music

yabancıdizi/dist/iframe.js, yabancıdizi/dist/metadata.json, yabancıdizi/dist/presence.js, yabancıdizi/iframe.ts, yabancıdizi/presence.ts, yabancıdizi/tsconfig.json
Okay, I don't know what happened but yabancıdizi (actually means foreign TV shows) was the first website I wanted to do if I were going to create a presence in this category. And, when I looked up into it, I figured out that they were using, _iframes in iframes_, I even told this to Timeraa I remember very well. But now, I don't know what changed but seems like it's not like that anymore and runs like a charm. So I made it ^:)
**Homepage:**
**Viewing a category page:**
**Viewing a user's profile:**
**Viewing an actor's page:**
**Watching an episode:**
**Watching a movie (yeah, odd but provides movies too):**
And here goes fror's thing:
=> Added yabancıdizi, another Turkish foreign TV series service!

DiziBOX/dist/iframe.js, DiziBOX/dist/metadata.json, DiziBOX/dist/presence.js, DiziBOX/iframe.ts, DiziBOX/presence.ts, DiziBOX/tsconfig.json, Ekşi Şeyler/dist/metadata.json, Ekşi Şeyler/dist/presence.js, Ekşi Şeyler/presence.ts, Ekşi Şeyler/tsconfig.json, Trendyol/dist/metadata.json, Trendyol/dist/presence.js, Trendyol/presence.ts, Trendyol/tsconfig.json, dizilab/dist/metadata.json, dizilab/dist/presence.js, dizilab/presence.ts, ekşi sözlük/dist/metadata.json, ekşi sözlük/dist/presence.js, ekşi sözlük/presence.ts, ekşi sözlük/tsconfig.json, sahibinden.com/dist/metadata.json, sahibinden.com/dist/presence.js, sahibinden.com/presence.ts, sahibinden.com/tsconfig.json, yabancıdizi/dist/metadata.json, yabancıdizi/dist/presence.js, yabancıdizi/presence.ts
_Yet another Turkish service._ Well yeah, this time I added some different websites _cuz_ people request it.
`ADDED` DiziBOX, another foreign TV shows provider.
`ADDED` Trendyol, another shopping website.
`ADDED` ekşi sözlük, just like Urban Dictionary.
`ADDED` Ekşi Şeyler, ekşi sözlük but _more_ official concept.
`ADDED` sahibinden.com, platform that you can buy used and non-used stuff (literally everything).
`EDITED` Missmatching variable names in both dizilab and yabancıdizi presences.
Nothing to tell much about it. You just watch and have fun.
**Homepage:**
**Searching:**
**Serie's profile:**
**User profile:**
**Watching an episode:**
This is so popular right now; don't really know why.
**Homepage:**
**Searching or viewing special categories:**
**Viewing a category:**
**Product …
=> Added 5 more presences of Turkish services!

Playerbros/dist/metadata.json, Playerbros/dist/presence.js, Playerbros/presence.ts, Playerbros/tsconfig.json, ShiftDelete.net/dist/metadata.json, ShiftDelete.net/dist/presence.js, ShiftDelete.net/presence.ts, ShiftDelete.net/tsconfig.json
_Both Turkish, of course :^)_ ShiftDelete.Net presence supports both their website (for technology and other stuff news) and their forum (also it's one of the biggest technology forums in Turkey). And Playerbros looks cool.
As I said, it works with website and forum without any conflicts. Amazed? ADD IT!
**Homepage:**
**Searching:**
**Reading an article:**
Yep, the big part is here. Dope.
**Homepage:**
**Searching:**
**Alter forums:**
**Forum posts:**
**Viewing a forum user:**
Never heard of this before, but seems fine. This closes #621. Thx.
**Homepage:**
**Viewing a page:**
**Searching:**
**Reading a post:**
**Viewing an author profile:**
__Here goes fror's thing :^)__
=> Added ShiftDelete.Net and Playerbros!

PreMiD/dist/metadata.json, PreMiD/dist/presence.js, PreMiD/presence.ts
Wow, now with fixed profile names and better/clean code! Sorry Timeraa and others :3 _I wasn't able to test it but I'm pretty sure it'll work; we can try! <33
=> Am I even allowed to do this :^) Rework of PreMiD presence!

PreMiD/dist/metadata.json, PreMiD/dist/presence.js
Wow, what a fix. Everything else works great tho, good job EGGSY, we love u <3
=> Oopsie, homepage doesn't work!

ShiftDelete.net/dist/metadata.json, ShiftDelete.net/dist/presence.js, ShiftDelete.net/presence.ts
So now it detects when you're creating a new post! Amazing right? Look at this beautiful view! OMG!
=> Updated ShiftDelete.Net!

WoXArea/dist/metadata.json, WoXArea/dist/presence.js, WoXArea/presence.ts, WoXArea/tsconfig.json
_Yet another Turkish service_. This was requested before, it's not my thing to support hacking forums or etc. but this was requested and seems like PreMiD is OK to have these kind of stuff so here it is. This closes #623. 
**Homepage:**
**Viewing a forum:**
**Viewing a thread:**
**Starting a new thread:**
**Searching:**
**Viewing a user profile:**
And fror's thing of course ❤️ :
=> Added WoXArea.

Webtekno/dist/metadata.json, Webtekno/dist/presence.js, Webtekno/presence.ts
So now it can detects when you're viewing an author's profile. Also ~rewrote the code, it was awful.
=> Edited Webtekno a bit.

Hulu/dist/metadata.json, Hulu/dist/presence.js, Hulu/presence.ts
Completely rewrote the code for hulu. Works with the new UI. I may have missed something, so if you have any issues, report them to me.
=> 🔧 Patched Hulu

ITV Hub/dist/metadata.json, ITV Hub/dist/presence.js
=> Added show name to live TV

dizilab/dist/metadata.json, dizilab/dist/presence.js, dizilab/presence.ts
Basically, this:
Now looks like this:
Amazed? Use it >:)
=> dizilab now works with their forums!

Wish/dist/metadata.json, Wish/dist/presence.js
=> Wish Presence

Watchill/dist/metadata.json, Watchill/dist/presence.js, Watchill/presence.ts, Watchill/tsconfig.json
I never heard of this website before but it seems like it is very nice, the double subtitle option is hell of a feature (really nice), they have their own players _so that made things really easier_, it's fast and beautiful. Only bad reason is, it doesn't have that much users _yet_. This looks promising.
**Homepage:**
**Searching:**
**Movie page:**
**Show page:**
**Watching a show:**
**User profiles:**
This was requested in one of my other pull request's comment section by @Kritosna, thanks, I'll use this service now.
__And fror's thing:__
=> Added Watchill, another amazing Turkish service :^)

Echo Radio/dist/metadata.json, Echo Radio/dist/presence.js, Sway Radio/dist/metadata.json, Sway Radio/dist/presence.js
=> Sway Radio & Echo Radio

巴哈姆特/dist/metadata.json, 巴哈姆特/dist/presence.js, 巴哈姆特/presence.ts, 巴哈姆特/tsconfig.json
=> added bahamut presence

Bounce/dist/metadata.json, Bounce/dist/presence.js
=> Loading... (Bounce)

Proxim Radio/dist/metadata.json, Proxim Radio/dist/presence.js
=> Proxim Radio Presence Add

Fortnite-API/dist/metadata.json, Fortnite-API/dist/presence.js
Made a presence for: https://fortnite-api.com/
First presence so its 💩
=> Added fortnite-api presence

4gamers/dist/metadata.json, 4gamers/dist/presence.js, 4gamers/presence.ts, 4gamers/tsconfig.json
=> add 4gamers.com.tw

BBC iPlayer/dist/iframe.js, BBC iPlayer/dist/metadata.json, BBC iPlayer/dist/presence.js
closes https://github.com/PreMiD/Presences/issues/333
=> BBC iPlayer 

VirusTotal/dist/metadata.json, VirusTotal/dist/presence.js
=> VirusTotal Presence

Dominos Pizza/dist/metadata.json, Dominos Pizza/dist/presence.js
closes https://github.com/PreMiD/Presences/issues/638
=> Added Domino's Pizza presence

LucidChart/dist/metadata.json, LucidChart/dist/presence.js
closes https://github.com/PreMiD/Presences/issues/692
=> Added LucidChart presence

R10.net/dist/metadata.json, R10.net/dist/presence.js
One of the software development forums that I use often. I enjoy it.
**Index Page:**
**User Control Panel:**
**User Profile Page:**
Everything will be fine.....
=> Create R10.net Presence

HabboFests/dist/metadata.json, HabboFests/dist/presence.js
=> Habbofests Presence

Super Mangas/dist/metadata.json, Super Mangas/dist/presence.js, Super Mangas/presence.ts, Super Mangas/tsconfig.json
=> Added Super Mangas presence

BuzzFeed/dist/metadata.json
i have Forget to change The BuzzFeed News  URL in the BuzzFeed metadata, Sorry
=> Changing URL (i forget it **BuzzFeed**)

Lawcodev/dist/metadata.json, Lawcodev/dist/presence.js
I made another **presence!** (the 3rd) 🎉
=> New Presence for Lawcodev

CHIP Online/dist/metadata.json, CHIP Online/dist/presence.js
=> adding a CHIP Online Presence

BuzzFeed/dist/metadata.json
=> 🎉 API down

dizilab/dist/iframe.js, dizilab/dist/metadata.json, dizilab/iframe.ts
I hate vidmoly more than anytime now. Works now, I guess, don't recommend Vidmoly at all.
=> Fixed dizilab "somehow".

HackerNoon/dist/metadata.json, HackerNoon/dist/presence.js
Presence For HackerNoon Website
**Viewing User Profile:**
**Viewing Homepage:**
**Reading a Post:**
**Searching:**
**Viewing Any Tag:**
=> HackerNoon Presence

Bundle Haber/dist/metadata.json, Bundle Haber/dist/presence.js
=> adding a Bundle Haber Presence

JeuxVideo.com/dist/metadata.json, JeuxVideo.com/dist/presence.js, JeuxVideo.com/presence.ts, JeuxVideo.com/tsconfig.json
Presence for the major french board & news site about video games.
=> JeuxVideo.com Presence

Dream Animes/dist/metadata.json, Dream News/dist/metadata.json
Before someone asks why i changed the Dream Animes presence, @Eviu was the original creator of the presence and @Viruzaum contributed to update the presence, I asked permission from @Viruzaum if i can change that.
=> Dream's staff requested me the Dream News logo (+ changing/fixing stuff)

.github/ISSUE_TEMPLATE/service_request.md
just to prevent whitespaces, nothing new
=> minor update.

Tune Radio/metadata.json, Tune Radio/presence.js
**Tune Radio Presence**
I am requesting for my presence for "Tune Radio" to be added to the presence store.
**Screenshot of presence:**
=> Tune Radio

eggsy.codes/dist/metadata.json, eggsy.codes/dist/presence.js, eggsy.codes/presence.ts, eggsy.codes/tsconfig.json
You didn't see anything like this before >:) This is what you can do when you own the website, amirite?
**Homepage:**
**Projects page:**
**My overlay creator page:**
**PreMiD homepage:**
**Presence stats page:**
**Presence info page:**
**Metadata creator page:**
__And fror's thing:_
=> Added eggsy.codes with a shiny way!

Tatsumaki/dist/metadata.json, Tatsumaki/dist/presence.js
=> adding Tatsumaki presence

Dank Memer/dist/metadata.json, Dank Memer/dist/presence.js
=> adding Dank Memer presence

Discord Bot List/dist/metadata.json, Discord Bot List/dist/presence.js
=> adding Discord Bot List presence

ApertureBot/dist/metadata.json, ApertureBot/dist/presence.js, R10.net/dist/metadata.json, Türk Hack Team/dist/metadata.json, Türk Hack Team/dist/presence.js
**R10.net RPC:** Bugs and Category name fixed!
ApertureBot:
and
Turk Hack Team:
=> Update (R10.net) & Add Presence (ApertureBot + Türk Hack Team)

Groovy/dist/metadata.json, Groovy/dist/presence.js
=> adding groovy bot presence

Discord Bot List/dist/metadata.json, Discord Bot List/dist/presence.js
=> Updated Discord Bot List

5Mods/dist/metadata.json, 5Mods/dist/presence.js, 5Mods/presence.ts, 5Mods/tsconfig.json
Added Presence for 5Mods / https://www.gta5-mods.com/ (They call themselves 5Mods and thats also their logo)
This had been lying around on my hard drive for a few weks now already, but I just checked and it's still working.
=> Added 5Mods Presence

CodAre/dist/metadata.json, CodAre/dist/presence.js
=> adding CodAre presence

Kabal's/dist/metadata.json, Kabal's/dist/presence.js
=> adding Kabal's presence

Glynet/dist/metadata.json, Glynet/dist/presence.js
**Looking to the homepage**
**Looking to the music library**
**Listening to a song**
**Notifications**
**Explore**
**Settings**
**Looking to a profile**
**Reading an article**
=> Added Glynet, a social media network.

GeoGuessr/dist/metadata.json, GeoGuessr/dist/presence.js, GeoGuessr/presence.ts, GeoGuessr/tsconfig.json
This is a presence for GeoGuessr (https://www.geoguessr.com/https://geoguessr.com), a geography game where you got dropped somewhere in the world and you need to guess where you are. The main feature of this presence is it shows the current map that you are playing.
- This presence completes issue #636. (and I missed the deadline)
- The logo is modified based on the original `.svg` logo.
- There's only one map that you can test for free, which is [the different variation of the map "World"](https://geoguessr.com/maps/trial-world), but it works for all maps that is available on the site, ~~and you can test it by creating an account with a temporary email address~~.
| -- | -- |
| ![2019-12-15_22-06-20](https://user-images.githubusercontent.com/11584103/70924217-bf311 …
=> Add GeoGuessr presence

Altdentifier/dist/metadata.json, Altdentifier/dist/presence.js, Carl-bot/dist/metadata.json, Carl-bot/dist/presence.js
=> adding Altdentifier presence and a small fix on Carl-bot presence

TryHackMe/dist/metadata.json, TryHackMe/dist/presence.js, TryHackMe/presence.ts, TryHackMe/tsconfig.json
[TryHackMe](https://tryhackme.com) is a cyber security learning platform. Users complete rooms on security topics to further their knowledge and to earn points and compete on global leaderboards.
This version of the presence (1.0.0) supports the leaderboard, dashboard, room management pages and the rooms themsleves.
The Rich Presence image has been changed to the [following](https://i.imgur.com/nYQ4R2R.png), however the image was still cached upon screenshot creation.
Room
Dashboard
Leaderboard
Management
=> TryHackMe Presence Addition

Log.com.tr/dist/metadata.json, Log.com.tr/dist/presence.js
=> Added Log.com.tr, a technology blog.

Teknobuk/dist/metadata.json, Teknobuk/dist/presence.js
=> Added Teknobuk, a technology blog.

Flare Radio/dist/metadata.json, Flare Radio/dist/presence.js
=> flare update

Fortnite-API/dist/metadata.json, Fortnite-API/dist/presence.js
- added some missing pages & updated the clientId
- updated the logo and other metadata
=> Fortnite-API presence update

Jetanimes/dist/iframe.js, Jetanimes/dist/metadata.json, Jetanimes/dist/presence.js, Jetanimes/iframe.ts, Jetanimes/presence.ts, Jetanimes/tsconfig.json
so much ads and redirects that it becomes painful to even think about it.
closes #308
=> Added Jetanimes

OKanime/dist/iframe.js, OKanime/dist/metadata.json, OKanime/dist/presence.js, OKanime/iframe.ts, OKanime/presence.ts, OKanime/tsconfig.json
but it's actually just Jetanimes³ in disguise
closes #546
=> Added OKanime

HBO GO/dist/metadata.json
Hi,
As i had a problem to use our plugin to HBO GO in my country, I`ve add some international urls of this service.
=> Added international urls of HBO GO

Bounce/dist/metadata.json, Bounce/dist/presence.js
=> Fixed Error

Pinterest/dist/metadata.json
closes https://github.com/PreMiD/Presences/issues/846
=> Pinterest fix

DiscordLabs.org/dist/metadata.json, DiscordLabs.org/dist/presence.js
DiscordLabs.org `RPC`  Check our our amazing list of lab approved discord bots!
=> DiscordLabs.org

Twitch/dist/metadata.json, Twitch/dist/presence.js, Twitch/presence.ts
Fixed full-screen videos so it no longer displays the "Hosting" message.
Normal Video
Fullscreen Video
=> Patched Twitch

Kahve BOT/dist/metadata.json, Kahve BOT/dist/presence.js
=> KahveBOT Presence updated. (added timestamp, and fixed some bugs.)

Guilded.gg/dist/metadata.json, Guilded.gg/dist/presence.js
Guilded.gg `RPC` Guilded is the new standard in gaming team management. With Discord bots, Overwatch stats, Fortnite scrims, CS:GO team finder, Destiny 2 LFG, and more.
=> Guilded.gg

ChickenFM/dist/metadata.json, ChickenFM/dist/presence.js
=> Add ChickenFM

HentaiWorld/dist/iframe.js, HentaiWorld/dist/metadata.json, HentaiWorld/dist/presence.js, HentaiWorld/iframe.ts, HentaiWorld/presence.ts, HentaiWorld/tsconfig.json
Hello,
I send this request with added Presence to add HentaiWorld.eu to the Presence Shop. The site is not owned by me but I asked the owners if I would agree and they agreed to send the request. The HentaiWorld.eu site is an Anime +18 (Hentai) site in Sub-ITA or SUB-EN!
=> Presence Add | HentaiWorld.eu 

Trello/dist/metadata.json, Trello/dist/presence.js, Trello/presence.ts
=> Trello Recode

Guilded.gg/dist/metadata.json, Guilded.gg/dist/presence.js, enthix.net/dist/metadata.json, enthix.net/dist/presence.js
New Enthix `RPC` and Guilded.gg `RPC` Update
For Guilded.gg i added more directory and updated edit/create script
=> Guilded.gg Update and New RPC for enthix.net

9anime/dist/metadata.json, mvs4u/dist/metadata.json
=> fortnite scam

Paybutik/dist/metadata.json, Paybutik/dist/presence.js, Paybutik/presence.ts, Paybutik/tsconfig.json
=> ✌ Added Paybutik Presence

Telegram/dist/metadata.json, Telegram/dist/presence.js, Telegram/presence.ts, Telegram/tsconfig.json
=> 💬 Added Telegram Presence

Hangout Hotel/dist/metadata.json
=> 🏩 Hangout Hotel

TürkAnimeTV/dist/iframe.js, TürkAnimeTV/dist/metadata.json, TürkAnimeTV/dist/presence.js, TürkAnimeTV/iframe.ts, TürkAnimeTV/presence.ts, TürkAnimeTV/tsconfig.json
=> 👌 Added TürkAnimeTV Presence

Dora the Explorer/dist/metadata.json, Dora the Explorer/dist/presence.js
=> for eggsy ❤️

HentaiWorld/dist/metadata.json, MangaWorld/dist/metadata.json, MangaWorld/dist/presence.js, MangaWorld/presence.ts, MangaWorld/tsconfig.json
The site is not owned by me but I have already applied to the founders of MangaWorld for the creation and publication of the Presence!
The presence of HentaiWorld had an old Thumbnail and missing Tags, I created the presence and I proceeded to update the Metadata.
=> [ Presence Request ] Added Presence of MangaWorld and edited Metadata of HentaiWorld

discordtrlist.xyz/dist/metadata.json, discordtrlist.xyz/dist/presence.js
=> discordtrlist

HentaiWorld/dist/metadata.json, MangaWorld/dist/metadata.json, MangaWorld/dist/presence.js, MangaWorld/presence.ts
**The founders of the site asked me to modify the respective logos of the two sites.**
**And I added some new functions to MangaWorld's presence.**
_I was also wrong (grammatically) to insert tags in the MangaWorld presence._
_The HentaiWorld logo has a white part and a transparent background so I'm not sure see if it is seen 
with the white background of GitHub._
=> [ Update of Two Presences ] HentaiWorld Logo and MangaWorld Functions.

AnimeLab/dist/metadata.json, AnimeLab/dist/presence.js, AnimeLab/presence.ts
Closes https://github.com/PreMiD/Presences/issues/935
=> AnimeLab Fix

yabancıdizi/dist/metadata.json
=> they changed their url :crab:

Jellyfin/dist/metadata.json, Jellyfin/dist/presence.js
Add Jellyfin presence for both official site [jellyfin.org](https://jellyfin.org) and self hosted site (web client).
The official site presence if fully finished.
For the web client, movies and tv show type libraries have full support as well as any other web panels.
=> Add Jellyfin support, web client (movies/tv) and official website.

Express Radio/dist/metadata.json, Express Radio/dist/presence.js, HabboFests/dist/metadata.json, Plex/dist/metadata.json, PlutoTV/dist/metadata.json, Proxim Radio/dist/metadata.json, Uptimerobot/dist/metadata.json
Closes https://github.com/PreMiD/Presences/issues/957
=> Category fixes and a small radio added.

Canva/dist/metadata.json, Canva/dist/presence.js
**_Canva is a simplified graphic-design tool, founded in 2012. It uses a drag-and-drop format and provides access to photographs, vector images, graphics, and fonts._**
=> [ New Presence ] Uploaded new presence for Canva.com

Japari Library/dist/metadata.json, Japari Library/dist/presence.js, Japari Library/presence.ts, Japari Library/tsconfig.json
=> Japari Library presence

AnimeSaturn/dist/metadata.json, Google Calendar/dist/metadata.json, Google Calendar/dist/presence.js
Updated the Logo of Animesaturn: 
Added new presence for Google Calendar.
=> New presence for Google Calendar & new Logo for AnimeSaturn

Emby/dist/metadata.json, Emby/dist/presence.js, Jellyfin/dist/metadata.json, Jellyfin/dist/presence.js
Ok, this is gonna be a big one.
- When playing video media it's check the info of it to show the most appropiate presence (Movie, Tv-Show or LiveTV)
- Added presence for music playback and music libraries
- Implemented presence of LiveTV
- Code cleaning and some bug fixes
- New presence
- Supports both, the official site and the web client
- Display what are you playing on the web client: movies, tv-series, music.
- Display interactions with the web app, on home, on admin panel, browsing data of an item
=> Presence addition + Changes to existing presence

Animesoul/dist/metadata.json, Animesoul/dist/presence.js, Animesoul/presence.ts, Animesoul/tsconfg.json
Added Animesoul discord presence
=> Added Animesoul

Animesoul/dist/metadata.json
=> i commit ded

CONTRIBUTING.md
=> forget about it

QDSSClub/dist/metadata.json, QDSSClub/dist/presence.js
QDSSClub is a mix between a Blog and a Forum managed by YouTubers: Quei Due Sul Server.
=> 🔼 Added presence for QDSSClub

AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js
I removed a big error...
**_ERROR:_**
**_Solved:_**
=> 🔄 AnimeSaturn: Removed Big Error 😱 

UpBeatRadio/dist/metadata.json, UpBeatRadio/dist/presence.js, divinediscordbots/dist/metadata.json, divinediscordbots/dist/presence.js
`A small list of Discord bots for your servers`
And upbeat presence update as there are new tabs
=> Divine Discord Bot List

UpBeatRadio/dist/metadata.json, UpBeatRadio/dist/presence.js
=> Fully Recoded UpBeatRadio Presence + Owner Change as other one got banned and i fully recoded this one

osu!kawata/dist/metadata.json, osu!kawata/dist/presence.js, osu!kawata/presence.ts, osu!kawata/tsconfig.json
=> Added osu!kawata

DashNet/dist/metadata.json, DashNet/dist/presence.js
closes https://github.com/PreMiD/Presences/issues/1029
=> DashNet (Cookie Clicker)

Custom Status/dist/metadata.json, VLC/dist/metadata.json
=> Wow, links for two!

Manga Livre/dist/metadata.json, Manga Livre/dist/presence.js, Manga Livre/presence.ts
- .net instead of .com
- .trim() for categories
- and search by class name instead of jspath
=> Manga Livre fix

AnimeSaturn/dist/iframe.js, AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js, Simonektv/dist/metadata.json, Simonektv/dist/presence.js
**Added the presence for Simonektv**
**Added iFrame for AnimeSaturn Videos**
=> Added new Presence and added iFrame for AnimeSaturn

Bots on Discord/dist/metadata.json, Bots on Discord/dist/presence.js
=> adding Bots on Discord presence

CONTRIBUTING.md
I may have missed something, request changes if you see something I may have missed.
=> 🏗️ Guideline Revisions

AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js, HentaiWorld/dist/iframe.js, HentaiWorld/dist/metadata.json, HentaiWorld/dist/presence.js
**HentaiWorld Error Solved & Translated**
**HentaiWorld Error Solved**
**AnimeSaturn localStorage to document.cookie with an example of one Cookie**
=> 🔄 Update: AnimeSaturn( localStorage -> document.cookie ); HentaiWorld( Translated & Error Solved );

Super Hentais/dist/metadata.json, Super Hentais/dist/presence.js, Super Hentais/presence.ts, Super Hentais/tsconfig.json
Screenshots, presence working!
showing what you're seeing.
(i forgot to remove "lendo") 
it's a lot of pages, so i will only send these screenshots
=> add Super Hentais presence

Oglle/dist/metadata.json, Oglle/dist/presence.js
> New logo and thumbnail;
> Tidy English description;
> Problems showing some pages in the tidy presence.
=> 📝 [OGLLE.COM.BR] Presence Version 1.1

HentaiWorld/dist/iframe.js, HentaiWorld/dist/metadata.json, HentaiWorld/dist/presence.js, MangaWorld/dist/metadata.json, MangaWorld/dist/presence.js
=> 🔄 HentaiWorld ordered and errors fixed; MangaWorld ordered and updated presence.

Oglle/dist/metadata.json, Oglle/dist/presence.js
=> 🚀[OGLLE.COM.BR] Mega Update -  V1.2

Pulse/dist/metadata.json, Pulse/dist/presence.js
https://cdn.discordapp.com/attachments/630142339872194591/680164993177878532/unknown.png
=> Added Presence • Pulse 🎶

Bounce/dist/metadata.json, Bounce/dist/presence.js
=> Update Presence • Bounce 🎶

AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js
Ordered file structure and document.cookie error fixed. ( Error for ";")
Before:
After:
=> 🔄 Ordered file structure and function document.cookie error fixed.

discordbio/dist/metadata.json, discordbio/dist/presence.js
=> Discord.bio presence

Gitea/dist/metadata.json, Gitea/dist/presence.js, Gitea/presence.ts, Gitea/tsconfig.json
Added a Presence for the Gitea Website.
P.S. I didn't do a presence in a long time. While the code should work, I may have done something wrong in the metadata, so please check if you can find any errors.
=> Gitea Presence

taiga Bot/dist/metadata.json, taiga Bot/dist/presence.js, taiga Bot/presence.ts, taiga Bot/tsconfig.json
PreMiD Presence for the taiga Discord Bot.
This presence uses multiple Applications for different Displaynames in Presence, however all are used for Websites owned by the taiga Bot or of Sub-Projects which are made by taiga.
This has been tested a lot and has already been used in another Presence of mine before.
=> taiga Bot Presence

ListenOnRepeat/dist/iframe.js, ListenOnRepeat/dist/metadata.json, ListenOnRepeat/dist/presence.js, ListenOnRepeat/iframe.ts, ListenOnRepeat/presence.ts
=> ListenOnRepeat fix

Astr.io/dist/metadata.json, Astr.io/dist/presence.js, PreMiD/dist/metadata.json, PreMiD/dist/presence.js
=> Added status.premid.app & astr.io

AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js, Canva/dist/metadata.json, Canva/dist/presence.js, MangaWorld/dist/metadata.json, MangaWorld/dist/presence.js
=> 🔄 [ AnimeSaturn - Canva - MangaWorld ]Ordered the file structure & Fixed some Bugs & Added smallImageText

RootMe/dist/metadata.json, RootMe/dist/presence.js, RootMe/presence.ts, RootMe/tsconfig.json
I am publishing the first version of my Root Me presence. ✨
=> ✨First version of RootMe presence

MangasPROJECT/dist/metadata.json, MangasPROJECT/dist/presence.js, MangasPROJECT/presence.ts, MangasPROJECT/tsconfig.json
Presence working! (main page)
viewing a manga page
Reading
=> MangasPROJECT presence

Rythm/dist/metadata.json, Rythm/dist/presence.js
**What's the name of the service?**
Rythm
**What should the Presence display?**
Which page you're currently viewing (web dashboard will be added once it's accessible again).
**Why do you want support for this service?**
It's a very good music bot for Discord and usable for free.
**Are you able to provide an image for the service? (512x512 minimum)**
**What should the presence look like when active?**
=> ⭐ Added Rythm (Bot)

Astr.io/dist/metadata.json, Astr.io/dist/presence.js
Updating presence as per #1121
=> Update Presence • Astr.io

AniNews/dist/metadata.json, ResetEra/dist/metadata.json, ResetEra/dist/presence.js
- Well, they just changed the logo, nothing else.
=> Changing logo of AniNews and Adding ResetEra

Tsuki Mangás/dist/metadata.json, Tsuki Mangás/dist/presence.js
=> :sparkles: Adding Tsuki Mangás

Mangalib/dist/metadata.json, Mangalib/dist/presence.js
This presence is for website Mangalib. A popular site for reading manga in my region
UPDATED:
=> Mangalib presence

Defly.io/dist/metadata.json, Defly.io/dist/presence.js
---
Name: Defly.io Presence Creation
About: Pull request for adding Defly.io.
---
**Screenshots**
=> Defly.io Presence Creation

PyPi/dist/metadata.json, PyPi/dist/presence.js
=> Added the Python Package Index support

Photopea/dist/metadata.json, Photopea/dist/presence.js
=> Added Photopea support

DaFont/dist/metadata.json, DaFont/dist/presence.js, Photopea/dist/metadata.json, PyPi/dist/metadata.json, Repl.it/dist/metadata.json
=> Added DaFont support

Radio Garden/dist/metadata.json, Radio Garden/dist/presence.js
Proof of working presence. Includes radiostation name, location and listening time elapsed
=> New presence for Radio Garden

TVNZ OnDemand/dist/iframe.js, TVNZ OnDemand/dist/metadata.json, TVNZ OnDemand/dist/presence.js
=> Add TVNZ OnDemand Presence

AnimeSaturn/dist/iframe.js, AnimeSaturn/dist/metadata.json, AnimeSaturn/dist/presence.js
Added Movie & OVA recognition for resolve a bug.
=> 🔄 Update: Added Movie & OVA recognition

Carl-bot/dist/metadata.json, Carl-bot/dist/presence.js
This changes resolves error that the server name does not appear.
=> Updating Carl-bot presence

DownDetector/dist/metadata.json, DownDetector/dist/presence.js
=> Adding Downdetector presence

SimulatorFM/dist/metadata.json, SimulatorFM/dist/presence.js
This is the Fork for Simulator.FM
For more information contact me on Discord: HuckinB#0001
=> Add SimulatorFM to Store

osu!ripple/dist/metadata.json, osu!ripple/presence.ts
- Modified imgur link
- Fixed a bug, please check the changes, there are only two lines
=> Fix bugs in osu!ripple

GDBrowser/dist/metadata.json, GDBrowser/dist/presence.js
Presence for [GDBrowser](https://gdbrowser.com) written in JavaScript
Screenshots:
=> Added GDBrowser Presence

Sitting on Clouds Radio/dist/metadata.json, Sitting on Clouds Radio/dist/presence.js, Sitting on Clouds Radio/presence.ts, Sitting on Clouds Radio/tsconfig.json
Someone in another Discord server saw I had presences on PreMiD and begged me to make one for this site so here we are 😅
=> Add Sitting on Clouds Radio

discordbio/dist/metadata.json, discordbio/dist/presence.js
At first... The presence was not shown. I think the reason is the "www" part.
And I removed some spelling mistakes.
=> Fix Discord.Bio

MangaWorld/dist/metadata.json, MangaWorld/dist/presence.js
=> 🔄 Update: Removed "scan ITA" from manga name.

Mixcloud/dist/metadata.json
According to the change of brand logo.
=> Update Mixcloud Metadata

Yarn/dist/metadata.json, Yarn/dist/presence.js, Yarn/presence.ts, Yarn/tsconfig.json
=> First version of Yarn presence

DownDetector/dist/metadata.json, DownDetector/dist/presence.js
=> Decoding some strings

FIFA Web App/dist/metadata.json, FIFA Web App/dist/presence.js, FIFA Web App/presence.ts, FIFA Web App/tsconfig.json
=> FIFA Web App

Spotify Podcasts/dist/metadata.json, Spotify Podcasts/dist/presence.js, Spotify Podcasts/presence.ts
=> Spotify fix

Nuxt.js/dist/metadata.json, Nuxt.js/dist/presence.js, Nuxt.js/presence.ts, Nuxt.js/tsconfig.json
=> 🔰First version of Nuxt.js presence🔰

DuckDuckGo/dist/metadata.json, DuckDuckGo/dist/presence.js
=> Add DuckDuckGo presence

Anime Music Quiz/dist/metadata.json, Anime Music Quiz/dist/presence.js
=> 🔼 New Presence: Anime Music Quiz [ animemusicquiz.com ]

Stuff/dist/metadata.json, Stuff/dist/presence.js
=> Add Stuff.co.nz presence

ThreeNow/dist/iframe.js, ThreeNow/dist/metadata.json, ThreeNow/dist/presence.js
=> Add ThreeNow presence

Bing/dist/metadata.json, Bing/dist/presence.js
=> Add bing presence

Electron/dist/metadata.json, Electron/dist/presence.js, Electron/presence.ts, Electron/tsconfig.json, Koya/dist/metadata.json, Koya/dist/presence.js, Koya/presence.ts, Koya/tsconfig.json
=> 🚀First version of Koya presence🚀

Senpa.io/dist/metadata.json, Senpa.io/dist/presence.js, Senpa.io/presence.ts, Senpa.io/tsconfig.json
=> 🚀Add Senpa.io presence🚀

Rádio Animu/dist/metadata.json
=> mother 3 for the nintendo 3ds

Emojipedia/dist/metadata.json, Emojipedia/dist/presence.js
=> Add emojipedia presence

TruckersFM/dist/metadata.json
- Updated Artwork
- Updated Description
- Updated Colour
- Updated ags
=> Update TruckersFM Presence

AnimeWorld/dist/iframe.js, AnimeWorld/dist/metadata.json, AnimeWorld/dist/presence.js, AnimeWorld/iframe.ts, AnimeWorld/presence.ts
The presence was inaccurate, I asked the creator, Bas950, if I could modify it and he gave me consent and also a great help. Thank you Bro ❤ . Presence, I think, is PreMiD's **coolest** presence.
New Thumbnail:
=> 🔁 𝙐𝙥𝙙𝙖𝙩𝙚：AnimeWorld.tv big presence Update！

Disney+/dist/metadata.json
This should hopefully fix the presence not working for some people.
=> Disney+: use regex for url matching

CurveFM/dist/metadata.json, CurveFM/dist/presence.js
(cant see large image because discord dev portal is being annoying, and takes years to add it, then adds like 10 of the same image under the same now, then wont let u remove anything so ye...)
=> New Presence • CurveFM

Bounce/dist/metadata.json, Bounce/dist/presence.js
=> Revert "rip bounce"

Custom Status/dist/metadata.json, Custom Status/dist/presence.js
Page will be able to detect if presence is added or not.
=> 📝 Update Custom Status

CONTRIBUTING.md
- Implemented the new guidelines suggested.
- Accented some key words.
- Added a note for media keys.
=> 🚧 Guideline Revisions

CONTRIBUTING.md
=> 🚧 Guideline Revisions 2

.vscode/settings.json, WIMS/dist/metadata.json, WIMS/dist/presence.js, WIMS/presence.ts, WIMS/tsconfig.json
The presence still is an absolute mess, but it works. I might update it in the coming weeks/months.
=> Fixed the issues with the WIMS presence

I Love Music/dist/metadata.json, I Love Music/dist/presence.js, s.to/dist/metadata.json, s.to/dist/presence.js
> Removed iFrame
> Removed "board.s.to"
=> v1.5.2 s.to

I Love Music/dist/metadata.json, I Love Music/dist/presence.js
=> v1.2.1 I Love Music

VidCloud9/dist/iframe.js, VidCloud9/dist/metadata.json, VidCloud9/dist/presence.js, Vidstreaming/.gitattributes, Vidstreaming/dist/iframe.js, Vidstreaming/dist/metadata.json, Vidstreaming/dist/presence.js
Presences for both sites are stable and working.
**VidCloud9:**
**Vidstreaming:**
=> Vidstreaming.io and VidCloud9.com

VUDU/dist/metadata.json, VUDU/dist/presence.js
This presence is made for https://www.vudu.com/
It'll create a rich presence for whenever a user is watching a movie on VUDU.
=> Add presence for VUDU

RemDB/dist/metadata.json, RemDB/dist/presence.js
RemDB is a Player- and Clandatabase from a private server (S4 Remnants) of the game S4 League.
A quick preview can be found here: [Preview](https://kevin.s-ul.eu/nmTxxdWN.mp4)
=> Adding 'RemDB' presence.

RemDB/dist/metadata.json
I entered a wrong User ID in the metadata.
=> Fixed wrong User ID.

Tsuki Mangás/dist/metadata.json, Tsuki Mangás/dist/presence.js
- _Place of the chapter changed to avoid big names_
- _New presence while editing the profile(a small error spam was avoided)_
- _New presence to inform which gender have been selected on the list_
- _Fixed "Página true", now it informs that the page is open_
=> Fixed and New features

Overbuff/dist/metadata.json, Overbuff/dist/presence.js
• See what role you are watching at (Support, Tank, Offense, Defense)
• See what role ranking you are watching at
• Added missing pages
• Full player profile support (Overview, Heroes, Records, Trends, Activity)
• Cleanups
=> Overbuff update.

Instant-Gaming/dist/metadata.json, Instant-Gaming/dist/presence.js
Website: [Instant Gaming](https://www.instant-gaming.com/en/)
Preview of the presence: [Preview](https://kevin.s-ul.eu/BUYrGkQk.mp4)
There isn't really much code in it since the website works a little different because it uses different URLs for each language.
The most important stuff, see what product you are looking at, is working on every language.
When viewing a product, it will always show the platform it is for, the product's title and the product's price.
I'd take any suggestions related to the website that also could be added without any problems.
So far only user profiles and products are working.
=> Instant Gaming support.

RunoPW/dist/metadata.json, RunoPW/dist/presence.js
Update metadata.js and presence.js
=> Update metadata.js and presence.js

VirusTotal/dist/metadata.json, VirusTotal/dist/presence.js
I recoded VirusTotal again. Now it should work better and the code look better organized.
=> v1.3 VirusTotal

VirusTotal/dist/metadata.json, VirusTotal/dist/presence.js
*beep boop* I've prettified and refactored some Presences...
=> 🤖 Daily QA

MangaYabu/dist/metadata.json, MangaYabu/dist/presence.js
=> Add MangaYabu! presence

Rooster Teeth/dist/metadata.json, Rooster Teeth/dist/presence.js
closes https://github.com/PreMiD/Presences/issues/644
=> New Presence: Rooster Teeth

Honeygain/dist/metadata.json, Honeygain/dist/presence.js
=> New Presence: Honeygain

SiriusXM/dist/metadata.json, SiriusXM/dist/presence.js
=> New Presence: SiriusXM

PartydoosMediaGroup/dist/metadata.json
description: servies > services
=> Fixed Spelling Mistake

SimulatorFM/dist/metadata.json, SimulatorFM/dist/presence.js
=> Rescuing SimulatorFM

Emby/dist/metadata.json, Emby/dist/presence.js
Updated url paths and fixed presence
=> Update for Emby presence

Club Penguin Rewritten/dist/metadata.json, Club Penguin Rewritten/dist/presence.js
=> Revert "Update "Club Penguin Rewritten" to 3.0.0"

Complex Radio/dist/metadata.json, Complex Radio/dist/presence.js, Complex Radio/presence.ts, Complex Radio/tsconfig.json
=> Complex Radio

Dream Animes/dist/metadata.json, Dream Animes/dist/presence.js
=> Video Type fix (OVA/Especial)

Championgg/dist/metadata.json, Championgg/dist/presence.js, Championgg/presence.ts, Championgg/tsconfig.json
=> New presence: Champion.gg

Monos Chinos/dist/iframe.js, Monos Chinos/dist/metadata.json, Monos Chinos/dist/presence.js, Monos Chinos/iframe.ts, Monos Chinos/presence.ts, Monos Chinos/tsconfig.json
=> New Presence: Monos Chinos

Apple/dist/metadata.json, Apple/dist/presence.js, Apple/presence.ts, Apple/tsconfig.json
A presence for Apple's Website
=> New Presence: Apple

Emby/dist/metadata.json, Jellyfin/dist/metadata.json
Changed format of regExp fields on the Jellyfin and Emby presences.
=> Changed regExp format, ticket #01205

websites/G/GitLab/dist/metadata.json, websites/G/GitLab/presence.ts, websites/G/GitLab/tsconfig.json
=> GitLab Presence

websites/J/Jackbox/dist/metadata.json, websites/J/Jackbox/presence.ts
As standard, the screenshots
Username off
Timestamp off
=> Jackbox - Presence Settings

websites/M/Mixer/dist/metadata.json, websites/M/Mixer/presence.ts, websites/S/SoundCloud/dist/metadata.json, websites/S/SoundCloud/presence.ts
Did not include screenshots for SoundCloud as it did not affect anything visually. Only modified the queries and other things.
**Mixer**:
=> Optimized SoundCloud and Rewrote Mixer

websites/B/bilibili/dist/metadata.json, websites/B/bilibili/presence.ts
=> ⬆️ Updates and fix bilibili

websites/D/Dizilla/dist/metadata.json, websites/D/Dizilla/iframe.ts, websites/D/Dizilla/presence.ts, websites/D/Dizilla/tsconfig.json
it works. me pro code.
damn
good show (ily carla <333)
this closes #1426 and closed #1571 already :star:
=> :star: Dizilla, most requested service ever!!!

websites/A/Animes House/dist/metadata.json, websites/A/Animes House/iframe.ts, websites/A/Animes House/presence.ts, websites/C/Comic Space/dist/metadata.json, websites/C/Comic Space/presence.ts, websites/G/GitLab/dist/metadata.json, websites/G/GitLab/presence.ts, websites/H/Horizon GO/dist/metadata.json, websites/H/Horizon GO/presence.ts, websites/J/Jackbox/dist/metadata.json, websites/J/Jackbox/presence.ts, websites/M/MangaYabu/dist/metadata.json, websites/M/MangaYabu/presence.ts, websites/M/Meus Animes/dist/metadata.json, websites/M/Meus Animes/presence.ts, websites/M/MusicCast/dist/metadata.json, websites/M/MusicCast/presence.ts, websites/N/Nakama Mangas/dist/metadata.json, websites/N/Nakama Mangas/presence.ts, websites/P/Peloton/dist/metadata.json, websites/P/Peloton/presence.ts, websites/S/Streamlabs/dist/metadata.json, websites/S/Streamlabs/presence.ts
*beep boop* I've prettified and refactored some Presences...
=> 🤖 Semi-weekly SE

websites/S/SteamPrices.com/dist/metadata.json, websites/S/SteamPrices.com/presence.ts, websites/S/SteamPrices.com/tsconfig.json
Add support for a Steam game price comparison website.
Pictures of it working:
=> Add Support for SteamPrices.com

websites/A/Apple Music/dist/metadata.json, websites/A/Apple Music/presence.ts
Updated website element locations to fix the Apple Music presence.
=> [Apple Music] Fixed Element Locations

.github/CODEOWNERS, .github/workflows/SV.yml, schemaValidator.ts
Added a couple adjustments to the script
=> Schema Validation Adjustments

websites/O/osu!Kurikku/dist/metadata.json, websites/O/osu!Kurikku/presence.ts, websites/O/osu!Kurikku/tsconfig.json
Yes, the Kurikku's owner wants to join the partner, but PreMiD does not accept new partners rn, so I made this simple presence for them.
=> Add osu!Kurikku

websites/T/Tsuki Mangás/dist/metadata.json, websites/T/Tsuki Mangás/presence.ts
> some people didn't like the last update, so let's make it optional
_yes the rp is lag because my pc is garbage_
<details> 
<summary></b>History Info</summary>
</details>
<details> 
<summary></b>Dark Resources and Logo Switch</summary>
</details>
<details> 
<summary></b>Reset timestamp in every presence update</summary>
</details>
<details> 
<summary></b>Show Comment and Report</summary>
</details>
<details> 
<summary></b>Hide Username in /perfil and in the smallImageText of history</summary>
</details>
_press O to big ooF_
=> Tsuki Mangás - Update again, new stuff etc.

websites/D/Durarara/dist/metadata.json, websites/D/Durarara/presence.ts, websites/D/Durarara/tsconfig.json
=> Drrr.com | Durarara!! Chat Presence

websites/#/网易云音乐/dist/metadata.json, websites/#/网易云音乐/presence.ts, websites/#/网易云音乐/tsconfig.json
=> Add 网易云音乐 (NetEaseCloud Music)

websites/S/Sparknotes/dist/metadata.json, websites/S/Sparknotes/presence.ts, websites/S/Sparknotes/tsconfig.json
=> Sparknotes Created

websites/R/Radio Nintendo/dist/metadata.json, websites/R/Radio Nintendo/presence.ts, websites/R/Radio Nintendo/tsconfig.json, websites/W/wikiHow/presence.ts
=> Add radio nintendo presence

.github/workflows/SV.yml
* diff-tree commit seems to be broken for PRs but fine for direct pushes
* using the changed-files action works for PRs only
=> Update SV workflow

.github/workflows/SV.yml
GitHub wants me to merge it with yours for some reason, please accept
=> Might as well fix this w/ your patch

websites/A/Anihub/dist/metadata.json, websites/A/Anihub/presence.ts, websites/A/Anihub/tsconfig.json
- 🔄 [[DreamAnimes](https://github.com/PreMiD/Presences/tree/master/websites/D/Dream%20Animes) now is [Anihub](https://github.com/PreMiD/Presences/tree/master/websites/A/Anihub)]
> **Presence's Proofs**
<details>
<summary><b>/login</b> <i>(click to expand)</i></summary>
</details>
<details>
<summary><b>/registro</b> <i>(click to expand)</i></summary>
</details>
<details>
<summary><b>/</b> <i>(click to expand)</i></summary>
</details>
<details>
<summary><b>/videos</b> <i>(click to expand)</i></summary>
_Playback paused_ | _Playing back_ | Comment <br> _any character on textarea active it_ | _Report_
-|-|-|-
</details>
<details>
<summary><b>/anime</b> <i>(click to expand)</i></summary>
</details>
<details>
<summary><b>/animes</b> <i>(click to expand)</i></summary>
</details>
<details> …
=> 💠 Anihub: New Presence

websites/W/WebSDR/dist/metadata.json, websites/W/WebSDR/presence.ts, websites/W/WebSDR/tsconfig.json
[Link to the site](http://websdr.ewi.utwente.nl:8901)
This is my first presence so I am very open to criticism.
=> Add presence for UTwente's WebSDR

websites/O/osu!online/dist/metadata.json, websites/O/osu!online/presence.ts, websites/O/osu!online/tsconfig.json
=> Add osu!online

websites/A/AI Dungeon/dist/metadata.json, websites/A/AI Dungeon/presence.ts, websites/A/AI Dungeon/tsconfig.json
Now includes (Base site):
[![Image from Gyazo](https://i.gyazo.com/d37868517d08751a4f60d77aa00f83e3.gif)](https://gyazo.com/d37868517d08751a4f60d77aa00f83e3)
--------------------------------------------------------------------------------------------------------------
Main site aidungeon.io is now fixed thanks to Bas.
=> AI Dungeon Release

websites/A/Animelizm/dist/metadata.json, websites/A/Animelizm/iframe.ts, websites/A/Animelizm/presence.ts, websites/A/Animelizm/tsconfig.json
=> Add Animelizm.com presence

websites/O/Outline/dist/metadata.json, websites/O/Outline/presence.ts, websites/O/Outline/tsconfig.json
Alright. Here's a simple one. This website strips all the clutter from news articles. That's it for the preword.
*(confidential fields has been censored)*
| Image                                                                                                                        | Link visited                     |
| ---------------------------------------------------------------------------------------------------------------------------- | -------------------------------- |
| ![2020-05-29_11-15-39](https://user-images.githubusercontent.com/11584103/83225308-afd8fe00-a1a9-11ea-9dcb-47cf28ad527b.png) | https://outline.com/             |
| ![2020-05-29_12-38-20](https://user-images.githubusercontent.com/11584103/83225313-b2d3ee80-a1a9-11ea-83c2-944beee48dd1.png) | …
=> Add Outline presence

websites/H/Hulu/dist/metadata.json, websites/H/Hulu/presence.ts
=> Hulu fixes

websites/S/SnowBoltz/dist/metadata.json, websites/S/SnowBoltz/presence.ts
All work fine for me other people someone work someone not i hope this update is last bugs fix everything look same just fix the bugs and rewrite it all
[+] Fixed on show only Icon 
[+] Add more on admin page
=> SnowBoltz Fixed

websites/G/Google Meet/dist/metadata.json, websites/G/Google Meet/presence.ts
Now the presence shows how many people are in the room.
=> Google Meet Updates

websites/D/Dizipub/dist/metadata.json, websites/D/Dizipub/presence.ts, websites/D/Dizipub/tsconfig.json, websites/W/WoxeBot/dist/metadata.json, websites/W/WoxeBot/presence.ts, websites/W/WoxeBot/tsconfig.json
See the actual request here: https://github.com/PreMiD/Presences/pull/1660
=> adding Dizipub & WoxeBot presence | Re-opened due to an error in pull#1660

websites/J/Jisho/dist/metadata.json, websites/J/Jisho/presence.ts, websites/J/Jisho/tsconfig.json
=> Add presence for Jisho.org

websites/N/Nookazon/dist/metadata.json, websites/N/Nookazon/presence.ts, websites/N/Nookazon/tsconfig.json
Uh... Adds Nookazon. I also use a switch statement this time. :D
=> Add "Nookazon"

websites/J/Jellyfin/dist/metadata.json, websites/J/Jellyfin/presence.ts
Warning was showing up on the console telling that setInterval was taken X ms under devHelper. This time was increasing over time with no limit making the ui unresponsive.
Proves of the presence working after the changes:
=> Bugfix: setInterval increasing over time with no limit

.github/CONTRIBUTING.md, .prettierignore
- Removed extra spaces between parenthesis.
- Added missing words.
- Removed prettier new lines.
=> Guideline Updates

websites/H/Hangout Hotel/dist/metadata.json
New domain added, category changed to games as it should have been that already (st00pid me)
=> Update metadata.json - Hangout Hotel

websites/G/Garden/dist/metadata.json, websites/G/Garden/presence.ts, websites/G/Garden/tsconfig.json
Here are some screenshots to show you how it works
<a href="https://zupimages.net/viewer.php?id=20/23/2pqv.png"><img src="https://zupimages.net/up/20/23/2pqv.png" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=20/23/5rg9.png"><img src="https://zupimages.net/up/20/23/5rg9.png" alt="" /></a>
=> Add Garden presence

websites/M/MSPFA/dist/metadata.json, websites/M/MSPFA/presence.ts, websites/M/MSPFA/tsconfig.json
This is my first time contributing to open-source software, so I'm not exactly sure what I should add. Attached you'll find 2 screenshots that I hope are enough proof it works. ![Homepage](https://i.imgur.com/h1KYQa8.png) ![In an adventure](https://i.imgur.com/wuRMcXa.png)
=> Add MSPFA presence

websites/S/StatusBot/dist/metadata.json, websites/S/StatusBot/presence.ts, websites/S/StatusBot/tsconfig.json
Applying the StatutBot presence for verification.
=> Added StatusBot Presence

websites/Q/Qwant/dist/metadata.json, websites/Q/Qwant/presence.ts, websites/Q/Qwant/tsconfig.json
[Qwant](https://www.qwant.com/) is a search engine that respects your privacy and eases discovering and sharing via a social approach. (This also includes [Qwant Junior](https://www.qwantjunior.com/))
closes #1621 
<details>
</details>
<details>
<summary>Screenshots (Qwant Junior)</summary>
</details>
=> Add Qwant Presence

websites/D/Discord.js/dist/metadata.json, websites/D/Discord.js/presence.ts, websites/M/MyBOT/dist/metadata.json, websites/M/MyBOT/presence.ts
Discord.js had a little something bad and I fixed that (the smallImageText didn't change in the UpdateData event).
MyBOT presence was outdated and I made it from scratch.
I also added Spanish translations for both
=> Edited MyBOT and D.js presences

websites/G/Garden/dist/metadata.json, websites/G/Garden/presence.ts
Update of the description and support of the "creations" section of the forum with the new fork
<a href="https://imgur.com/X3PzoT6"><img src="https://i.imgur.com/X3PzoT6.png" title="source: imgur.com" /></a>
=> Garden presence update

websites/T/TrickSplit.io/dist/metadata.json, websites/T/TrickSplit.io/iframe.ts, websites/T/TrickSplit.io/presence.ts, websites/T/TrickSplit.io/tsconfig.json
[Tricksplit.io](https://Tricksplit.io) is an alternative Agar.io website/server, with different modes, skins, etc.
closes #1678
<details>
</details>
=> Add Tricksplit.io Presence

websites/G/Gitbook/dist/metadata.json, websites/G/Gitbook/presence.ts, websites/G/Gitbook/tsconfig.json
[Gitbook](https://www.gitbook.com/) is a website where you can create and host documentation for various things.
closes #1600
<details>
</details>
=> Add Gitbook Presence

websites/0-9/20XX/dist/metadata.json, websites/0-9/20XX/iframe.ts, websites/0-9/20XX/presence.ts, websites/0-9/20XX/tsconfig.json
[20XX](https://20xx.io) is a unique platform MOBA created by InfernoPlus which includes a variety of characters and maps to play on.
<details>
</details>
=> Add 20XX Presence

websites/A/Anime-Sugoi/dist/metadata.json, websites/A/Anime-Sugoi/presence.ts
[+] Playing Status
[+] Unknow Page bugs fixed
[+] Edit on title cannot find
=> Anime-Sugoi Update

websites/D/Discord Templates/dist/metadata.json, websites/D/Discord Templates/presence.ts, websites/D/Discord Templates/tsconfig.json, websites/D/Dizilla/dist/metadata.json, websites/D/Dizilla/iframe.ts
🔗 **Partner Presence!**
Discord Server Templates is where you can easily find templates for your Discord server. Templates are free and everyone can easily add their own templates! You can also get upvotes for your templates and become the **most** votes templates and get on our [top templates](https://discordtemplates.com/templates/top) page! Visit our website [here](https://discordtemplates.com).
Here are some examples:
[Twitter](https://twitter.com/dctemplates) - [Team](https://discordtemplates.com/about#team) - [Discord Server](https://discordtemplates.com/redirect/discord)
🚧 PS: Our website is still in development/public testing. We've tried our best to outcome with a stable website but expect some bugs, issues and problems at this point. We'll try our best to provide you a stable …
=> :star: Discord Templates presence!

websites/A/Agar.io/dist/metadata.json, websites/A/Agar.io/iframe.ts, websites/A/Agar.io/presence.ts, websites/A/Agar.io/tsconfig.json
[Agar.io](https://agar.io/) - The smash hit game! Control your cell and eat other players to grow larger! Play with millions of players around the world and try to become the biggest cell of all!
closes #947
<details>
</details>
=> Add Agar.io Presence

websites/Q/Quizlet/dist/metadata.json, websites/Q/Quizlet/iframe.ts, websites/Q/Quizlet/presence.ts, websites/Q/Quizlet/tsconfig.json
[Quizlet](https://quizlet.com/) makes simple learning tools that let you study anything. Start learning today with flashcards, games and learning tools — all for free.
closes #1014
<details>
</details>
=> Add Quizlet Presence

websites/L/LeetCode/dist/metadata.json, websites/L/LeetCode/presence.ts, websites/L/LeetCode/tsconfig.json
[Leetcode](https://www.leetcode.com) is a website to help software developers to ace their technical interviews.
<details>
<br>
<br/>
<br/>
<br/>
<br/>
</details>
=> Add LeetCode presence

websites/S/Senpa.io/dist/metadata.json
=> ⏫Update Presence Icon⏫

websites/A/Anime-Sugoi/dist/metadata.json, websites/A/Anime-Sugoi/iframe.ts, websites/A/Anime-Sugoi/presence.ts
=> Anime-Sugoi | Update

websites/L/Loritta/dist/metadata.json, websites/L/Loritta/presence.ts, websites/L/Loritta/tsconfig.json
Loritta is a Discord bot for utility, fun, entertainment, moderation and more.
<details>
<summary>Screenshot</summary>
</details>
=> Add Loritta Presence.

websites/C/Club Penguin Rewritten/dist/metadata.json, websites/C/Club Penguin Rewritten/presence.ts
=> Add music jam rooms (Club Penguin Rewritten v4.1.0)

websites/A/Apple Music/dist/metadata.json, websites/A/Apple Music/presence.ts
Updated website element locations to fix the Apple Music presence a second time.
=> [Apple Music] Fixed Element Locations (2)

websites/S/Spiderum/dist/metadata.json, websites/S/Spiderum/presence.ts, websites/S/Spiderum/tsconfig.json
=> add spiderum presence v1.0.0

websites/T/taiga Bot/dist/metadata.json, websites/T/taiga Bot/presence.ts
This Updated the taiga Presence for the new Website and removed some old URLs that are not used anymore.
(French and Dutch Descriptions were provided by the taiga Translation Team)
=> Updated taiga Presence

websites/S/SnowBoltz/dist/metadata.json, websites/S/SnowBoltz/presence.ts
[+] Update Domain docs, shop
[+] Edite unknow page
=> SnowBoltz | Update

websites/0-9/20XX.info/dist/metadata.json, websites/0-9/20XX.info/iframe.ts, websites/0-9/20XX.info/presence.ts, websites/0-9/20XX.info/tsconfig.json
[20XX.info](https://20xx.info) is a website that tracks stats in 20XX.io.
<details>
</details>
=> Add 20XX.info presence

websites/I/Instagram/dist/metadata.json, websites/I/Instagram/presence.ts
A lot has changed since I did my last PR, so I hope everything is correct.
This PR removed the Placeholder "NAME-HERE" when viewing a Post which was accidentally pushed and adds Support for Direct Messages which were recently introduced to the Instagram Website.
=> Updated Instagram

websites/T/Taco/dist/metadata.json, websites/T/Taco/presence.ts, websites/T/Taco/tsconfig.json
[Taco ](https://tacobot.app/) is a discord bot that manages Trello boards and notifies users of board updates.
<details>
</details>
=> Add Taco Presence

websites/D/DeviantArt/dist/metadata.json, websites/D/DeviantArt/presence.ts, websites/F/Fandom/dist/metadata.json, websites/F/Fandom/presence.ts, websites/G/Gamepedia/dist/metadata.json, websites/G/Gamepedia/presence.ts, websites/G/GeoGuessr/dist/metadata.json, websites/G/GeoGuessr/presence.ts, websites/O/Outline/dist/metadata.json, websites/O/Outline/presence.ts, websites/T/Typeracer/dist/metadata.json, websites/T/Typeracer/presence.ts
This update contains minor changes to some of my presences, if you don't mind.
This PR includes updates to the following presences:
- DeviantArt (1.1.6)
- Fandom (1.1.6)
- Gamepedia (1.1.9)
- GeoGuessr (1.2.4)
- Outline (1.0.1)
- Typeracer (1.1.6)
- Change `var` variables to `const` and `let` because of the `no-var` rule
- Change `presenceData` interface to `PresenceData` (Outline)
- Add additional tags (Fandom, Gamepedia)
- Add schema to `presence.json`
- Update regex (Fandom, Gamepedia)
- Update string for the home page/index (GeoGuessr)
| ![Discord_2020-06-17_21-39-30](https://user-images.githubusercontent.com/11584103/84915150-a840b100-b0e6-11ea-8e12-4ce8d453726d.png) | https://www.deviantart.com/
| …
=> Update multiple presences (17/06/2020)

websites/T/TrackMania Exchange/dist/metadata.json, websites/T/TrackMania Exchange/presence.ts, websites/T/TrackMania Exchange/tsconfig.json
This is the presence for TrackMania Exchange, also known as TMX and TM-Exchange (https://tm-exchange.com), which is a website to share tracks from the TrackMania game series. As requested, this presence shows the track info for the tracks, and also most, if not all, pages on the network.
This PR resolves #998.
- I have tried my best to upscale the logo manually (except the TMX logo, it's already 1024x). You can see the logos here. If you can make a better version out of it, be my guest and contact me.
- I probably going to do [ManiaExchange](https://mania.exchange/) after this. Even If I'm making one, I don't know if I should merge this presence to ManiaExchange because the portal also includes TMX on it.
| Image …
=> Add TrackMania Exchange presence

websites/O/Online Soccer Manager/dist/metadata.json, websites/O/Online Soccer Manager/presence.ts
=> Online Soccer Manager | Update to 1.1.0

websites/N/Neox Scanlator/dist/metadata.json, websites/N/Neox Scanlator/presence.ts
=> Fix presence (Neox Scanlator)

websites/A/AnimeFLV/dist/metadata.json, websites/A/AnimeFLV/iframe.ts, websites/A/AnimeFLV/presence.ts
Added myself as a contributor since the author isn't even on the discord server afaik
From permanent: 
To:
=> AnimeFLV fix

websites/S/Super Mangás/dist/metadata.json, websites/S/Super Mangás/presence.ts, websites/S/Super Mangás/tsconfig.json
=> New Presence (Super Mangas)

websites/W/WhatsApp/dist/metadata.json, websites/W/WhatsApp/presence.ts
Updated the names of some div classes so the presence can work again
=> WhatsApp Fix

websites/K/Kael/dist/metadata.json, websites/K/Kael/presence.ts, websites/K/Kael/tsconfig.json
=> Kael Bot Presence (kaelbot.xyz)

websites/T/Tatsumaki/dist/metadata.json, websites/T/Tatsumaki/presence.ts
=> [Update] Tatsumaki Presence

websites/B/Bounce/dist/metadata.json, websites/B/Bounce/presence.ts
=> Bounce | Coming soon to a speaker near you!

websites/B/Bounce/dist/metadata.json, websites/B/Bounce/presence.ts
Fixes Invalid JSON response setting values as undefined as seen below.
=> Issue's fixed

websites/K/KeyFM/dist/metadata.json, websites/K/KeyFM/presence.ts, websites/K/KeyFM/tsconfig.json
=> Added KeyFM

websites/T/Twitch/dist/metadata.json, websites/T/Twitch/presence.ts
Twitch has been completely rewritten to support the new channel update.
**Stream**:
**Profile**:
For Twitch presence users, if you find a page that shows this:
Contact me on the PreMiD Discord server with the page URL, and I will add it.
=> Twitch Rewrite

websites/F/Formuliser/dist/metadata.json, websites/F/Formuliser/presence.ts, websites/F/Formuliser/tsconfig.json
Adds presence for https://formuliser.oojmed.com
=> Add Formuliser presence

websites/B/Bloxcast/dist/metadata.json, websites/B/Bloxcast/presence.ts
=> Change state and details of Bloxcast Presence

.github/CONTRIBUTING.md
Upon merging this pull request, the following will be enforced in the presence review process:
- Presences must not be in all caps.
- Presence authors must publish screenshots of the settings in the extension as seen [here](https://imgur.com/a/OD3sj5R) along with proof that the presence is functional.
=> New Setting Guidelines

websites/F/FairyAnime/dist/metadata.json, websites/F/FairyAnime/iframe.ts, websites/F/FairyAnime/presence.ts, websites/F/FairyAnime/tsconfig.json, websites/S/SnowBoltz/dist/metadata.json, websites/S/SnowBoltz/presence.ts
On browsing
On anime select 
On watching
Note: The logo is too big so I have cut it down and go like that I don't have the other logo for this website
=> Added | Fairyanime

websites/0-9/4anime/dist/metadata.json
=> [4anime] Bump to version 1.5.9

websites/A/AnimeSaturn/dist/metadata.json, websites/A/AnimeSaturn/presence.ts
=> 🔁 Updated WebSite. AnimeSaturn

websites/G/Glenn Bot List/dist/metadata.json, websites/G/Glenn Bot List/presence.ts, websites/G/Glenn Bot List/tsconfig.json
Home and Tags
Bot
Profile
Add new bot
=> Added Glenn Bot List

websites/F/fnbr.co/dist/metadata.json, websites/F/fnbr.co/presence.ts, websites/S/skindb.co/dist/metadata.json, websites/S/skindb.co/presence.ts, websites/S/skindb.co/tsconfig.json
Simple presence for [skindb.co](https://skindb.co)
Proof: https://imgur.com/cGXZyYu
=> Add skindb.co presence and updated fnbr.co presence

websites/M/ManiaExchange/dist/metadata.json, websites/M/ManiaExchange/presence.ts, websites/M/ManiaExchange/tsconfig.json
*See also: Hans5958/PreMiD-Presences-Personal#1*
This is the presence for ManiaExchange (MX) (https://mania.exchange, https://mania-exchange.com), a website that initially started as a track sharing website for TrackMania² (and other), but then expanded to host other things related to TrackMania as a whole. You can say it is a sequel to TrackMania Exchange (TMX) and it's accompanying presence.
- This presence supports the following parts of the site.
- Portal (https://mania.exchange)
- ManiaExchange for Trackmania² (https://tm.mania.exchange)
- ManiaExchange for ShootMania (https://sm.mania.exchange)
- ItemExchange (https://item.mania.exchange)
- Accounts (https://accounts.mania.exchange)
- API Documentation (https://api.mania.exchange)
- Images are from various sources, along with the …
=> Add ManiaExchange presence

websites/C/ChickenFM/dist/metadata.json, websites/C/ChickenFM/presence.ts
Hi, I updated the ChickenFM Presence for my new website
=> Updated ChickenFM Presence

websites/E/Erisly/dist/metadata.json, websites/E/Erisly/presence.ts, websites/E/Erisly/tsconfig.json
=> Erisly Presence (Partner)

websites/C/Clarity Clan/dist/metadata.json, websites/C/Clarity Clan/presence.ts, websites/C/Clarity Clan/tsconfig.json
Please add Clarity Clan presence. It's a growing minecraft clan website.
=> Adding Clarity Clan presence

.github/CONTRIBUTING.md
Add a guideline that enforces category usage.
*Not really necessary but it's better to be more verbose*
=> Category Notice

websites/W/Wikipedia/dist/metadata.json, websites/W/Wikipedia/presence.ts
*I got questions on [the notes section](#notes), I kindly ask to answer them.*
It's been a while since the last update for the Wikipedia presence, and I think there still room of improvement for the presence. As someone who had experience on editing the wiki, there are still a lot of things that is missing, such as different details for the different namespaces (Talk:, Wikipedia:, User:, etc.), incomplete support for other Wikipedia wikis than English Wikipedia, and *subjectively* a bad implementation for the presence. 
With the issues in mind, I have decided to try to fix the aforementioned issues, as well as adding features and fixing bugs for the frequent Wikipedia editors and readers.
- Add my base and do significant refactor
- Add …
=> Update Wikipedia presence (2.7.0)

websites/S/SimulatorHits/dist/metadata.json, websites/S/SimulatorHits/presence.ts, websites/S/SimulatorHits/tsconfig.json
=> Add SimulatorHits to Store

websites/H/HabboCity/dist/metadata.json, websites/H/HabboCity/presence.ts
Hey!
I simply added a new page of HabboCity to the presence.
Good day to you!
=> Update presence.ts - HabboCity

websites/P/Prime Video/dist/metadata.json, websites/P/Prime Video/presence.ts
=> Fix Prime Vid

.github/CONTRIBUTING.md
If someone has a better way of wording this, by all means, correct it.
=> Service and URL Notice

websites/C/Custom Status/dist/metadata.json, websites/E/eggsy.codes/dist/metadata.json
urGENT, couldn't change the service names because if I did, it'll make me lose all current users and they'll stuck with an outdated eggsy.codes presence.
=> 🛠 domain change for my presences

@types/premid/index.d.ts
=> Fix typo in summary of showSetting

websites/U/UserBenchmark/dist/metadata.json, websites/U/UserBenchmark/presence.ts, websites/U/UserBenchmark/tsconfig.json
UserBenchmark Presence with full support over the entire website.
=> UserBenchmark Presence

websites/S/Shazam/dist/metadata.json, websites/S/Shazam/presence.ts, websites/S/Shazam/tsconfig.json
Shazam presence that fully supports the website.
=> Shazam Presence

.eslintrc.json, presenceUpdater.ts, schemaValidator.ts, syntaxEnforcer.ts, websites/S/Serendia Squad/dist/metadata.json
- Changes ESLint config and its override to match the current ECMAScript target of our TypeScript config;
- Disallows empty lines at the start/end of files and sets the maximum of empty lines between functions to 1 (self explanatory);
- "Allows multiple variable declarations per scope but requires consecutive variable declarations to be combined into a single declaration" (not much of a performance difference, reduces file sizes);
- Forces linebreak style to LF ([why](https://jessitron.com/2019/11/11/line-endings-in-git));
- `noInlineConfig` - disables inline configuration of ESLint for security purposes;
- `reportUnusedDisableDirectives` - self explanatory, related to the previous rule;
- Overrides the rules for non-Presence scripts (e.g. the updater needs a node environment compared to …
=> Code maintenance

websites/A/AnimeWorld/dist/metadata.json, websites/A/AnimeWorld/iframe.ts, websites/A/AnimeWorld/presence.ts
AnimeWorld recently updated the website. I changed everything so that it works properly and took advantage of it to order the file "iframe.ts".
=> 🔄 AnimeWorld: Big update of the WebSite.

websites/G/Google Domains/dist/metadata.json, websites/G/Google Domains/presence.ts, websites/G/Google Domains/tsconfig.json
Google Domains presence with full support over the entire website.
Resolve #1316
=> Google Domains Presence

websites/D/Discord/dist/metadata.json, websites/D/Discord/presence.ts
Why do elements have to be different in other regions...
=> Discord fix.

massVer.ts, presenceUpdater.ts
=> missed that

websites/0-9/20XX/dist/metadata.json, websites/0-9/20XX/presence.ts
This adds the Cube character from the new [1.1.2](https://20xx.io/nxc/patch.html) version of 20XX.
=> 20XX: Add cube to character map

websites/Y/Yandex Music/dist/metadata.json, websites/Y/Yandex Music/presence.ts, websites/Y/Yandex Music/tsconfig.json
This PR adds support for Yandex Music.
Screenshots:
=> Add Yandex Music RPC

websites/G/Google Meet/dist/metadata.json, websites/G/Google Meet/presence.ts
Fixed issue that was preventing the Presence from showing the number of users in the room.
=> Google Meet presence update

websites/W/Wikiquote/dist/metadata.json, websites/W/Wikiquote/presence.ts, websites/W/Wikiquote/tsconfig.json
This is a presence for Wikiquote (www.wikiquote.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains quotes from various people.
- This presence supports all languages of Wikiquote.
| ![](https://user-images.githubusercontent.com/11584103/90750995-c2258c80-e2ff-11ea-98e8-189ae3034c2c.png) | https://www.wikiquote.org |
| ![](https://user-images.githubusercontent.com/11584103/90750999-c356b980-e2ff-11ea-9f92-9aef7be55a33.png) | https://en.wikiquote.org/wiki/Main_Page |
| ![](https://user-images.githubusercontent.com/11584103/90751005-c5207d00-e2ff-11ea-8cf1-2cf9c05fb173.png) | …
=> Add Wikiquote presence

websites/W/Wikiversity/dist/metadata.json, websites/W/Wikiversity/presence.ts, websites/W/Wikiversity/tsconfig.json
This is a presence for Wikiversity (www.wikiversity.org), a website from Wikimedia Foundation (the same company that made Wikipedia) that contains free online courses.
- This presence supports all languages of Wikiversity, including the beta version (https://beta.wikiversity.org).
| ![](https://user-images.githubusercontent.com/11584103/90757429-d2416a00-e307-11ea-9a7c-827d9dff8ffb.png) | https://www.wikiversity.org |
| ![](https://user-images.githubusercontent.com/11584103/90757431-d3729700-e307-11ea-9f67-0bc8d5f0bd04.png) | https://en.wikiversity.org/wiki/Wikiversity:Main_Page |
| …
=> Add Wikiversity presence

websites/D/Discord Extreme List/dist/metadata.json
Added new domains to metadata that are now used on the site, also added more langs for description sourced from the i18n repo: https://github.com/discordextremelist/i18n
=> Added new domains, lang descs

websites/C/Codecademy/dist/metadata.json, websites/C/Codecademy/presence.ts
* ## Added support for the `/learn/course-name/modules/` endpoint
* ## Added support for paid paths endpoint
* ## Fixed "undefined" showing up in presence details when in a course lesson
=> [1.1.0] Update 'Codecademy' presence

websites/A/AnimeWho/dist/metadata.json, websites/A/AnimeWho/iframe.ts, websites/A/AnimeWho/presence.ts, websites/A/AnimeWho/tsconfig.json
=> Add new site for store

websites/G/GitHub/dist/metadata.json, websites/G/GitHub/presence.ts
Hey all! I was using the GH extension, but it didnt work for most things, like the all repo features, or other ones that needed to get data from the site its self, not just the URL. Cheers
=> Fixes the extension to show all the features

websites/R/Rustlabs/dist/metadata.json, websites/R/Rustlabs/presence.ts, websites/R/Rustlabs/tsconfig.json
=> Adding Rustlabs.com presence to PreMiD.

websites/K/Keep It Wholesome/dist/metadata.json, websites/K/Keep It Wholesome/presence.ts, websites/K/Keep It Wholesome/tsconfig.json
=> Adding keepitwholesome.com presence to PreMiD.

.github/CONTRIBUTING.md
- Replaced all instances of `verifier` with `reviewer` for consistency. 
- Added a notice regarding pull request review delays.
- Made it clear that adding, deleting, or modifying DOM elements is not permitted.
- Included new developer restriction guidelines.
=> Guidelines: Futureproofing

.eslintrc.json
=> Revert "⏪ Revert #1954 and #2048"

websites/R/REYFM/dist/metadata.json, websites/R/REYFM/presence.ts, websites/R/REYFM/tsconfig.json, websites/R/Reach Radio/dist/metadata.json, websites/R/Reach Radio/presence.ts, websites/R/Reach Radio/tsconfig.json
=> REYFM & Reach Radio

websites/D/Disney+/dist/metadata.json, websites/D/Disney+/presence.ts
Adds support for Disney+ in India (Disney+ Hotstar)
=> Disney+: add Disney+ Hotstar support

websites/R/Repeat/dist/metadata.json, websites/R/Repeat/presence.ts, websites/R/Repeat/tsconfig.json
=> New Presence • Repeat

websites/E/Epic Games/dist/metadata.json, websites/E/Epic Games/presence.ts, websites/E/Epic Games/tsconfig.json
=> Presence | Epic Games

websites/D/DevTR/dist/metadata.json, websites/D/DevTR/presence.ts, websites/D/DevTR/tsconfig.json
=> Presence | DevTR

websites/S/Stips/dist/metadata.json
added `altnames` and changed version
=> Presence Update: Stips

websites/S/skindb.co/dist/metadata.json, websites/S/skindb.co/presence.ts
Added support for [skindb.co/fallguys](https://skindb.co/fallguys).
Proof: [media.wtf/95781050](https://media.wtf/95781050)
=> Presence update: skindb.co

websites/S/SnowBoltz/dist/metadata.json, websites/S/SnowBoltz/presence.ts
- Fixed bugs that show the wrong title
- Deleted docs.
- Change something on some page
=> SnowBoltz Update!

websites/A/Aternos/dist/metadata.json, websites/A/Aternos/presence.ts
fix that the presence text is "Home Page" even when the user opens the panel
=> Fix Aternos presence

websites/Y/Yaay/dist/metadata.json, websites/Y/Yaay/presence.ts, websites/Y/Yaay/tsconfig.json
Here's the presence for new Turkish social media called Yaay. It's a website that's still in development and requires tons of more works but still, it's a really cool and good concept, looks just like Twitter.
[Visit their website](https://yaay.com.tr) || [Visit my website](https://eggsy.xyz) || [View on Store (when approved)](https://premid.app/store/presences/Yaay)
=> 🔥 Yaay presence!

websites/A/AsphaltEvents/dist/metadata.json, websites/A/AsphaltEvents/presence.ts, websites/A/AsphaltEvents/tsconfig.json
---
Name: Asphalt Events
About: 
First commit, includes current website pages of Asphalt Events.
---
**Screenshots**
=> Added Asphalt Events

websites/B/BeastFM/dist/metadata.json, websites/B/BeastFM/presence.ts, websites/B/BeastFM/tsconfig.json
=> Add BeastFM

websites/M/MangaHost/dist/metadata.json, websites/M/MangaHost/presence.ts, websites/M/MangaHost/tsconfig.json
Some examples...
Checking a novel/manga content page:
Reading a novel/mangá:
Looking for new releases:
=> Add MangaHost Presence

websites/D/Dank Memer/dist/metadata.json, websites/D/Discord Bot List/dist/metadata.json, websites/D/Discord Bots/dist/metadata.json, websites/G/Groovy/dist/metadata.json, websites/G/Groovy/presence.ts, websites/K/Kabal's/dist/metadata.json, websites/K/Kahve BOT/dist/metadata.json, websites/T/Tatsumaki/dist/metadata.json, websites/T/Tatsumaki/presence.ts
=> Updates | Tatsumaki, Kahve BOT, Kabal's and more!

websites/F/FiveM/dist/metadata.json, websites/F/FiveM/presence.ts
Fixes https://github.com/PreMiD/Presences/pull/2045#issuecomment-691600705
#2045
=> Fix FiveM bug

websites/L/LinusTechTips/dist/metadata.json, websites/L/LinusTechTips/presence.ts, websites/L/LinusTechTips/tsconfig.json
**Name:** Linus Tech Tips Forum
**About:**
First commit, includes requested features from the following suggestion.
closes https://github.com/PreMiD/Presences/issues/2120
=> Added Linus Tech Tips Forum

websites/A/AsphaltEvents/dist/metadata.json, websites/A/AsphaltEvents/presence.ts
- Added Support for branding, privacy, terms of service, cookie policy, and advertising pages.
- Added small icon to index and create event presences
- Change presences logo URL (Image no longer has a transparent background)
=> Multiple pages added, small icons and logo URL update

websites/D/DMOJ/dist/metadata.json, websites/D/DMOJ/presence.ts
=> Add users rank/problem points to DMOJ rich presence

websites/M/Mixcloud/dist/metadata.json, websites/M/Mixcloud/presence.ts
Mixcloud deployed an update to their UI, making this plugin presence obsolete to its state. This is a try into making it work once again.
=> Update Mixcloud plugin

websites/R/Radiko/dist/metadata.json, websites/R/Radiko/presence.ts, websites/R/Radiko/tsconfig.json
Radiko is Japanese website that provide radio livestream in real time.
*I test this presence using my alts account.*
- When idling
- When stream some radio
- Pause state
=> Add Radiko Presence

websites/X/XKCD/dist/metadata.json, websites/X/XKCD/presence.ts, websites/X/XKCD/tsconfig.json
XKCD is a webcomic of romance, sarcasm, math, and language made by Randall Munroe.
**Non-Comic Page**
**Comic Page**
**Title Text**
=> Add XKCD Presence

websites/T/Town of Salem/dist/metadata.json, websites/T/Town of Salem/presence.ts, websites/T/Town of Salem/tsconfig.json
A deception game made by BlankMediaGames.
This PR closes #2126 
|Event|Image|Description|
|-|-|-|
|Non-game page|![Browsing BlankMediaGames](https://cdn.discordapp.com/attachments/710280407777673277/754881552638410822/Screen_Shot_2020-09-13_at_5.23.45_PM.png)|Shows the current page the user is browsing and how long they were browsing|
|Logging into the page|![Logging in](https://cdn.discordapp.com/attachments/710280407777673277/754881561203310743/Screen_Shot_2020-09-13_at_5.22.17_PM.png)|Appears when the user loads the page and begins logging in|
|In the main menu|![Browsing Home Screen](https://cdn.discordapp.com/attachments/710280407777673277/754881551560343734/Screen_Shot_2020-09-13_at_5.22.32_PM.png)|Appears in the main, the shop, cauldron, achievements, etc. screens|
|In a game …
=> Add Town of Salem Presence

websites/S/Spinsha.re/dist/metadata.json, websites/S/Spinsha.re/presence.ts
---
Name: SpinShare
About: Fixed presence showing innerHTML for users with patreon.
---
**Screenshots**
Before:
After:
> After your pull request has been made, you should have a screenshot and the code.
=> SpinShare Update - Fixed Displaying Patreon User Span HTML

websites/M/Mark Scans/dist/metadata.json, websites/M/Mark Scans/presence.ts, websites/M/Mark Scans/tsconfig.json
I had made this presence, but I gave it to Markinhoz and he couldn't post it, so I'm posting it.
=> New presence (Mark Scans)

websites/C/Chess/dist/metadata.json, websites/C/Chess/presence.ts
Here is an update for the presence to handle new pages on Chess.com.
=> Update Chess Presence

websites/S/SCP Wiki/dist/metadata.json
=> Added SCP Wiki website

websites/L/Laftel/dist/metadata.json, websites/L/Laftel/presence.ts, websites/L/Laftel/tsconfig.json
=> New presence: Laftel

websites/C/CodAre/dist/metadata.json, websites/C/CodAre/presence.ts, websites/C/CodAre/tsconfig.json
codare.fun is a code sharing website for discord bots
=> Added codare.fun presence

websites/C/CatchPlay/dist/metadata.json, websites/C/CatchPlay/presence.ts, websites/C/CatchPlay/tsconfig.json
CATCHPLAY is a Taiwanese multimedia company founded in 2007, whose businesses include OTT VOD streaming service operation, linear television channel operation and theatrical film distribution. Legally, it operates as a Taiwan branch of CatchPlay, Inc., a company registered in Cayman Islands.
=> New presence: CatchPlay

websites/G/Glynet/dist/metadata.json, websites/G/Glynet/presence.ts, websites/L/Log.com.tr/dist/metadata.json, websites/L/Log.com.tr/presence.ts, websites/T/Teknobuk/dist/metadata.json, websites/T/Teknobuk/presence.ts
=> Fixed Glynet, Log.com.tr and Teknobuk Presences

websites/C/CartoonCrazy.net/dist/metadata.json, websites/C/CartoonCrazy.net/iframe.ts, websites/C/CartoonCrazy.net/presence.ts
Should probs recode it sometime...
=> Cartoon Crazy - Quick fix so it works again

websites/B/BeastFM/dist/metadata.json, websites/B/BeastFM/presence.ts, websites/B/BeastFM/tsconfig.json
Important: this pull request is opened in the name of @MicroBotCodes
Proff that the presence works ok.
=> Update BeastFM presence

websites/H/Hentailib/dist/metadata.json, websites/H/Hentailib/presence.ts, websites/M/Mangalib/dist/metadata.json, websites/M/Mangalib/presence.ts, websites/R/Ranobelib/dist/metadata.json, websites/R/Ranobelib/presence.ts
=> Update Presences: Mangalib, Ranobelib, Hentailib

websites/V/Vanis.io/dist/metadata.json, websites/V/Vanis.io/presence.ts, websites/V/Vanis.io/tsconfig.json
added new presence from Issues #1788
=> New Presence: Vanis.io

websites/C/Coub/dist/metadata.json, websites/C/Coub/presence.ts, websites/C/Coub/tsconfig.json
=> New Presence: Coub

websites/F/Flickr/dist/metadata.json, websites/F/Flickr/presence.ts, websites/F/Flickr/tsconfig.json
Flickr Presence as requested by #2199 
Screenshots:
=> Add Flickr support.

websites/0-9/9anime/dist/metadata.json, websites/A/Anghami/dist/metadata.json, websites/C/Chaturbate/dist/metadata.json, websites/F/Fmovies/dist/metadata.json, websites/H/HBO Max/dist/metadata.json, websites/L/LookMovie/dist/metadata.json, websites/M/mvs4u/dist/metadata.json, websites/O/OKanime/dist/metadata.json, websites/V/VLC/dist/metadata.json, websites/W/Wolfy/dist/metadata.json
Transferred DooM's presences to the bot account. He will be missed.
=> Migrate Presences

websites/0-9/9anime/dist/metadata.json, websites/0-9/9anime/presence.ts, websites/A/Anghami/dist/metadata.json, websites/A/Anghami/presence.ts, websites/C/Chaturbate/dist/metadata.json, websites/C/Chaturbate/presence.ts, websites/F/Fmovies/dist/metadata.json, websites/F/Fmovies/presence.ts, websites/L/LookMovie/dist/metadata.json, websites/L/LookMovie/presence.ts, websites/M/mvs4u/dist/metadata.json, websites/M/mvs4u/presence.ts, websites/O/OKanime/dist/metadata.json, websites/O/OKanime/presence.ts, websites/T/Tidal/dist/metadata.json, websites/T/Tidal/presence.ts, websites/V/VLC/dist/metadata.json, websites/V/VLC/presence.ts, websites/W/Wolfy/dist/metadata.json, websites/W/Wolfy/presence.ts
9anime proof of working:
* Browsing:
* Watching:
Tidal proof of working:
Resolves #2229, resolves #2227, resolves #2252
=> 🐛  Fix 9anime & Tidal presence and change other presences.

websites/B/bilibili/dist/metadata.json, websites/B/bilibili/presence.ts
Just make it work.
Some things in bilibili have changed, and I will recode some things when I have free time.
=> Fix Bilibili

websites/I/Invidious/dist/metadata.json, websites/I/Invidious/presence.ts, websites/I/Invidious/tsconfig.json
Adds support for [Invidious](https://github.com/iv-org/invidious/).
Invidious can be self-hosted. There used to be an [official instance](https://invidio.us/), but it was since replaced with a [list of popular public instances](https://instances.invidio.us/). URLs were taken from said list, minus .onion and .i2p domains.
Edit: Closes #1883, thanks @Isa27-0 for the heads-up.
=> New Presence: Invidious

websites/M/MEGA/dist/metadata.json, websites/M/MEGA/presence.ts, websites/M/MEGA/tsconfig.json
Resolves #2034
There are more pages supported but it would've taken a hot minute to do the screenshots
=> New Presence: MEGA (mega.nz)

websites/D/Dash Radio/dist/metadata.json, websites/D/Dash Radio/presence.ts, websites/D/Dash Radio/tsconfig.json
=> Dash Radio Rich Presence

websites/Y/YouTube Music/dist/metadata.json, websites/Y/YouTube Music/presence.ts
Fixed author string
From: 
To:
=> 🐛 Fix youtube music - author string

websites/F/FurAffinity/dist/metadata.json, websites/F/FurAffinity/presence.ts, websites/F/FurAffinity/tsconfig.json
=> New presence: FurAffinity

websites/Y/YouTube Music/dist/metadata.json, websites/Y/YouTube Music/presence.ts
Author(s) without channel:
Author with channel:
**I didn't notice it because i wasn't listening to author with no channel.**
=> 🐛 YouTube Music: fix authors with no channel

websites/S/Sling TV/dist/metadata.json, websites/S/Sling TV/presence.ts, websites/S/Sling TV/tsconfig.json
Presence for [Sling TV](https://www.sling.com/), 3 states: Browsing, Watching and Paused.
Will improve support for specific parts of the site over time!
=> New Presence: Sling TV

websites/D/Destiny.gg/dist/metadata.json, websites/D/Destiny.gg/presence.ts, websites/D/Destiny.gg/tsconfig.json
got bored so i made a d.gg presence
preview images:
- Viewing Homepage:
- Viewing Stream:
- Editing Profile
- Subscribing
- Donating
- Chatting
=> Added Destiny.gg 

websites/F/Flacless/dist/metadata.json, websites/F/Flacless/presence.ts, websites/F/Flacless/tsconfig.json
=> new presence: Flacless

websites/U/Unsplash/dist/metadata.json, websites/U/Unsplash/presence.ts, websites/U/Unsplash/tsconfig.json
Fixes #2132
I made Unsplash presence that should support most of the service
=> New Presence: Unsplash

websites/I/Invidious/dist/metadata.json
Adds invidious.cmh.pw to Invidious App.
=> Add my Invidious Instance

websites/A/AnimeKisa/dist/metadata.json, websites/A/AnimeKisa/iframe.ts, websites/A/AnimeKisa/presence.ts, websites/A/AnimeKisa/tsconfig.json
https://www.youtube.com/watch?v=uuGcSnMJmOU&feature=youtu.be
fucking kill me
=> Adding AnimeKisa presence

websites/R/REYFM/dist/metadata.json, websites/R/REYFM/presence.ts
=> REYFM API fixes.

websites/Z/Zoom/dist/metadata.json, websites/Z/Zoom/presence.ts, websites/Z/Zoom/tsconfig.json
=> New Presence: Zoom

websites/L/LoL Esports/dist/metadata.json, websites/L/LoL Esports/iframe.ts, websites/L/LoL Esports/presence.ts, websites/L/LoL Esports/tsconfig.json
=> LoL Esports

websites/T/taiga Bot/dist/metadata.json, websites/T/taiga Bot/presence.ts
This Pull Request rewrites the taiga Bot Presence and introduces the following changes:
- Presence texts are now dynamically fetched from the Website. Therefore, new Pages are now instantly supported by the Presence
- Removed support for Subdomains that no longer exist, will be removed in the future, or where it's not necessary.
Screenshots of the presence working:
Additionally,  I haven't done a Contribution since June. I already checked the new Guidelines, but if I still did anything wrong, please tell me!
=> Rewrite of taiga Bot Presence

websites/W/Wikibooks/dist/metadata.json, websites/W/Wikibooks/presence.ts, websites/W/Wikidata/dist/metadata.json, websites/W/Wikidata/presence.ts, websites/W/Wikimedia Commons/dist/metadata.json, websites/W/Wikimedia Commons/presence.ts, websites/W/Wikinews/dist/metadata.json, websites/W/Wikinews/presence.ts, websites/W/Wikipedia/dist/metadata.json, websites/W/Wikipedia/presence.ts, websites/W/Wikiquote/dist/metadata.json, websites/W/Wikiquote/presence.ts, websites/W/Wikisource/dist/metadata.json, websites/W/Wikisource/presence.ts, websites/W/Wikispecies/dist/metadata.json, websites/W/Wikispecies/presence.ts, websites/W/Wikiversity/dist/metadata.json, websites/W/Wikiversity/presence.ts, websites/W/Wikivoyage/dist/metadata.json, websites/W/Wikivoyage/presence.ts, websites/W/Wiktionary/dist/metadata.json, websites/W/Wiktionary/presence.ts
Alright, I finally get PreMiD to work. Turns out it's because I disable PreMiD and I forgot about it. Since it works, now I can test the presence updates I made and then create pull requests to the main repo.
I have updates for all of my presences, but I'm going to take this slowly and try to make it simple since there's quite something going on behind there.
This update contains bug fixes for all of the current Wikimedia Foundation wiki presences.
This PR includes updates for the following presences:
- Wikipedia (2.7.4)
- Wikibooks (1.0.2)
- Wikidata (1.0.2)
- Wikimedia Commons (1.0.2)
- Wikinews (1.0.2)
- Wikiquote (1.0.2)
- Wikisource (1.0.2)
- Wikispecies (1.0.2)
- Wikiversity (1.0.2)
- Wikivoyage (1.0.2)
- Wiktionary (1.0.2)
- Update …
=> Update all Wikimedia presences (18/10/2020)

websites/P/Peacock/dist/metadata.json, websites/P/Peacock/presence.ts, websites/P/Peacock/tsconfig.json
Presence for [Peacock](https://www.peacocktv.com), 4 states: Browsing, Watching, Paused and Live.
closes #1938
=> New Presence: Peacock

websites/T/TruckStopRadio/dist/metadata.json, websites/T/TruckStopRadio/presence.ts
Changes to this presence affects only the current playing song and to prevent future website UI changes affecting the display of information.
=> Truck Stop Radio changed Element to IDs.

websites/S/Starz/dist/metadata.json, websites/S/Starz/presence.ts
Fixed movie/series info (also removed subtitle since it’s no longer available in the HTML markup)
Fixed live TV info
Added routing for multiple URLs with elapsed time
Added Contributor
Before:
After:
closes #1490
=> Updated Starz Presence

websites/B/BigBlueButton/dist/metadata.json, websites/B/BigBlueButton/presence.ts, websites/B/BigBlueButton/tsconfig.json
Some examples of the presence working:
=> Add BigBlueButton presence v1.0.0.

websites/H/Hacktoberfest/dist/metadata.json, websites/H/Hacktoberfest/presence.ts, websites/H/Hacktoberfest/tsconfig.json
=> Added Hacktoberfest presences

websites/D/DreamSub/dist/metadata.json, websites/D/DreamSub/iframe.ts, websites/D/DreamSub/presence.ts, websites/D/DreamSub/tsconfig.json
I created the discord presence for the website dreamsub.stream.
This is an example of the final presence:
https://prnt.sc/v3eqww
=> DreamSub Discord Presence

websites/T/TruckersFM/dist/metadata.json, websites/T/TruckersFM/presence.ts
v1.3.0
Updated Images
Removed current viewing page
Example of testing:
=> TFM: Updated Branding & Removed Viewing

websites/P/Pulse/dist/metadata.json, websites/P/Pulse/presence.ts
apologies for my mistakes previously. This should now compile perfectly and run smoothly. 
here's proof of it working on my user :) 
https://i.imgur.com/KY6S0i0.png
thanks for dealing with my idiocy :P
=> Fix issues from previous PR (Pulse)

websites/B/Blkom/dist/metadata.json, websites/B/Blkom/iframe.ts, websites/B/Blkom/presence.ts, websites/B/Blkom/tsconfig.json
=> Adds Blkom Presence.

websites/D/DiziBOX/dist/metadata.json, websites/D/DiziBOX/presence.ts, websites/Y/yabancıdizi/dist/metadata.json, websites/Y/yabancıdizi/presence.ts
=> 🔧 Update "DiziBOX" and "yabancıdizi"

websites/P/Philo/dist/metadata.json, websites/P/Philo/presence.ts, websites/P/Philo/tsconfig.json
Presence for [Philo.com](https://www.philo.com), 4 states: Browsing, Watching, Paused and Live.
=> New Presence: Philo

websites/I/IMDbFilmIzle/dist/metadata.json, websites/I/IMDbFilmIzle/presence.ts
=> changed some stuff on IMDb Film İzle

websites/P/Philo/dist/metadata.json, websites/P/Philo/presence.ts
Always show episode info if available (even if live)
Before:
Now:
=> Updated Philo Presence

websites/M/Memesena/dist/metadata.json, websites/M/Memesena/presence.ts, websites/M/Memesena/tsconfig.json
added a presence for [Memesena](https://www.memesena.com)
kindly review and merge if found correct. Can provide working proof if required.
=> add Memesena Presence

websites/R/Radio Garden/dist/metadata.json, websites/R/Radio Garden/presence.ts
Basically a rewrite of [radio.garden](http://radio.garden/) for new site design.
Playback stopped
Tuning into a station
Playing station, displaying station name and localisation
=> Radio Garden: update for new site design, new playing states

websites/D/Dual/dist/metadata.json, websites/D/Dual/presence.ts
Changed some API values to ones that function
=> Changed API keys and incremented version

websites/V/VRChat/dist/metadata.json, websites/V/VRChat/presence.ts
**Added:**
- Support for feedback.vrchat.com
**Improved/Fixed:**
- Code for hello.vrchat.com now uses a switch statement instead of an if-statement.
- Fixed [world instance bug](https://github.com/PreMiD/Presences/pull/2439/commits/0eb519c6f1cc2824023b863d4395cccb0ee20522)
=> VRChat: Patch 1

websites/W/Webflow/dist/metadata.json, websites/W/Webflow/presence.ts, websites/W/Webflow/tsconfig.json
Phew! That was a big one Fixes: #1832
=> Webflow Presence

websites/C/Curve Fever Pro/.gitattributes, websites/C/Curve Fever Pro/dist/metadata.json, websites/C/Curve Fever Pro/presence.ts, websites/C/Curve Fever Pro/tsconfig.json
Discord Presence For Game 'Curve Fever Pro'
=> Curve Fever Pro

websites/X/Xero.gg/dist/metadata.json, websites/X/Xero.gg/presence.ts, websites/X/Xero.gg/tsconfig.json
Showcase: [Showcase](https://streamable.com/7c39tj)
Website: [xero.gg](https://xero.gg/)
What it is: xero.gg is a player and clan database for the private server called "S4 Xero" of the base game "S4 League".
What the presence does: The presence mainly shows what profile or clan you are currently looking at or what news you are currently reading. More features included and might follow.
Screenshots of the presence:
=> Added xero.gg support.

websites/X/Xero.gg/dist/metadata.json
Changed the thumbnail due to wrong position of the game logo.
=> xero.gg | Changed thumbnail.

websites/D/DiziBOX/dist/metadata.json, websites/D/Dizilla/dist/metadata.json
=> 🔧 update urls

websites/X/Xero.gg/dist/metadata.json, websites/X/Xero.gg/presence.ts
Added 2 settings to the xero.gg presence.
• Show chatting opponent
• Show profile names
Showcase of it working: [Video](https://kevin.s-ul.eu/BPYU9Qic.mp4)
=> xero.gg | Added settings.

websites/M/MojeVideo/dist/metadata.json, websites/M/MojeVideo/presence.ts, websites/M/MojeVideo/tsconfig.json
Presence for site MojeVideo.sk
=> MojeVideo Presence

websites/G/Google Podcast/dist/metadata.json, websites/G/Google Podcast/presence.ts, websites/G/Google Podcast/tsconfig.json
Fixes #2141
Made a Presence that should implement all of the Google Podcast
=> Google Podcast Presence

websites/B/Blob Project/dist/metadata.json, websites/B/Blob Project/presence.ts, websites/B/Blob Project/tsconfig.json
=> Added Blob Project Presences

websites/P/Proxer/dist/metadata.json, websites/P/Proxer/iframe.ts, websites/P/Proxer/presence.ts, websites/P/Proxer/tsconfig.json
New presence for proxer.me, focuses on displaying the current episode for now
=> Proxer: New presence

websites/D/Dizimag/dist/metadata.json, websites/D/Dizimag/iframe.ts, websites/D/Dizimag/presence.ts, websites/D/Dizimag/tsconfig.json
**While watching**
**in user profile**
**in tv series page**
[it's working fine.](https://dizimag2.org/)
=> Added Dizimag support.

websites/B/Bonk2.io/dist/metadata.json, websites/B/Bonk2.io/iframe.ts, websites/B/Bonk2.io/presence.ts, websites/B/Bonk2.io/tsconfig.json
[Bonk2.io](https://bonk2.io) is a multiplayer browser game where the objective is to knock all of the opponents off the edge of the screen and be the last man standing.
May or may not close #2042
<details>
</details>
<details>
</details>
=> Add Bonk2.io presence

websites/D/Dropbox/dist/metadata.json, websites/D/Dropbox/presence.ts, websites/D/Dropbox/tsconfig.json
=> New Presence: Dropbox

websites/A/AnimePill/dist/metadata.json, websites/A/AnimePill/iframe.ts, websites/A/AnimePill/presence.ts, websites/A/AnimePill/tsconfig.json
Website: [animepill.com](animepill.com)
=> added animepill.com

websites/B/Bonk2.io/dist/metadata.json, websites/B/Bonk2.io/presence.ts
Last PR had a small bug where the timestamp kept restarting while playing a game. This PR should fix that and game timestamps work properly now.
=> Bonk2.io: Fix game timestamp bug

websites/T/top.gg/dist/metadata.json, websites/T/top.gg/presence.ts
=> top.gg - Presence update and fixes.

websites/B/Bonk Leagues/dist/metadata.json, websites/B/Bonk Leagues/presence.ts, websites/B/Bonk Leagues/tsconfig.json
[Bonk Leagues](https://github.com/features/codespaces) - The best tools for bonk.io, featuring a skin manager, XP checker and more for bonk.io
<details>
</details>
=> Add Bonk Leagues Presence

websites/N/Newgrounds/dist/metadata.json, websites/N/Newgrounds/presence.ts, websites/N/Newgrounds/tsconfig.json
[Newgrounds](https://www.newgrounds.com/) - A community of artists, game developers, musicians, voice actors and writers who create and share some of the best stuff on the web!
closes #2305
<details>
</details>
<details>
</details>
=> Add Newgrounds Presence

websites/A/Agar.io/dist/metadata.json, websites/A/Agar.io/iframe.ts, websites/A/Agar.io/presence.ts
Added a setting to show the username in Agar.io.
=> Agar.io: Add show username setting

websites/S/StoryFire/dist/metadata.json, websites/S/StoryFire/presence.ts, websites/S/StoryFire/tsconfig.json
[StoryFire](https://storyfire.com/) - Watch and create the stories and videos that you want while growing a massive fanbase!
closes #2146
<details>
</details>
<details>
</details>
=> Add StoryFire Presence

websites/R/Repeat/dist/metadata.json, websites/R/Repeat/presence.ts
Updated Repeats API link as we now have a new one.
=> Updated API Link

websites/T/Teams/dist/metadata.json, websites/T/Teams/presence.ts, websites/T/Teams/tsconfig.json
Hello!
I have made rich presence for microsoft teams. It supports all (I think) pages of microsoft teams, except of course extensions and manager/teacher/admin only things.
Example screenshot of one of it: https://imgur.com/a/tDwvdEm
Screenshot of settings: https://imgur.com/a/rfuPRuE
=> Microsoft Teams Rich Presence

websites/J/Jet Set Radio Live/dist/metadata.json, websites/J/Jet Set Radio Live/presence.ts
Original owner: @sks316 
This PR rewrites the presence to
- Show the station that they are on
- Show timestamps
- Allow options to hide timestamps and current song
<details>
</details>
<details>
</details>
=> Jet Set Radio Live: Rewrite presence

websites/J/Jira Software/dist/metadata.json, websites/J/Jira Software/presence.ts, websites/J/Jira Software/tsconfig.json
I made a Rich Presence for Jira Software, a website for planning and tracking the development process of a project.
I use it a lot at work, so I said to myself..why not build a PreMiD presence for it..and voilà.
It's made up of a lot of pages, subpages and sections, so the screenshots will be quite a lot. sry.
- Presence settings: https://i.imgur.com/uc7VADf.png
- Homepage: https://i.imgur.com/Nnc28hl.png
- Homepage:  https://i.imgur.com/n1ilke2.png
- "Roadmap" subsection: https://i.imgur.com/J3uVMsP.png
- "Backlog" subsection: https://i.imgur.com/dS6IvB1.png
- "Board" subsection: https://i.imgur.com/CiA42HL.png
- "Reports" subsection:
- Homepage: https://i.imgur.com/IrhpQYj.png
- "Burnup" subsection: https://i.imgur.com/FCE9xhN.png
- "Burndown" subsection: https://i.imgur.com/bv78pcb.png …
=> Jira Software - Website 

websites/B/Blockchain/dist/metadata.json, websites/B/Blockchain/presence.ts, websites/B/Blockchain/tsconfig.json
=> Blockchain Presence

websites/S/Something.Host/dist/metadata.json, websites/S/Something.Host/presence.ts, websites/S/Something.Host/tsconfig.json
I have made this presence during my freetime for https://something.host/. It's an hosting company offering Minecraft servers, Discord bot hosting and VPS. I wanted to contribute to PreMid in some way. 💜
Screenshot: https://u.amaury.xyz/jAlxN.png
=> 💜 Add Something.Host

websites/G/Giphy/dist/metadata.json, websites/G/Giphy/presence.ts
Missing setActivity on Giphy presence, so no activity was being set on the user profile
=> 🐛 Add missing presence.setActivity

websites/V/VRChat/dist/metadata.json, websites/V/VRChat/presence.ts
- Implemented privacy mode into feedback.vrchat.com
- Searches are now hidden when privacy mode is turned on
- Added support for VRChat Plus
=> VRChat: Patch 2

websites/C/CodAre/dist/metadata.json, websites/C/CodAre/presence.ts
i updated this presence because https://codare.fun is updated.
=> Updated because codare.fun site is updated.

websites/C/Chess/dist/metadata.json, websites/C/Chess/presence.ts
I've changed the logo to a crisper one and I added some small images for the presence.
=> Chess presence : added smallImageKey; new logo and translation in metadata.json

websites/N/NPM Package Registry/dist/metadata.json, websites/N/NPM Package Registry/presence.ts
- Added scoped package support
=> NPM Package Registry: Added support for scoped packages

websites/T/Tidal/dist/metadata.json, websites/T/Tidal/presence.ts
**Tidal**
Version: **1.0.7 -> 1.0.8**
**Fixes:**
- Fixed showing song.
<details>
</details>
=> 🐛 Tidal: Fix presence

websites/P/pxls.space/dist/metadata.json, websites/P/pxls.space/presence.ts, websites/P/pxls.space/tsconfig.json
New pxls.space presence.
Tracking canvas pixels and overall pixels placed.
=> Pxls.space presence

websites/M/MyAnimeList/dist/metadata.json, websites/M/MyAnimeList/presence.ts
Added state for the forum to show the title of the threads.
=> MyAnimeList - Added state for forum

websites/B/binarysearch/dist/metadata.json, websites/B/binarysearch/presence.ts, websites/B/binarysearch/tsconfig.json
[binarysearch](binarysearch.com) is a website where people practice coding questions for technical interviews and also race with your friends to solve problems
=> add binarysearch presence

websites/C/Custom Status/dist/metadata.json
Not for testing purposes anymore 😎 Check out the new page [here](https://eggsy-tailwind.netlify.app/projects/premid/custom-status) and see [here](https://eggsy.xyz/projects/premid/custom-status) that it still working on the old one as well.
=> Update custom status, getting ready for the website update.

websites/N/NativShark/dist/metadata.json, websites/N/NativShark/presence.ts, websites/N/NativShark/tsconfig.json
[https://www.nativshark.com/](www.nativshark.com/) is a paid language learning platform for learning Japanese.
This presence allows you to share what you're currently reading, learning or practicing on the site.
=> Add NativShark Presence

websites/M/Meme Police/dist/metadata.json, websites/M/Meme Police/iframe.ts, websites/M/Meme Police/presence.ts, websites/M/Meme Police/tsconfig.json
=> Meme Police website

websites/M/MDN Web Docs/dist/metadata.json, websites/M/MDN Web Docs/presence.ts, websites/M/MDN Web Docs/tsconfig.json
All the web docs of MDN please accept this :C
=> Finally all MDN Web Docs

websites/A/AniMixPlay/dist/metadata.json, websites/A/AniMixPlay/iframe.ts, websites/A/AniMixPlay/presence.ts, websites/A/AniMixPlay/tsconfig.json
Requested By https://github.com/PreMiD/Presences/issues/2600
=> Added Presence for AniMixPlay.to

websites/H/Hako/dist/metadata.json, websites/H/Hako/presence.ts, websites/H/Hako/tsconfig.json, websites/Y/Yoakemoe/dist/metadata.json
=> ln.hako.re website

websites/P/pixiv/dist/metadata.json, websites/P/pixiv/presence.ts
=> Fixed 'Pixiv' prensence not working!

websites/F/fastani.net/dist/metadata.json, websites/F/fastani.net/presence.ts, websites/F/fastani.net/tsconfig.json
based on twist.moe source code
=> added fastani.net

websites/T/top.gg/dist/metadata.json, websites/T/top.gg/presence.ts
This fix includes the following sections that were partially to fully nonfunctional due to the recent css-changes on top.gg:
- DSL (top.gg servers)
- DBL (top.gg bots)
- top.gg Staff Sections (including queue etc)
=> Fixes due to css-changes on top.gg

websites/M/Monkeytype/dist/metadata.json, websites/M/Monkeytype/presence.ts, websites/M/Monkeytype/tsconfig.json
I hope you like it.
screenshots:
=> New presence: Monkeytype.

websites/O/Overleaf/dist/metadata.json, websites/O/Overleaf/presence.ts, websites/O/Overleaf/tsconfig.json
The rich presence probs are better with white background:
So I chose the first one.
Though, the Premid Logo is transparent.
=> 🍃 Added Overleaf presence

websites/M/MyAnimeList/dist/metadata.json, websites/M/MyAnimeList/presence.ts
Working proves are added below.
**Viewing clubs, invitations, and joined clubs:** 
**Viewing Blogs:** 
**Viewing News:** 
**Viewing featured articles:**
**Viewing Peoples:**
**Viewing Characters:**
=> Added new pages | MyAnimeList.net

websites/G/Gogoanime/dist/metadata.json
=> updated gogoanime url (video -> vc)

websites/V/VLC/readme.md
VLC must be restarted for the web interface to start, which tripped me up when trying to set up, hopefully this should help.
=> Tell user to restart VLC during presence setup

websites/M/Multporn/dist/metadata.json, websites/M/Multporn/presence.ts, websites/M/Multporn/tsconfig.json
Name: Multporn.net
About: Website for Adult Comics
Working Proof below, although i cant show the Site as its Full of NSFW Content.
Ill gladly Fix any Errors, Mistakes and Bugs you encounter!
=> New Rich Presence: Multporn

websites/X/Xero.gg/dist/metadata.json, websites/X/Xero.gg/presence.ts
Whats new: The website has added a "Challenges" page so I updated my presence to make it work with the new website update.
Proof of it working: [Video](https://streamable.com/47nr6e)
=> xero.gg | Added "Challenges" page.

websites/T/Twitter/dist/metadata.json, websites/T/Twitter/presence.ts
=> Twitter update

websites/S/Spotify Podcasts/dist/metadata.json, websites/S/Spotify Podcasts/presence.ts
=> Spotify Podcasts update
