websites/K/KissAsian/iframe.ts
websites/K/KissAsian/metadata.json
websites/K/KissAsian/presence.ts

- Resolves #7676
- Add regex to match everything but disqus.org or .com (because those websites stop the iframe injection from working.)
- Fix elements
<details>
</details>

fix(KissAsian): fix presence

---

websites/W/wumpus.store/metadata.json
websites/W/wumpus.store/presence.ts

chore(wumpus.store): update assets

---

websites/W/WaniKani/metadata.json
websites/W/WaniKani/presence.ts

* Adds recent mistakes to the presence
* Updates dashboard statistics selectors
* Updates regexes for lesson path
<details>
</details>

feat(WaniKani): add recent mistakes page

---

websites/T/TikTok/metadata.json
websites/T/TikTok/presence.ts

- Add more features
- Add more settings
- Fix issues
- Add cache for video elements to prevent issues
- Goes with [https://github.com/PreMiD/Localization/pull/7379](https://github.com/PreMiD/Localization/pull/7379)
<details>
</details>

feat(TikTok): rewrite presence

---

websites/R/Radio Garden/metadata.json
websites/R/Radio Garden/presence.ts

chore(Radio Garden): update assets

---

websites/W/WhatsApp/metadata.json
websites/W/WhatsApp/presence.ts

- Add more details when not chatting
<details>
</details>

feat(WhatsApp): rewrite presence & add features

---

websites/T/Tetris/metadata.json
websites/T/Tetris/presence.ts

chore(Tetris): update assets

---

websites/I/Instagram/metadata.json
websites/I/Instagram/presence.ts

- if/elseif => switch
- add reels support w/ cache & buttons
- Support /reel/ on user profile
- Bump version
- Cleanup privacy
<details>
</details>

feat(Instagram): rewrite presence

---

websites/I/Instagram/metadata.json
websites/I/Instagram/presence.ts
websites/O/Otakudesu/metadata.json

chore(Instagram): update assets

---

websites/T/Taiyō/metadata.json
websites/T/Taiyō/presence.ts

Add presence for Taiyō, a manga reader
<details>
<summary> Saiba mais </summary>
</details>

feat(Taiyō): Add presence

---

websites/T/Taiyō/metadata.json
websites/T/Taiyō/presence.ts

chore(Taiyō): update assets

---

websites/H/Hypixel/metadata.json
websites/H/Hypixel/presence.ts

since rewrite is taking longer than expected
resolves #7821 
Does not fix all paths, but the most common ones.
Other issues will be addressed in rewrite
<details><summary>screenshots</summary>
</details>

fix(Hypixel): fixes most apparent issues

---

websites/A/ArcViewer/metadata.json
websites/A/ArcViewer/presence.ts

First time using getLogs please help me improve if needed. did test leaving page open on new extension version did not seem to cause slowdowns even after leaving open for more than 10 minutes when the old version would've, maybe don't merge until new extension version is on chrome?
<details>
</details>

feat(ArcViewer): add presence

---

websites/C/Craiyon/metadata.json
websites/C/Craiyon/presence.ts

* Updates query selectors for new layout
* Adds support for blog, search, and individual image pages
<details>
</details>

feat(Craiyon): update selectors, add blog, search

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

- implement Assets
- Implement Future
- Fix bug with new types of LargeImageKey
<details>
</details>

chore(BBC): implement Assets & fix bug

---

websites/I/Is it Christmas/metadata.json
websites/I/Is it Christmas/presence.ts

chore(Is it Christmas): update assets

---

websites/F/FMovies/metadata.json
websites/F/FMovies/presence.ts

- Resolves #7858
- Note: ww4.fmovies.co calls series, films so yeah, dont know what to do about that.
<details>
</details>

feat(FMovies): add regex & support more versions

---

websites/S/SlimeRead/metadata.json
websites/S/SlimeRead/presence.ts

<details>
<summary> Some images </summary>
home
manga page
reader page
</details>

feat(SlimeRead): add presence

---

websites/M/movie-web/metadata.json
websites/M/movie-web/presence.ts

<details>
</details>
---
Updated code to match the newest website version.

fix(movie-web): resolve metadata parsing issue

---

websites/D/Discord ID/metadata.json
websites/D/Discord ID/presence.ts

- fix(Setting): not working due to issue with two different setting ids for setting (bruh).
<details>
</details>

feat(discord ID): rewrite presence

---

websites/S/SlimeRead/metadata.json
websites/S/SlimeRead/presence.ts

chore(SlimeRead): update assets

---

websites/0-9/000webhost/metadata.json
websites/0-9/000webhost/presence.ts

- Shorten selectors
- if/elseif/else =>Switch
<details>
</details>

feat(000Webhost): rewrite presence

---

websites/0-9/2048Verse/metadata.json
websites/0-9/2048Verse/presence.ts

Resolves #7870 
<details>
</details>

feat(2048Verse): add presence

---

websites/#/アイドルマスターシャイニーカラーズ/metadata.json
websites/#/アイドルマスターシャイニーカラーズ/presence.ts

feat(アイドルマスターシャイニーカラーズ): add some codes and tag

---

websites/B/BeatLeader/metadata.json
websites/B/BeatLeader/presence.ts

Added new christmas logo
Fixed a selector on profile pages
Buttons
<details>
</details>

feat(BeatLeader): add logo & fix selector

---

websites/0-9/000webhost/metadata.json
websites/0-9/000webhost/presence.ts
websites/0-9/2048Verse/metadata.json
websites/0-9/2048Verse/presence.ts

chore(2048Verse): update assets

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

fix issues created. [https://deepscan.io/dashboard/#view=project&tid=6792&pid=16014&bid=485392&subview=pull-request&prid=1808745](https://deepscan.io/dashboard/#view=project&tid=6792&pid=16014&bid=485392&subview=pull-request&prid=1808745)
<details>
n/a
</details>

fix(BBC): resolve new deepscan issue

---

websites/#/アイドルマスターシャイニーカラーズ/metadata.json
websites/V/Vidoza/metadata.json

chore(アイドルマスターシャイニーカラーズ): format metadata

---

websites/F/FlaviBot/metadata.json
websites/F/FlaviBot/presence.ts

- Resolves #7853
- Add presence for FlaviBot
<details>
</details>

feat(FlaviBot): add presence

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

chore(BBC): update deepscan fix

---

websites/D/Doodstreams/metadata.json
websites/D/Doodstreams/presence.ts

chore(Doodstreams): update assets

---

websites/R/Roblox/metadata.json
websites/R/Roblox/presence.ts

- Resolves #7432
- Switch to Assets;;
- If/else if/else => Switch;
- Checks before deleting fields;
- Shorten some selectors;
- Add missing pages;
- Change fetch => queryselectors;
<details>
</details>

feat(Roblox): rewrite presence

---

websites/F/FlaviBot/metadata.json
websites/F/FlaviBot/presence.ts

chore(FlaviBot): update assets

---

websites/R/Roblox/metadata.json
websites/R/Roblox/presence.ts

chore(Roblox): update assets

---

websites/F/FMovies/metadata.json
websites/F/FMovies/presence.ts

- fix(FMovies): fix wrong if/elseif/else
- Resolves #7890
<details>
</details>

fix(FMovies): fix wrong if/elseif/else

---

websites/M/MUBI/metadata.json
websites/M/MUBI/presence.ts

- Fix/Simplify queryselectors
- Change switch to true & pathname.includes
<details>
</details>

fix(MUBI): change switch due to different path layout

---

websites/K/KEXP/metadata.json
websites/K/KEXP/presence.ts

chore(KEXP): update assets

---

websites/M/MUBI/metadata.json
websites/M/MUBI/presence.ts

- Add viewstate for when you're viewing a movie, to display different items.
<details>
</details>

feat(MUBI): add viewState

---

websites/R/Reddit/metadata.json
websites/R/Reddit/presence.ts

- Resolves #7891
<details>
</details>

perf(Reddit): fix switching client, which lags browser

---

websites/R/Reddit/metadata.json
websites/R/Reddit/presence.ts

chore(Reddit): update assets

---

websites/C/ComicK/metadata.json

chore(ComicK): format metadata

---

websites/C/CacaX/metadata.json
websites/C/CacaX/presence.ts

chore(CacaX): update assets

---

websites/S/SlimeRead/metadata.json
websites/S/SlimeRead/presence.ts

add new case branches and change hex color

refactor(SlimeRead): add new case branches and change hex color

---

websites/N/Notespace/metadata.json
websites/N/Notespace/presence.ts

- I wanted to add the multilanguge but i saw that its for when the presence gets 1000+ users
- There is not much right now on the page so only added the pages for now when the app comes out ill add all of the
- The presence is mainly in polish i can change it to english if you want cuz its a polish page
- This url is not 2 months old because it was switched to it from notespace.pl where it was that for 8 months
- main page
- about us page

feat(Notespace): add presence

---

websites/N/Notespace/metadata.json
websites/N/Notespace/presence.ts

chore(Notespace): update assets

---

websites/A/AnimeSuge/metadata.json
websites/A/AnimeSuge/presence.ts

- Resolves #7912
- Change domain; 
- Change to better performing static pages check, with more details;
<details>
</details>

fix(AnimeSuge): fix issues by rewriting presence 

---

websites/P/Planet Minecraft/metadata.json
websites/P/Planet Minecraft/presence.ts

Planet Minecraft is a family friendly community that shares and respects the creative works and interests of others. They have a variety of entertaining ways to explore and upload content, socialize and find like minded creative members from around the world that love the game of Minecraft.
<details>
</details>

feat(Planet Minecraft): add presence

---

websites/A/Animevietsub/metadata.json

Change the url from animevietsub.fan to animevietsub.io
<details>
</details>

fix(Animevietsub): update url

---

websites/0-9/4chan/metadata.json
websites/0-9/4chan/presence.ts

A presence for 4chan.
<details>
</details>

feat(4chan): add presence

---

websites/S/SoundCloud/metadata.json

chore(SoundCloud): format metadata

---

websites/B/BoardGameGeek/metadata.json
websites/B/BoardGameGeek/presence.ts

chore(BoardGameGeek): update assets

---

package-lock.json
package.json

*beep boop* oh wait, I'm not a bot...

chore(deps): bump pmd from 1.2.0 to 1.2.1

---

websites/P/Pinterest/metadata.json
websites/P/Pinterest/presence.ts

- Resolves #7365 ;
- Changes if/else if/else to switch;
- Add buttons & toggle button setting;
- Etc;
<details>
</details>

feat(Pinterest): rewrite presence

---

websites/E/Emberspark Games/metadata.json
websites/E/Emberspark Games/presence.ts

chore(Emberspark Games): update assets

---

websites/P/Pinterest/metadata.json
websites/P/Pinterest/presence.ts

chore(Pinterest): update assets

---

websites/A/Anim/metadata.json
websites/A/Anim/presence.ts
websites/P/Pinterest/metadata.json

chore(Anim): update assets

---

package-lock.json
package.json

chore(deps): bump pmd from 1.2.1 to 1.2.2

---

websites/T/Tumblr/metadata.json
websites/T/Tumblr/presence.ts

- Resolves #7950
- Fix issues;
- Shorten document.location.pathname/hostname/href to variables;
- Change if/else if/else to switch
<details>
</details>

fix(Tumblr): fix issues by rewriting presence

---

websites/P/PreMiD/metadata.json

Downscales the thumbnail from 8k to 1k, cause, wtf??

chore(PreMiD): downscale thumbnail for optimization

---

websites/M/Monos Chinos/metadata.json
websites/M/Monos Chinos/presence.ts

- Resolves #7932
- Fix it not showing the episode number.
<details>
</details>

fix(Mono Chinos): fix episode number not showing

---

websites/P/PreMiD/metadata.json

chore(PreMiD): update assets

---

websites/W/Warriorcats/metadata.json
websites/W/Warriorcats/presence.ts

feat(Warriorcats): add presence

---

websites/Y/YouTube/metadata.json
websites/Y/YouTube/presence.ts
websites/Y/YouTube/util/pvPrivacyUI.ts

Makes button look good on light mode + some minor style tweaks

feat(YouTube): improve pvpui styling

---

websites/S/Secret Hitler/metadata.json
websites/S/Secret Hitler/presence.ts

Resolves #5340 
<details>
</details>

feat(Secret Hitler): add presence

---

websites/S/Secret Hitler/metadata.json
websites/S/Secret Hitler/presence.ts

chore(Secret Hitler): update assets

---

websites/S/Soundgasm/metadata.json
websites/S/Soundgasm/presence.ts

chore(Soundgasm): update assets

---

websites/W/Warriorcats/metadata.json
websites/W/Warriorcats/presence.ts

- Replaced every lowercase letter in the `presenceData.details` with a uppercase letter for the beginning in the commit: https://github.com/NULLYUKI/Presences/commit/c19fd22ce518a1faf041ff0a553bf43466daa0cf
- Updated the version number in the commit: https://github.com/NULLYUKI/Presences/commit/f9af77d73429e7ce520b6e79680ffab0e7f96cba
<details>
Screenshots will follow until I have managed to fix this issue I'm having: 
</details>

style(Warriorcats): Replaced lowercase letter with uppercase letter in the beginning of a sentence

---

websites/A/AniMi Club/iframe.ts
websites/A/AniMi Club/metadata.json
websites/A/AniMi Club/presence.ts

<details>
https://i.imgur.com/HnGyqR6
https://i.imgur.com/54QKVEA
</details>

feat(AniMi Club): added presence

---

websites/W/Warriorcats/metadata.json

style(Warriorcats): update metadata line ending

---

websites/A/AniMi Club/metadata.json
websites/A/AniMi Club/presence.ts

chore(AniMi Club): update assets

---

websites/T/TuneIn/metadata.json
websites/T/TuneIn/presence.ts

- Introduce settings for user customization:
- Language selection
- Privacy mode toggle
- Timestamp visibility toggle
- Cover image display toggle
- Optimize time handling and display
- Address minor inconsistencies with context checks
<details>
</details>

feat(TuneIn): enhance presence functionality

---

.github/CONTRIBUTING.md

- Resolves #7985 
- ^ by changing it to the general.json file, since with graphql we cant really give a link.
- feat: Adds theusaf & timeraa as reviewers
- chore: Removes encrypted as reviewer
- feat: Adds title to reviewer's profile picture
- chore: Updates check images to match current checks & to be higher quality
- style: format file
<details>
n/a
</details>

chore(Contributing.md): fix issues & correct outdated text

---

websites/W/WINDOWS93/iframe.ts
websites/W/WINDOWS93/metadata.json
websites/W/WINDOWS93/presence.ts

Resolves #7316 
<details>
</details>

feat(WINDOWS93): add presence

---

websites/W/WINDOWS93/metadata.json
websites/W/WINDOWS93/presence.ts

chore(WINDOWS93): update assets

---

websites/G/GX.games/metadata.json
websites/G/GX.games/presence.ts

Resolves #8001 
<details>
</details>

feat(GX.games): add presence

---

websites/G/GX.games/metadata.json
websites/G/GX.games/presence.ts

chore(GX.games): update assets

---

websites/L/Lazada/metadata.json
websites/L/Lazada/presence.ts

Adding a new presence for Lazada
<details>
</details>

feat(Lazada): add presence

---

websites/L/Lazada/metadata.json
websites/L/Lazada/presence.ts

chore(Lazada): update assets

---

websites/H/HTB Academy/metadata.json
websites/H/HTB Academy/presence.ts

chore(HTB Academy): update assets

---

websites/S/SOAP2DAY/metadata.json

I just added the domain
<details>
</details>

feat(Soap2Day) added new Domain

---

websites/S/SOAP2DAY/metadata.json

chore(SOAP2DAY): format metadata

---

websites/S/Shikimori/metadata.json
websites/S/Shikimori/presence.ts

1. Changed URL of [Shikimori](https://shikimori.one/): shikimori.me-> shikimori.one, regExp.
2. Removed useless context words.
3. Fixed some pages.
<details>
| Home | User's Page |
| --- | --- | 
| ![image](https://github.com/PreMiD/Presences/assets/37224822/2db8ec23-a19a-41d9-909a-409ec5134026) | ![image](https://github.com/PreMiD/Presences/assets/37224822/fed421eb-13ed-4e3c-af4e-ad79f9dfa447) | 
| Anime Page | Anime List Page |
| --- | --- | 
| ![image](https://github.com/PreMiD/Presences/assets/37224822/f7d2143f-8098-4d6c-835c-e070b9174dc6) | ![image](https://github.com/PreMiD/Presences/assets/37224822/b5346b6f-2e41-4259-bef3-62d8756916b8) |
</details>

fix(Shikimori): new domain, rewrite presence

---

websites/D/Docchi/iframe.ts
websites/D/Docchi/metadata.json
websites/D/Docchi/presence.ts

Polsih library-website with anime series and movies.

feat(Docchi): add presence

---

websites/D/Docchi/metadata.json
websites/D/Docchi/presence.ts

chore(Docchi): update assets

---

websites/W/WaniKani/metadata.json
websites/W/WaniKani/presence.ts

* Updates selectors for dashboard numbers
* Adds lesson picker details
<details>
</details>

feat(WaniKani): update dashboard selector, add lesson picker details

---

websites/Y/YouTube/metadata.json
websites/Y/YouTube/presence.ts
websites/Y/YouTube/util/index.ts
websites/Y/YouTube/video_sources/api.ts
websites/Y/YouTube/video_sources/default.ts
websites/Y/YouTube/video_sources/embed.ts
websites/Y/YouTube/video_sources/movies.ts
websites/Y/YouTube/video_sources/old.ts
websites/Y/YouTube/video_sources/shorts.ts
websites/Y/YouTube/video_sources/tv.ts

* Fixes #8023 
* Adds an API source which is used if no other sources match
<details>
</details>

feat(YouTube): add api source and fix shorts selectors

---

websites/Y/YouTube Music/metadata.json
websites/Y/YouTube Music/presence.ts

chore(YouTube Music): update assets

---

websites/D/Docchi/metadata.json

added sibnet video player to regex

chore(Docchi): update iframe regex

---

websites/I/IDLIX/metadata.json
websites/I/IDLIX/presence.ts

Updated url and added ActivityType Watching
All idlix urls redirect to https://tv.idlixofficial.co

chore(IDLIX): update url

---

websites/L/Lazada/metadata.json
websites/L/Lazada/presence.ts

Added more domain to support URL for other countries and Imagekeys.
<details>
</details>

feat(Lazada): Added more domain & Imagekeys

---

websites/B/BitView/metadata.json
websites/B/BitView/presence.ts

BitView is a small video repository website in the old YouTube style.
The presence works almost in the same way as the YouTube presence, with some details such as texts or showing the user's image when viewing their channel.

feat(BitView): add presence

---

websites/B/BitView/metadata.json
websites/B/BitView/presence.ts
websites/L/Lazada/metadata.json

chore(BitView): update assets

---

websites/M/ModDB/metadata.json
websites/M/ModDB/presence.ts

Closes #7630
Adds ModDB support
<details>
</details>

feat(ModDB): add ModDB

---

websites/A/AniWatch/metadata.json

chore(AniWatch): update assets

---

websites/M/ModDB/metadata.json
websites/M/ModDB/presence.ts

chore(ModDB): update assets

---

websites/A/Amazon Kindle/metadata.json
websites/A/Amazon Kindle/presence.ts

Addition of Amazon Kindle as a service
<details>
</details>

feat(Amazon Kindle): add presence

---

websites/A/AniCrush/metadata.json
websites/A/AniCrush/presence.ts

chore(AniCrush): update assets

---

websites/A/Amazon Kindle/metadata.json
websites/A/Amazon Kindle/presence.ts

chore(Amazon Kindle): update assets

---

websites/T/TVer/metadata.json
websites/T/TVer/presence.ts

chore(TVer): update assets

---

websites/S/Sorryfield/metadata.json

chore(Sorryfield): format metadata

---

websites/G/Gemini/metadata.json
websites/G/Gemini/presence.ts

chore(Gemini): update assets

---

websites/A/ABEMA/metadata.json
websites/A/ABEMA/presence.ts

feat(ABEMA): add presence

---

websites/A/ABEMA/metadata.json
websites/A/ABEMA/presence.ts

chore(ABEMA): update assets

---

websites/Q/Quaver/metadata.json
websites/Q/Quaver/presence.ts

Resolves #8101
<details>
</details>

feat(Quaver): add presence

---

websites/Q/Quaver/metadata.json
websites/Q/Quaver/presence.ts

chore(Quaver): update assets

---

websites/D/Disney+/metadata.json
websites/N/Netflix/metadata.json
websites/S/SoundCloud/metadata.json
websites/T/Twitch/metadata.json
websites/Y/YouTube Music/metadata.json
websites/Y/YouTube/metadata.json

This is so that I can test and work efficiently on the Extension for Manifest v3.

chore: update default presences to manifest v3 matching

---

websites/D/Disney+/metadata.json
websites/N/Netflix/metadata.json
websites/S/SoundCloud/metadata.json
websites/T/Twitch/metadata.json
websites/Y/YouTube Music/metadata.json
websites/Y/YouTube/metadata.json

chore: format metadata

---

websites/N/neal.fun/metadata.json
websites/N/neal.fun/presence.ts

chore(neal.fun): update assets

---

websites/D/Desu-Online/metadata.json
websites/D/Docchi/metadata.json
websites/V/Vizjer/metadata.json

chore: update meffiu's presences to manifest v3 matching

---

websites/G/Geode/metadata.json
websites/G/Geode/presence.ts

feat(Geode): add presence

---

websites/M/movie-web/metadata.json

chore(movie-web): format metadata

---

websites/G/Geode/metadata.json
websites/G/Geode/presence.ts

chore(Geode): update assets

---

websites/S/Stake/metadata.json
websites/S/Stake/presence.ts

The presence didn't work when using the "Show Balance" option.
-> Fixed balance & currency parsing
<details>
</details>

fix(Stake): fixed balance and currency parsing

---

websites/L/LITT Live/metadata.json
websites/L/LITT Live/presence.ts
websites/S/Stake/metadata.json

chore(LITT Live): update assets

---

websites/T/Tabii/metadata.json
websites/T/Tabii/presence.ts

chore(Tabil): update assets

---

websites/M/MatchBox/metadata.json
websites/M/MatchBox/presence.ts

chore(MatchBox): update assets

---

websites/N/Nebula/metadata.json
websites/N/Nebula/presence.ts

chore(Nebula): update assets

---

websites/A/AnimeYuzu/metadata.json
websites/A/AnimeYuzu/presence.ts

chore(AnimeYuzu): update assets

---

websites/K/KQM/metadata.json
websites/K/KQM/presence.ts

Presence for KeqingMains (KQM); a Genshin Impact guides website
<details>
</details>

feat(KQM): add presence

---

websites/K/KQM/metadata.json
websites/K/KQM/presence.ts

chore(KQM): update assets

---

websites/I/Incels.is/metadata.json
websites/I/Incels.is/presence.ts

chore(Incels.is): update assets

---

websites/U/uwowocosplay/metadata.json
websites/U/uwowocosplay/presence.ts

Displays what you look at and where on the page you are.
Also displays the image of the thing you are looking at right now
<details>
I have split the Name of the Cosplay in the half of the words. If i should not do that, just tell me.
Due to fact of having all Infos and no real way of getting a consistent short name, it is made like this.
</details>

feat(Uwowocosplay): add presence

---

websites/R/Rate Your Music/metadata.json
websites/R/Rate Your Music/presence.ts

chore(Rate Your Music): update assets

---

websites/D/diziwatch/metadata.json
websites/D/diziwatch/presence.ts

A plugin for the movie/anime platform diziwatch.net
- [✔️ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [✔️ ] I linted the code by running `yarn format`
- [✔️ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

feat(DIZIWATCH): add presence 

---

websites/U/uwowocosplay/metadata.json
websites/U/uwowocosplay/presence.ts

chore(uwowocosplay): update assets

---

websites/D/diziwatch/metadata.json
websites/D/diziwatch/presence.ts

chore(diziwatch): update assets

---

websites/U/uwowocosplay/metadata.json
websites/U/uwowocosplay/presence.ts

Re-do of #8180 since my Branch was kinda funky.
Presence was strangely broken and then randomly worked.
Made it persistent, since i initially hated the way i did it in the first place. Yall merged faster than i could fix it today haha
<details>
Old one, currently in store:
</details>

feat(uwowocosplay): fix presence bug

---

websites/M/meow.camera/metadata.json
websites/M/meow.camera/presence.ts

feat(meow.camera): added presense

---

websites/M/MyOnlineRadio/metadata.json
websites/M/MyOnlineRadio/presence.ts

chore(MyOnlineRadio): update assets

---

websites/Z/ZenMarket/metadata.json
websites/Z/ZenMarket/presence.ts

chore(ZenMarket): update assets

---

websites/L/Library of Babel/metadata.json

chore(Library of Babel): format metadata

---

websites/C/ComicK/metadata.json
websites/C/ComicK/presence.ts

The URL of the website had changed and the layout also changed slightly. Closes #8163 
<details>
</details>

feat(ComicK): fix presence and update url (#8163)

---

websites/R/RadiosNet/metadata.json
websites/R/RadiosNet/presence.ts

**EN**: The most famous radio aggregator on the Brazilian Internet, active since 1997.
**PT-BR**: O agregador de rádios mais famoso da internet brasileira, em atividade desde 1997.
<details>
</details>

feat(RadiosNet): add presence

---

websites/P/Poke/metadata.json
websites/P/Poke/presence.ts

chore(Poke): update assets

---

websites/R/RadiosNet/metadata.json
websites/R/RadiosNet/presence.ts

chore(RadiosNet): update assets

---

websites/M/Mahjong Soul/game_variables.ts
websites/M/Mahjong Soul/metadata.json
websites/M/Mahjong Soul/presence.ts
websites/M/Mahjong Soul/util.ts

- Adds a presence for the Mahjong Soul website/game.
- Resolves #5456
<details>
</details>

feat(Mahjong Soul): add presence

---

websites/M/Mahjong Soul/metadata.json
websites/M/Mahjong Soul/presence.ts

chore(Mahjong Soul): update assets

---

websites/J/Japanese Mahjong Wiki/metadata.json
websites/J/Japanese Mahjong Wiki/presence.ts

chore(Japanese Mahjong Wiki): update assets

---

websites/D/Daily Mail/metadata.json
websites/D/Daily Mail/presence.ts

chore(Daily Mail): update assets

---

websites/S/Score Saber/metadata.json
websites/S/Score Saber/presence.ts

Made it less likely to show undefined stuff when switching pages.
Added matches to metadata.
Changed enum to Record<string, string>
<details>
</details>

fix(Score Saber): qol fixes

---

websites/I/Incels.is/metadata.json
websites/I/Incels.is/presence.ts

I did this before but I was dumb and didn't reset, so commits from other issues were included
<details>
</details>

fix(Incels.is): nsfw fix

---

websites/C/Character.AI/metadata.json
websites/C/Character.AI/presence.ts

I added support for the new website while maintaining support for the old website now found at https://old.character.ai and cleaned up the code base.
<details>
</details>

fix(c.ai): added support for the new website

---

websites/B/BeatLeader/metadata.json
websites/B/BeatLeader/presence.ts

Fixed broken map cover images because of move to webp
Fixed April
Less undefined when switching between pages
<details>
</details>

fix(Beatleader): qol fixes

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/service_request.yml

- Removes nsfw section from service template
- Updates guidelines 
- Removes certain rules which are no longer applicable
- Fixes some grammatical issues
- Adds new metadata sections
- Adds additional common rules and guidelines during developmennt
</details>

feat(Documentation): update guidelines and templates

---

websites/A/Anix/iframe.ts
websites/A/Anix/metadata.json
websites/A/Anix/presence.ts

Closes #7519 
<details>
</details>

feat(Anix): add presence

---

websites/A/Anix/metadata.json
websites/A/Anix/presence.ts

chore(Anix): update assets

---

websites/T/Tinkercad/metadata.json
websites/T/Tinkercad/presence.ts

chore(Tinkercad): update assets

---

websites/K/Kittensgame/metadata.json
websites/K/Kittensgame/presence.ts

chore(Kittensgame): update assets

---

websites/E/EWAIFU/metadata.json
websites/E/EWAIFU/presence.ts

chore(EWAIFU): update assets

---

websites/J/Just Dance Now/metadata.json

chore(Just Dance Now): format metadata

---

websites/I/IDLIX/iframe.ts
websites/I/IDLIX/metadata.json
websites/I/IDLIX/presence.ts

- Fix issues that were created by site changes & by #8044
<details>
</details>

fix(IDLIX): fix presence not working

---

websites/I/IDLIX/metadata.json

chore(IDLIX): format metadata

---

websites/N/notespace/metadata.json

chore(notespace): format metadata

---

websites/F/fbox.to/metadata.json
websites/F/fbox.to/presence.ts

fix(fbox): finds data correctly now

---

websites/W/Wcostream/iframe.ts
websites/W/Wcostream/metadata.json
websites/W/Wcostream/presence.ts

Resolves #8268
<details>
</details>

fix(WCOStream): fix presence & remove broken code

---

websites/T/The Mahjong/metadata.json
websites/T/The Mahjong/presence.ts

closes #8270 
<details>
</details>

feat(The Mahjong): add presence

---

websites/T/The Mahjong/metadata.json
websites/T/The Mahjong/presence.ts

chore(The Mahjong): update assets

---

package-lock.json
websites/T/TOD/metadata.json
websites/T/TOD/presence.ts

**EN**: TOD is a video-streaming platform which includes a lot of movies, TV shows and matches provided by BeIN.
**AR**: تود هى منصة بث فيديو حيث تحتوي على الكثير من الأفلام والمسلسات والمباريات المقدمة من بي إن.
<details>
With playing status:
</details>

feat(TOD): add presence

---

websites/T/TOD/metadata.json
websites/T/TOD/presence.ts

chore(TOD): update assets

---

websites/R/Reddit/metadata.json
websites/R/Reddit/presence.ts

- Updates selectors for new layout
- Fixes #8293
<details>
</details>

fix(Reddit): update selectors

---

websites/S/Stake.us/metadata.json
websites/S/Stake.us/presence.ts
websites/T/TOD/metadata.json

chore(Stake.us): update assets

---

websites/Y/YouTube/video_sources/miniplayer.ts

chore(YouTube): format miniplayer resolver code

---

websites/C/CHZZK/metadata.json
websites/C/CHZZK/presence.ts

User want it to be a separate Presence, they don't want to show other Naver services
<details>
</details>

feat(CHZZK): add presence

---

websites/N/Naver/metadata.json
websites/N/Naver/presence.ts

chore(Naver): update assets

---

websites/F/Four Winds Mah Jong/metadata.json
websites/F/Four Winds Mah Jong/pages/knowledge.ts
websites/F/Four Winds Mah Jong/pages/pocketpc.ts
websites/F/Four Winds Mah Jong/pages/ppc.ts
websites/F/Four Winds Mah Jong/pages/store.ts
websites/F/Four Winds Mah Jong/presence.ts

- Adds a presence for 4windsmahjong.com, a somewhat old website with some useful information
<details>
</details>

feat(Four Winds Mahjong): add presence

---

websites/P/Pub/metadata.json
websites/P/Pub/presence.ts

Adds a presence for the dart/flutter package repository, Pub.
<details>
</details>

feat(Pub): add presence

---

websites/K/Kotobade Asobou/metadata.json
websites/K/Kotobade Asobou/presence.ts
websites/K/Kotobade Asobou/strings.ts

Adds a presence for Kotobade Asobou, a Japanese version of the Wordle game
<details>
</details>

feat(Kotobade Asobou): add presence

---

websites/M/Minecraft Wiki/metadata.json

chore(Minecraft Wiki): update assets

---

websites/F/Four Winds Mah Jong/metadata.json
websites/F/Four Winds Mah Jong/presence.ts

chore(Four Winds Mah Jong): update assets

---

websites/K/Kotobade Asobou/metadata.json
websites/K/Kotobade Asobou/presence.ts

chore(Kotobade Asobou): update assets

---

websites/P/Pub/metadata.json
websites/P/Pub/presence.ts

chore(Pub): update assets

---

websites/M/meow.camera/metadata.json
websites/M/meow.camera/presence.ts

Fixed if checks for stats such that missing stats will not prevent the whole thing from not being shown. Replaced temperature with local time since that seems to have been removed.
<details>
Proof showing updated stat section with local time and full stats
Proof showing stats still show even if some stats are missing
</details>

fix(meow.camera): fixed stats, added local time

---

websites/W/watch.lonelil.com/metadata.json

I added some additional URLs (see issue below)
<details>
</details>
Resolves https://github.com/PreMiD/Presences/issues/8208
also a possible fix for https://github.com/PreMiD/Presences/issues/8021

fix(watch.lonelil.com): added additional urls

---

websites/I/IDLIX/metadata.json
websites/I/IDLIX/presence.ts

fix presence and fix issues
<details>
</details>

fix(IDLIX): rewrite presence & fix issues

---

websites/S/Stremio/metadata.json
websites/S/Stremio/presence.ts

Updated the logo to the latest version.
Old:
New:

chore(Stremio): update logo

---

websites/S/Stremio/metadata.json
websites/S/Stremio/presence.ts

chore(Stremio): update assets

---

websites/A/AnimeDrive/metadata.json
websites/A/AnimeDrive/presence.ts

chore(AnimeDrive): update assets

---

websites/W/WriterDuet/metadata.json
websites/W/WriterDuet/presence.ts

chore(WriterDuet): update assets

---

websites/P/Podurama/metadata.json
websites/P/Podurama/presence.ts

chore(Podurama): update assets

---

websites/V/Videoland/metadata.json
websites/V/Videoland/presence.ts

- Fix issues
<details>
</details>

chore(Videoland): rewrite presence & fix null & undefined issues

---

websites/A/Animeflix/metadata.json

chore(Animeflix): format metadata

---

websites/R/Replit/metadata.json
websites/R/Replit/presence.ts

Resolves #8218 
rewrite presence to fix issues
<details>
</details>

fix(Replit): rewrite presence to fix issues

---

websites/R/Replit/metadata.json
websites/R/Replit/presence.ts

chore(Replit): update assets

---

websites/I/Indavideó/iframe.ts
websites/I/Indavideó/metadata.json
websites/I/Indavideó/presence.ts

Added presence for indavideo.hu.
Supported routes: /, /search, /video, /myprofile/basicdata, /myprofile/customize, /myprofile/myvideos, /myprofile/mylooprs, /myprofile/myplaylists, /myprofile/mywatchlater, /myprofile/mysubscribes, /myprofile/stripfactory
Supported subdomains: auto.indavideo.hu, film.indavideo.hu, csimota.indavideo.hu, palyazat.indavideo.hu, upload.indavideo.hu
<details>
</details>

feat(Indavideó): add presence

---

websites/C/Cosmote TV/metadata.json
websites/C/Cosmote TV/presence.ts

fix title not showing on live tv, and fix on-demand content not showing at all
<details>
</details>

fix(Cosmote TV): fix title

---

websites/S/Sorryfield/metadata.json
websites/S/Sorryfield/presence.ts

Corresponding to Sorryfield 1.11.0 update
(Category edited, Today's pick system)
<details>
</details>

feat(Sorryfield): update presence for 1.11.0 update

---

websites/S/Sorryfield/metadata.json
websites/S/Sorryfield/presence.ts

chore(Sorryfield): update assets

---

websites/I/Indavideó/metadata.json
websites/I/Indavideó/presence.ts

chore(Indavideó): update assets

---

websites/T/Threads/metadata.json
websites/T/Threads/presence.ts

Add Threads presence
<details>
</details>

feat(Threads): add presence

---

websites/T/Threads/metadata.json
websites/T/Threads/presence.ts

chore(Threads): update assets

---

websites/P/pokerogue/metadata.json
websites/P/pokerogue/presence.ts

Resolves #8357
- Add presence
<details>
</details>

feat(PokeRogue): add presence

---

websites/P/PokeRogue/metadata.json
websites/P/PokeRogue/presence.ts

chore(PokeRogue): update assets

---

websites/G/Game8/metadata.json
websites/G/Game8/presence.ts

Adds support for Game8, a game wiki website.
<details>
</details>

feat(Game8): add presence

---

websites/G/Game8/metadata.json
websites/G/Game8/presence.ts

chore(Game8): update assets

---

websites/D/Disney+/metadata.json
websites/D/Disney+/presence.ts

This PR fixes all functionality of the Disney+ presence. Some translations are missing but they were already missing before now.
- Fixes #8060 
- Fixes #7933 
- Fixes #7531 
<details>
</details>

fix(Disney+): update broken selectors, fix functionality

---

websites/D/Dropout/metadata.json
websites/D/Dropout/presence.ts

chore(Dropout): update assets

---

websites/C/Codewars/metadata.json

chore(Codewars): format metadata

---

websites/T/The Mahjong/metadata.json
websites/T/The Mahjong/presence.ts

This PR adds support for other languages, fixes #8390 
<details>
</details>

fix(The Mahjong): add support for language routes

---

websites/M/Masuru/metadata.json
websites/M/Masuru/presence.ts

chore(Masuru): update assets

---

websites/H/Hoppscotch/metadata.json
websites/H/Hoppscotch/presence.ts

chore(Hoppscotch): update assets

---

websites/S/SoundCloud/metadata.json
websites/S/SoundCloud/presence.ts

Could resolve #8412 (it did on my end)
<details>
</details>

fix(SoundCloud): fix only showing browsing

---

websites/C/ChatGPT/metadata.json

chore(ChatGPT): format metadata

---

websites/P/Prime Video/metadata.json

chore(Prime Video): format metadata

---

websites/N/Netflix/functions/fetchMetadata.ts
websites/N/Netflix/functions/getBuildIdentifier.ts
websites/N/Netflix/metadata.json
websites/N/Netflix/package-lock.json
websites/N/Netflix/package.json
websites/N/Netflix/presence.ts
websites/N/Netflix/types.ts

A full recode of the Netflix Presence to make it much more reliable and work on 2.6.0. Now using the Netflix internal API.
<details>
(Images have strings because PR needs to be merged)
</details>
Needs https://github.com/PreMiD/Localization/pull/7415

chore(netflix): recode presence

---

websites/H/Hoppscotch/metadata.json
websites/H/Hoppscotch/presence.ts
websites/H/Hoppscotch/routes/profile.ts
websites/H/Hoppscotch/routes/rest.ts

This PR introduces multiple changes, including:
1. Add profile route & asset
2. fix URL instantiation bug in `rest` route (when using environment variables)
3. Hide query params by default (when using environment variables)
<details>
</details>

feat(Hoppscotch): add profile route

---

websites/N/NPO Start/metadata.json
websites/N/NPO Start/presence.ts

Resolves #5279
<details>
</details>

feat(NPO Start): add presence

---

websites/P/Panzoid/metadata.json
websites/P/Panzoid/shared.ts

chore(Panzoid): update assets

---

websites/V/Voirdrama/metadata.json
websites/V/Voirdrama/presence.ts

chore(Voirdrama): update assets

---

websites/W/Wolfery/metadata.json
websites/W/Wolfery/presence.ts

chore(Wolfery): update assets

---

websites/D/Deezer/metadata.json

Updated so that it contains the updated Deezer logo and website
What it does is basically changing the old logo and background image into the new Deezer format, and also the toggle switch color to the new color scheme
<h1>New Background:</h1>
<h1>New Logo:</h1>
<h1>New Color:</h1>

feat(Deezer): update metadata.json adding new visuals

---

websites/P/PokeRogue/metadata.json
websites/P/PokeRogue/presence.ts

feat(PokeRogue): add localhost ip since u can run it locally
<details>
</details>

feat(PokeRogue): add localhost ip

---

websites/A/Apple Music/metadata.json
websites/D/Deezer/metadata.json
websites/P/PokeRogue/metadata.json

chore: format metadatas

---

websites/S/Skribbl.io/metadata.json

Specifies the kahoot localization files to include the button string

fix(Skribbl.io): adjust multiLanguage setting

---

websites/D/Deezer/metadata.json

chore(Deezer): update assets

---

websites/A/Animevietsub/metadata.json

chore(Animevietsub): update domain

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

Resolves #6023
Resolves #7852
<details>
</details>

feat(BBC): use new activity types & new assets

---

websites/L/LiveATC/metadata.json
websites/L/LiveATC/presence.ts

feat(LiveATC): add presence

---

websites/H/HDrezka/metadata.json
websites/H/HDrezka/presence.ts

chore(HDrezka): update assets

---

websites/C/Codeberg/metadata.json
websites/C/Codeberg/presence.ts

This pull requests adds a presence for Codeberg (https://codeberg.org), it adds presences for _almost_ every page on the site, it does not have presences for files, specific issues/PRs, and profile ?tab (or /-/) paths.
<details>
</details>

feat: add Codeberg presence

---

websites/D/daily.dev/metadata.json
websites/D/daily.dev/presence.ts

feat(daily.dev): add rich presence

---

websites/A/Animevietsub/metadata.json

chore(Animevietsub): format metadata

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

chore(BBC): update assets

---

websites/L/LiveATC/metadata.json
websites/L/LiveATC/presence.ts

chore(LiveATC): update assets

---

websites/D/daily.dev/metadata.json
websites/D/daily.dev/presence.ts

chore(daily.dev): update assets

---

websites/A/Anime Genzai/metadata.json
websites/A/Anime Genzai/presence.ts

Resolve #8439
<details>
| Explore | Search |
| --- | --- |
| ![image](https://github.com/PreMiD/Presences/assets/37224822/373b4981-ab8a-4349-84fc-eb5237ab7ec7) | ![image](https://github.com/PreMiD/Presences/assets/37224822/e6982c12-5bb1-447a-b010-a63e90b81c4b) |
| Anime page | Watching series |
| --- | --- |
| ![image](https://github.com/PreMiD/Presences/assets/37224822/52cb4056-556a-4026-8744-d0949670807b) | ![image](https://github.com/PreMiD/Presences/assets/37224822/81f40929-ed27-464b-891c-38481dbd8d6a) |
</details>

fix(Anime Genzai): update presence

---

websites/A/AWTWA/iframe.ts
websites/A/AWTWA/metadata.json
websites/A/AWTWA/presence.ts

Hello, I added support for french anime streaming website AWTWA.
<details>
</details>

feat(AWTWA): add presence

---

websites/C/Chompu/metadata.json
websites/C/Chompu/presence.ts

chore(Chompu): update assets

---

websites/A/AWTWA/metadata.json
websites/A/AWTWA/presence.ts

chore(AWTWA): update assets

---

websites/N/NIKKE.GG/metadata.json
websites/N/NIKKE.GG/presence.ts

chore(NIKKE.GG): update assets

---

websites/L/League of Angels: Pact/metadata.json
websites/L/League of Angels: Pact/presence.ts

chore(League of Angels: Pact): update assets

---

websites/M/Max/metadata.json
websites/M/Max/presence.ts

Fixes #7371 
<details>
</details>

feat(Max): add presence

---

websites/0-9/7tv/metadata.json
websites/0-9/7tv/presence.ts

chore(7tv): update assets

---

websites/C/CTFtime/metadata.json
websites/C/CTFtime/presence.ts

chore(CTFtime): update assets

---

websites/A/AnimationDigitalNetwork/metadata.json

Added german version
<details>
</details>

feat(AnimationDigitalNetwork): add DE version

---

websites/D/Disney+/metadata.json
websites/D/Disney+/presence.ts

fix(Disney+): fix invalid selectors

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Add id's to the input templates for url direct links

feat: add ids to templates

---

websites/L/LTTStore/metadata.json
websites/L/LTTStore/presence.ts

chore(LTTStore): update assets

---

websites/P/Papara Topluluk/metadata.json
websites/P/Papara Topluluk/presence.ts

They updated the logo. _Not sure if this is the correct way to update the assets._

chore(PaparaTopluluk): update logo url

---

websites/D/Distrokid/metadata.json
websites/D/Distrokid/presence.ts

Finishes #8563
<details>
</details>

feat(DistroKid): add presence

---

websites/P/Papara Topluluk/metadata.json
websites/P/Papara Topluluk/presence.ts

chore(Papara Topluluk): update assets

---

websites/H/HiAnime/metadata.json

chore(HiAnime): update assets

---

websites/D/Distrokid/metadata.json
websites/D/Distrokid/presence.ts

chore(DistroKid): update assets

---

websites/T/Tio Anime/metadata.json
websites/T/Tio Anime/presence.ts

Resolves #8569
<details>
</details>

feat(Tio Anime): add watching type and make code more readable

---

websites/B/BetterAnime/metadata.json
websites/B/BetterAnime/presence.ts

Resolves #8570 
Can't show proof since i don't have an account. but it should just work.
<details>
Can't show proof since i don't have an account. but it should just work.
</details>

feat(BetterAnime): add wachting type and improve some aspects

---

websites/I/iBroadcast/metadata.json
websites/I/iBroadcast/presence.ts

Resolves #8559
add typin listening, cover with setting & improve code
<details>
</details>

feat(iBroadCast): add typing, cover with setting & improve code

---

websites/I/iBroadcast/metadata.json

chore(iBroadcast): format metadata

---

websites/A/AnimeUnity/iframe.ts
websites/A/AnimeUnity/metadata.json
websites/A/AnimeUnity/presence.ts

Add animeUnity, an Italian website for watching anime
<details>
</details>

feat(AnimeUnity): add new presence

---

websites/N/notespace/metadata.json
websites/N/notespace/presence.ts

- added the english part of the site (forgot to do it last time)
- changed how the paths and herfs are checked

feat(notespace): update presence

---

websites/A/AnimeUnity/metadata.json
websites/A/AnimeUnity/presence.ts

chore(AnimeUnity): update assets

---

websites/0-9/9anime/metadata.json
websites/0-9/9anime/presence.ts

chore(9anime): update assets

---

websites/S/Salad/metadata.json
websites/S/Salad/presence.ts

chore(Salad): update assets

---

websites/F/fbox.to/metadata.json

This PR updates the FBOX presence's domain from `fbox.to` to `fboxz.to`.
Resolves #8558
<details>
</details>

fix(FBOX): update domain

---

websites/G/Google Meet/metadata.json
websites/G/Google Meet/presence.ts

Resolves #8608
<details>
</details>

feat(Google Meet): add settings and use a cache

---

websites/D/Disney+/metadata.json
websites/D/Disney+/presence.ts

fix(Disney+): broken timestamp

---

websites/R/Roblox/metadata.json
websites/R/Roblox/presence.ts

- Change some details to the name
- Add ternary operator(s) where needed
<details>
</details>

feat(Roblox): change some details => name & add ternary operator

---

websites/R/RTLplay/metadata.json
websites/R/RTLplay/presence.ts

chore(RTLplay): update assets

---

websites/A/AnimeSaturn/metadata.json
websites/A/AnimeSaturn/presence.ts

AnimeSaturn is a streaming website (italian subbed) for anime
<details>
<summary> Proof showing the creation/modification is working as expected 
</summary>
</details>

feat(AnimeSaturn): add new presence

---

websites/S/StreamingCommunity/iframe.ts
websites/S/StreamingCommunity/metadata.json
websites/S/StreamingCommunity/presence.ts

StreamingCommunity is a website to watch tv series and movies in italian for free
<details>
</details>

feat(StreamingCommunity): add new presence

---

websites/S/StreamingCommunity/metadata.json
websites/S/StreamingCommunity/presence.ts

chore(StreamingCommunity): update assets

---

websites/K/Keymash/metadata.json
websites/K/Keymash/presence.ts

Added missing pages, fixed broken ones and removed now non-existent pages. 
Added buttons where they were useful, with settings to enable/disable.
Updated the domain.
Updated the logo.
Resolves #8454 
<details>
</details>

refactor(Keymash): update presence

---

websites/N/Nitro Type/metadata.json
websites/N/Nitro Type/presence.ts

Added /leagues page descrption.
<details>
</details>

feat(Nitro Type): add leagues page

---

websites/K/Keymash/metadata.json
websites/K/Keymash/presence.ts

chore(Keymash): update assets

---

websites/N/Netflix/metadata.json
websites/N/Netflix/presence.ts

Resolves #8610
<details>
</details>

feat(Netflix): add show cover setting

---

websites/N/Nitro Type/metadata.json

chore(Nitro Type): format metadata

---

websites/K/KOLEO/metadata.json
websites/K/KOLEO/presence.ts
websites/S/StreamingCommunity/metadata.json

feat(KOLEO): add presence

---

websites/M/MangaWorld/metadata.json

Resolves [#7585](https://github.com/PreMiD/Presences/issues/7585)
I updated the domain (the current is  [mangaworld.ac](https://www.mangaworld.ac/))
<details>
</details>

fix(MangaWorld): update domain

---

websites/K/KOLEO/metadata.json
websites/K/KOLEO/presence.ts

chore(KOLEO): update assets

---

websites/#/アイドルマスターシャイニーカラーズ/metadata.json
websites/#/アイドルマスターシャイニーカラーズ/presence.ts

Add some pages.
- /miniGamePortal
- /daifugo
- /characterProfile
<details>
</details>

feat(アイドルマスターシャイニーカラーズ): add some codes

---

websites/K/Kotobade Asobou/metadata.json
websites/K/Kotobade Asobou/presence.ts
websites/K/Kotobade Asobou/strings.ts

When using the Japanese strings, also changes the name of the presence to the Japanese version.
<details>
</details>

feat(Kotobade Asobou): add presence title translation

---

websites/A/AccSaber/metadata.json
websites/A/AccSaber/presence.ts

feat(AccSaber): add presence

---

websites/K/Komik Indo/metadata.json
websites/K/Komik Indo/presence.ts

chore(Komik Indo): update assets

---

websites/A/AccSaber/metadata.json
websites/A/AccSaber/presence.ts

chore(AccSaber): update assets

---

websites/S/StreamingCommunity/metadata.json

The domain has changed so i updated it
<details>
</details>

fix(StreamingCommunity): update domain

---

websites/Y/yabancıdizi/metadata.json

Since the address of the site has been changed, the link of the new site has been corrected and shared.
<details>
</details>

fix(yabancıdizi): update url

---

websites/Y/yabancıdizi/metadata.json

chore(yabancıdizi): format metadata

---

websites/B/bilibili/metadata.json
websites/B/bilibili/presence.ts

Fixed all issues mentioned in #8641 and added some additional improvements.
Specifically: Added support for "Tweets", "Articles", "Playlists", "Messages", and "Live Broadcasts"
<details>
<details>
<summary>Tweets</summary>
<hr>
</details>
<details>
<summary>Articles</summary>
</details>
<details>
<summary>Playlists</summary>
<hr>
</details>
<details>
<summary>Messages</summary>
</details>
<details>
<summary>Live Broadcasts</summary>
</details>
</details>

feat(bilibili): update presence

---

websites/M/MangaGo/metadata.json
websites/M/MangaGo/presence.ts

chore(MangaGo): update assets

---

websites/A/AnimixPlay/metadata.json

chore(AnimixPlay): format metadata

---

websites/A/AnimixPlay/metadata.json
websites/A/AnimixPlay/presence.ts

chore(AnimixPlay): update assets

---

websites/A/Anime Sama/metadata.json
websites/A/Anime Sama/presence.ts

Add cover/thumbnail largeImageKey and watching status
<details>
</details>

feat(Anime Sama): add cover and watching status

---

websites/M/movie-web/metadata.json

feat(movie-web): add more instances

---

websites/T/Twitch/metadata.json
websites/T/Twitch/presence.ts

Fix #8674 
<details>
</details>

fix(Twitch): profile picture doesn't appeaer

---

tools/auto/presenceValidator.ts
tools/classes/PresenceCompiler.ts

Add presence name to warnings/errors for multiple presence PRs.
<details>
Locally:
</details>

feat: validator & compiler provide presence name in errors

---

websites/I/iHeartRadio/metadata.json
websites/I/iHeartRadio/presence.ts

chore(iHeartRadio): update assets

---

websites/A/Apple Podcasts/metadata.json
websites/A/Apple Podcasts/presence.ts

chore(Apple Podcasts): update assets

---

websites/Z/Zoom/metadata.json
websites/Z/Zoom/presence.ts

title says it all.
<details>
Queryselectors etc are the same, so i don't see a need for this..
</details>

perf(Zoom): improve presence code & make it more readable

---

websites/Z/ZeroTwo/metadata.json

n/a tilte says enough
<details>
n/a
</details>

chore(ZeroTwo): change domain to correct one

---

websites/Z/Zerion/metadata.json
websites/Z/Zerion/presence.ts

Fix presence.
<details>
</details>

fix(Zerion): change domain

---

websites/G/Genius/metadata.json
websites/G/Genius/presence.ts

@Bas950 stinkt.
<details>
</details>

fix(Genius): fix presence

---

websites/D/Disney+/metadata.json
websites/D/Disney+/presence.ts

Should work..
See [this convo](https://discord.com/channels/493130730549805057/527675240231206934/1286366576609722500) on Discord
<details>
</details>

fix(Disney+): hotstar not working

---

websites/C/Codeberg/metadata.json
websites/C/Codeberg/presence.ts

chore(Codeberg): update assets

---

websites/S/Shiroko/metadata.json

chore(Shiroko): update assets

---

websites/Y/YouTube/metadata.json
websites/Y/YouTube/presence.ts

feat(Youtube): enable endtimestamp for youtube shorts

---

websites/M/Miruro/metadata.json
websites/M/Miruro/presence.ts

chore(Miruro): update assets

---

websites/S/SoundCloud/metadata.json
websites/S/SoundCloud/presence.ts

fix(SoundCloud): fix errors

---

websites/G/GoPlay/metadata.json

chore(GoPlay): update assets

---

websites/Y/YTPLR/metadata.json
websites/Y/YTPLR/presence.ts

chore(YTPLR): update assets

---

websites/S/StreamingCommunity/metadata.json
websites/Y/YTPLR/metadata.json

chore(StreamingCommunity): format metadata

---

websites/C/Crunchyroll/metadata.json
websites/C/Crunchyroll/presence.ts

feat(Crunchyroll): use watching type

---

websites/W/Watch-Anime/metadata.json
websites/W/Watch-Anime/presence.ts

chore(Watch-Anime): update assets

---

websites/T/TuneIn/metadata.json
websites/T/TuneIn/presence.ts

Fixes #8765 
<details>
</details>

feat(TuneIn): use listening type & fix only show browsing

---

websites/S/Spotify Podcasts/metadata.json
websites/S/Spotify Podcasts/presence.ts

Fixes #8685 
<details>
</details>

feat(Spotify Podcasts): use listening type

---

websites/D/DramaCool/metadata.json
websites/D/DramaCool/presence.ts

Fixes #8781 
<details>
</details>

feat(DramaCool): fix not showing & use watching type

---

websites/C/ChatGPT/metadata.json
websites/D/Docchi/metadata.json

chore(Docchi): format metadata

---

websites/B/Brave Search/metadata.json
websites/B/Brave Search/presence.ts

chore(Brave Search): update assets

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

As the title mentions, I have added a new setting feature "Privacy" which hides the name of the video playing and then I have updated the metadata to "videos" for it to appear as "x is watching ...".
Apparently the holding shift and opening the popup isn't working so no screenshots, but it should work since its not a major change.
<details>
</details>

feat(Physics Wallah): New update, added privacy features and metadata

---

websites/J/Jellyfin/metadata.json
websites/J/Jellyfin/presence.ts

feat(Jellyfin): use new types & support localhost images

---

websites/A/Amazon Kindle/metadata.json

chore(Amazon Kindle): format metadata

---

websites/K/Kick/metadata.json
websites/K/Kick/presence.ts

chore(Kick): format code

---

websites/Y/YouTube Music/metadata.json
websites/Y/YouTube Music/presence.ts

Resolves issues.
<details>
Before:
0-0
After:
</details>

fix(Youtube Music): resolve issues

---

websites/W/Weverse/metadata.json

chore(Weverse): format metadata

---

websites/V/Voiranime/metadata.json
websites/V/Voiranime/presence.ts

Add multilanguage, watching status, privacy mode, show buttons settings && show timestamps settings
<details>
With privacy mode off:
With privacy mode on :
</details>

feat(Voiranime): add privacy mode && show button/show timestamp settings

---

websites/T/TuMangaOnline/metadata.json

Add new domain because it has changed
<details>
</details>

fix(TuMangaOnline): update domain

---

websites/B/bol.com/metadata.json
websites/B/bol.com/presence.ts

- Rewrite presence;
- Add settings;
- Fix issues due to layout change;
<details>
</details>

feat(Bol.Com): rewrite presence & add settings & fixes

---

websites/B/bol.com/metadata.json

chore(bol.com): format metadata

---

websites/C/Chompu/metadata.json
websites/C/Chompu/presence.ts

feat(Chompu): switch presence to listening type

---

websites/T/TwitCasting/metadata.json
websites/T/TwitCasting/presence.ts

resolves #8681
<details>
</details>

feat(TwitCasting): streaming and profile implementation

---

websites/A/AniCrush/metadata.json
websites/A/AniCrush/presence.ts

resolves #8728
<details>
</details>

feat(AniCrush): watching activity, anime cover as large image

---

websites/B/Board Game Arena/metadata.json
websites/B/Board Game Arena/presence.ts

fixes #8847
<details>
</details>

fix(Board Game Arena): fix undefined name for games

---

websites/Z/ZDFmediathek/metadata.json
websites/Z/ZDFmediathek/presence.ts

resolves #7311 
<details>
</details>

fix(ZDFmediathek): fix videos and video data not found

---

websites/C/Chompu/metadata.json
websites/Y/YTPLR/metadata.json

chore(YTPLR): format metadata

---

websites/J/Jummbox/metadata.json

close #8664
<details>
</details>

fix(Jummbox): update url

---

websites/R/RTL+/metadata.json

close #8863
<details>
</details>

fix(RTL+): change domain

---

websites/G/Gemini/metadata.json

chore(Gemini): format metadata

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

The website had changed a few things so the thing wasn't working, the code is mildly updated and everything works
<details>
</details>

fix(Physics Wallah): Website updated

---

websites/Y/YNOProject/metadata.json
websites/Y/YNOProject/presence.ts

chore(YNOProject): update assets

---

websites/W/Wcostream/metadata.json

chore(Wcostream): format metadata

---

websites/B/BeatLeader/metadata.json

chore(BeatLeader): format metadata

---

websites/B/BeatLeader/metadata.json
websites/L/LessWrong/metadata.json
websites/L/LessWrong/presence.ts

chore(LessWrong): update assets

---

websites/C/CacaX/metadata.json
websites/C/CacaX/presence.ts

I added a new page + fix profil page + update metadata (from cacax.fun to cacax.fr)
<details>
</details>

chore(CacaX): update metada + fixs

---

websites/Z/Zaiko/metadata.json
websites/Z/Zaiko/presence.ts

chore(Zaiko): update assets

---

websites/A/AniLibria/metadata.json
websites/A/AniLibria/presence.ts

Added presence for [AniLibria](https://anilibria.top/).
<details>
[Screenshots](https://imgur.com/a/ToYqjdl)
idk, I couldn't directly paste the images into github.
</details>

feat(AniLibria): add presence

---

websites/0-9/1anime/metadata.json
websites/0-9/1anime/presence.ts

Initial commit for a 1anime presence (Support play/pause state, current anime being watched and episode count).
- [ X ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ X ] I linted the code by running `yarn format`
- [ X ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)

feat(1Anime): Add presence

---

websites/C/Club Penguin Journey/metadata.json
websites/C/Club Penguin Journey/presence.ts

Added presence for [Club Penguin Journey](https://cpjourney.net/).
<details>
</details>

feat(Club Penguin Journey): Add presence

---

websites/A/AniLibria/metadata.json
websites/A/AniLibria/presence.ts

chore(AniLibria): update assets

---

websites/M/myCANAL/metadata.json
websites/M/myCANAL/presence.ts

- Youth category detection added
- Resize content image.
<details>
</details>

fix(Mycanal): Better detection + crop thumbnail

---

websites/0-9/1anime/metadata.json
websites/0-9/1anime/presence.ts
websites/A/AniLibria/metadata.json

chore(1anime): update assets

---

websites/A/AniLibria/metadata.json
websites/C/Club Penguin Journey/metadata.json
websites/C/Club Penguin Journey/presence.ts

chore(Club Penguin Journey): update assets

---

websites/M/myCANAL/metadata.json
websites/P/PlanetXO/metadata.json
websites/P/PlanetXO/presence.ts

chore(PlanetXO): update assets

---

websites/A/AniLibria/metadata.json
websites/W/Websim/metadata.json
websites/W/Websim/presence.ts

Initial commit for a new presence
Last Pull, No Changes were made. See https://github.com/PreMiD/Presences/pull/8942

feat(Websim): Add presence

---

websites/W/Websim/metadata.json
websites/W/Websim/presence.ts

chore(Websim): update assets

---

websites/K/KBHGames/metadata.json
websites/K/KBHGames/presence.ts

- Added presence for [KBHGames](https://kbhgames.com). Requested via Issue #8933 
- Adds images for game playing as Large Image, gets from the css style in <head> because it spouts errors out if gotten from page as it removes it after game is started. 
- Also adds a button to view game currently being played.
- [ x ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ x ] I linted the code by running `yarn format`
- [ x ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>

feat(KBHGames): Add presence

---

websites/T/Twitch/metadata.json
websites/T/Twitch/presence.ts

fix(Twitch): fix show pfp option
<details>
</details>

fix(Twitch): fix show pfp option

---

websites/K/KBHGames/metadata.json
websites/K/KBHGames/presence.ts

chore(KBHGames): update assets

---

websites/S/Skribbl.io/metadata.json
websites/S/Skribbl.io/presence.ts

https://github.com/PreMiD/Localization/pull/7506

feat(Skribbl.io): change multiLanguage setting

---

websites/W/watch.lonelil.com/metadata.json
websites/W/watch.lonelil.com/presence.ts

https://github.com/PreMiD/Localization/pull/7507

feat(watch.lonelil.com): change multiLanguage setting

---

websites/E/Edgenuity/metadata.json
websites/E/Edgenuity/presence.ts

fix(Edgenuity): fixed player detection

---

websites/G/Genius/metadata.json

chore(Genius): update assets

---

websites/S/StudyStream/metadata.json
websites/S/StudyStream/presence.ts

feat(StudyStream): add presence

---

websites/J/jut.su/metadata.json
websites/J/jut.su/presence.ts

feat(jut.su): add cover art and change activity type to watching

---

websites/L/LessWrong/metadata.json

chore(LessWrong): format metadata

---

websites/S/StudyStream/metadata.json
websites/S/StudyStream/presence.ts

chore(StudyStream): update assets

---

websites/T/TuneIn/metadata.json
websites/T/TuneIn/presence.ts

Resolves #8983 
<details>
</details>

fix(TuneIn): fix presence not working with switch stations

---

websites/S/Sorryfield/metadata.json
websites/S/Sorryfield/presence.ts

- added startTimestamp
- added chart (by song) list page
<details>
</details>

feat(Sorryfield): add startTimestamp and chart (by song) list page

---

websites/I/Incels.is/metadata.json

chore(Incels.is): format metadata

---

websites/S/StreamEast/metadata.json
websites/S/StreamEast/presence.ts

This PR adds presence for the popular sports streaming platform, StreamEast.
<details>
</details>

feat(StreamEast): add presence

---

websites/S/StreamEast/metadata.json
websites/S/StreamEast/presence.ts

chore(StreamEast): update assets

---

websites/Y/Yandex Music/metadata.json
websites/Y/Yandex Music/presence.ts

feat(Yandex Music): rewrite presence

---

websites/S/Studio.Design/metadata.json
websites/S/Studio.Design/presence.ts

Add presence for the no-code website design tool, Studio.Design.
<details>
</details>

feat(Studio.Design): add presence

---

websites/C/CHZZK/metadata.json
websites/C/CHZZK/presence.ts

- fixed stream info
<details>
</details>

fix(CHZZK): stream info not show

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/service_request.yml

Update GitHub issue template
<details>
</details>

chore(issue_template): change github issue template (presence to activity)

---

websites/S/Studio.Design/metadata.json
websites/S/Studio.Design/presence.ts

chore(Studio.Design): update assets

---

websites/Z/Zombies World Records/metadata.json
websites/Z/Zombies World Records/presence.ts

feat(Zombies World Records): add presence

---

websites/H/HEO Systems/metadata.json
websites/H/HEO Systems/presence.ts

feat(HEO Systems): add presence

---

websites/C/CHZZK/metadata.json

chore(CHZZK): format metadata

---

websites/R/Royal Road/metadata.json
websites/R/Royal Road/presence.ts

chore(Royal Road): update assets

---

websites/G/GoPlay/metadata.json
websites/G/GoPlay/presence.ts

Fixes #9046 
<details>
</details>

feat(GoPlay): use watching type & remove settings

---

websites/A/AnimeLib/lib.ts
websites/A/AnimeLib/metadata.json
websites/A/AnimeLib/presence.ts

chore(AnimeLib): update assets

---

websites/A/AnimeLib/lib.ts
websites/Z/Zombies World Records/metadata.json
websites/Z/Zombies World Records/presence.ts

chore(Zombies World Records): update assets

---

websites/D/DMOJ/metadata.json

This updates the developer of the presence to my new discord account.

chore(DMOJ): update discord account

---

websites/A/AnimeLib/lib.ts
websites/A/AnimeLib/metadata.json
websites/A/AnimeLib/presence.ts

types(AnimeLib): improve typings in lib.ts
refactor(AnimeLib): make lib.ts more readable
chore(AnimeLib): add new tags in metadata.json
<details>
</details>

feat(AnimeLib): add privacy mode for 'reviews' case

---

websites/Z/Zalando/metadata.json
websites/Z/Zalando/presence.ts

rewrite activity:
- Add buttons + Settings;
- Update strings;
- Better/Shorter selectors;
- Change to switch instead of elseif;
<details>
</details>

chore(Zalando): rewrite activity

---

websites/D/Dek-d/metadata.json
websites/D/Dek-d/presence.ts

chore(Dek-d): update assets

---

websites/S/Sushi Scan/metadata.json
websites/S/Sushi Scan/presence.ts

Added a presence for the website https://sushiscan.net/

feat(Sushi Scan): add presence

---

websites/S/SOOP/metadata.json
websites/S/SOOP/presence.ts

Resolves #8926 
<details>
</details>

feat(SOOP): add activity

---

websites/W/WeTV/metadata.json
websites/W/WeTV/presence.ts

Fixes #8510 
<details>
</details>

feat(WeTV): add cover image setting and refactor activity logic

---

websites/A/AnimeLib/metadata.json

chore(AnimeLib): format metadata

---

websites/F/Freek/metadata.json
websites/F/Freek/presence.ts

chore(Freek): update assets

---

websites/S/Sushi Scan/metadata.json
websites/S/Sushi Scan/presence.ts

chore(Sushi Scan): update assets

---

websites/S/SOOP/metadata.json
websites/S/SOOP/presence.ts
websites/S/Sushi Scan/metadata.json

chore(SOOP): update assets

---

.github/workflows/crowdin.yml

Avoid running on forks
<details>
</details>

chore: add conditional check for repository owner in Crowdin workflow

---

websites/A/Apple TV+/metadata.json
websites/A/Apple TV+/presence.ts

feat(Apple TV+): rewrite activity

---

websites/D/Desu-Online/metadata.json
websites/D/Desu-Online/presence.ts

- 2.6 watching activity type
- privacy and buttons switchable settings
- removed pages that no longer exist
- use of switch case
- minor display fixes
<details>
<summary> Without privacy enabled </summary>
</details>
<details>
<summary> With privacy enabled </summary>
</details>

feat(Desu-Online): update presence

---

websites/C/Cineby/api.ts
websites/C/Cineby/metadata.json
websites/C/Cineby/presence.ts

Resolves #8999 
Resolves #9084 
<details>
</details>

feat(Cineby): add activity

---

websites/S/SoundCloud/metadata.json
websites/S/SoundCloud/presence.ts

chore(SoundCloud): only show small image on pause

---

websites/P/PlanetXO/metadata.json

- [ ✅ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ✅ ] I linted the code by running `yarn format`
- [ ✅ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>

chore(PlanetXO): Removed unneeded metadata.

---

websites/S/Sflix/metadata.json
websites/S/Sflix/presence.ts

chore(Sflix): update assets

---

websites/P/PlanetXO/metadata.json

chore(PlanetXO): format metadata

---

websites/C/Cineby/metadata.json
websites/C/Cineby/presence.ts
websites/S/Sflix/metadata.json

chore(Cineby): update assets

---

websites/A/AnimeUnity/metadata.json

Update url because it has change
close #9092 
<details>
</details>

fix(AnimeUnity): update outdated url

---

websites/A/AnimeUnity/metadata.json

chore(AnimeUnity): format metadata

---

websites/F/Freek/metadata.json

This pr implements the following:
- Improved iframe regex, as I forgot that there are mutliple sources. 
- Doesn't include all sources, as there are a multitude of backup up sources that are rarely used.
<details>
</details>

feat(Freek): add more sources to iframe regex

---

websites/T/Trakt/metadata.json
websites/T/Trakt/presence.ts

This pr implements the following:
- Resolves #8859 
<details>
</details>

feat(Trakt): display show and movie covers

---

websites/A/AnimeSaturn/metadata.json

fix(AnimeSaturn): update domain

---

websites/G/Granblue Fantasy/metadata.json
websites/G/Granblue Fantasy/presence.ts

chore(Granblue Fantasy): update assets

---

websites/A/AnimeSaturn/metadata.json

chore(AnimeSaturn): format metadata

---

websites/P/PCGamingWiki/metadata.json
websites/P/PCGamingWiki/presence.ts

chore(PCGamingWiki): update assets

---

websites/G/Google Play/metadata.json

Removes the regex as it's just plain wrong
<details>
</details>

chore(Google Play): remove regExp

---

websites/A/ArcViewer/metadata.json
websites/A/ArcViewer/presence.ts

Added timestamps and switched to Watching to show the time bar
Fixed 360 and 90 small images
Fixed state not showing anything
<details>
</details>

feat(ArcViewer): add timebar and fixes

---

websites/P/PlanetXO/metadata.json
websites/P/PlanetXO/presence.ts

Updated it so /player will show as "Viewing Player" as before it fell to default and we had requests to change this.
- [ ✅ ] I read the [Presence Guidelines](https://github.com/PreMiD/Presences/blob/main/.github/CONTRIBUTING.md)
- [ ✅ ] I linted the code by running `yarn format`
- [ ✅ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Presences/blob/main/.github/COMMIT_CONVENTION.md)
<details>
Small Edit to add "Viewing Player".
</details>

chore(PlanetXO): Added Player Support

---

websites/U/U-NEXT/metadata.json
websites/U/U-NEXT/presence.ts

chore(U-NEXT): update assets

---

websites/M/MoviesJoy/metadata.json

chore(MoviesJoy): format metadata

---

websites/G/Granblue Fantasy/metadata.json
websites/G/Granblue Fantasy/presence.ts

- Remove `largeImageText`
- Fix getting correct boss HP when on `Simple` health mode
<details>
</details>

chore(Granblue Fantasy): remove `largeImageText` & fix getting boss hp

---

websites/D/DEX Screener/metadata.json
websites/D/DEX Screener/presence.ts

Added a presence for the website https://dexscreener.com
<details>
</details>

feat(DEX Screener): add presence

---

websites/D/DEX Screener/metadata.json
websites/D/DEX Screener/presence.ts

chore(DEX Screener): update assets

---

websites/G/Granblue Fantasy/metadata.json
websites/G/Granblue Fantasy/presence.ts

Center and add padding/border to character image
<details>
| Before | After |
| --- | --- |
| ![Discord_IIo2mJ2tFz](https://github.com/user-attachments/assets/d330c61f-5437-4226-b49a-12c00cc8b615) | ![Discord_vA4IIT3Q3d](https://github.com/user-attachments/assets/346fdbbc-2fee-481b-b143-a0db0bb8c298) |
| ![Discord_utq8B8QTjC](https://github.com/user-attachments/assets/bdbb87fc-1d3b-497f-9fb1-0d3f066862ec) | ![Discord_dPJC01Csft](https://github.com/user-attachments/assets/bf86367f-2778-453e-a314-cc6d088fdb94) |
| ![Discord_CQps3DnGoW](https://github.com/user-attachments/assets/b4cf68ec-7fcc-4ee8-929e-53d64b77e2ef) | ![Discord_D76J36nkb3](https://github.com/user-attachments/assets/9d110140-caef-4863-bfae-51e7 …

feat(Granblue Fantasy): style character image

---

websites/P/Phira/metadata.json
websites/P/Phira/presence.ts

Resolves #8652 
<details>
</details>

feat(Phira): add activity

---

websites/N/Netflix/metadata.json
websites/N/Netflix/presence.ts

chore(Netflix): update version to 6.2.0 & implement season logic

---

websites/C/Claude/metadata.json
websites/C/Claude/presence.ts

chore(Claude): update assets

---

websites/P/Phira/metadata.json
websites/P/Phira/presence.ts

chore(Phira): update assets

---

websites/P/PikiDiary/metadata.json
websites/P/PikiDiary/presence.ts

PikiDiary is a small microblogging platform with option to start a live.
The web also has a PWA app that works fine with the activity.
<details>
</details>

feat(PikiDiary): add activity

---

websites/P/PikiDiary/metadata.json
websites/P/PikiDiary/presence.ts

chore(PikiDiary): update assets

---

websites/E/Eurogamer/metadata.json
websites/E/Eurogamer/presence.ts

feat(Eurogamer): add activity

---

websites/T/Timeguessr/metadata.json
websites/T/Timeguessr/presence.ts

chore(Timeguessr): update assets

---

websites/R/RadiosNet/metadata.json

Adding a "www" to see if the presence loads again.
<details>
</details>

chore: adding www in metadata

---

websites/V/Viu/metadata.json
websites/V/Viu/presence.ts

feat(Viu): update activity type

---

websites/R/RadiosNet/metadata.json
websites/R/RadiosNet/presence.ts

fix(RadiosNet): replacing the search's "+" with a space

---

websites/J/Jackbox/metadata.json

The mobile UI is the same as the desktop UI, so this activity should support mobile devices

refactor(Jackbox): enable mobile flag

---

websites/K/kisskh/metadata.json
websites/K/kisskh/presence.ts

chore(kisskh): update assets

---

websites/E/Eurogamer/metadata.json
websites/E/Eurogamer/presence.ts

chore(Eurogamer): update assets

---

websites/K/kisskh/metadata.json
websites/P/Pi Fansubs/metadata.json
websites/P/Pi Fansubs/presence.ts

chore(Pi Fansubs): update assets

---

tools/classes/PresenceCompiler.ts
tools/metadataSorter.ts

chore: update metadata sorter

---

@types/premid/index.d.ts
eslint.config.mjs
premid/src/functions/getTimestamps.ts
premid/src/functions/getTimestampsFromMedia.ts
premid/src/functions/timestampFromFormat.ts
premid/src/index.ts

This pull request introduces new utility functions for handling timestamps and updates the ESLint configuration for TypeScript files. The most significant changes include the addition of three new timestamp-related functions, their exports, and an update to the ESLint configuration to enforce rules for TypeScript files.
New utility functions for handling timestamps:
* [`premid/src/functions/getTimestamps.ts`](diffhunk://#diff-1a9a7e07e614ca7c9538b2fe2961e07e8f727fcd15fd15439875f5bf4676694fR1-R14): Added a function to convert current media time and duration into Unix timestamps.
* [`premid/src/functions/getTimestampsFromMedia.ts`](diffhunk://#diff-de1504dd43769753dbff0abfa4783e3256d1747b0bedd389a527da0bf4abe551R1-R16): Added a function to get timestamps from an HTML media element (audio or …

feat: add deprecation rule

---

.github/PULL_REQUEST_TEMPLATE.MD
.resources/README.MD

yeah, only that 😅
<details>
</details>

chore: presence > activity

---

cli/src/classes/ActivityCompiler.ts
cli/src/util/getActivities.ts
cli/src/util/sarif.ts
websites/G/Game8/metadata.json
websites/T/Town of Salem/metadata.json
websites/U/Uncyclopedia/metadata.json
websites/W/WriterDuet/metadata.json

This pull request introduces a new feature to ensure that tags in activity metadata are unique and includes updates to several metadata files to comply with this new requirement. The most important changes include adding a `tags` property to the `ActivityMetadata` interface, implementing a check for unique tags in the `ActivityCompiler` class, and updating metadata files to remove duplicate tags.
* [`cli/src/classes/ActivityCompiler.ts`](diffhunk://#diff-4b641eee1584ff4d0b1869b930f1c19dcb75d607a52e4d35221a89085fe10d49R28): Added a `tags` property to the `ActivityMetadata` interface and implemented a check in the `ActivityCompiler` class to ensure tags are unique. If duplicates are found, an error message is logged, and a SARIF log entry is added. …

feat(validator): add tags check

---

websites/P/Plex/metadata.json
websites/P/Plex/presence.ts

Fixes #9267 but pd is 403
<details>
</details>

chore(Plex): lint

---

websites/A/AnimeLib/metadata.json
websites/A/AnimeLib/presence.ts

types(AnimeLib): typed routes
<details>
</details>

chore(AnimeLib): settings in native language

---

websites/A/AnimeciX/metadata.json

-New domain added
-Turkish description added
-New tags added
<details>
</details>

feat(AnimeciX): Update metadata new domain

---

websites/O/osu ppy/metadata.json
websites/O/osu ppy/osu!ppy.json
websites/O/osu ppy/presence.ts

add missing strings && change getStrings in presence.ts
<details>
</details>

fix(osu!ppy): add missing strings && change getStrings in presence.ts

---

websites/D/Deno/metadata.json
websites/D/Deno/presence.ts

- Update Deno's logo to Deno 2
- Update cover
- Remove discontinued websites and routes
- Fix all outdated routes
- Add support for `docs.deno.com`
- Append `™` to `Deploy` since it's a trademark
<details>
</details>

chore(Deno): keep functions updated

---

websites/A/Anizium/iframe.ts
websites/A/Anizium/metadata.json
websites/A/Anizium/presence.ts

Created new Premid presences integration for the new anime watching "Anizium" website.
Testing: Each page tested one by one, no issues found.
<details>
</details>

feat(Anizium): Add new presence

---

websites/C/Cyfrin Updraft/metadata.json
websites/C/Cyfrin Updraft/presence.ts

Cyfrin Updraft integration for PreMiD
A brief description on [Updraft](https://updraft.cyfrin.io): 
Cyfrin Updraft helps kickstart your web3 development career with free courses that teach you the skills to become a smart contract engineer or a security auditor. 
This integration adds simple PreMiD statuses for students engaging with our courses and lessons. 
<details>
</details>

feat(Cyfrin Updraft): add Cyfrin Updraft presence

---

websites/J/Jackbox/games/Non-Pack/bigsurvey.ts
websites/J/Jackbox/games/index.ts
websites/J/Jackbox/presence.ts
websites/J/Jackbox/types.ts

- Adds support for the Jackbox Survey Scramble
<details>
</details>

feat(Jackbox): add The Jackbox Survey Scramble

---

websites/N/NPM Package Registry/metadata.json
websites/N/NPM Package Registry/presence.ts

- Fix and add a funny message for 404 pages
<details>
</details>

chore(NPM Package Registry): fix info of non-exist pacakge

---

websites/V/VLC/metadata.json
websites/V/VLC/presence.ts

Fixes decoding of the html through decodeReq this made " show as \&quot;
Fixes deprecated timestamps function
Fixes copy paste mistake when getting Type from the request, causing it to not be set properly
<details>
</details>

fix(VLC): revert breaking change from #4946 & fix deprecated & fix Type

---

websites/B/BBC/metadata.json
websites/B/BBC/presence.ts

refactor(BBC): import getTimestamps and fix strings being undefined

---

websites/Y/YTyping/iframe.ts
websites/Y/YTyping/metadata.json
websites/Y/YTyping/presence.ts

Add the YTyping presence for https://ytyping.net/.
<details>
</details>

feat(YTyping): add YTyping presence

---

websites/T/Twitch/metadata.json
websites/T/Twitch/presence.ts

Fixes #9243 
<details>
Unfixed:
Fixed:
</details>

fix(Twitch): popup chat no longer shows default status

---

.github/PULL_REQUEST_TEMPLATE.MD
README.md
cli/src/commands/release.ts
cli/src/commands/updateAssets.ts
cli/src/util/log.ts
package.json

This pull request includes significant updates to the `README.md` file to provide clearer instructions for developers and a change to the Node.js version requirement in the `package.json` file. The most important changes include enhancing the README with detailed setup instructions, usage of a CLI tool, and updating the Node.js version requirement.
Enhancements to `README.md`:
* Added a description of how Activities enhance Discord presence.
* Updated the "Getting Started" section with step-by-step instructions for setting up the development environment, learning the basics, and starting to create or edit Activities.
* Introduced a new section for CLI commands, including commands for creating and developing Activities with live-reload functionality.
* Added a detailed guide on testing …

docs: update README with comprehensive developmend guide

---

cli/src/index.ts

fix(CLI): make options consistent
<details>
n/a
</details>

fix(CLI): make options consistent

---

websites/R/Raycast/metadata.json
websites/R/Raycast/presence.ts

Add a new presence - Raycast
<details>
</details>

feat(Raycast): add Raycast presence

---

.github/renovate.json

Renovate will automatically ask for reviewers for PRs.
<details>
</details>

chore(renovate.json): add reviewers

---

websites/D/DeviantArt/metadata.json
websites/D/DeviantArt/presence.ts

Fixes #6865 
<details>
Unfixed:
Fixed:
</details>

fix(DevianArt): don't show undefined in gallery

---

websites/S/Suno/metadata.json
websites/S/Suno/presence.ts

Resolves #9353 
<details>
</details>

feat(Suno): add activity

---

cli/src/index.ts
websites/I/Inlx/metadata.json
websites/I/Inlx/presence.ts

Adds support for Inlx, https://inlx.site. Based on TheSite activity by Striker. Tested all pages referenced to confirm accurate updates to presence.
<details>
</details>

feat(Inlx): add Inlx presence

---

.github/PULL_REQUEST_TEMPLATE.MD

Update the `yarn format` to `npm run lint` in PR template

chore: update lint command in PR template

---

websites/Q/Quizypedia/metadata.json
websites/Q/Quizypedia/presence.ts

This PR adds support for the French website [https://www.quizypedia.fr/](https://www.quizypedia.fr/).
<details>
</details>

feat(Quizypedia): add Quizypedia presence

---

.github/workflows/release.yml
cli/package.json
cli/src/commands/release.ts
cli/src/util/log.ts

This pull request introduces several significant changes to the `cli` package, focusing on removing MongoDB dependencies and replacing them with API calls, updating the package version, and cleaning up related code.
* [`cli/src/commands/release.ts`](diffhunk://#diff-a5814267bcedbf491f9c7257d6c250b59bda75e02caecfaf069c5d7f90db89d1L9-R16): Removed `MongoClient` import and all MongoDB-related code, replacing it with API calls for managing activities. [[1]](diffhunk://#diff-a5814267bcedbf491f9c7257d6c250b59bda75e02caecfaf069c5d7f90db89d1L9-R16) [[2]](diffhunk://#diff-a5814267bcedbf491f9c7257d6c250b59bda75e02caecfaf069c5d7f90db89d1L45-R48) [[3]](diffhunk://#diff-a5814267bcedbf491f9c7257d6c250b59bda75e02caecfaf069c5d7f90db89d1L59-R84) [[4]](diffhunk://#diff-a5814267bcedbf491f9c7257d6c250b59bda75 …

chore(release): replace mongodb with management endpoint

---

websites/B/Backloggd/metadata.json

also support www.
Resolves #9297
<details>
n/a
</details>

feat(Backloggd): also support www.domain

---

websites/B/bilibili/metadata.json

add chinese altname
<details>
</details>

chore(bilibili): add chinese altname

---

websites/I/IDLIX/metadata.json
websites/I/IDLIX/presence.ts

simplify regex to make it work again.
<details>
</details>

fix(IDLIX): simplify regex

---

websites/P/Plex/metadata.json
websites/P/Plex/presence.ts

fix(Plex): local images not getting uploaded

---

websites/N/Nexon/metadata.json
websites/N/Nexon/presence.ts

- Add activity
<details>
</details>

Feat(Nexon): add activity

---

websites/B/Bun/metadata.json
websites/B/Bun/presence.ts

Add activity for https://bun.sh.
<details>
</details>

feat(Bun): add acitivity

---

websites/C/ChatGPT/ChatGPT.json
websites/C/ChatGPT/metadata.json
websites/C/ChatGPT/presence.ts

Add showGPTName option && add some pages not supported
<details>
</details>

feat(ChatGPT): add some features

---

websites/E/Emby/metadata.json

Resolves #9172
feat(Emby): add app domain
<details>
n/a
</details>

feat(Emby): add app domain

---

websites/I/iQIYI/metadata.json
websites/I/iQIYI/presence.ts

Resolves #9369
<details>
n/a
</details>

feat(iQIYI): add watch type and change to destructured variables

---

.github/CONTRIBUTING.md

Just some chores I did locally while working on another contribution.
* Fixed typos in CONTRIBUTING.md
N/A
* Split off from https://github.com/PreMiD/Activities/pull/9389

chore(docs): fix typos in contribution guide

---

package-lock.json
websites/C/Chorki/metadata.json
websites/C/Chorki/presence.ts

Resolves issue #9145 : Added missing Playback Bar.
<details>
</details>

feat(Chorki): Added missing Playback Bar

---

websites/G/Grok/Grok.json
websites/G/Grok/functions/fetchResponsesMetadata.ts
websites/G/Grok/metadata.json
websites/G/Grok/package-lock.json
websites/G/Grok/package.json
websites/G/Grok/presence.ts
websites/G/Grok/types.ts

Resolves: https://github.com/PreMiD/Activities/issues/9395
<details>
</details>

feat(Grok): add activity

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

Updated metadata and added option to disable buttons.
<details>
No screenshot for now but its a small change just a few lines.
</details>

feat(Physics Wallah): Updated metadata and added option to disable buttons

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

feat(Physics Wallah): added option to disable buttons

---

websites/G/Google Drive/Google Drive.json
websites/G/Google Drive/metadata.json
websites/G/Google Drive/presence.ts
websites/G/Google Maps/Google Maps.json
websites/G/Google Maps/metadata.json
websites/G/Google Maps/presence.ts
websites/G/Google Messages/Google Messages.json
websites/G/Google Messages/metadata.json
websites/G/Google Messages/presence.ts
websites/G/Google Photos/Google Photos.json
websites/G/Google Photos/metadata.json
websites/G/Google Photos/presence.ts
websites/O/Outlook/Outlook.json
websites/O/Outlook/metadata.json
websites/O/Outlook/presence.ts
websites/X/Xbox/Xbox.json
websites/X/Xbox/metadata.json
websites/X/Xbox/presence.ts

add multilanguage to multiple Activities
<details>
</details>

feat: add multilanguage to some popular Activities

---

websites/C/Chompu/metadata.json
websites/C/Chompu/presence.ts
websites/U/Undercards/presence.ts

feat(Chompu): fix and update activity

---

websites/I/IDLIX/metadata.json
websites/I/IDLIX/presence.ts

Resolves #9368
fix strings causing presence to not work
<details>
</details>

fix(IDLIX): fix strings causing presence to not work

---

websites/D/Dreamhack/metadata.json
websites/D/Dreamhack/presence.ts

Add activity for the site named Dreamhack, which is a platform to learn hacking by guides, wargames, and CTFs in Korea.
<details>
</details>

feat(Dreamhack): add activity

---

websites/E/Eurogamer/presence.ts
websites/I/Império Network/metadata.json
websites/I/Império Network/presence.ts

Add a new activity
<details>
</details>

feat(Império Network): add activity

---

websites/A/Animevietsub/metadata.json
websites/A/Animevietsub/presence.ts

- Add Button Show Title As Presence
- Add Button Show timestamps
- Add Timestamp
- Show image of the anime on large Image Key
> Proof showing the creation/modification is working as expected
>![image](https://github.com/user-attachments/assets/b5db5f7b-a794-4297-a02a-c92fba0dcd6d)
><video alt="image" src="https://github.com/user-attachments/assets/d8272c0d-e8b2-4bd5-8e28-7fb4c572c94c">

feat(Animevietsub): add feauture

---

websites/S/Sezonluk Dizi/metadata.json

update to the new domain
close #9466 
New domain confirmed by site creators
https://x.com/sezonlukdizi/status/1721112866516828384
<details>
</details>

fix(Sezonluk Dizi): update domain

---

websites/F/Freek/metadata.json

Update to the now domain
close #9470 
<details>
</details>

fix(Freek): update domain

---

websites/general.json

Added descriptions for:
- anime
- browsing
- viewAccount
- viewChannel
- viewEpisode
- viewGenre
- viewHome
- viewList
- viewManga
- viewMember
- viewMovie
- viewPlaylist
- viewProduct
- viewProfile
- viewSeries
- viewShow
- viewThread
- viewUser
- viewWishlist
Added strings:
- viewACategory
- viewADraft
- viewAFile
- viewAHelpPage
- viewAModule
- viewATemplate
- viewATopic
- viewDraft
- viewFile
- viewHelpPage
- viewTopic
- viewTemplate
- viewATemplate
<details>
n/a
</details>

feat(General): add more general strings & add some descriptions

---

websites/W/Wikipedia/metadata.json
websites/W/Wikipedia/presence.ts
websites/W/Wikipedia/wikipedia.json

Resolves #9446
Relies on #9478
- Change to using general/activity strings;
- Add privacy mode with selector;
- Change regex to work on the homepage of different versions;
<details>
</details>

feat(Wikipedia): recode activity 

---

websites/U/Udio/metadata.json
websites/U/Udio/presence.ts

Resolves #9479
<details>
</details>

feat(Udio): add activity

---

websites/K/Kitsu/metadata.json

Update to the new domain
(refer to https://canary.discord.com/channels/493130730549805057/1362958281190019163)
<details>
</details>

fix(Kitsu): update domain

---

websites/A/Anizium/metadata.json
websites/A/Anizium/presence.ts

Used default logo instead broken image element path
<details>
</details>

feat(Anizium): remove thumbnail element

---

websites/D/DeepL/DeepL.json
websites/D/DeepL/metadata.json
websites/D/DeepL/presence.ts

Reworking of the Activity as it was no longer functional.
I've taken the liberty of designating myself as the author of the activity, as the original author no longer seems active.
<details>
</details>

fix(DeepL): rework Activity

---

websites/G/Google Calendar/Google Calendar.json
websites/G/Google Calendar/metadata.json
websites/G/Google Calendar/presence.ts
websites/G/Google Docs/metadata.json
websites/G/Google Docs/presence.ts
websites/G/Google Drive/metadata.json
websites/G/Google Drive/presence.ts
websites/G/Google Maps/Google Maps.json
websites/G/Google Maps/metadata.json
websites/G/Google Maps/presence.ts
websites/G/Google Photos/metadata.json
websites/G/Google Photos/presence.ts

- Update regex for multiple Activities
- Added support for letters with accents (Google Maps Activity)
- Complete fix of the Google Calendar activity + addition of multilanguage (I took the liberty of authoring this activity as it is no longer maintained).
<details>
Before:
After:
</details>

fix: change regex && repairing the Google Calendar Activity

---

websites/N/neal.fun/metadata.json
websites/N/neal.fun/presence.ts

Add stimulation clicker.
<details>
</details>

feat(neal.fun): add stimulation clicker

---

websites/A/Anizium/metadata.json
websites/A/Anizium/presence.ts

Fully re-coded
Fixed all bugs
<details>
</details>

feat(Anizium): Re-code and update presence

---

websites/M/Medal/metadata.json
websites/M/Medal/presence.ts

Closes #9360 
<details>
</details>

feat(Medal): add activity

---

websites/T/TruckersFM/metadata.json

Updated description as provided by the TFM team - including a Dutch translation.
- [ ✔️] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [ ✔️] I linted the code by running `npm run lint`
- [ ✔️] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)

fix(TruckersFM): new description & better translation

---

websites/T/Twitch/metadata.json

- [x ] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [ x] I linted the code by running `npm run lint`
- [x ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)
<details>
just added few missing letters
</details>

refactor(Twitch): udpate French description

---

websites/D/Dreamhack/metadata.json
websites/D/Dreamhack/presence.ts

I updated the Activity due to renewal of the website.
I added features to show settings and a button.
I found a mistake in my nickname inside the metadata and fixed it.
<details>
</details>

feat(Dreamhack): update activity

---

websites/T/TradingView/metadata.json
websites/T/TradingView/presence.ts

close #9545 
I took the liberty of changing the app ID to update the logo on services like PresenceDB
<details>
</details>

fix(TradingView): update logo & thumbnail

---

websites/W/Watch-Anime/metadata.json

refactor(Watch-Anime): update contributors

---

websites/S/Sketchful.io/metadata.json
websites/S/Sketchful.io/presence.ts

- Resolves #7171 
<details>
</details>

feat(Sketchful.io): add activity

---

websites/P/Playlist Randomizer/iframe.ts
websites/P/Playlist Randomizer/metadata.json
websites/P/Playlist Randomizer/presence.ts

- Resolves #9336 
<details>
</details>

feat(Playlist Randomizer): add activity

---

websites/W/Wuthering Waves/Wuthering Waves.json
websites/W/Wuthering Waves/metadata.json
websites/W/Wuthering Waves/presence.ts

- Adds an activity for wutheringwaves.kurogames.com
- Resolves #9537
<details>
</details>

feat(Wuthering Waves): add activity

---

websites/0-9/5etools/metadata.json
websites/0-9/5etools/presence.ts

- Adds support for the 2014 subdomain
- Updates selector for subtitle
<details>
</details>

feat(5etools): add 2014 subdomain

---

websites/Y/YouTube/metadata.json
websites/Y/YouTube/presence.ts
websites/Y/YouTube/util/index.ts

- Allows for the current chapter to be used in details and state
- Resolves #6077 
<details>
*The following is the display for `%title% - %chapter%`*
</details>

feat(YouTube): add chapter support

---

websites/T/Twitch/metadata.json
websites/T/Twitch/presence.ts

adds a setting to show the streamer as the activity title
<details>
</details>

feat(Twitch): add streamer as title setting

---

websites/P/Prydwen Institute/games/afk-journey.ts
websites/P/Prydwen Institute/games/arknights-endfield.ts
websites/P/Prydwen Institute/games/ash-echoes.ts
websites/P/Prydwen Institute/games/counter-side.ts
websites/P/Prydwen Institute/games/etheria-restart.ts
websites/P/Prydwen Institute/games/eversoul.ts
websites/P/Prydwen Institute/games/gfl-exilium.ts
websites/P/Prydwen Institute/games/index.ts
websites/P/Prydwen Institute/games/limbus-company.ts
websites/P/Prydwen Institute/games/nikke.ts
websites/P/Prydwen Institute/games/re1999.ts
websites/P/Prydwen Institute/games/solo-leveling.ts
websites/P/Prydwen Institute/games/star-rail.ts
websites/P/Prydwen Institute/games/wuthering-waves.ts
websites/P/Prydwen Institute/games/zenless.ts
websites/P/Prydwen Institute/lists.ts
websites/P/Prydwen Institute/metadata.json
websites/P/Prydwen Institute/presence.ts
websites/P/Prydwen Institute/util.ts

The website moved to a new domain a while ago and started supporting multiple different games
<details>
</details>

feat(Prydwen Institute): update for new website

---

websites/R/RoyaleAPI/RoyaleAPI.json
websites/R/RoyaleAPI/iframe.ts
websites/R/RoyaleAPI/metadata.json
websites/R/RoyaleAPI/presence.ts
websites/R/RoyaleAPI/util.ts

Adds an activity for RoyaleAPI
<details>
</details>

feat(RoyaleAPI): add activity

---

websites/A/AniKenji Movie/metadata.json
websites/A/AniKenji Movie/presence.ts

Update for new Web Theme
<details>
<b>Home Page</b> <br> ![Home Page](https://github.com/user-attachments/assets/caecac38-949a-42c9-ab41-e54bbad83599) <br>
<b>Movie Look Up</b> <br> ![Movie Look Up Page](https://github.com/user-attachments/assets/52ab0f32-e1c2-4d52-941e-73d0e85a4037) <br>
<b>Watching Page</b> <br> ![Watching Page](https://github.com/user-attachments/assets/a44e9382-fdde-44f3-b162-5ce7fa675cb4)
</details>

feat(AniKenji Movie): Update for new Theme

---

websites/N/NovaStream/presence.ts

- Add `/index.html` support along with `/`
- Fix the content rating display (see screenshot)
<details>
BEFORE:
AFTER:
</details>

fix(Novastream): fix rating display & add /index.html support

---

websites/N/NovaStream/metadata.json
websites/N/NovaStream/presence.ts

feat(Novastream): add support for settings page

---

websites/Y/YouTube Music/metadata.json
websites/Y/YouTube Music/presence.ts

adds setting to show artist as title
deprecation stuff
moved assets into an enum
<details>
</details>

feat(YouTube Music): add 'Show Artist as Title' setting

---

websites/H/Hero Forge/metadata.json
websites/H/Hero Forge/presence.ts

- Fixes #8952 
<details>
</details>

fix(Hero Forge): update item selectors

---

websites/0-9/1Anime/metadata.json
websites/0-9/1Anime/presence.ts
websites/A/AnimeKai/metadata.json
websites/A/AnimeKai/presence.ts
websites/A/AnimeciX/metadata.json
websites/A/AnimeciX/presence.ts
websites/A/AnizmTV/metadata.json
websites/A/AnizmTV/presence.ts
websites/F/Facebook/metadata.json
websites/F/Facebook/presence.ts
websites/I/iQIYI/metadata.json
websites/I/iQIYI/presence.ts
websites/M/Medal/metadata.json
websites/M/Medal/presence.ts
websites/N/niconico/metadata.json
websites/N/niconico/presence.ts
websites/O/OnlyHit/metadata.json
websites/O/OnlyHit/presence.ts
websites/R/RoyaleAPI/metadata.json
websites/R/RoyaleAPI/presence.ts
websites/V/VLC/metadata.json
websites/V/VLC/presence.ts
websites/V/VocaDB/metadata.json
websites/V/VocaDB/presence.ts
websites/W/Wave FM/metadata.json
websites/W/Wave FM/presence.ts

Fixes activity type assignment issues after recent type changes

refactor: fix activity type assignment

---

websites/N/NeedCoolerShoes/metadata.json
websites/N/NeedCoolerShoes/presence.ts

feat(NeedCoolerShoes): add activity

---

websites/E/Editor for Blather 'Round/metadata.json
websites/E/Editor for Blather 'Round/presence.ts

feat(Editor for Blather 'Round): add activity

---

websites/D/Deck Shop/Deck Shop.json
websites/D/Deck Shop/metadata.json
websites/D/Deck Shop/presence.ts

Adds an activity for 'Deck Shop', a Clash Royale deck comparison website
<details>
</details>

feat(Deck Shop): add activity

---

websites/E/Emurse/metadata.json
websites/E/Emurse/presence.ts

Adds an activity for Emurse, a speech-focused language website
<details>
</details>

feat(Emurse): add activity

---

websites/A/AnimeGO/metadata.json

fix(AnimeGO): add regexp for mirrors

---

websites/N/NeedCoolerShoes/metadata.json

Fixes thumbnail by using source url, which contains the extension in the path section of the url

chore(NeedCoolerShoes): update thumbnail

---

websites/Y/Yandex Music/metadata.json
websites/Y/Yandex Music/presence.ts

Fix Yandex Music activity
Resolves #9519 
<details>
</details>

fix(Yandex Music): update definition player

---

websites/R/RankOne/RankOne.json
websites/R/RankOne/metadata.json
websites/R/RankOne/presence.ts

Add activity
<details>
</details>

feat(RankOne): add activity

---

websites/B/Best Buy/metadata.json
websites/B/Best Buy/presence.ts

- Resolves #6926 
<details>
</details>

feat(Best Buy): add activity

---

websites/N/NPR/metadata.json
websites/N/NPR/presence.ts

Adds an activity for NPR
<details>
</details>

feat(NPR): add activity

---

websites/T/The Verge/metadata.json
websites/T/The Verge/presence.ts

Add activity
<details>
</details>

feat(The Verge): add activity

---

websites/O/OtakuPT/metadata.json
websites/O/OtakuPT/presence.ts

Add activity
<details>
</details>

feat(OtakuPT): add activity

---

websites/T/TMBW/metadata.json

The author id in the code was incorrect so I corrected it by replacing it by the correct author's user id

feat:(TMBW): corrected the author's user id

---

websites/I/Invidious/metadata.json

Updates the URLs to align with the official instances list and remove dead sites.

chore(invidious): update urls

---

websites/N/Navidrome/metadata.json
websites/N/Navidrome/presence.ts

covers
listening to activitytype
artist as title setting
Resolved #9527 
<details>
</details>

feat(Navidrome): add covers, listening and artist as title

---

websites/A/Asmrone/metadata.json
websites/A/Asmrone/presence.ts

feat(Asmrone): add activity

---

websites/I/iQIYIs/metadata.json
websites/I/iQIYIs/presence.ts

Add support for [iQIYIs](https://iqiyis.com), an streaming web app.
<details>
</br>
</br>
</details>

feat(iQIYIs): add activity

---

websites/S/Sunniesnow/metadata.json
websites/S/Sunniesnow/presence.ts

Add support for Sunniesnow, an open-source web rhythm game.
<details>
</details>

feat(Sunniesnow): add activity

---

websites/A/AnimeKai/metadata.json
websites/A/AnimeKai/presence.ts

Add AnimeKai.bz to supported URLs list https://github.com/PreMiD/Activities/issues/9560
feat(AnimeKai):
Add functionality while veiwing own boorkmarks https://github.com/PreMiD/Activities/issues/9560
Add functionality while looking at notifications https://github.com/PreMiD/Activities/issues/9560
- [✅] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [✅] I linted the code by running `npm run lint`
- [✅] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)

feat(AnimeKai): update supported urls

---

websites/R/RetroCrush/metadata.json
websites/R/RetroCrush/presence.ts

This PR adds full RetroCrush support—a vintage anime platform—featuring:
- **Dynamic Live TV info**: automatically detects the currently airing program and updates in real time.  
- **All‑page support**: handles `/livetv`, `/movies`, `/shows`, `/genres`, `/watchlist`, `/find`, `/details`, and `/watch`.  
- **Dynamic search display**: shows the user’s current search term in the activity.  
- **Dynamic descriptions**: extracts and displays movie/anime descriptions on detail pages.  
- **Playback timestamps**: tracks video start/end times and toggles play/pause icons.  
- **Smart cache**: minimizes DOM queries by caching and only refreshing when channel, program, or episode changes.
Resolves #5381
<details> …

feat(RetroCrush): add activity

---

websites/G/GOG/GOG.json
websites/G/GOG/metadata.json
websites/G/GOG/presence.ts

Added new page `/mods`
<details>
</details>

feat(GOG): new mods page

---

websites/A/AnimEly/iframe.ts
websites/A/AnimEly/metadata.json
websites/A/AnimEly/presence.ts

AnimeElysium
Shows what you're watching on AnimeElysium directly on your Discord.
Displays the anime title, episode number, and playback status in real time.
Features:
Displays current anime and episode and etc.
Shows if you're playing, paused, or browsing
<details>
</details>

feat(AnimEly): add activity

---

websites/A/AlternativeScans/metadata.json
websites/A/AlternativeScans/presence.ts

Adds activity for AlternativeScans.icu
- Shows Series
- Shows Chapters
- Shows Buttons
<details>
</details>

feat(AlternativeScans): add activity

---

websites/T/Tsukime/metadata.json
websites/T/Tsukime/presence.ts

Adds activity for Tsukime.com
- Shows Anime/Manga
- Shows for Users
- Shows if Searching
- Shows Episodes
<details>
</details>

feat(Tsukime): add activity

---

websites/B/Blooket/metadata.json
websites/B/Blooket/presence.ts

<details>
(for context, Racing and Deceptive Dinos were updated by Blooket and their subdomains were changed)
</details>

feat(Blooket): updated mode support

---

websites/V/Vizer/metadata.json

update domain
fix #9748 
<details>
</details>

fix(Vizer): update domain

---

websites/A/AniKenji Movie/metadata.json
websites/A/AniKenji Movie/presence.ts

fix(AniKenji Movie): Fix Buttons

---

websites/O/osu ppy/metadata.json
websites/O/osu ppy/osu!ppy.json
websites/O/osu ppy/presence.ts

fix #9759 
<details>
</details>

fix(osu!ppy): fix multilanguage strings

---

@types/premid/index.d.ts

See https://discord.com/developers/docs/change-log#clickable-links-and-customizable-statuses-in-rich-presence

feat: add StatusDisplayType enum and update PresenceOptions with new fields 

---

websites/T/Taobao/metadata.json
websites/T/Taobao/presence.ts

Adds a new Presence for Taobao / Tmall ( taobao.com / tmall.com )
- Detects homepage, search results, and product pages.
- Shows product title and shop name when available.
- Adds a "View Product" button linking to the item.
<details>
</details>

feat(Taobao): add activity

---

websites/S/Sflix/iframe.ts
websites/S/Sflix/metadata.json
websites/S/Sflix/presence.ts

This PR changes the following:
- Resolves #9774 (updated domains)
- Adds 3 new settings: Show Browsing Status, Hide When Paused, Show Title As Presence
- Adds thumbnail to the detail presence
- Adds [season & episode indicator](https://premid.github.io/Activities/v1/api/presence-data.html#special-season-and-episode-formatting)
- Adds support for most previously not supported pages
- Fixes iFrameRegExp using an incorrect domain
<details>
</details>

feat(Sflix): update activity

---

websites/A/anilife/metadata.json
websites/A/anilife/presence.ts

Add activity for [anilife.app](https://anilife.app) and [anilife.live](https://anilife.live), a korean animation streaming service
<details>
<h2>anilife.app</h2>
<h2>anilife.live</h2>
</details>

feat(anilife): add activity

---

websites/Y/YouTube Music/metadata.json
websites/Y/YouTube Music/presence.ts

Resolves #9815
<details>
</details>

fix(Youtube Music): fix artist being duplicated

---

websites/W/Watch-Anime/metadata.json
websites/W/Watch-Anime/presence.ts

feat(Watch-Anime): update activity

---

websites/A/Anroll/iframe.ts
websites/A/Anroll/metadata.json
websites/A/Anroll/presence.ts

This plugin adds Anroll.net support to PreMiD, allowing users to show that they are watching episodes on Discord Rich Presence.
It is constantly updated based on the user's current page.
<details>
</details>

feat(Anroll): add activity

---

websites/P/Panais/metadata.json
websites/P/Panais/presence.ts

feat(Panais): add activity

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

Changed the application id because the previous one got deleted
<details>
No screenshot because just changed the application id.
</details>

fix(Physics Wallah): Updated the application id

---

websites/W/Wplace/metadata.json
websites/W/Wplace/presence.ts

feat(Wplace): add activity

---

websites/P/Physics Wallah/metadata.json
websites/P/Physics Wallah/presence.ts

Just what the title said
<details>
</details>

feat(Physics Wallah): Added a new feature where it shows up as viewing notes

---

websites/A/AniKenji Movie/metadata.json
websites/A/AniKenji Movie/presence.ts

fix(AniKenji Movie): fix not display title and add support new domain

---

websites/W/WitAnime/iframe.ts
websites/W/WitAnime/metadata.json
websites/W/WitAnime/presence.ts

This presence is designed for the Arabic WitAnime website. It features playback timestamp tracking, full support for all website routes, and includes internal caching to prevent unnecessary requests.
Resolve #9866 
<details>
HomePage
Anime List
Movie List
Season Anime List
Episode Schedule
Anime Description
Watching Movie
Watching Anime
Contact Us
</details>

feat(WitAnime): add activity

---

websites/N/NixOS/metadata.json
websites/N/NixOS/presence.ts

This PR introduces a new activity for the NixOS website. NixOS is the Linux distribution based on the Nix package manager. Nix introduces a new way to manage packages and systems, by declaring them via pure functional code. The [nixpkgs] package repository currently holds more than a hundred thousand of packages.
[nixpkgs]: https://github.com/nixos/nixpkgs
This PR adds support for multiples websites from NixOS foundation:
- The main website at https://nixos.org with support for
- Landing pages and various front pages
- Manuals for both Nixpkgs and NixOS
- Guides like Nix Pills
- Packages and options search at https://search.nixos.org
- Hydra, the Nix-based continuous build system at https://hydra.nixos.org
- The Nix Channel statuses at https://status.nixos.org
- The Official Wiki at …

feat(NixOS): add activity

---

websites/R/Rooster Teeth/iframe.ts
websites/R/Rooster Teeth/metadata.json
websites/R/Rooster Teeth/presence.ts

Rooster Teeth was bought by old employees and they have revived the website bringing back their shows and forums
<details>
</details>

feat(Rooster Teeth): add activity

---

websites/A/AnROLL/metadata.json
websites/A/AnROLL/presence.ts

This pull request introduces a complete overhaul of the AnROLL presence, refactored from the ground up to support the latest version of the Anroll.net website and to fix long-standing bugs related to its dynamic player.
The previous implementation was broken due to site structure changes. This version introduces a more resilient and feature-rich experience.
* **Solved Timestamp Failure:** The root cause of the timestamp not appearing was identified and fixed by correctly setting the activity type to `ActivityType.Watching`.
* **Resilient Video Tracking:** Implemented a robust, polling-based video tracker (`masterTrackerInterval`) that correctly handles the dynamically injected video player, resolving the "always paused" and timing-related bugs.
* **Corrected Cover Image Scraping:** The …

feat(Anroll): complete overhaul and new features

---

websites/F/FFXIV Lodestone/metadata.json
websites/F/FFXIV Lodestone/presence.ts

FFXIV Lodestone is an official companion website for Final Fantasy XIV.
I made this activity for **https://github.com/PreMiD/Activities/issues/8675**.
- Resolves #8675
<details>
</details>

feat(FFXIV Lodestone): add activity

---

websites/B/Bluesky/metadata.json
websites/B/Bluesky/presence.ts

Resolves #9929 
<details>
</details>

chore(Bluesky): update logo

---

websites/T/Tempest Mangas/handlers/route.ts
websites/T/Tempest Mangas/managers/settings.ts
websites/T/Tempest Mangas/metadata.json
websites/T/Tempest Mangas/presence.ts
websites/T/Tempest Mangas/types.ts
websites/T/Tempest Mangas/utils.ts

Added <a href="https://tempestmangas.com/">Tempest Mangas</a> Presence
<details>
</details>

feat(Tempest Mangas): add presence

---

websites/N/NOW TV/metadata.json
websites/N/NOW TV/presence.ts

Added a new presence for NOW TV, the streaming service used to watch Sky Sports, Cinema, Entertainment and more in the United Kingdom.
<details>
Privacy mode:
</details>

feat(NOW TV): add activity

---

websites/G/Google NotebookLM/handlers/route.ts
websites/G/Google NotebookLM/managers/settings.ts
websites/G/Google NotebookLM/metadata.json
websites/G/Google NotebookLM/presence.ts
websites/G/Google NotebookLM/types.ts
websites/G/Google NotebookLM/utils.ts

Added <a href="https://notebooklm.google.com/">Google NotebookLM</a> Presence
Resolves: https://github.com/PreMiD/Activities/issues/9497
<details>
</details>

feat(Google NotebookLM): add presence 

---

websites/S/Sakura AI/handlers/route.ts
websites/S/Sakura AI/managers/poster.ts
websites/S/Sakura AI/managers/settings.ts
websites/S/Sakura AI/metadata.json
websites/S/Sakura AI/presence.ts
websites/S/Sakura AI/types.ts
websites/S/Sakura AI/utils.ts

Added <a href="https://www.sakura.fm">Sakura AI</a> Presence
Resolves https://github.com/PreMiD/Activities/issues/9192
<details>
</details>

feat(SakuraAI): add activity

---

websites/S/Stigstream/handlers/route.ts
websites/S/Stigstream/iframe.ts
websites/S/Stigstream/managers/poster.ts
websites/S/Stigstream/managers/settings.ts
websites/S/Stigstream/metadata.json
websites/S/Stigstream/presence.ts
websites/S/Stigstream/types.ts
websites/S/Stigstream/utils.ts

Added <a href="https://stigstream.com">Stigstream</a> Presence
Resolves https://github.com/PreMiD/Activities/issues/9551
<details>
</details>

feat(Stigstream): add activity

---

websites/F/Fantasy Premier League/metadata.json
websites/F/Fantasy Premier League/presence.ts

Added a presence for the FPL website. With over 11 million players, Fantasy Premier League is the biggest Fantasy Football game in the world.
<details>
Privacy mode:
</details>

feat(Fantasy Premier League): add activity

---

websites/R/RTBF Auvio/metadata.json
websites/R/RTBF Auvio/util.ts

<details>
This is a quick fix if CORS fails on certain URLs. I'm open to other solutions that allow me to keep the desired visual elements instead of discarding them.
</details>

fix(RTBF Auvio): cors fail fallback

---

websites/C/CinePulse/metadata.json
websites/C/CinePulse/presence.ts

- Displays current activity (title, author, status)
- Includes custom icons and metadata
- Tested locally with PreMiD extension
- [ ✕ ] I read the [Activity Guidelines](https://github.com/PreMiD/Activities/blob/main/.github/CONTRIBUTING.md)
- [ ✕ ] I linted the code by running `npm run lint`
- [ ✕ ] The PR title follows the repo's [commit conventions](https://github.com/PreMiD/Activities/blob/main/.github/COMMIT_CONVENTION.md)
<details>
</details>

feat(CinePulse): add activity

---

.gitignore
websites/C/Channel 4/metadata.json
websites/C/Channel 4/presence.ts

Added an activity for [Channel 4](https://channel4.com). Channel 4 is a publicly-owned free-to-air channel that covers the United Kingdom. It's home to a streaming service, six TV channels and a film production studio.
<details>
News site:
Privacy mode:
</details>

feat(Channel 4): add activity

---

websites/C/combi.fm/metadata.json
websites/C/combi.fm/presence.ts

Added a site with presence activity
<details>
Settings
</details>

feat(combi.fm): add activity

---

websites/B/Bunpro/metadata.json
websites/B/Bunpro/presence.ts

The Bunpro activity has been broken for some time due to HTML structure changes. I fixed these issues, updated the wording for some activities to be more accurate, and added some more info to activities.
<details>
</details>

feat(Bunpro): additional settings, more info shown and bugfixes

---

websites/A/animepahe/metadata.json

Added "animepahe.si" as a new URL to the activity, as animepahe has updated their URL. (this is their new main url and all other domains redirect to that)
Updated the version number.
<details>
shows homepage
shows playing an anime
</details>

fix(animepahe): add new URL and bump version

---

websites/M/Mangafire/metadata.json
websites/M/Mangafire/presence.ts

Fix title not showing 
fix #9930 
<details>
</details>

fix(Mangafire): fix incorrect selector

---

websites/P/Prime Video/metadata.json
websites/P/Prime Video/presence.ts

I wanted to add a setting to show the title as the presence name. Resolves https://github.com/PreMiD/Activities/issues/9700
Then I removed the deprecated timestamps function to the new ones.
And I fixed the video selector because it wasn't showing timestamps.
And I realized that this presence has a lot more issues, I think the cleanest solution would be to rewrite it completely.
In the meantime, it works a bit more than before
<details>
</details>

feat(Prime Video): added Title as Presence name setting + other fixes

---

websites/F/FL Studio/metadata.json
websites/F/FL Studio/presence.ts

feat(FL Studio): add activity (#8304)

---

websites/C/CinePulse/metadata.json
websites/C/CinePulse/presence.ts

fix(CinePulse): changed their url (.to -> .cc)

---

websites/A/AnizmTV/metadata.json
websites/A/AnizmTV/presence.ts

Anizm.TV activity updated to fix compatibility issues with the redesigned website and add clickable text and images functionality. The previous version stopped working correctly due to site structure changes, requiring selector updates and improved error handling.
Changes include:
- Fixed selectors to work with the new site design
- Added clickable text (detailsUrl, stateUrl) and image functionality (largeImageUrl, smallImageUrl) 
- Replaced buttons with clickable text/images for improved interaction
- Updated page detection logic for all site sections
- Enhanced error handling with try-catch blocks
- Improved code formatting and removed unnecessary comments
- Bumped version to 3.0.1
These changes improve user experience by allowing direct navigation to the site when clicking on any …

feat(AnizmTV): fix site selectors and add clickable elements
